module Siko.MIR.Data where

import Siko.MIR.Type

data Variant = { name :: String,
                 type :: String
               }

data AlgebraicDataType = { name :: String,
                           variants :: [Variant],
                         }

data RecordField = { name :: String,
                     type :: Type,
                   }

data Record = { name :: String,
                fields :: [RecordField]
              }
