module SSG.Template {

import SSG.MD

pub fn render(layout: String, doc: Document) -> String {
    let title = match doc.metadata.fields.get("title") {
        Some(t) => t,
        None => "",
    };
    let date = match doc.metadata.fields.get("date") {
        Some(d) => d,
        None => "",
    };
    layout
        .replace("{{title}}", title)
        .replace("{{date}}", date)
        .replace("{{content}}", doc.body)
}

}
