module Siko.MIR.Backend.Ownership.V3.ConstraintInfo where

import Map

import Siko.MIR.Backend.Ownership.V3.TypeVariableInfo

data ConstraintInfo = VariantConstraint Int TypeVariable TypeVariableInfo
                    | MemberConstraint String TypeVariable TypeVariableInfo
                    deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data OwnershipInfo = Owner TypeVariable
                   | Borrower TypeVariable Int
                   deriving (PartialEq, Eq, PartialOrd, Ord, Show)
