module Siko.MIR.Backend.Ownership.V3.FunctionInfoStore where

import Siko.MIR.Program as P
import Siko.MIR.Backend.Ownership.V3.FunctionInfo
import Map

data FunctionInfoStore = { functions :: Map P.Identity FunctionInfo }

createFunctionInfoStore :: FunctionInfoStore
createFunctionInfoStore = FunctionInfoStore Map.empty

getFunctionInfo :: FunctionInfoStore -> P.Identity -> Option FunctionInfo
getFunctionInfo function_info_store id = Map.get function_info_store.functions id
