module Siko.MIR.Backend.Ownership.V3.FunctionInfo where

import Siko.MIR.Backend.Ownership.V3.InferenceInfo
import Siko.MIR.Backend.Ownership.V3.TypeVariableInfo

data FunctionInfo = { args :: [TypeVariableInfo],
                      result :: TypeVariableInfo,
                      members :: [MemberInfo],
                      variants :: [VariantInfo],
                      converters :: [Converter],
                    }
