module Siko.MIR.Backend.Ownership.V3.TypeVariableInfo where

data TypeVariable = TypeVariable Int deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show TypeVariable where
    show (TypeVariable i) = "#{}" % i

data TypeVariableInfo = { ownership_var :: TypeVariable,
                          arg_group_var :: TypeVariable,
                        } deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show TypeVariableInfo where
    show (TypeVariableInfo o a) = "({}, {})" % (o, a)
