module Siko.Resolver.Macros.Bridge.Traits {

import Siko.AST.QualifiedName
import Siko.Constants.Builtins as B
import Siko.Interner as I
import Siko.Interpreter.Strings
import Siko.Interpreter.Types
import Siko.Interpreter.Value
import Siko.Resolver.Macros.Bridge.Value
import Siko.Resolver.Macros.Bridge.State

fn trait_def(state: BridgeState, name: QualifiedName) -> Value {
    let qname = B.get_macro_trait_def_qn();
    Value(
        named_type(qname),
        ValueKind.Struct(StructBox(qname, [
            make_string(I.resolve(name.name())),
            handle_value(B.get_macro_qualified_name_qn(), state.add_name(name)),
        ])),
    )
}

fn macro_error(message: String) -> Value {
    variant_value(
        B.get_macro_error_qn(),
        B.get_macro_error_not_supported_qn(),
        0,
        [make_string(message)],
    )
}

pub fn resolution_ok(state: BridgeState, name: QualifiedName) -> Value {
    let trait_type = named_type(B.get_macro_trait_def_qn());
    let error_type = named_type(B.get_macro_error_qn());
    result_value(trait_type, error_type, True, trait_def(state, name))
}

pub fn resolution_error(message: String) -> Value {
    let trait_type = named_type(B.get_macro_trait_def_qn());
    let error_type = named_type(B.get_macro_error_qn());
    result_value(trait_type, error_type, False, macro_error(message))
}

}
