module Siko.HIR.Data where

import Siko.Syntax.Location
import Siko.HIR.Type
import Siko.HIR.Program as HP
import Siko.Util.SharedString as SS

data DeriveInfo = { class_name :: HP.FullyQualifiedName,
                    location :: Location,
                  } deriving (Show)

data Variant = { name :: SS.SharedString,
                 location :: Location,
                 items :: [Type],
               } deriving (Show)

data VariantInfo = VariantInfo HP.FullyQualifiedName Int Location deriving (Show)

data AlgebraicDataType = { name :: HP.FullyQualifiedName,
                           location :: Location,
                           type_args :: [Type],
                           variants :: [Variant],
                           variant_ctors :: [Type],
                           derived_classes :: [DeriveInfo],
                           type :: Type,
                        } deriving (Show)

data RecordField = RecordField SS.SharedString Type deriving (Show)

data Record = { name :: HP.FullyQualifiedName,
                location :: Location,
                type_args :: [Type],
                fields :: [RecordField],
                external :: Bool,
                record_ctor :: Type,
                derived_classes :: [DeriveInfo],
                type :: Type,
                implicit_member :: Bool,
              } deriving (Show)

getFieldByName :: Record -> SS.SharedString -> Option RecordField
getFieldByName record name = find record.fields (\RecordField field_name _ -> field_name == name)