module Siko.HIR.Program where

import Siko.Syntax.Location
import Siko.HIR.Function as F
import Siko.HIR.Data as D
import Siko.HIR.Class as C
import Siko.HIR.Type as T
import Siko.HIR.Effect as E
import Map
import Siko.Util.SharedString as SS

data FullyQualifiedName = FullPath SS.SharedString SS.SharedString
                        | FullPathWithVariant SS.SharedString SS.SharedString SS.SharedString
                        | FullPathWithLambda FullyQualifiedName F.LambdaId
                        | FullPathWithInstanceId SS.SharedString SS.SharedString C.InstanceId
                        | ModulePath SS.SharedString
                        | SubItem FullyQualifiedName SS.SharedString
                        | Effectless SS.SharedString SS.SharedString
                        deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show FullyQualifiedName where
    show f = case f of
        FullPath m n -> "{}.{}" % (m, n)
        FullPathWithVariant m n v -> "{}.{}/{}" % (m, n, v)
        FullPathWithLambda n i -> "{}/{}" % (n, i)
        FullPathWithInstanceId m n i -> "{}.{}/#{}" % (m, n, i)
        ModulePath m -> "{}" % m
        SubItem p n -> "{}/{}" % (p, n)
        Effectless m n -> "{}.{}" % (m, n)

getResolvableName :: FullyQualifiedName -> SS.SharedString
getResolvableName f = do
    s <- case f of
        FullPath m n -> "{}.{}" % (m, n)
        FullPathWithVariant m n v -> "{}.{}" % (m, v)
        FullPathWithLambda n i -> panic "getResolvableName called for a lambda"
        FullPathWithInstanceId m n i -> panic "getResolvableName called for a instance member"
        ModulePath m -> panic "getResolvableName called for a module"
        SubItem p n -> panic "getResolvableName called for a sub item"
        Effectless m n -> "{}.{}" % (m, n)
    SS.create s

getShortName :: FullyQualifiedName -> SS.SharedString
getShortName f = case f of
        FullPath m n -> n
        FullPathWithVariant m n v -> n
        FullPathWithLambda n i -> SS.create "{}_lambda" % getShortName n
        FullPathWithInstanceId m n i -> n
        ModulePath m -> m
        SubItem p n -> n
        Effectless m n -> n

getModuleName :: FullyQualifiedName -> SS.SharedString
getModuleName f = case f of
        FullPath m n -> m
        FullPathWithVariant m n v -> m
        FullPathWithLambda n i -> getModuleName n
        FullPathWithInstanceId m n i -> m
        ModulePath m -> m
        SubItem p n -> getModuleName p
        Effectless m n -> m

data Item a = Function (F.Function a)
            | Adt D.AlgebraicDataType
            | Record D.Record
            | Class C.Class
            | Variant D.VariantInfo
            | Module Location // dummy item, just for detecting name conflicts
            | Effect E.Effect
            deriving (Show)

data Program a = { items :: Map FullyQualifiedName (Item a),
                   instances :: Map C.InstanceId C.Instance,
                 } deriving (Show)

addInstance a :: Program a -> C.Instance -> Program a
addInstance program i = do
    (instances, _) <- insert program.instances i.id i
    program <- program { instances = instances }
    program

addItem a :: Program a -> FullyQualifiedName -> Item a -> (Program a, Option Location)
addItem program name item = do
    (items, old) <- insert program.items name item
    program <- program { items = items }
    location <- case old of
        Some item -> Some (getLocation item)
        None -> None
    (program, location)

getLocation a :: Item a -> Location
getLocation item = case item of
    Function f -> f.location
    Adt adt -> adt.location
    Record record -> record.location
    Class c -> c.location
    Variant (D.VariantInfo _ _ location) -> location
    Module location -> location
    Effect eff -> eff.location

getItem a :: Program a -> FullyQualifiedName -> Item a
getItem program name = case get program.items name of
    Some i -> i
    None -> panic "No item found {}" % name

getFunction a :: Program a -> FullyQualifiedName -> F.Function a
getFunction program name =
    case get program.items name of
        Some (Function f) -> f
        _ -> panic "Function {} not found" % name

getFunctionOpt a :: Program a -> FullyQualifiedName -> Option (F.Function a)
getFunctionOpt program name =
    case get program.items name of
        Some (Function f) -> Some f
        _ -> None

getAdt a :: Program a -> FullyQualifiedName -> D.AlgebraicDataType
getAdt program name =
    case get program.items name of
        Some (Adt adt) -> adt
        _ -> panic "Adt {} not found" % name

getAdtOpt a :: Program a -> FullyQualifiedName -> Option D.AlgebraicDataType
getAdtOpt program name =
    case get program.items name of
        Some (Adt adt) -> Some adt
        _ -> None

getVariant a :: Program a -> FullyQualifiedName -> Int -> D.Variant
getVariant program name index =
    case get program.items name of
        Some (Adt adt) -> do
            atIndex adt.variants index
        _ -> panic "No adt found {}" % name

getVariantInfo a :: Program a -> FullyQualifiedName -> D.VariantInfo
getVariantInfo program name =
    case get program.items name of
        Some (Variant info) -> info
        _ -> panic "No adt info found {}" % name

getVariantCtor a :: Program a -> FullyQualifiedName -> Int -> T.Type
getVariantCtor program name index =
    case get program.items name of
        Some (Adt adt) -> do
            atIndex adt.variant_ctors index
        _ -> panic "No adt found {}" % name

getRecord a :: Program a -> FullyQualifiedName -> D.Record
getRecord program name =
    case get program.items name of
        Some (Record record) -> record
        _ -> panic "No record found {}" % name

getRecordOpt a :: Program a -> FullyQualifiedName -> Option D.Record
getRecordOpt program name =
    case get program.items name of
        Some (Record record) -> Some record
        _ -> None

getClass a :: Program a -> FullyQualifiedName -> C.Class
getClass program name =
    case get program.items name of
        Some (Class c) -> c
        _ -> panic "No class found {}" % name

getEffect a :: Program a -> FullyQualifiedName -> E.Effect
getEffect program name =
    case get program.items name of
        Some (Effect eff) -> eff
        _ -> panic "No effect found {}" % name


getFunctions a :: Program a -> [F.Function a]
getFunctions program =
    program.items |> Map.iter |> Iterator.filter (\(qn, item) -> case item of
        Function _ -> True
        _ -> False) |> Iterator.map (\(qn, item) -> case item of
            Function f -> f
            _ -> panic "Function is not a function") |> toList

getAdts a :: Program a -> [D.AlgebraicDataType]
getAdts program =
    program.items |> Map.iter |> Iterator.filter (\(qn, item) -> case item of
        Adt adt -> True
        _ -> False) |> Iterator.map (\(qn, item) -> case item of
            Adt adt -> adt
            _ -> panic "Adt is not an adt") |> toList

getRecords a :: Program a -> [D.Record]
getRecords program =
    program.items |> Map.iter |> Iterator.filter (\(qn, item) -> case item of
        Record record -> True
        _ -> False) |> Iterator.map (\(qn, item) -> case item of
            Record record -> record
            _ -> panic "Record is not a record") |> toList

getClasses a :: Program a -> [C.Class]
getClasses program =
    program.items |> Map.iter |> Iterator.filter (\(qn, item) -> case item of
        Class _ -> True
        _ -> False) |> Iterator.map (\(qn, item) -> case item of
            Class c -> c
            _ -> panic "Class is not a Class") |> toList

getInstances a :: Program a -> [C.Instance]
getInstances program =
    program.instances |> Map.iter |> Iterator.map (\(id, i) -> i) |> toList

updateInstanceMemberType a :: Program a -> FullyQualifiedName -> T.Type -> Program a
updateInstanceMemberType program name type = do
    (items, _) <- alter (\f -> case f of
        Some (Function f) -> Some ( Function (f { type = Some type }))
        _ -> panic "Instance member not found") name program.items
    program { items = items }

getInstance a :: Program a -> C.InstanceId -> C.Instance
getInstance program instance_id = do
    case get program.instances instance_id of
        Some i -> i
        None -> panic "Instance not found {}" % instance_id