module Siko.Resolver.Environment where

import Siko.Resolver.Expr
import Siko.HIR.Pattern
import Siko.Syntax.Ident
import Map

data PatternEnvironment = { bindings :: Map String [Ident], irrefutable :: Bool }

data Environment = { block_bindings :: Map String BindRef,
                     parent :: Option Environment }

createPatternEnvironment :: Bool -> PatternEnvironment
createPatternEnvironment irrefutable = PatternEnvironment empty irrefutable

createEnvironment :: Option Environment -> Environment
createEnvironment parent = Environment empty parent

append :: Ident -> Option [Ident] -> Option [Ident]
append name names = case names of
    Some names -> Some (names + [name])
    None -> Some [name]

addBindingToPatternEnv :: PatternEnvironment -> Ident -> PatternEnvironment
addBindingToPatternEnv env name = do
    (bindings, _) <- alter (append name) (getString name) env.bindings
    env <- env { bindings = bindings }
    env

addBinding :: Environment -> BindRef -> Environment
addBinding env bind_ref = do
    (BindRef s _) <- bind_ref
    (block_bindings, _) <- insert env.block_bindings s bind_ref
    env <- env { block_bindings = block_bindings }
    env

getAllBindings :: PatternEnvironment -> [String]
getAllBindings env = env.bindings |> Map.iter |> Iterator.fold (\names, (name, _) -> names + [name]) []
