module Main where

import Siko.Resolver.Core
import Siko.Cache
import Siko.Resolver.Cache
import Siko.Syntax.Cache

main = do
    modules <- loadCache getSyntaxModuleCachePath
    (functions, classes, instances, effects, adts, records) <- resolve modules
    updateCache getResolvedFunctionCachePath functions
    updateCache getResolvedClassCachePath classes
    updateCache getResolvedInstanceCachePath instances
    updateCache getResolvedEffectCachePath effects
    updateCache getResolvedAdtCachePath adts
    updateCache getResolvedRecordCachePath records
    ()
