module Siko.AST.Traits {

import Siko.AST.Data
import Siko.AST.Generics
import Siko.AST.Function
import Siko.AST.Identifier
import Siko.AST.Annotations

pub struct AssociatedType {
    pub name: Identifier,
}

pub struct TraitDef {
    pub annotations: Vec[Annotation],
    pub public: Bool,
    pub name: Identifier,
    pub type_args: Vec[Identifier],
    pub associated_types: Vec[AssociatedType],
    pub type_arg_defs: Option[TypeArgDefs],
    pub methods: Vec[FunctionDef],
    pub method_map: MethodMap,
    pub required_method_names: Vec[Identifier],
}

}
