module Siko.Backend.Ownership.Inference where

import Siko.MIR.Program as P
import Siko.MIR.Function as F
import Siko.MIR.Type as T
import Siko.MIR.Expr as E
import Siko.Backend.Traversal
import Siko.Backend.Ownership.DataTypes as DataTypes
import Siko.Backend.Ownership.Unification
import Siko.Util.DependencyProcessor
import Std.Util
import Map

data FunctionTypeStore = { functions :: Map P.Identity FunctionType }

data FunctionVar = FunctionVar P.Identity E.Var deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data Context = { function_type_store :: FunctionTypeStore,
                 expr_types :: Map E.ExprId T.Type,
                 function_vars :: Map FunctionVar T.Type }

instance Apply Context where
    //apply :: Context -> Substitution -> Context
    apply context sub = do
        expr_types <- context.expr_types |> Map.iter |> map (\(expr_id, type) -> do
            new_type <- apply type sub
            //if expr_id == (E.ExprId 8)
            //    then println "{} -> {}" % (type, new_type)
            //    else ()
            (expr_id, new_type)) |> toMap
        function_vars <- context.function_vars |> Map.iter |> map (\(v, type) -> (v, apply type sub )) |> toMap
        context <- context { expr_types = expr_types, function_vars = function_vars }
        context

getExprType :: Context -> E.ExprId -> T.Type
getExprType context expr_id = case get context.expr_types expr_id of
    Some t -> t
    None -> panic "Could not get expr type for {}" % expr_id

dump :: Context -> String -> ()
dump context msg = do
    println "-------{}---------" % msg
    context.expr_types |> Map.iter |> forEach (\(v, t) -> println "{} - {}" % (v, t))
    context.function_vars |> Map.iter |> forEach (\(v, t) -> println "{} - {}" % (v, t))

initExpr :: P.Identity -> Context -> E.Expr -> (Context, E.Expr)
initExpr function_id context expr = do
    E.Expr s_expr type expr_id <- expr
    (expr_types, prev) <- insert context.expr_types expr_id type
    assert (isNone prev)
    context <- context { expr_types = expr_types }
    context <- case s_expr of
        E.VarDecl v rhs -> do
            E.Expr _ rhs_type rhs_expr_id <- rhs
            var <- FunctionVar function_id v
            (function_vars, _) <- insert context.function_vars var rhs_type
            context { function_vars = function_vars }
        _ -> context
    (context, expr)

unifyExprs :: Context -> E.Expr -> E.Expr -> Context
unifyExprs context expr1 expr2 = do
    E.Expr _ _ id1 <- expr1
    E.Expr _ _ id2 <- expr2
    type1 <- getExprType context id1
    type2 <- getExprType context id2
    sub <- createSubstitution
    sub <- unify sub type1 type2
    context <- apply context sub
    context

unifyExprWithVar :: Context -> E.ExprId -> FunctionVar -> Context
unifyExprWithVar context expr_id var = do
    type1 <- getExprType context expr_id
    type2 <- case get context.function_vars var of
        Some t -> t
        None -> panic "Var {} not found in context" % var
    sub <- createSubstitution
    sub <- unify sub type1 type2
    context <- apply context sub
    context

checkExpr :: P.Identity -> Context -> E.Expr -> (Context, E.Expr)
checkExpr function_id context expr = do
    E.Expr s_expr t id <- expr
    context <- case s_expr of
        E.Do items -> do
            last_index <- getLength items - 1
            last <- atIndex items last_index
            context <- unifyExprs context expr last
            context
        E.StaticFunctionCall f_id args -> do
            case get context.function_type_store.functions f_id of
                Some function_type -> do
                    function_type :: FunctionType <- function_type // FIXME
                    (context, function_type, index) <- args |> List.iter |> fold (\(context, function_type, index), arg -> do
                        E.Expr _ _ arg_id <- arg
                        arg_type <- getExprType context arg_id
                        func_arg_type <- atIndex function_type.args index
                        sub <- createSubstitution
                        //println "arg unify {} {}" % (arg_type, func_arg_type)
                        sub <- unify sub arg_type func_arg_type
                        //println "sub: {}" % sub
                        context <- apply context sub
                        function_type <- apply function_type sub
                        (context, function_type, index + 1)) (context, function_type, 0)
                    sub <- createSubstitution
                    result_type <- getExprType context id
                    //println "result? {}, {}" % (function_type.result, result_type)
                    sub <- unify sub function_type.result result_type
                    context <- apply context sub
                    result_type <- getExprType context id
                    context
                None -> panic "Function {} not found in function type store" % f_id
        E.VarRef arg -> do
            var <- FunctionVar function_id arg
            unifyExprWithVar context id var
        E.Clone args -> context
        E.FieldAccess name rhs -> context
        E.CaseOf body cases -> cases |> List.iter |> fold (\context, c -> unifyExprs context c.body expr) context
        E.StringLiteral lit -> context
        E.VarDecl v rhs -> do
            E.Expr _ _ rhs_expr_id <- rhs
            var <- FunctionVar function_id v
            unifyExprWithVar context rhs_expr_id var
        _ -> panic "NYI {}" % s_expr
    (context, expr)

initFunction :: Context -> F.Function -> Context
initFunction context function = case function.kind of
    F.Normal body -> do
        (context, _) <- function.args |> List.iter |> fold (\(context, index), arg_type -> do
            var <- FunctionVar function.id (E.Arg index)
            (function_vars, _) <- insert context.function_vars var arg_type
            context <- context { function_vars = function_vars }
            (context, index + 1)) (context, 0)
        println "Processing {} - init" % function.id
        (context, _) <- traverse context body (Some (initExpr function.id)) None
        context
    _ -> context

checkFunction :: Context -> F.Function -> Context
checkFunction context function = case function.kind of
    F.Normal body -> do
        println "Processing {} - check" % function.id
        (context, _) <- traverse context body (Some (checkExpr function.id)) None
        context
    _ -> context

updateExpr :: Context -> E.Expr -> (Context, E.Expr)
updateExpr context expr = do
    E.Expr s_expr t expr_id <- expr
    case get context.expr_types expr_id of
        Some t -> (context, E.Expr s_expr t expr_id)
        None -> panic "Expr {} not found in context" % expr_id

updateFunctionKind :: Context -> F.FunctionKind -> F.FunctionKind
updateFunctionKind context kind = case kind of
    F.Normal body -> do
        (context, body) <- traverse context body (Some updateExpr) None
        F.Normal body
    k -> k

processFunctions :: P.Program -> FunctionTypeStore -> [P.Identity] -> (P.Program, FunctionTypeStore)
processFunctions program function_type_store functions = do
    context <- Context function_type_store empty empty
    context <- functions |> List.iter |> fold (\context, id -> do
        function <- P.getFunction program id
        context <- initFunction context function
        context) context
    //dump context "after init"
    context <- functions |> List.iter |> fold (\context, id -> do
        function <- P.getFunction program id
        context <- checkFunction context function
        context) context
    //dump context "after check"
    program <- functions |> List.iter |> fold (\program, id -> do
        function <- P.getFunction program id
        kind <- updateFunctionKind context function.kind
        P.updateFunctionKind program id kind) program
    (program, context.function_type_store)

processProgram :: P.Program -> [DependencyGroup P.Identity] -> [DependencyGroup P.Identity] -> P.Program
processProgram program data_groups function_groups = do
    program <- DataTypes.processDataTypes program data_groups
    function_type_store <- program.functions |> Map.iter |> fold (\function_type_store, (id, function) -> do
        function_type <- FunctionType function.args function.result
        (functions, _) <- insert function_type_store.functions id function_type
        function_type_store { functions = functions } ) (FunctionTypeStore empty)
    (program, function_type_store) <- function_groups |> List.iter |> fold (\(program, function_type_store), group -> do
        processFunctions program function_type_store group.items) (program, function_type_store)
    program