module Std.Hash.FNV1a {

import Std.Vec

pub fn compute32(input: Vec[U8]) -> U32 {
    let hash: U32 = 0x811c9dc5;
    for byte in input {
        hash = (hash ^ byte.as_int().as_u32()) * 0x01000193;
    }
    hash
}

pub fn compute64(input: Vec[U8]) -> U64 {
    let hash: U64 = 0xcbf29ce484222325;
    for byte in input {
        hash = (hash ^ byte.as_int().as_u64()) * 0x00000100000001b3;
    }
    hash
}

}
