module Siko.MIR.Expr where

import Siko.MIR.Program
import Siko.Util.Format
import Siko.MIR.Type as T
import Json

data Var = Named String
         | Temp Int
         | Arg Int
         | FnArg Int
         deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show Var where
    show v = case v of
        Named v -> "_{}" % v
        Temp v -> "tmp_{}" % v
        Arg i -> "arg{}" % i
        FnArg i -> "fn_arg{}" % i

data RecordUpdateItem = { field_name :: String,
                          body :: Expr }
                        deriving (Show)

data RangeKind = Inclusive | Exclusive deriving (Show)

data Checker = IntegerChecker String
             | StringChecker String
             | CharChecker Char
             | CharRangeChecker Char Char RangeKind
             | VariantChecker Int Var T.Type
             | WildcardChecker

instance Show Checker where
    show checker = case checker of
        IntegerChecker lit -> "i:{}" % lit
        StringChecker lit -> "s:{}" % lit
        CharChecker lit -> "c:{}" % lit
        CharRangeChecker s e kind -> "{}:{}:{}" % (s, e, kind)
        VariantChecker i v type -> "v:{} {} :: {}" % (i, v, type)
        WildcardChecker -> "w"

data Case = { checker :: Checker, body :: Expr } deriving (Show)

data ExprId = ExprId Int deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data Expr = Expr SimpleExpr T.Type ExprId deriving (Show)

data ConverterKind = NormalConverter
                   | BorrowerConverter
                   | FieldConverter Bool
                   deriving (Show)

data SimpleExpr = Do [Expr]
                | Multi [Expr]
                | StaticFunctionCall Identity [Expr]
                | IntegerLiteral String
                | StringLiteral String
                | FloatLiteral String
                | CharLiteral Char
                | VarDecl Var Expr
                | VarRef Var
                | FieldAccess String Expr
                | If Expr Expr Expr
                | List [Expr]
                | Return Expr
                | Continue Expr
                | Break Expr
                | RecordUpdate Var [RecordUpdateItem]
                | Loop Var Expr Expr [ExprId] [ExprId]
                | CaseOf Expr [Case]
                | Clone Expr
                | Deref Expr
                | Ref Expr
                | Move Expr
                | Box Expr
                | Converter Expr ConverterKind
                deriving (Show)

short :: Expr -> String
short expr = do
    Expr s _ _ <- expr
    case s of
        Do args -> "Do"
        Multi args -> "Multi"
        StaticFunctionCall id args -> "StaticFunctionCall({})" % id
        IntegerLiteral lit -> "IntegerLiteral"
        StringLiteral lit -> "StringLiteral"
        FloatLiteral lit -> "FloatLiteral"
        CharLiteral lit -> "CharLiteral"
        VarDecl v arg -> "VarDecl"
        VarRef v -> "VarRef({})" % v
        FieldAccess n rhs -> "FieldAccess"
        If cond true_branch false_branch -> "If"
        List args -> "List"
        Return arg -> "Return"
        Continue arg -> "Continue"
        Break arg -> "Break"
        RecordUpdate var updates -> "RecordUpdate"
        Loop var initializer body _ _ -> "Loop"
        CaseOf body cases -> "CaseOf"
        Clone expr -> "Clone"
        Deref expr -> "Deref"
        Ref expr -> "Ref"
        Move expr -> "Move"
        Box expr -> "Box"
        Converter expr _ -> "Converter"

prettyPrint :: Expr -> Indent -> (String, Bool)
prettyPrint expr ind = do
    Expr expr expr_type expr_id <- expr
    case expr of
        Do args -> do
            inner <- inc ind
            args <- args |> List.iter |> Iterator.map (\arg -> do
                "{}{}" % (inner, (prettyPrint arg inner).0)) |> toList
            s <- "do\n{}" % (join args "\n")
            (s, False)
        Multi args -> do
            args <- args |> List.iter |> Iterator.map (\arg -> do
                "{}" % ((prettyPrint arg ind).0)) |> toList
            s <- "Multi: {}" % (join args ";")
            (s, False)
        StaticFunctionCall id args -> do
            args <- args |> List.iter |> Iterator.map (\arg -> do
                (s, simple) <- prettyPrint arg ind
                if simple then s else "({})" % s) |> toList
            s <- "{} {}" % (id, join args " ")
            (s, isEmpty args)
        IntegerLiteral lit -> ("{}" % lit, True)
        StringLiteral lit -> ("\"{}\"" % escapeString lit, True)
        FloatLiteral lit -> ("{}" % lit, True)
        CharLiteral lit -> ("'{}'" % lit, True)
        VarDecl v arg -> do
            Expr _ arg_type id <- arg
            s <- "{} :: {} <- {}" % (v, arg_type, (prettyPrint arg ind).0)
            (s, False)
        VarRef v -> ("{}" % v, True)
        FieldAccess n rhs -> do
            (s, simple) <- prettyPrint rhs ind
            s <- if simple
                then "{}.{}" % (s, n)
                else "({}).{}" % (s, n)
            (s, True)
        If cond true_branch false_branch -> do
            s <- "if {} then {} else {}" % ((prettyPrint cond ind).0, (prettyPrint true_branch ind).0, (prettyPrint false_branch ind).0)
            (s, True)
        List args -> do
            args <- args |> List.iter |> Iterator.map (\arg -> do
                (s, simple) <- prettyPrint arg ind
                s) |> toList
            s <- "[{}]" % (join args ", ")
            (s, True)
        Return arg -> do
            (s, simple) <- prettyPrint arg ind
            s <- if simple then s else "({})" % s
            s <- "return {}" % s
            (s, simple)
        Continue arg -> do
            (s, simple) <- prettyPrint arg ind
            s <- if simple then s else "({})" % s
            s <- "continue {}" % s
            (s, simple)
        Break arg -> do
            (s, simple) <- prettyPrint arg ind
            s <- if simple then s else "({})" % s
            s <- "break {}" % s
            (s, simple)
        RecordUpdate var updates -> do
            args <- updates |> List.iter |> Iterator.map (\update -> do
                (s, simple) <- prettyPrint update.body ind
                ("{} : {}" % (update.field_name, s))) |> toList
            s <- "({} {{ {} }})" % (var, join args ", ")
            (s, True)
        Loop var initializer body _ _ -> do
            (initializer, simple) <- prettyPrint initializer ind
            initializer <- if simple then initializer else "({})" % initializer
            (body, _) <- prettyPrint body ind
            s <- "loop {} <- {} {}" % (var, initializer, body)
            (s, False)
        CaseOf body cases -> do
            inner <- inc ind
            args <- cases |> List.iter |> Iterator.map (\case_branch -> do
                "{}{} -> {}" % (inner, case_branch.checker, (prettyPrint case_branch.body inner).0)) |> toList
            s <- "case ({}) of\n{}" % ((prettyPrint body inner).0, join args "\n")
            (s, False)
        Clone expr -> do
            (s, simple) <- prettyPrint expr ind
            ("clone({})" % s, False)
        Deref expr -> do
            (s, simple) <- prettyPrint expr ind
            ("deref({})" % s, False)
        Ref expr -> do
            (s, simple) <- prettyPrint expr ind
            ("ref({})" % s, False)
        Move expr -> do
            (s, simple) <- prettyPrint expr ind
            ("move({})" % s, False)
        Box expr -> do
            (s, simple) <- prettyPrint expr ind
            ("box({})" % s, False)
        Converter expr kind -> do
            //(s, simple) <- prettyPrint expr ind
            //("(convert[{},{}]({}) :: {})" % (expr_id, kind, s, expr_type), False)
            prettyPrint expr ind

build k args extras = do
    arg_ids <- List.map args (\Expr _ _ (ExprId i) -> JsonString (show i))
    args <- List.map args toJson
    kind <- JsonObjectItem "kind" (JsonString k)
    if isEmpty args
    then ([kind] + extras, args)
    else ([kind, JsonObjectItem "args" (JsonList arg_ids)] + extras, args)

toJson :: Expr -> Json
toJson expr = do
    Expr s type (ExprId i) <- expr
    type <- JsonObjectItem "type" (JsonString (show type))
    id <- JsonObjectItem "id" (JsonString (show i))
    (kinds, subs) <- case s of
        Do args -> build "do" args []
        Multi args -> panic "Multi in toJson"
        StaticFunctionCall id args -> build "staticfunctioncall" args [JsonObjectItem "f_id" (JsonString (show id))]
        IntegerLiteral lit -> build "integerliteral" [] [JsonObjectItem "value" (JsonString lit)]
        StringLiteral lit -> build "stringliteral" [] [JsonObjectItem "value" (JsonString lit)]
        FloatLiteral lit -> build "floatliteral" [] [JsonObjectItem "value" (JsonString lit)]
        CharLiteral lit -> build "charliteral" [] [JsonObjectItem "value" (JsonString (show lit))]
        VarDecl v arg -> build "vardecl" [arg] [JsonObjectItem "var" (JsonString (show v))]
        VarRef v -> build "varref" [] [JsonObjectItem "var" (JsonString (show v))]
        FieldAccess n rhs -> build "fieldaccess" [rhs] [JsonObjectItem "field" (JsonString n)]
        If cond true_branch false_branch -> build "if" [cond, true_branch, false_branch] []
        List args -> build "list" args []
        Return arg -> build "return" [arg] []
        Continue arg -> build "continue" [arg] []
        Break arg -> build "break" [arg] []
        RecordUpdate var updates -> panic "RecordUpdate in toJson"
        Loop var initializer body _ _ -> build "loop" [initializer, body] [JsonObjectItem "var" (JsonString (show var))]
        CaseOf body cases -> do
            (case_bodies, cases) <- List.mapS [] cases (\case_bodies, c -> do
                Expr _ _ (ExprId i) <- c.body
                case_bodies <- List.push case_bodies (toJson c.body)
                items <- [JsonObjectItem "checker" (JsonString (show c.checker)),
                          JsonObjectItem "body" (JsonString (show i))]
                (case_bodies, JsonObject items))
            (kinds, subs) <- build "caseof" [body] [JsonObjectItem "cases" (JsonList cases)]
            (kinds, subs + case_bodies)
        Clone expr -> panic "Clone in toJson"
        Deref expr -> panic "Deref in toJson"
        Ref expr -> panic "Ref in toJson"
        Move expr -> panic "Move in toJson"
        Box expr -> panic "Box in toJson"
        Converter arg _ -> build "converter" [arg] []
    if isEmpty subs
    then JsonObject ([id, type] + kinds)
    else do
        subs <- List.fold [] subs (\subs, sub -> case sub of
            JsonList s -> subs + s
            j -> List.push subs j)
        JsonList ([JsonObject ([id, type] + kinds)] + subs)
