module Siko.Resolver.Function where

import Map
import Siko.HIR.Expr as HE
import Siko.HIR.ExprIdGenerator
import Siko.HIR.FullyQualifiedName as FQ
import Siko.HIR.Function as HF
import Siko.HIR.PatternIdGenerator
import Siko.HIR.Type as HT
import Siko.HIR.TypeVarGenerator
import Siko.Resolver
import Siko.Resolver.Environment
import Siko.Resolver.Error
import Siko.Resolver.Expr
import Siko.Resolver.ModuleResolver
import Siko.Resolver.Type
import Siko.Syntax.Attribute as SA
import Siko.Syntax.Function as SF
import Siko.Syntax.Ident
import Siko.Syntax.Location
import Siko.Syntax.Module as SM
import Siko.Syntax.Pattern as SP
import Siko.Util.SharedString as SS

data LambdaInfo = { id :: HF.LambdaId,
                    arg_count :: Int,
                    host :: FQ.FullyQualifiedName,
                    body :: HE.Expr ()
                  } deriving (Show)

data FunctionScopeResolver = { functions :: Map SS.SharedString FQ.FullyQualifiedName,
                               parent :: Option FunctionScopeResolver
                             } deriving (Show, PartialEq, Eq)

createEmptyFunctionScopeResolver :: FunctionScopeResolver
createEmptyFunctionScopeResolver = FunctionScopeResolver Map.empty None

resolveLocalFunction :: FunctionScopeResolver -> SS.SharedString -> Option FQ.FullyQualifiedName
resolveLocalFunction function_scope_resolver name = do
    case get function_scope_resolver.functions name of
        Some qn -> Some qn
        None -> case function_scope_resolver.parent of
            Some parent -> resolveLocalFunction parent name
            None -> None

data UnresolvedFunctionInfo = { function :: UnresolvedFunction,
                                name :: FQ.FullyQualifiedName,
                                kind :: HF.FunctionKind,
                                function_scope_resolver :: FunctionScopeResolver,
                                type_resolver :: TypeResolverState,
                                var_gen :: TypeVarGenerator
                              } deriving (Show, PartialEq, Eq)

createNormalUnresolvedFunctionInfo :: UnresolvedFunction -> FQ.FullyQualifiedName -> ModuleResolver -> UnresolvedFunctionInfo
createNormalUnresolvedFunctionInfo unresolved_function qn module_resolver = UnresolvedFunctionInfo unresolved_function qn HF.Normal createEmptyFunctionScopeResolver (createTypeResolverState module_resolver) createTypeVarGenerator

data UnresolvedFunction = { name :: Ident,
                            functions :: [SF.Function],
                            signatures :: [SF.FunctionSignature]
                          } deriving (Show, PartialEq, Eq)

createUnresolvedFunction :: Ident -> UnresolvedFunction
createUnresolvedFunction name = UnresolvedFunction name [] []

getFunctionLocation :: UnresolvedFunctionInfo -> Location
getFunctionLocation unresolved_function_info = do
    Ident name location <- unresolved_function_info.function.name
    location

addFunction :: SF.Function -> UnresolvedFunction -> UnresolvedFunction
addFunction function f = do
    functions <- List.push f.functions function
    f { functions = functions }

addFunctionSignature :: SF.FunctionSignature -> UnresolvedFunction -> UnresolvedFunction
addFunctionSignature signature f = do
    signatures <- List.push f.signatures signature
    f { signatures = signatures }

collectUnresolvedFunctions :: [SM.Item] -> [UnresolvedFunction]
collectUnresolvedFunctions items = do
    (functions, signatures) <- List.fold ([], []) items (\(functions, signatures), item -> case item of
        SM.Function f -> (List.push functions f, signatures)
        SM.FunctionSignature s -> (functions, List.push signatures s)
        _ -> (functions, signatures))
    mergeUnresolvedFunctions functions signatures

mergeUnresolvedFunctions :: [SF.Function] -> [SF.FunctionSignature] -> [UnresolvedFunction]
mergeUnresolvedFunctions functions signatures = do
    unresolved_functions <- List.fold Map.empty functions (\unresolved_functions, function -> do
        name <- getString function.name
        unresolved_function <- case get unresolved_functions name of
            Some unresolved_function -> unresolved_function
            None -> createUnresolvedFunction function.name
        unresolved_function <- addFunction function unresolved_function
        Map.put unresolved_functions name unresolved_function)
    unresolved_functions <- List.fold unresolved_functions signatures (\unresolved_functions, signature -> do
        name <- getString signature.name
        unresolved_function <- case get unresolved_functions name of
            Some unresolved_function -> unresolved_function
            None -> createUnresolvedFunction signature.name
        unresolved_function <- addFunctionSignature signature unresolved_function
        Map.put unresolved_functions name unresolved_function)
    Map.fold [] unresolved_functions (\unresolved_functions, (_, unresolved_function) -> List.push unresolved_functions unresolved_function)

processAttributes a :: (ResolverState a) => a -> UnresolvedFunction -> (a, [HF.Attribute])
processAttributes state unresolved_function = do
    (state, attributes) <- List.fold (state, []) unresolved_function.signatures (\(state, attributes), signature -> do
        (state, attrs) <- processAttributeList state signature.attributes
        (state, attributes + attrs))
    List.fold (state, attributes) unresolved_function.functions (\(state, attributes), function -> do
        (state, attrs) <- processAttributeList state function.attributes
        (state, attributes + attrs))
    where
        processAttributeList a :: (ResolverState a) => a -> [SA.Attribute] -> (a, [HF.Attribute])
        processAttributeList state attributes = do
            List.fold (state, []) attributes (\(state, attributes), attribute -> do
                Ident name _ <- attribute.name
                case (SS.get name) of
                    "Inline" -> (state, List.push attributes HF.Inline)
                    _ -> (addError state (InvalidAttribute attribute.name), attributes))

processExternConstraints :: [SF.ExternConstraint] -> [HF.ExternConstraint]
processExternConstraints extern_constraints = List.map extern_constraints processExternConstraint
    where
        processExternConstraint :: SF.ExternConstraint -> HF.ExternConstraint
        processExternConstraint extern_constraint = case extern_constraint of
            SF.ExternConverter (SF.Converter from to) -> HF.ExternConverter (HF.Converter (processConstraintPath from) (processConstraintPath to))
            SF.ExternEquality (SF.Equal from to) -> HF.ExternEquality (HF.Equal (processConstraintPath from) (processConstraintPath to))
            SF.Independent path -> HF.Independent (processConstraintPath path)

        processConstraintPath :: SF.ConstraintPath -> HF.ConstraintPath
        processConstraintPath path = case path of
            SF.Argument index -> HF.Argument index
            SF.Result -> HF.Result
            SF.Field index parent -> HF.Field index (processConstraintPath parent)
            SF.Extern index parent -> HF.Extern index (processConstraintPath parent)
            SF.Variant index parent -> HF.Variant index (processConstraintPath parent)
            SF.Implicit index parent -> HF.Implicit index (processConstraintPath parent)

processLambdas :: [LambdaInfo] -> FQ.FullyQualifiedName -> ExprIdGenerator -> PatternIdGenerator -> [HF.Function ()]
processLambdas lambdas qn expr_id_gen pattern_id_gen = lambdas |> List.iter |> Iterator.map (\lambda -> do
        lambda_qn <- FQ.FullPathWithLambda qn lambda.id
        kind <- (HF.Lambda lambda.id)
        arg_count <- lambda.arg_count
        HE.Expr _ _ _ location <- lambda.body
        HF.Function location lambda_qn arg_count kind None None (Some lambda.body) None [HF.Inline] [] expr_id_gen pattern_id_gen) |> toList

processSubFunctions a :: (ResolverState a) => a -> FunctionScopeResolver -> TypeResolverState -> [SM.Item] -> FQ.FullyQualifiedName -> (a, [UnresolvedFunctionInfo], FunctionScopeResolver)
processSubFunctions state function_scope_resolver type_resolver sub_items qn = do
    unresolved_functions <- collectUnresolvedFunctions sub_items
    local_functions_map <- unresolved_functions |> List.iter |> Iterator.map (\f -> do
        name <- (getString f.name)
        qn <- FQ.SubItem qn name
        (name, qn)) |> toMap
    function_scope_resolver <- FunctionScopeResolver local_functions_map (Some (function_scope_resolver))
    sub_unresolved_function_infos <- List.map unresolved_functions (\unresolved_function -> do
        qn <- FQ.SubItem qn (getString unresolved_function.name)
        UnresolvedFunctionInfo unresolved_function qn HF.Normal function_scope_resolver type_resolver (getVarGen state))
    (state, sub_unresolved_function_infos, function_scope_resolver)

processFunctionSignature a :: (ResolverState a) => a -> TypeResolverState -> SF.FunctionSignature -> (a, TypeResolverState, Option [HT.Type], HT.Type)
processFunctionSignature state type_resolver signature = do
    state <- checkTypeArguments state signature.type_arguments
    (state, type_resolver) <- processClassConstraints state type_resolver signature.constraints
    (type_resolver, state, type) <- processTypeSignature type_resolver state signature.type_signature
    (state, type_resolver, effects) <- case signature.effects of
        Some effects -> do
            (state, type_resolver, effects) <- List.fold (state, type_resolver, []) effects (\(state, type_resolver, effects), eff -> case resolveEffect type_resolver.module_resolver eff.name of
                Ok (qn, count) -> do
                    state <- checkTypeArguments state eff.arguments
                    (type_resolver, args) <- List.mapS type_resolver eff.arguments resolveTypeArg
                    state <- if getLength args != count
                    then do
                        (Ident _ location) <- eff.name
                        addError state (InvalidEffectArgCount count (getLength args) location)
                    else state
                    (state, type_resolver, List.push effects (HT.Named qn args))
                Err err -> do
                    state <- addError state err
                    (state, type_resolver, effects))
            (state, type_resolver, Some effects)
        None -> (state, type_resolver, None)
    (state, type_resolver, effects, type)

processSingleFunction a :: (ResolverState a) => a -> TypeResolverState -> UnresolvedFunctionInfo -> Option [HT.Type] -> Option HT.Type -> ExprIdGenerator -> PatternIdGenerator -> (a, [HF.Function ()], [UnresolvedFunctionInfo])
processSingleFunction state type_resolver unresolved_function_info effects type expr_id_gen pattern_id_gen = do
    function <- atIndex unresolved_function_info.function.functions 0
    (state, attributes) <- processAttributes state unresolved_function_info.function
    (state, effects, desugared_body) <- case function.body of
        Some body if List.isEmpty function.arguments -> (state, effects, Some body)
        Some body -> (state, effects, Some (desugarFunctionArgs function.arguments body))
        None -> do
            state <- function.arguments |> List.iter |> Iterator.fold (\state, p -> case p of
                SP.Pattern binding location -> case binding of
                    SP.Binding _ -> state
                    _ -> addError state (InvalidExternArg location)) state
            state <- if isSome effects
            then addError state (ExternEffect function.name)
            else state
            (state, Some [], None)
    (state, sub_unresolved_function_infos, function_scope_resolver) <- processSubFunctions state unresolved_function_info.function_scope_resolver type_resolver function.sub_items unresolved_function_info.name
    (state, expr_id_gen, pattern_id_gen, hir_body, lambdas) <- case desugared_body of
        Some expr -> do
            context <- createContext unresolved_function_info.name type_resolver state expr_id_gen pattern_id_gen function_scope_resolver
            env <- createEnvironment (HF.LambdaId 0) None
            (context, env, expr) <- processExpr context env expr
            (context.state, context.expr_id_gen, context.pattern_id_gen, Some expr, context.lambdas)
        None -> if isNone type && HF.isNormal unresolved_function_info.kind
            then do
                state <- addError state (ExternFnWithoutType function.name)
                (state, expr_id_gen, pattern_id_gen, None, [])
            else (state, expr_id_gen, pattern_id_gen, None, [])
    arg_count <- getLength function.arguments
    orig_type <- Std.Intrinsics.clone type // FIXME: borrow error workaround
    simplified_type <- case type of
        Some type -> Some (HT.removeOwnership type)
        None -> None
    location <- getFunctionLocation unresolved_function_info
    function <- HF.Function location unresolved_function_info.name arg_count unresolved_function_info.kind simplified_type orig_type hir_body effects attributes (processExternConstraints function.extern_constraints) expr_id_gen pattern_id_gen
    lambdas <- processLambdas lambdas unresolved_function_info.name expr_id_gen pattern_id_gen
    (state, [function] + lambdas, sub_unresolved_function_infos)

processFunctionMulti a :: (ResolverState a) => a -> TypeResolverState -> UnresolvedFunctionInfo -> Option [HT.Type] -> Option HT.Type -> ExprIdGenerator -> PatternIdGenerator -> (a, [HF.Function ()], [UnresolvedFunctionInfo])
processFunctionMulti state type_resolver unresolved_function_info effects type expr_id_gen pattern_id_gen = do
    (state, attributes) <- processAttributes state unresolved_function_info.function
    (state, arg_count_map, err) <- unresolved_function_info.function.functions |> List.iter |> Iterator.fold (\(state, arg_count_map, err), f -> do
        (state, err) <- if isNone f.body
        then do
            state <- addError state (ExternFnWithMultiDef f.name)
            (state, True)
        else (state, err)
        (state, err) <- if List.isEmpty f.arguments
        then do
            state <- addError state (MultiDefNoArg f.name)
            (state, True)
        else (state, err)
        arg_count_map <- Map.add arg_count_map f.name (getLength f.arguments)
        (state, arg_count_map, err)) (state, empty, False)
    (state, err) <- if getSize arg_count_map != 1
    then do
        names <- unresolved_function_info.function.functions |> List.iter |> Iterator.map (\f -> DefArgCount f.name (getLength f.arguments)) |> toList
        state <- addError state (MultiDefArgCountMismatch names)
        (state, True)
    else (state, err)
    location <- getFunctionLocation unresolved_function_info
    if not err
    then do
        arg_cases <- unresolved_function_info.function.functions |> List.iter |> Iterator.map (\f -> (f.arguments, Option.unwrap f.body)) |> toList
        sub_items <- unresolved_function_info.function.functions |> List.iter |> Iterator.fold (\sub_items, f -> sub_items + f.sub_items) []
        desugared_body <- desugarFunctionArgsMulti arg_cases
        (state, expr_id_gen, pattern_id_gen, hir_body, lambdas, sub_unresolved_function_infos) <- do
            (state, sub_unresolved_function_infos, function_scope_resolver) <- processSubFunctions state unresolved_function_info.function_scope_resolver type_resolver sub_items unresolved_function_info.name
            context <- createContext unresolved_function_info.name type_resolver state expr_id_gen pattern_id_gen function_scope_resolver
            env <- createEnvironment (HF.LambdaId 0) None
            (context, env, expr) <- processExpr context env desugared_body
            (context.state, context.expr_id_gen, context.pattern_id_gen, Some expr, context.lambdas, sub_unresolved_function_infos)
        arg_count <- getLength (atIndex unresolved_function_info.function.functions 0).arguments
        function <- HF.Function location unresolved_function_info.name arg_count unresolved_function_info.kind type type hir_body effects attributes [] expr_id_gen pattern_id_gen
        lambdas <- processLambdas lambdas unresolved_function_info.name expr_id_gen pattern_id_gen
        (state, [function] + lambdas, sub_unresolved_function_infos)
    else do
        function <- HF.Function location unresolved_function_info.name 0 unresolved_function_info.kind type type None effects attributes [] expr_id_gen pattern_id_gen
        (state, [function], [])

processUnresolvedFunction a :: (ResolverState a) => a -> UnresolvedFunctionInfo -> (a, [HF.Function ()], [UnresolvedFunctionInfo])
processUnresolvedFunction state unresolved_function_info = do
    expr_id_gen <- createExprIdGenerator
    pattern_id_gen <- createPatternIdGenerator
    state <- setVarGen state unresolved_function_info.var_gen
    (state, effects, type, type_resolver) <- case getLength unresolved_function_info.function.signatures of
        0 -> (state, None, None, unresolved_function_info.type_resolver)
        1 -> do
            signature <- atIndex unresolved_function_info.function.signatures 0
            signature <- Std.Intrinsics.clone signature // FIXME: borrow error workaround
            (state, type_resolver, effects, type) <- processFunctionSignature state unresolved_function_info.type_resolver signature
            (state, effects, Some type, type_resolver)
        _ -> do
            signatures <- List.map unresolved_function_info.function.signatures (\s -> s.name)
            state <- addError state (ConflictingSignatures signatures)
            (state, None, None, unresolved_function_info.type_resolver)
    (state, functions, sub_unresolved_function_infos) <- case getLength unresolved_function_info.function.functions of
        0 -> do
            arg_count <- case type of
                Some t -> getLength (HT.getArgs t)
                None -> 0
            location <- getFunctionLocation unresolved_function_info
            (state, attributes) <- processAttributes state unresolved_function_info.function
            function <- HF.Function location unresolved_function_info.name arg_count unresolved_function_info.kind type type None effects attributes [] expr_id_gen pattern_id_gen
            (state, [function], [])
        1 -> processSingleFunction state type_resolver unresolved_function_info effects type expr_id_gen pattern_id_gen
        _ -> processFunctionMulti state type_resolver unresolved_function_info effects type expr_id_gen pattern_id_gen
    (state, functions, sub_unresolved_function_infos)
