module Siko.Backend where

import Siko.Backend.Passes.CreateVars as CreateVars
import Siko.Backend.Passes.Box as Box
import Siko.Backend.Ownership.Inference as Inference
import Siko.Backend.Traversal
import Siko.MIR.Program as P
import Siko.MIR.Data
import Siko.MIR.Type as T
import Siko.MIR.Function as F
import Siko.MIR.Expr
import Siko.Config
import Siko.Util.DependencyProcessor
import Map
import Hack

collectDataDeps :: P.Program -> Map P.Identity [P.Identity]
collectDataDeps program = do
    dependencies <- empty
    dependencies <- program.adts |> Map.iter |> fold (\dependencies, (id, adt) -> do
            deps <- adt.variants |> List.iter |> fold (\deps, variant -> do
                deps + [T.getIdentity variant.type]) []
            (dependencies, _) <- insert dependencies id deps
            dependencies
        ) dependencies
    dependencies <- program.records |> Map.iter |> fold (\dependencies, (id, record) -> do
            deps <- record.fields |> List.iter |> fold (\deps, field -> do
                deps + [T.getIdentity field.type]) []
            deps <- case record.external_info of
                Some external_info -> do
                    external_info :: ExternalRecordInfo <- external_info // FIXME
                    external_info.type_args |> List.iter |> fold (\deps, type_arg -> do
                        deps + [T.getIdentity type_arg]) deps
                None -> deps
            (dependencies, _) <- insert dependencies id deps
            dependencies
        ) dependencies
    dependencies

data Context = { deps :: [P.Identity] }
                 deriving (PartialEq, Eq, PartialOrd, Ord)

processExpr :: Context -> Expr -> (Context, Expr)
processExpr context expr = do
    Expr s_expr _ _ <- expr
    case s_expr of
        StaticFunctionCall id _ -> do
            deps <- context.deps + [id]
            context <- context { deps = deps }
            (context, expr)
        _ -> (context, expr)

getDepsForFunction :: P.Program -> F.Function -> [P.Identity]
getDepsForFunction program function = case function.kind of
    F.Normal body -> do
        context <- Context []
        (context, _) <- traverse context body (Some processExpr) None
        context.deps
    _ -> []

collectFunctionDeps :: P.Program -> Map P.Identity [P.Identity]
collectFunctionDeps program = do
    dependencies <- empty
    dependencies <- program.functions |> Map.iter |> fold (\dependencies, (id, function) -> do
            deps <- getDepsForFunction program function
            (dependencies, _) <- insert dependencies id deps
            dependencies
        ) dependencies
    dependencies

processProgram :: Config -> P.Program -> Int -> P.Program
processProgram config program expr_id = do
    data_dependencies <- collectDataDeps program
    data_groups <- processDependencies data_dependencies
    function_dependencies <- collectFunctionDeps program
    function_groups <- processDependencies function_dependencies
    program <- Box.processProgram program data_groups
    program <- CreateVars.processProgram program expr_id
    program <- Inference.processProgram program data_groups function_groups
    s <- P.dump program
    writeTextFile (getOutputFileName config OptMIR) s
    program