module Siko.Backend.Instantiation where

import Siko.MIR.Program as MP
import Siko.MIR.Function as MF
import Siko.MIR.Type as MT
import Siko.MIR.Expr as ME
import Siko.MIR.Data as MD

import Siko.LIR.Program as LP
import Siko.LIR.Function as LF
import Siko.LIR.Type as LT
import Siko.LIR.Expr as LE
import Siko.LIR.Data as LD

import Siko.Backend.Ownership.Unification as U
import Siko.Backend.Ownership.Inference as Inference
import Siko.Backend.Ownership.Inference.Common as InferenceC

import Map
import Set

data LIRKey = FunctionKey MP.Identity MF.FunctionType
            | RecordKey MP.Identity [MT.OwnershipKind]
            | AdtKey MP.Identity [MT.OwnershipKind]
            deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data QueuedItem = QueuedItem LIRKey deriving (Show)

data Name = { module_name :: String, name :: String } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data NameMap = { names :: Map Name Int }

getName :: NameMap -> MP.Identity -> (NameMap, LP.Identity)
getName name_map mir_id = do
    MP.Identity mod name _ <- mir_id
    (names, id) <- alter (\old -> case old of
        Some old_id -> Some (old_id + 1)
        None -> Some 1) (Name mod name) name_map.names
    lir_id <- case id of
        Some id -> LP.Identity mod name id
        None -> LP.Identity mod name 0
    (name_map { names = names}, lir_id)

data Queue = { name_map :: NameMap,
               lir_ids :: Map LIRKey LP.Identity,
               lir_functions :: Map LP.Identity LF.Function,
               type_ids :: Map MT.Type LT.Type,
               lir_records :: Map LP.Identity LD.Record,
               lir_adts :: Map LP.Identity LD.AlgebraicDataType,
               item_queue :: [QueuedItem],
               inference_info_store :: InferenceC.InferenceInfoStore,
               var_gen :: U.OwnershipVarGenerator }

createQueue :: InferenceC.InferenceInfoStore -> U.OwnershipVarGenerator -> Queue
createQueue inference_info_store var_gen =
                Queue { name_map = NameMap Map.empty,
                      lir_ids = Map.empty,
                      lir_functions = Map.empty,
                      type_ids = Map.empty,
                      lir_records = Map.empty,
                      lir_adts = Map.empty,
                      item_queue = [],
                      inference_info_store = inference_info_store,
                      var_gen = var_gen }

createId :: MP.Identity -> (NameMap, Option LP.Identity) -> Option LP.Identity -> ((NameMap, Option LP.Identity), Option LP.Identity)
createId mir_id (name_map, _) old = case old of
    Some name -> ((name_map, Some name), Some name)
    None -> do
        (name_map, lir_id) <- getName name_map mir_id
        ((name_map, Some lir_id), Some lir_id)

getMIRId :: LIRKey -> MP.Identity
getMIRId key = case key of
    FunctionKey id _ -> id
    RecordKey id _ -> id
    AdtKey id _ -> id

getLIRId :: Queue -> LIRKey -> (Queue, LP.Identity)
getLIRId queue key = do
    mir_id <- getMIRId key
    lir_id :: Option LP.Identity <- None
    ((name_map, lir_id), lir_ids, _) <- alterS (createId mir_id) (queue.name_map, None) key queue.lir_ids
    (queue { name_map = name_map, lir_ids = lir_ids }, Option.unwrap lir_id)

addFunction :: Queue -> LF.Function -> Queue
addFunction queue function = do
    (lir_functions, _) <- Map.insert queue.lir_functions function.id function
    queue { lir_functions = lir_functions }

addRecord :: Queue -> LD.Record -> Queue
addRecord queue record = do
    (lir_records, _) <- Map.insert queue.lir_records record.id record
    queue { lir_records = lir_records }

addAdt :: Queue -> LD.AlgebraicDataType -> Queue
addAdt queue adt = do
    (lir_adts, _) <- Map.insert queue.lir_adts adt.id adt
    queue { lir_adts = lir_adts }

addItem :: Queue -> QueuedItem -> Queue
addItem queue item = do
    item_queue <- queue.item_queue + [item]
    queue { item_queue = item_queue }

processVar :: ME.Var -> LE.Var
processVar var = case var of
    ME.Named n -> LE.Named n
    ME.Temp i -> LE.Temp i
    ME.Arg i -> LE.Arg i

processRangeKind :: ME.RangeKind -> LE.RangeKind
processRangeKind range_kind = case range_kind of
    ME.Inclusive -> LE.Inclusive
    ME.Exclusive -> LE.Exclusive

processChecker :: Queue -> ME.Checker -> (Queue, LE.Checker)
processChecker queue checker = case checker of
    ME.IntegerChecker lit -> (queue, LE.IntegerChecker lit)
    ME.StringChecker lit -> (queue, LE.StringChecker lit)
    ME.CharChecker lit -> (queue, LE.CharChecker lit)
    ME.CharRangeChecker s e kind -> (queue, LE.CharRangeChecker s e (processRangeKind kind))
    ME.VariantChecker i v t -> do
        (queue, type) <- processType queue t
        (queue, LE.VariantChecker i (processVar v) type)
    ME.WildcardChecker -> (queue, LE.WildcardChecker)

processCase :: Queue -> ME.Case -> (Queue, LE.Case)
processCase queue c = do
    (queue, checker) <- processChecker queue c.checker
    (queue, body) <- processExpr queue c.body
    (queue, LE.Case checker body)

processExpr :: Queue -> ME.Expr -> (Queue, LE.Expr)
processExpr queue mir_expr = do
    ME.Expr s_expr mir_type id <- mir_expr
    (queue, lir_s_expr) <- case s_expr of
        ME.Do items -> do
            (queue, items) <- items |> List.iter |> fold (\(queue, items), item -> do
                (queue, item) <- processExpr queue item
                (queue, items + [item])) (queue, [])
            (queue, LE.Do items)
        ME.StaticFunctionCall id args -> do
            arg_types <- args |> List.iter |> map (\ME.Expr _ t _ -> t) |> toList
            (indices, arg_types) <- List.mapS Map.empty arg_types normalizeType
            (indices, result) <- normalizeType indices mir_type
            normalized_function_type <- MF.FunctionType arg_types result
            //println "{} :: {}" % (id, normalized_function_type)
            function_key <- FunctionKey id normalized_function_type
            (queue, lir_id) <- getLIRId queue function_key
            queue <- addItem queue (QueuedItem function_key)
            (queue, args) <- args |> List.iter |> fold (\(queue, args), arg -> do
                (queue, arg) <- processExpr queue arg
                (queue, args + [arg])) (queue, [])
            (queue, LE.StaticFunctionCall lir_id args)
        ME.IntegerLiteral i -> (queue, LE.IntegerLiteral i)
        ME.VarDecl v rhs -> do
            lir_var <- processVar v
            (queue, lir_rhs) <- processExpr queue rhs
            (queue, LE.VarDecl lir_var lir_rhs)
        ME.CaseOf body cases -> do
            (queue, lir_body) <- processExpr queue body
            (queue, lir_cases) <- List.mapS queue cases processCase
            (queue, LE.CaseOf lir_body lir_cases)
        ME.FieldAccess n rhs -> do
            (queue, lir_rhs) <- processExpr queue rhs
            (queue, LE.FieldAccess n lir_rhs)
        ME.VarRef v -> do
            lir_var <- processVar v
            (queue, LE.VarRef lir_var)
        ME.Clone arg -> do
            (queue, arg) <- processExpr queue arg
            (queue, LE.Clone arg)
        ME.Ref arg -> do
            (queue, arg) <- processExpr queue arg
            (queue, LE.Ref arg)
        ME.Move arg -> do
            (queue, arg) <- processExpr queue arg
            (queue, LE.Move arg)
        ME.Deref arg -> do
            (queue, arg) <- processExpr queue arg
            (queue, LE.Deref arg)
        _ -> panic "NYI {}" % s_expr
    //println "{} ---> {}" % (mir_type, s_expr)
    (queue, lir_type) <- processType queue mir_type
    lir_expr <- LE.Expr lir_s_expr lir_type (LE.ExprId 0)
    (queue, lir_expr)

normalizeIndex :: Map Int Int -> Int -> (Map Int Int, Int)
normalizeIndex indices index = do
    next <- getSize indices
    (index, indices, _) <- Map.alterS (\index, old -> case old of
        Some old -> (old, Some old)
        None -> (next, Some next)) 0 index indices
    (indices, index)

normalizeArg :: Map Int Int -> MT.OwnershipKind -> (Map Int Int, MT.OwnershipKind)
normalizeArg indices kind = case kind of
    MT.VarKind _ -> panic "VarKind in args in lowering!"
    MT.OwnerKind -> (indices, MT.OwnerKind)
    MT.BorrowKind index -> do
        (indices, index) <- normalizeIndex indices index
        (indices, MT.BorrowKind index)

normalizeArgs :: Map Int Int -> [MT.OwnershipKind] -> (Map Int Int, [MT.OwnershipKind])
normalizeArgs indices args = do
    (indices, args) <- List.mapS indices args normalizeArg
    (indices, args)

normalizeType :: Map Int Int -> MT.Type -> (Map Int Int, MT.Type)
normalizeType indices type = case type of
    MT.Adt id args -> do
        (indices, args) <- normalizeArgs indices args
        (indices, MT.Adt id args)
    MT.Record id args -> do
        (indices, args) <- normalizeArgs indices args
        (indices, MT.Record id args)
    MT.Ref index t -> do
        (indices, t) <- normalizeType indices t
        (indices, index) <- normalizeIndex indices index
        (indices, MT.Ref index t)
    MT.Owner t -> do
        (indices, t) <- normalizeType indices t
        (indices, MT.Owner t)
    MT.Never -> (indices, MT.Never)
    MT.Box t -> do
        (indices, t) <- normalizeType indices t
        (indices, MT.Box t)
    MT.Var _ _ -> panic "Var type in LIR lowering! {}" % type

collectLifetimes :: MT.Type -> [LT.Lifetime]
collectLifetimes mir_type = do
    kinds <- MT.collectOwnershipKinds mir_type
    lifetimes <- kinds |> List.iter |> fold (\lifetimes, kind -> case kind of
            MT.BorrowKind i -> do
                lifetimes + [LT.Lifetime i]
            _ -> lifetimes) []
    lifetimes <- lifetimes |> sort |> dedup
    lifetimes

processType :: Queue -> MT.Type -> (Queue, LT.Type)
processType queue mir_type = case mir_type of
    MT.Adt id args -> do
        (_, args) <- normalizeArgs Map.empty args
        adt_key <- AdtKey id args
        (queue, lir_id) <- getLIRId queue adt_key
        queue <- addItem queue (QueuedItem adt_key)
        lifetimes <- collectLifetimes mir_type
        (queue, LT.Adt lir_id lifetimes)
    MT.Record id args -> do
        (_, args) <- normalizeArgs Map.empty args
        record_key <- RecordKey id args
        (queue, lir_id) <- getLIRId queue record_key
        queue <- addItem queue (QueuedItem record_key)
        lifetimes <- collectLifetimes mir_type
        (queue, LT.Record lir_id lifetimes)
    MT.Ref index t -> do
        (queue, lir_t) <- processType queue t
        (queue, LT.Ref (LT.Lifetime index) lir_t)
    MT.Owner t -> processType queue t
    MT.Never -> (queue, LT.Never)
    MT.Box t -> do
        (queue, lir_t) <- processType queue t
        (queue, LT.Box lir_t)
    MT.Var _ _ -> panic "Var type in LIR lowering! {}" % mir_type

processFunctionType :: Queue -> MF.FunctionType -> (Queue, LF.FunctionType, [LT.Lifetime])
processFunctionType queue mir_function_type = do
    (queue, lir_args) <- List.mapS queue mir_function_type.args processType
    lifetimes <- mir_function_type.args |> List.iter |> fold (\lifetimes, mir_arg -> do
        lifetimes + collectLifetimes mir_arg) []
    lifetimes <- lifetimes + collectLifetimes mir_function_type.result
    lifetimes <- lifetimes |> sort |> dedup
    (queue, lir_result) <- processType queue mir_function_type.result
    (queue, LF.FunctionType lir_args lir_result, lifetimes)

processFunction :: Queue -> MP.Program -> MP.Identity -> MF.FunctionType -> LP.Identity -> Queue
processFunction queue mir_program mir_id function_type lir_id = do
    //println "Instantiation: processing function {} {}" % (mir_id, function_type)
    mir_function <- MP.getFunction mir_program mir_id
    case mir_function.kind of
        MF.Normal mir_body expr_id_gen temp_var_gen -> do
            global_context <- InferenceC.createGlobalContext mir_program queue.inference_info_store
            (body, var_gen) <- Inference.instantiateFunction global_context queue.var_gen expr_id_gen mir_id function_type mir_body
            (queue, lir_body) <- processExpr queue body
            lir_kind <- LF.Normal lir_body
            (queue, lir_function_type, lifetimes) <- processFunctionType queue function_type
            lir_function <- LF.Function lir_id lifetimes lir_kind lir_function_type
            queue <- addFunction queue lir_function
            queue
        MF.VariantCtor index -> do
            lir_kind <- LF.VariantCtor index
            (queue, lir_function_type, lifetimes) <- processFunctionType queue function_type
            lir_function <- LF.Function lir_id lifetimes lir_kind lir_function_type
            queue <- addFunction queue lir_function
            queue
        MF.RecordCtor -> do
            lir_kind <- LF.RecordCtor
            (queue, lir_function_type, lifetimes) <- processFunctionType queue function_type
            lir_function <- LF.Function lir_id lifetimes lir_kind lir_function_type
            queue <- addFunction queue lir_function
            queue
        MF.Extern _ -> do
            lir_kind <- LF.Extern
            (queue, lir_function_type, lifetimes) <- processFunctionType queue function_type
            lir_function <- LF.Function lir_id lifetimes lir_kind lir_function_type
            queue <- addFunction queue lir_function
            queue
        _ -> queue

processField :: Queue -> MD.RecordField -> (Queue, LD.RecordField)
processField queue mir_field = do
    (queue, lir_type) <- processType queue mir_field.type
    (queue, LD.RecordField mir_field.name lir_type)

processVariant :: Queue -> MD.Variant -> (Queue, LD.Variant)
processVariant queue mir_variant = do
    (queue, lir_type) <- processType queue mir_variant.type
    (queue, LD.Variant mir_variant.name lir_type)

processExternalRecordInfo :: Queue -> MD.ExternalRecordInfo -> (Queue, LD.ExternalRecordInfo)
processExternalRecordInfo queue mir_external_record_info = do
    (queue, lir_type_args) <- List.mapS queue mir_external_record_info.type_args processType
    (queue, LD.ExternalRecordInfo lir_type_args)

processRecord :: Queue -> MP.Program -> MP.Identity -> [MT.OwnershipKind] -> LP.Identity -> Queue
processRecord queue mir_program mir_id args lir_id = do
    //println "Processing record {} {}" % (mir_id, args)
    mir_record <- MP.getRecord mir_program mir_id
    sub <- U.batch mir_record.ownership_vars args
    mir_record <- U.apply mir_record sub
    (queue, fields) <- List.mapS queue mir_record.fields processField
    (queue, external_info) <- case mir_record.external_info of
        Some external_info -> do
            (queue, external_info) <- processExternalRecordInfo queue external_info
            (queue, Some external_info)
        None -> (queue, None)
    external_class_impls <- [] // FIXME
    lifetimes <- collectLifetimes (MT.Record mir_id mir_record.ownership_vars)
    lir_record <- LD.Record lir_id lifetimes fields external_info external_class_impls
    queue <- addRecord queue lir_record
    queue

processAdt :: Queue -> MP.Program -> MP.Identity -> [MT.OwnershipKind] -> LP.Identity -> Queue
processAdt queue mir_program mir_id args lir_id = do
    //println "Processing adt {} {}" % (mir_id, args)
    mir_adt <- MP.getAdt mir_program mir_id
    sub <- U.batch mir_adt.ownership_vars args
    mir_record <- U.apply mir_adt sub
    (queue, variants) <- List.mapS queue mir_adt.variants processVariant
    external_class_impls <- [] // FIXME
    lifetimes <- collectLifetimes (MT.Record mir_id mir_adt.ownership_vars)
    lir_adt <- LD.AlgebraicDataType lir_id lifetimes variants external_class_impls
    queue <- addAdt queue lir_adt
    queue

processItem :: Queue -> MP.Program -> QueuedItem -> Queue
processItem queue mir_program item = do
    QueuedItem lir_key <- item
    lir_id <- case get queue.lir_ids lir_key of
        Some lir_id -> lir_id
        None -> panic "No lir id found for {}" % lir_key
    case lir_key of
        FunctionKey mir_id function_type -> do
            case get queue.lir_functions lir_id of
                Some _ -> queue
                None -> processFunction queue mir_program mir_id function_type lir_id
        RecordKey mir_id args -> do
            case get queue.lir_records lir_id of
                Some _ -> queue
                None -> processRecord queue mir_program mir_id args lir_id
        AdtKey mir_id args -> do
            case get queue.lir_adts lir_id of
                Some _ -> queue
                None -> processAdt queue mir_program mir_id args lir_id

processItems :: Queue -> MP.Program -> Queue
processItems queue mir_program = do
    loop queue <- queue do
        queue :: Queue <- queue // FIXME
        if List.isEmpty queue.item_queue
            then break queue
            else do
                items <- queue.item_queue
                queue <- queue { item_queue = [] }
                queue <- items |> List.iter |> fold (\queue, item -> processItem queue mir_program item) queue
                queue

processProgram :: MP.Program -> InferenceC.InferenceInfoStore -> U.OwnershipVarGenerator -> LP.Program
processProgram mir_program inference_info_store var_gen = do
    main_id <- MP.getMainIdentity
    main_function <- MP.getFunction mir_program main_id
    main_result <- case main_function.type.result of
        MT.Var _ t -> MT.Owner t
        _ -> panic "Unexpected main function resul type {}" % main_function.type.result
    function_key <- FunctionKey main_id (MF.FunctionType [] main_result)
    queue <- createQueue inference_info_store var_gen
    (queue, lir_main_id) <- getLIRId queue function_key
    queue <- addItem queue (QueuedItem function_key)
    queue <- processItems queue mir_program
    lir_program <- LP.createProgram
    lir_program <- queue.lir_functions |> Map.iter |> fold (\lir_program, (id, f) -> LP.addFunction lir_program id f) lir_program
    lir_program <- queue.lir_records |> Map.iter |> fold (\lir_program, (id, r) -> LP.addRecord lir_program id r) lir_program
    lir_program <- queue.lir_adts |> Map.iter |> fold (\lir_program, (id, adt) -> LP.addAdt lir_program id adt) lir_program
    lir_program