module Siko.HIR.Backend.Lowering.TypeMapping(createTypeMap) where

import Siko.HIR.Type as HT
import Siko.HIR.Data as HD
import Siko.HIR.Program as HP
import Siko.MIR.Function as MF
import Siko.HIR.Backend.Lowering.TypeStore as TS
import Siko.HIR.Backend.Unification as U
import Siko.HIR.Backend.Lowering as L
import Map

data Context = { var_mappings :: Map String [MF.Position],
                 owner_positions :: [MF.Position],
                 ref_positions :: [MF.Position],
                 lowering_context :: L.Context }

createTypeMap :: L.Context -> HT.Type -> Int -> MF.TypeMapping
createTypeMap lowering_context type arg_count = do
    args <- HT.getArgs type
    (args, _) <- List.split args arg_count
    result_type <- HT.getResultType type arg_count
    context <- Context empty [] [] lowering_context
    (context, _ ) <- args |> List.iter |> Iterator.fold (\(context, index), arg -> do
        steps <- [MF.FunctionArg index]
        context <- mapType context steps arg
        (context, index + 1)) (context, 0)
    context <- mapType context [MF.FunctionResult] result_type
    MF.TypeMapping context.var_mappings context.owner_positions context.ref_positions

addVarPosition :: Context -> String -> [MF.Step] -> Context
addVarPosition context name steps = do
    pos <- MF.Position steps
    (var_mappings, _) <- alter (\positions -> case positions of
        Some positions -> Some (positions + [pos])
        None -> Some [pos]) name context.var_mappings
    context { var_mappings = var_mappings }

addOwnerPosition :: Context -> [MF.Step] -> Context
addOwnerPosition context steps = do
    pos <- MF.Position steps
    owner_positions <- context.owner_positions + [pos]
    context { owner_positions = owner_positions }

addRefPosition :: Context -> [MF.Step] -> Context
addRefPosition context steps = do
    pos <- MF.Position steps
    ref_positions <- context.ref_positions + [pos]
    context { ref_positions = ref_positions }

mapType :: Context -> [MF.Step] -> HT.Type -> Context
mapType context steps type = case type of
    HT.Var _ _ -> panic "Var type in type mapping!"
    HT.FixedTypeArg name _ _ -> do
        addVarPosition context name steps
    HT.EffectTypeArg name _ _ -> do
        addVarPosition context name steps
    HT.Named qn args -> do
        case HP.getItem context.lowering_context.hir_program qn of
            HP.Record record -> do
                if record.external
                    then do
                        context <- List.foldE (\context, index, arg -> do
                            steps <- steps + [MF.External index]
                            context <- mapType context steps arg
                            context) context args
                        context
                    else do
                        (lowering_context, record) <- TS.instantiateRecord context.lowering_context record type
                        context <- context { lowering_context = lowering_context }
                        List.foldE (\context, index, (HD.RecordField _ field_type) -> do
                            steps <- steps + [MF.Field index]
                            context <- mapType context steps field_type
                            context) context record.fields
            HP.Adt adt -> do
                (lowering_context, adt) <- TS.instantiateAdt context.lowering_context adt type
                context <- context { lowering_context = lowering_context }
                List.foldE (\context, index, v -> do
                    steps <- steps + [MF.Variant index]
                    context <- List.foldE (\context, index, t -> do
                            steps <- steps + [MF.Field index]
                            context <- mapType context steps t
                            context) context v.items
                    context) context adt.variants
            _ -> panic "Named type is not an adt nor a record in type mapping"
    HT.Function from to -> panic "Function type in type mapping!"
    HT.Never var -> context
    HT.Ref t -> do
        context <- addRefPosition context steps
        mapType context steps t
    HT.Owner t -> do
        context <- addOwnerPosition context steps
        mapType context steps t
    HT.Tuple args -> do
        (context, _) <- args |> List.iter |> Iterator.fold (\(context, index), arg -> do
            steps <- steps + [MF.Field index]
            context <- mapType context steps arg
            (context, index + 1)) (context, 0)
        context
