module Main where

import Std.Util

data Color = Red Int | Blue Int Int [Int] deriving (Show)

data Person = { name :: String, age :: Int} deriving (Show)

data EmptyRecord = {} deriving (Show)

data Foo = Foo Int deriving (Show)
data Foo2 = Foo2 deriving (Show)
data Foo3 = Foo3 | Bar deriving (Show)

main = do
    color <- "{}" % Red 5
    person <- "{}" % Person { age=5, name = "Lily" }
    assert (color == "Red (5)")
    assert (person == "Person (Lily) (5)")
    assert (show (Foo 5) == "Foo (5)")
    assert (show Foo2 == "Foo2")
    assert (show Foo3 == "Foo3")
    assert (show EmptyRecord == "EmptyRecord")
