module Main where

import IO
import Siko.Args
import Time

traceLevel1Option = "trace1"

data TestInfo = { full_path :: String,
                  name :: String
                }

instance PartialEq TestInfo where
    opEq (TestInfo _ n1) (TestInfo _ n2) = opEq n1 n2

instance Eq TestInfo

instance PartialOrd TestInfo where
    partialCmp (TestInfo _ n1) (TestInfo _ n2) = partialCmp n1 n2

instance Ord TestInfo where
    cmp (TestInfo _ n1) (TestInfo _ n2) = cmp n1 n2

collectTests :: String ->
                String ->
                [String] ->
                [TestInfo] -> [TestInfo]
collectTests path parent selected tests = do
    if isDir path
    then do
        files <- listDir path
        (skip, sub_tests) <- List.fold (False, []) files (\(skip, tests), entry -> do
            subs <- String.split entry "/"
            file <- last subs
            if isDir entry
            then (skip, collectTests entry file selected tests)
            else do
                skip <- if file == "SKIP" then True else skip
                tests <- if file == "main.sk"
                then List.push tests (TestInfo path parent)
                else tests
                (skip, tests))
        if List.isEmpty selected
        then do
            if skip
            then do
                List.forEach sub_tests (\t -> println "Skipping {}" % t.name)
                tests
            else tests + sub_tests
        else do
            selected_tests <- List.filter sub_tests (\t -> List.contains selected t.name)
            tests + selected_tests
    else tests

data Statistics = { success :: Int,
                    failure :: Int
                  }

runTest :: String ->
           Int ->
           Int ->
           Statistics ->
           TestInfo ->
           Bool ->
           Bool ->
           Bool ->
           [String] -> Statistics
runTest binary total index stats test level2 dump pdp mir_functions = do
    i1 <- now
    print "--- Running test {} - {}/{} --- " % (test.name, total, index + 1)
    createDir "test_runs/{}" % test.name
    test_runs_path <- "test_runs/{}/{}" % (test.name, test.name)
    cmd <- [binary,
            "build",
            "./std",
            test.full_path,
            "-nooptimization",
            "-o",
            test_runs_path]
    cmd <- if level2
    then List.push cmd "-vv"
    else cmd
    cmd <- if dump
    then List.push cmd "-d"
    else cmd
    cmd <- if pdp
    then List.push cmd "-pdp"
    else cmd
    cmd <- List.fold cmd mir_functions (\cmd, f -> cmd + ["-m", f])
    //println "cmd {}" % cmd
    stats <- if runCommand cmd
    then do
        if isFile test_runs_path
        then if runCommand [test_runs_path]
            then stats { success = stats.success + 1 }
            else stats { failure = stats.failure + 1 }
        else stats { failure = stats.failure + 1 }
    else stats { failure = stats.failure + 1 }
    i2 <- now
    diff <- diffInMilliseconds i1 i2
    seconds <- diff / 1000
    millis <- remInt diff 1000
    println "{}.{}s" % (seconds, millis)
    stats

main = do
    args <- getArgs
    argparser <- createArgParser "Siko"
    traceLevel2Option <- "trace level 2"
    dumpOption <- "dump"
    pdpOption <- "print dataflow profile info"
    tracedMirFunctionOption <- "trace mir function"
    options <- [Simple (SimpleOption traceLevel2Option "-vv" "Enable level 2 traces" "Disabled"),
                Simple (SimpleOption dumpOption "-d" "Dump IR" "Disabled"),
                Simple (SimpleOption pdpOption "-pdp" "Print dataflow profiles" "Disabled"),
                WithArg (WithArgOption tracedMirFunctionOption "-m" "Traced MIR function" "-")]
    stage0_cmd <- Command "stage0" options "Run tests with stage0"
    stage1_cmd <- Command "stage1" options "Run tests with stage1"
    stage2_cmd <- Command "stage2" options "Run tests with stage2"
    merged_cmd <- Command "merged" options "Run tests with merged"
    siko_cmd <- Command "siko" options "Run tests with siko"
    argparser <- addCommand argparser stage0_cmd
    argparser <- addCommand argparser stage1_cmd
    argparser <- addCommand argparser stage2_cmd
    argparser <- addCommand argparser merged_cmd
    argparser <- addCommand argparser siko_cmd
    case processArgs argparser args of
        Ok result -> do
            level2 <- isValueSet result traceLevel2Option
            dump <- isValueSet result dumpOption
            pdp <- isValueSet result pdpOption
            mir_functions <- case getMultiValue result tracedMirFunctionOption of
                Some values -> values
                None -> []
            case result.command of
                cmd -> do
                    tests <- collectTests "./test" "./test" result.unused []
                    total <- List.getLength tests
                    tests <- tests |> List.sort
                    stats <- Statistics 0 0
                    stats <- List.foldE stats tests (\stats, index, test -> runTest cmd
                                                                                    total
                                                                                    index
                                                                                    stats
                                                                                    test
                                                                                    level2
                                                                                    dump
                                                                                    pdp
                                                                                    mir_functions)
                    println "Success {}, failure {}" % (stats.success, stats.failure)
        Err _ -> ()
