module Siko.Stuff where

data SourceCode = SourceCode String deriving (PartialEq, Eq, Show)

data Module = Module String String deriving (PartialEq, Eq, Show)

data ResolvedModule = ResolvedModule String String deriving (PartialEq, Eq, Show)

data TypedModule = TypedModule String String deriving (PartialEq, Eq, Show)

data Ast = Ast [Module] deriving (PartialEq, Eq, Show)

parse :: SourceCode -> Ast
parse (SourceCode source) = do
    println "parse {}" % source
    modules <- String.split source "," |> List.iter |> map (\m -> do
        subs <- String.split m " "
        name <- atIndex subs 0
        num <- atIndex subs 1
        Module name num) |> toList
    Ast modules

resolve :: Module -> ResolvedModule
resolve (Module name num) = do
    println "resolve {}" % name
    ResolvedModule name num

typeck :: ResolvedModule -> TypedModule
typeck (ResolvedModule name num) = do
    println "typeck {}" % name
    TypedModule name num
