module Main {

fn main() {
    test1();
    test2();
}


@derive(Clone)
class Object {

}

fn test1() {
    let outer = {
        let inner = Object();
        let other = inner;
        inner;
        other
    };
}

class Name {

}

class Address {
    street: Name
    city: Name
}

class Person {
    address: Address
}

fn test2() {
    let street = Name();
    let city = Name();
    let address = Address(street, city);
    let person = Person(address);
    street;
}

}