module Siko.Typechecker.Lowering.ClosureStore where

import Siko.Typechecker.Lowering
import Siko.Typechecker.Lowering.TypeStore as TS
import Siko.Typechecker.Lowering.Util
import Siko.HIR.Type as HT
import Siko.MIR.Expr as ME
import Siko.MIR.Function as MF
import Siko.MIR.Program
import Siko.MIR.Data as MD
import Siko.MIR.Type as MT
import Siko.Constants
import Map

data ClosureInstanceId = ClosureInstanceId Int deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data ClosureInstance = { id :: ClosureInstanceId,
                         name :: String,
                         args :: [HT.Type] } deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Closure = { name :: String,
                 instances :: [ClosureInstance] }

data ClosureInstanceSuccessor = NextClosureInstance Identity
                                | RealFunctionCall Identity

instance Show ClosureInstanceSuccessor where
    show c = case c of
        NextClosureInstance f -> show f
        RealFunctionCall f -> show f

data ClosureStore = { closures :: Map String Closure,
                      closure_type_map :: Map HT.Type String,
                      closure_calls :: Map String Identity,
                      successors :: Map ClosureInstance ClosureInstanceSuccessor }

createClosureStore :: ClosureStore
createClosureStore = ClosureStore empty empty empty empty

addClosureInstance :: ClosureStore -> HT.Type -> [HT.Type] -> (ClosureStore, ClosureInstance)
addClosureInstance store closure_type args = do
    (store, name) <- getClosureName store closure_type
    // FIXME: use a stateful alter here
    next_id <- case get store.closures name of
        Some closure -> do
            closure :: Closure <- closure
            getLength closure.instances
        None -> 0
    instance_id <- ClosureInstanceId next_id
    closure_instance <- ClosureInstance instance_id name args
    (closures, _) <- alter (\closure -> case closure of
        Some closure -> do
            closure :: Closure <- closure
            instances <- closure.instances + [closure_instance]
            Some closure { instances = instances }
        None -> Some (Closure name [closure_instance])) name store.closures
    (store { closures = closures }, closure_instance)

getClosureName :: ClosureStore -> HT.Type -> (ClosureStore, String)
getClosureName store closure_type = do
    name <- "Closure_{}" % getSize store.closure_type_map
    // FIXME use a stateful alter here
    (closure_type_map, _) <- alter (\closure -> case closure of
        Some closure -> Some closure
        None -> Some name) closure_type store.closure_type_map
    store <- store { closure_type_map = closure_type_map }
    name <- case get store.closure_type_map closure_type of
        Some name -> name
        None -> panic "Closure not found after creation"
    (store, name)

addClosureCall :: ClosureStore -> String -> Identity -> ClosureStore
addClosureCall store name function_id = do
    (closure_calls, _) <- insert store.closure_calls name function_id
    store { closure_calls = closure_calls }

getClosureCall :: ClosureStore -> HT.Type -> Identity
getClosureCall store closure_type = case get store.closure_type_map closure_type of
    Some closure_name -> case get store.closure_calls closure_name of
        Some function_id -> function_id
        None -> panic "Closure call for closure {} not found" % closure_name
    None -> panic "Closure name for closure type {} not found" % (HT.toString closure_type)

addClosureInstanceSuccessor :: ClosureStore -> ClosureInstance -> ClosureInstanceSuccessor -> ClosureStore
addClosureInstanceSuccessor store closure_instance closure_instance_successor = do
    (successors, _) <- insert store.successors closure_instance closure_instance_successor
    store { successors = successors }

getVariantName :: ClosureInstance -> String
getVariantName closure_instance = do
    ClosureInstanceId id <- closure_instance.id
    "I{}" % id

getVariantRecordIdentity :: ClosureInstance -> Identity
getVariantRecordIdentity closure_instance = Identity getInternalModuleName ("{}_{}" % (closure_instance.name, getVariantName closure_instance)) 0

getVariantCtorName :: ClosureInstance -> String
getVariantCtorName closure_instance = "{}_{}" % (closure_instance.name, getVariantName closure_instance)

getClosureIdentity :: String -> Identity
getClosureIdentity closure_name = do
    Identity getInternalModuleName closure_name 0

createClosures :: Context -> Context
createClosures context = do
    context <- context.closure_store.closures |> Map.iter |> fold (\context, (name, closure) -> do
        context <- closure.instances |> List.iter |> fold (\context, closure_instance -> do
            (context, mir_args) <- closure_instance.args |> List.iter |> fold (\(context, mir_args), arg -> do
                    (context, mir_arg) <- TS.processType context arg
                    mir_args <- mir_args + [mir_arg]
                    (context, mir_args)
                ) (context, [])
            variant_name <- getVariantName closure_instance
            record_identity <- getVariantRecordIdentity closure_instance
            (mir_fields, _) <- mir_args |> List.iter |> fold (\(mir_fields, index), mir_arg -> do
                    field_name <- getFieldName index
                    mir_field <- MD.RecordField field_name mir_arg
                    mir_fields <- mir_fields + [mir_field]
                    (mir_fields, index + 1)
                ) ([], 0)
            type_store <- context.type_store
            mir_variant_record <- MD.Record record_identity mir_fields None [] []
            (records, _) <- insert type_store.records record_identity mir_variant_record
            type_store <- type_store { records = records }
            mir_variant <- MD.Variant variant_name (MT.Record record_identity [])
            adt_identity <- Identity getInternalModuleName name 0
            type_store <- TS.addVariant type_store adt_identity mir_variant
            context <- context { type_store = type_store }
            context) context
        context) context
    context.closure_store.closure_calls |> Map.iter |> fold (\context, (closure_call_name, closure_call_identity) -> do
        closure <- case get context.closure_store.closures closure_call_name of
            Some closure -> closure
            None -> panic "Closure not found {}" % closure_call_name
        adt_identity <- (getClosureIdentity closure.name)
        closure_call_function <- getFunction context.mir_program closure_call_identity
        mir_closure_type <- MT.Adt adt_identity []
        adt <- TS.getAdt context.type_store adt_identity
        (context, cases, _) <- closure.instances |> List.iter |> fold (\(context, cases, index), closure_instance -> do
            variant <- atIndex adt.variants index
            variant_type <- TS.getRecord context.type_store (MT.getIdentity variant.type)
            ClosureInstanceId id <- closure_instance.id
            (context, prev_var) <- getNextTempVar context
            prev_var_ref <- ME.VarRef prev_var
            (context, prev_var_ref_expr) <- getExpr context (ME.Expr prev_var_ref variant.type)
            (context, args) <- closure_instance.args |> List.iter |> fold (\(context, arg_refs), arg -> do
                field_index <- getLength arg_refs
                field <- atIndex variant_type.fields field_index
                arg_ref <- ME.FieldAccess field.name prev_var_ref_expr
                (context, arg_ref_expr) <- getExpr context (ME.Expr arg_ref field.type)
                (context, arg_refs + [arg_ref_expr])) (context, [])
            next_fn <- case Option.unwrap (get context.closure_store.successors closure_instance) of
                NextClosureInstance fn -> fn
                RealFunctionCall fn -> fn
            arg_ref1 <- ME.VarRef (ME.Arg 1)
            arg_ref1_type <- atIndex closure_call_function.args 1
            (context, arg_ref1_expr) <- getExpr context (ME.Expr arg_ref1 arg_ref1_type)
            args <- args + [arg_ref1_expr]
            (context, body_expr) <- do
                    mir_function <- getFunction context.mir_program next_fn
                    body <- ME.StaticFunctionCall next_fn args
                    (context, body_expr) <- getExpr context (ME.Expr body mir_function.result)
                    getExpr context (ME.Expr (ME.Do [body_expr]) mir_function.result)
            checker <- ME.VariantChecker id prev_var mir_closure_type
            c <- ME.Case checker body_expr
            cases <- cases + [c]
            (context, cases, index + 1)) (context, [], 0)
        arg_ref0 <- ME.VarRef (ME.Arg 0)
        arg_ref0_type <- atIndex closure_call_function.args 0
        (context, arg_ref0_expr) <- getExpr context (ME.Expr arg_ref0 arg_ref0_type)
        new_body <- ME.CaseOf arg_ref0_expr cases
        (context, new_body_expr) <- getExpr context (ME.Expr new_body closure_call_function.result)
        new_kind <- MF.Normal new_body_expr
        mir_program <- context.mir_program
        mir_program <- updateFunctionKind context.mir_program closure_call_identity new_kind
        context <- context { mir_program = mir_program }
        context) context