module Siko.Typechecker.Lowering.Expr where

import Siko.Typechecker
import Siko.Typechecker.Class
import Siko.Typechecker.CaseChecker
import Siko.Typechecker.ClassStore
import Siko.Typechecker.Lowering
import Siko.Typechecker.Lowering.FunctionQueue as FQ
import Siko.Typechecker.Lowering.TypeStore
import Siko.Typechecker.Lowering.ClosureStore as CS
import Siko.Typechecker.Lowering.Util
import Siko.Typechecker.Lowering.ClassMemberCalls
import Siko.Typechecker.Unification as U
import Siko.Typechecker.Util as TUtil
import Siko.Typechecker.InstanceResolver as IR
import Siko.Typechecker.FunctionStore as FS
import Siko.HIR.Program as HPO
import Siko.HIR.Function as HF
import Siko.HIR.Expr as HE
import Siko.HIR.Class as HC
import Siko.HIR.Pattern as HP
import Siko.HIR.Data as HD
import Siko.HIR.Type as HT
import Siko.MIR.Expr as ME
import Siko.MIR.Type as MT
import Siko.MIR.Data as MD
import Siko.MIR.Program as MP
import Siko.Syntax.Ident
import Siko.Constants
import Map

processArgs :: Context -> U.Substitution -> [HE.Expr] -> (Context, [ME.Expr])
processArgs context sub args = do
    (context, mir_args) <- args |> List.iter |> fold (\(context, mir_args), e -> do
                (context, mir_arg) <- processExpr context sub e
                (context, mir_args + [mir_arg])) (context, [])
    (context, mir_args)

getMonomorphizedExprType :: Context -> U.Substitution -> HE.ExprId -> HT.Type
getMonomorphizedExprType context sub id = do
    type <- getExprType context.type_store id
    type <- HT.removeFixed type
    U.apply sub type

getMonomorphizedPatternType :: Context -> U.Substitution -> HP.PatternId -> HT.Type
getMonomorphizedPatternType context sub id = do
    type <- getPatternType context.type_store id
    type <- HT.removeFixed type
    U.apply sub type

processArgTypes :: Context -> U.Substitution -> [HE.Expr] -> [HT.Type]
processArgTypes context sub args =
    args |> List.iter |> map (\(HE.Expr _ id _) -> do
                getMonomorphizedExprType context sub id) |> toList

getFieldType :: MD.Record -> String -> MT.Type
getFieldType mir_record field_name = do
    loop index <- 0 do
        field <- atIndex mir_record.fields index
        if field.name == field_name then return field.type else index + 1

processBindArgs :: Context -> U.Substitution -> [HP.Pattern] -> ME.Expr -> MD.Record -> (Context, [ME.Expr])
processBindArgs context sub args var_ref_expr mir_record = do
    (context, arg_exprs, _) <- args |> List.iter |> fold (\(context, arg_exprs, index), arg -> do
        field <- atIndex mir_record.fields index
        field_access <- ME.FieldAccess field.name var_ref_expr
        field_access_expr <- ME.Expr field_access field.type
        (context, exprs) <- processBind context sub arg field_access_expr
        arg_exprs <- arg_exprs + exprs
        (context, arg_exprs, index + 1)) (context, [], 0)
    (context, arg_exprs)

processBind :: Context -> U.Substitution -> HP.Pattern -> ME.Expr -> (Context, [ME.Expr])
processBind context sub (HP.Pattern p id _) rhs = do
    (context, unit_type) <- processType context (HT.Tuple [])
    case p of
        HP.Binding ref -> do
            HP.BindRef _ pattern_id <- ref
            var <- patternToVar pattern_id
            var_decl <- ME.VarDecl var rhs
            var_decl_expr <- ME.Expr var_decl unit_type
            (context, [var_decl_expr])
        HP.Tuple args -> do
            var <- patternToVar id
            tuple_type <- getMonomorphizedPatternType context sub id
            (context, mir_tuple_type) <- processType context tuple_type
            var_ref <- ME.VarRef var
            var_ref_expr <- ME.Expr var_ref mir_tuple_type
            mir_record <- case mir_tuple_type of
                MT.Record record_id -> getRecord context.type_store record_id
                _ -> panic "Tuple in a bind expr is not a record type!"
            (context, arg_exprs) <- processBindArgs context sub args var_ref_expr mir_record
            var_decl <- ME.VarDecl var rhs
            var_decl_expr <- ME.Expr var_decl unit_type
            (context, [var_decl_expr] + arg_exprs)
        HP.Guarded _ _ -> panic "Guarded pattern in bind lhs in lowering"
        HP.Wildcard -> (context, [])
        HP.IntegerLiteral _ -> panic "Literal pattern in bind lhs in lowering"
        HP.StringLiteral _ -> panic "Literal pattern in bind lhs in lowering"
        HP.CharLiteral _ -> panic "Literal pattern in bind lhs in lowering"
        HP.CharRange _ _ _ -> panic "Range pattern in bind lhs in lowering"
        HP.Typed p _ -> processBind context sub p rhs
        HP.Record qn args -> do
            var <- patternToVar id
            record_type <- getMonomorphizedPatternType context sub id
            (context, mir_record_type) <- processType context record_type
            var_ref <- ME.VarRef var
            var_ref_expr <- ME.Expr var_ref mir_record_type
            mir_record <- case mir_record_type of
                MT.Record record_id -> getRecord context.type_store record_id
                _ -> panic "Record in a bind expr is not a record type!"
            (context, arg_exprs) <- processBindArgs context sub args var_ref_expr mir_record
            var_decl <- ME.VarDecl var rhs
            var_decl_expr <- ME.Expr var_decl unit_type
            (context, [var_decl_expr] + arg_exprs)
        HP.Variant qn index args -> do
            var <- patternToVar id
            adt_type <- getMonomorphizedPatternType context sub id
            (context, mir_adt_type) <- processType context adt_type
            var_ref <- ME.VarRef var
            var_ref_expr <- ME.Expr var_ref mir_adt_type
            mir_record <- case mir_adt_type of
                MT.Record record_id -> getRecord context.type_store record_id
                _ -> panic "Adt in a bind expr is not a record type!"
            (context, arg_exprs) <- processBindArgs context sub args var_ref_expr mir_record
            var_decl <- ME.VarDecl var rhs
            var_decl_expr <- ME.Expr var_decl unit_type
            (context, [var_decl_expr] + arg_exprs)

// FIXME: remove this stuff now that exprs are typed
data ValuePathInfo = { type :: MT.Type,
                       parent_expr :: ME.Expr
                     }

processCaseEnds :: [MatchInfo] -> [ME.Expr] -> [Option ME.Expr] -> Map ValuePath ValuePathInfo -> MT.Type -> ME.Expr
processCaseEnds match_infos mir_case_bodies mir_guards path_info_map unit_type = do
    if getLength match_infos == 1
        then do
            MatchInfo index additional_info <- atIndex match_infos 0
            mir_case_body <- atIndex mir_case_bodies index
            var_decls <- additional_info.binds |> List.iter |> map (\CaseBind path bind_ref -> do
                HP.BindRef _ pattern_id <- bind_ref
                var <- patternToVar pattern_id
                ref_expr <- case get path_info_map path of
                    Some path_info -> do
                        path_info :: ValuePathInfo <- path_info // FIXME
                        path_info.parent_expr
                    None -> panic "Path {} not found in path_info_map" % path
                var_decl <- ME.VarDecl var ref_expr
                ME.Expr var_decl unit_type) |> toList
            if isEmpty var_decls
                then mir_case_body
                else do
                    ME.Expr _ case_type <- mir_case_body
                    ME.Expr (ME.Do (var_decls + [mir_case_body])) case_type
        else case pop match_infos of
        Some (match_info, match_infos) -> do
            MatchInfo index add <- match_info
            cond_expr <- case atIndex mir_guards index of
                Some g -> g
                None -> panic "guard expr not found"
            then_expr <- atIndex mir_case_bodies index
            else_expr <- processCaseEnds match_infos mir_case_bodies mir_guards path_info_map unit_type
            ME.Expr _ then_type <- then_expr
            ME.Expr (ME.If cond_expr then_expr else_expr) then_type
        None -> panic "Matchinfos ran out!"

processChoiceTree :: Context -> Choice -> Map ValuePath ValuePathInfo -> [ME.Expr] -> [Option ME.Expr] -> (Context, ME.Expr)
processChoiceTree context choice path_info_map mir_case_bodies mir_guards = do
    (context, unit_type) <- processType context (HT.Tuple [])
    case choice of
        Choice path subchoices -> do
            parent_path <- getParentPath path
            parent_info <- case get path_info_map parent_path of
                Some parent_info -> parent_info
                None -> panic "Parent path {} not found in path info map" % parent_path
            (body_expr, body_type) <- case path of
                ItemIndex _ index _ -> do
                    record <- case parent_info.type of
                        MT.Record name -> getRecord context.type_store name
                        _ -> panic "Indexed type is not a record!"
                    field <- atIndex record.fields index
                    body <- ME.FieldAccess field.name parent_info.parent_expr
                    (ME.Expr body field.type, field.type)
                VariantPath _ _ variant_index index _ -> do
                    case parent_info.type of
                        MT.Adt name -> do
                            adt <- getAdt context.type_store name
                            variant <- atIndex adt.variants variant_index
                            variant_type <- getRecord context.type_store variant.type
                            field <- atIndex variant_type.fields index
                            body <- ME.FieldAccess field.name parent_info.parent_expr
                            (ME.Expr body field.type, field.type)
                        MT.Record name -> do
                            record <- case parent_info.type of
                                MT.Record name -> getRecord context.type_store name
                                _ -> panic "Record is not a record!"
                            field <- atIndex record.fields index
                            body <- ME.FieldAccess field.name parent_info.parent_expr
                            (ME.Expr body field.type, field.type)
                        _ -> panic "Indexed adt is not a record nor an adt"
                _ -> (parent_info.parent_expr, parent_info.type)
            (context, id) <- getNextVarId context
            pattern_var <- ME.Var "m{}" % id
            //println "Parent var {} {} {}" % (id, parent_info.type, body_type)
            pattern_var_ref <- ME.VarRef pattern_var
            pattern_var_ref_expr <- ME.Expr pattern_var_ref body_type
            (path_info_map, _) <- insert path_info_map path (ValuePathInfo body_type pattern_var_ref_expr)
            (context, cases) <- subchoices |> Map.iter |> fold (\(context, cases), (cond, subchoices) -> do
                choice <- atIndex subchoices 0
                (context, choice_expr) <- processChoiceTree context choice path_info_map mir_case_bodies mir_guards
                (cond, expr) <- case cond of
                    IntegerCondition literal -> do
                        (ME.IntegerChecker literal, choice_expr)
                    StringCondition literal -> do
                        (ME.StringChecker literal, choice_expr)
                    CharCondition literal -> do
                        (ME.CharChecker literal, choice_expr)
                    CharRangeCondition s e kind -> do
                        (ME.CharRangeChecker s e (case kind of
                                                    HP.Inclusive -> ME.Inclusive
                                                    HP.Exclusive -> ME.Exclusive), choice_expr)
                    VariantCondition index -> do
                        (ME.VariantChecker index pattern_var body_type, choice_expr)
                    WildcardCondition -> do
                        (ME.WildcardChecker, choice_expr)
                c <- ME.MatchCase cond expr
                cases <- cases + [c]
                (context, cases)) (context, [])
            var_decl <- ME.VarDecl pattern_var body_expr
            var_decl_expr <- ME.Expr var_decl unit_type
            var_ref <- ME.VarRef pattern_var
            var_ref_expr <- ME.Expr var_ref body_type
            ME.MatchCase _ (ME.Expr _ first_case_type) <- atIndex cases 0
            match <- ME.Match var_ref_expr cases
            match_expr <- ME.Expr match first_case_type
            do_expr <- ME.Expr (ME.Do [var_decl_expr, match_expr]) first_case_type
            (context, do_expr)
        CaseEnd cs -> do
            expr <- processCaseEnds cs mir_case_bodies mir_guards path_info_map unit_type
            (context, expr)

patternToVar :: HP.PatternId -> ME.Var
patternToVar pattern_id = do
    HP.PatternId id <- pattern_id
    ME.Var ("p_" + show id)

processDynamicFunctionCall :: Context -> HT.Type -> [ME.Expr] -> ME.Expr -> (Context, [ME.Expr])
processDynamicFunctionCall context receiver_type mir_args mir_receiver = do
    (context, calls) <- loop (context, receiver_type, args, receiver, calls)
                                  <- (context, receiver_type, mir_args, mir_receiver, []) do
                context :: Context <- context // FIXME
                (closure_store, name) <- CS.getClosureName context.closure_store receiver_type
                context <- context { closure_store = closure_store }
                result_type <- HT.getResultType receiver_type 1
                case pop args of
                    Some (arg, rest) -> do
                        (context, id) <- getNextVarId context
                        var <- ME.Var "closure{}" % id
                        function_type <- HT.Function receiver_type receiver_type
                        queue_item <- FQ.ClosureCall name function_type
                        (context, function_id) <- FQ.insert context queue_item
                        (context, mir_expr_type) <- processType context result_type
                        call <- ME.StaticFunctionCall function_id [receiver, arg]
                        call_expr <- ME.Expr call mir_expr_type
                        (context, unit_type) <- processType context (HT.Tuple [])
                        decl <- ME.VarDecl var call_expr
                        decl_expr <- ME.Expr decl unit_type
                        receiver <- ME.VarRef var
                        receiver_expr <- ME.Expr receiver mir_expr_type
                        calls <- calls + [decl_expr]
                        (context, result_type, rest, receiver_expr, calls)
                    None -> do
                        calls <- calls + [receiver]
                        break (context, calls)
    (context, calls)

processClassMemberCall :: Context ->
                         HT.Type ->
                         HT.Type ->
                         HPO.FullyQualifiedName ->
                         HPO.FullyQualifiedName ->
                         [ME.Expr] ->
                         Bool ->
                         (Context, ME.Expr)
processClassMemberCall context function_type arg_type class_name qn mir_args has_default_impl = do
    member_name <- HPO.getShortName qn
    entry <- IR.CacheEntry arg_type class_name
    (context, instance_info) <- case get context.state.instance_resolver.cache entry of
        Some instance_info -> (context, instance_info)
        None -> do
            // on demand check instance
            // code generated by lowering is not typechecked
            // some instance may not be in cache
            state <- context.state
            case IR.checkInstance state arg_type class_name of
                Ok (state, _) -> do
                    state :: TypecheckerState <- state
                    case get state.instance_resolver.cache entry of
                        Some instance_info -> do
                            context <- context { state = state }
                            (context, instance_info)
                        None -> panic "{}/{} not found in instance resolution cache" % (HT.toString arg_type, class_name)
                Err _ -> panic "{}/{} not found in instance resolution cache and no instance found" % (HT.toString arg_type, class_name)
    (context, function_id, arg_count) <- case instance_info of
        IR.UserDefinedInstanceInfo type instance_id _ -> do
            user_instance <- HPO.getInstance context.hir_program instance_id
            selected_member_name <- user_instance.members |> List.iter |> fold (\selected_member_name, member -> do
                name <- HPO.getShortName member
                if name == member_name
                    then Some member
                    else selected_member_name) None
            selected_member_name <- case selected_member_name of
                Some selected_member_name -> selected_member_name
                None -> qn
            function_type_info <- FS.getFunctionTypeInfo context.function_store selected_member_name
            arg_count <- getLength function_type_info.args
            queue_item <- FQ.Normal selected_member_name function_type
            (context, function_id) <- FQ.insert context queue_item
            (context, function_id, arg_count)
        IR.AutoDerivedInstanceInfo instance_id -> do
            if has_default_impl
                then do
                    queue_item <- FQ.Normal qn function_type
                    function_type_info <- FS.getFunctionTypeInfo context.function_store qn
                    arg_count <- getLength function_type_info.args
                    (context, function_id) <- FQ.insert context queue_item
                    (context, function_id, arg_count)
                else do
                    queue_item <- FQ.AutoDerive arg_type function_type class_name member_name
                    arg_count <- HT.getArgCount function_type
                    (context, function_id) <- FQ.insert context queue_item
                    (context, function_id, arg_count)
    processStaticFunctionCall context mir_args function_type function_id arg_count

processFormatExpr :: Context -> String -> [ME.Expr] -> [ME.Expr] -> (Context, ME.Expr)
processFormatExpr  context fmt exprs args = do
    subs <- String.split fmt "{}"
    string_type <- TUtil.getStringType
    (context, unit_type) <- processType context (HT.Tuple [])
    (context, mir_string_type) <- processType context string_type
    (context, exprs) <- loop (context, subs, args, exprs, prev) <- (context, subs, args, exprs, None) do
        (context, subs, exprs, sub_var) <- case pop subs of
            Some (head, rest) -> do
                (context, id) <- getNextVarId context
                var <- ME.Var "fmt{}" % id
                head_expr <- ME.Expr (ME.StringLiteral head) mir_string_type
                var_decl <- ME.VarDecl var head_expr
                var_decl_expr <- ME.Expr var_decl unit_type
                exprs <- exprs + [var_decl_expr]
                var_ref_expr <- ME.Expr (ME.VarRef var) mir_string_type
                (context, rest, exprs, var_ref_expr)
            None -> panic "Subs ran out!"
        (context, exprs, prev) <- case prev of
            Some prev -> do
                (context, prev) <- callOpAdd context string_type prev sub_var
                (context, id) <- getNextVarId context
                var <- ME.Var "fmt{}" % id
                var_decl <- ME.VarDecl var prev
                var_decl_expr <- ME.Expr var_decl unit_type
                exprs <- exprs + [var_decl_expr]
                var_ref_expr <- ME.Expr (ME.VarRef var) mir_string_type
                (context, exprs, var_ref_expr)
            None -> (context, exprs, sub_var)
        (context, args, exprs, arg_var) <- case pop args of
            Some (head, rest) -> do
                (context, id) <- getNextVarId context
                var <- ME.Var "fmt{}" % id
                ME.Expr _ head_type <- head
                var_decl <- ME.VarDecl var head
                var_decl_expr <- ME.Expr var_decl unit_type
                exprs <- exprs + [var_decl_expr]
                var_ref_expr <- ME.Expr (ME.VarRef var) head_type
                (context, rest, exprs, var_ref_expr)
            None -> do
                exprs <- exprs + [prev]
                break (context, exprs)
        (context, prev) <- callOpAdd context string_type prev arg_var
        (context, id) <- getNextVarId context
        var <- ME.Var "fmt{}" % id
        ME.Expr _ prev_type <- prev
        var_decl <- ME.VarDecl var prev
        var_decl_expr <- ME.Expr var_decl unit_type
        exprs <- exprs + [var_decl_expr]
        var_ref_expr <- ME.Expr (ME.VarRef var) prev_type
        (context, subs, args, exprs, Some (var_ref_expr))
    do_expr <- ME.Expr (ME.Do exprs) mir_string_type
    (context, do_expr)

processStaticFunctionCall :: Context -> [ME.Expr] -> HT.Type -> MP.Identity -> Int -> (Context, ME.Expr)
processStaticFunctionCall context mir_args function_type function_id arg_count = do
    arg_types <- HT.getArgsLimited function_type (getLength mir_args)
    current_arg_count <- getLength mir_args
    if arg_count == current_arg_count
        then do
            result_type <- HT.getResultType function_type current_arg_count
            (context, mir_result_type) <- processType context result_type
            call_expr <- ME.Expr (ME.StaticFunctionCall function_id mir_args) mir_result_type
            (context, call_expr)
        else if arg_count > current_arg_count // partial application
            then do
                diff <- arg_count - current_arg_count
                result_type <- HT.getResultType function_type current_arg_count
                (context, closures, functions) <- loop (context, closure_type, arg_types, closures, functions)
                                                <- (context, result_type, arg_types, [], []) do
                    context :: Context <- context // FIXME
                    if getLength functions < diff
                        then do
                            (closure_store, closure_instance) <- CS.addClosureInstance context.closure_store closure_type arg_types
                            closures <- closures + [closure_instance]
                            context <- context { closure_store = closure_store }
                            queue_item <- FQ.ClosureCtor (getLength arg_types) function_type closure_instance
                            (context, function_id) <- FQ.insert context queue_item
                            functions <- functions + [function_id]
                            queue_item <- FQ.ClosureCall closure_instance.name (HT.Function closure_type closure_type)
                            (context, _) <- FQ.insert context queue_item
                            first_arg <- HT.getArgsLimited closure_type 1
                            closure_type <- HT.getResultType closure_type 1
                            (context, closure_type, arg_types + first_arg, closures, functions)
                        else break (context, closures, functions)
                first_closure_fn <- atIndex functions 0
                (closure_store, _) <- closures |> List.iter |> fold (\(closure_store, index), closure -> do
                    closure_store <- if index + 1 == getLength closures
                        then do
                            CS.addClosureInstanceSuccessor closure_store closure (CS.RealFunctionCall function_id)
                        else do
                            next <- atIndex functions (index + 1)
                            CS.addClosureInstanceSuccessor closure_store closure (CS.NextClosureInstance next)
                    (closure_store, index + 1)) (context.closure_store, 0)
                context <- context { closure_store = closure_store }
                (context, mir_result_type) <- processType context result_type
                call_expr <- ME.Expr (ME.StaticFunctionCall first_closure_fn mir_args) mir_result_type
                (context, call_expr)
            else do
                (static_args, dynamic_args) <- List.split mir_args arg_count
                receiver_type <- HT.getResultType function_type (getLength static_args)
                (context, mir_static_call_expr_type) <- processType context receiver_type
                static_call <- ME.StaticFunctionCall function_id static_args
                static_call_expr <- ME.Expr static_call mir_static_call_expr_type
                (context, id) <- getNextVarId context
                var <- ME.Var "closure{}" % id
                (context, unit_type) <- processType context (HT.Tuple [])
                decl <- ME.VarDecl var static_call_expr
                decl_expr <- ME.Expr decl unit_type
                var_ref <- ME.VarRef var
                var_ref_expr <- ME.Expr var_ref mir_static_call_expr_type
                (context, calls) <- processDynamicFunctionCall context receiver_type dynamic_args var_ref_expr
                result_type <- HT.getResultType function_type current_arg_count
                (context, mir_result_type) <- processType context result_type
                do_expr <- ME.Expr (ME.Do ([decl_expr] + calls)) mir_result_type
                (context, do_expr)

removeMulti :: [ME.Expr] -> [ME.Expr]
removeMulti exprs = exprs |> List.iter |> fold (\exprs, expr -> do
                ME.Expr s_expr s_type <- expr
                case s_expr of
                    ME.Multi args -> exprs + args
                    _ -> exprs + [ME.Expr s_expr s_type]) []

processExpr :: Context -> U.Substitution -> HE.Expr -> (Context, ME.Expr)
processExpr context sub hir_expr = do
    HE.Expr expr expr_id _ <- hir_expr
    expr_type <- getMonomorphizedExprType context sub expr_id
    (context, mir_expr_type) <- processType context expr_type
    case expr of
        HE.StaticFunctionCall qn args -> do
            arg_types <- processArgTypes context sub args
            function_type_info <- FS.getFunctionTypeInfo context.function_store qn
            (function_type, var_gen) <- TUtil.instantiateType function_type_info.function_type context.state.var_gen
            state <- context.state // FIXME
            state <- state { var_gen = var_gen }
            (state, function_type, _) <- getFunctionType state arg_types expr_type function_type
            context <- context { state = state }
            queue_item <- FQ.Normal qn function_type
            (context, function_id) <- FQ.insert context queue_item
            arg_count <- getLength function_type_info.args
            (context, mir_args) <- processArgs context sub args
            processStaticFunctionCall context mir_args function_type function_id arg_count
        HE.DynamicFunctionCall receiver args -> do
            HE.Expr _ receiver_id _ <- receiver
            receiver_type <- getMonomorphizedExprType context sub receiver_id
            (context, mir_receiver) <- processExpr context sub receiver
            (context, mir_args) <- processArgs context sub args
            arg_types <- processArgTypes context sub args
            (context, calls) <- processDynamicFunctionCall context receiver_type mir_args mir_receiver
            do_expr <- ME.Expr (ME.Do calls) mir_expr_type
            (context, do_expr)
        HE.ClassMemberCall qn args -> do
            arg_types <- processArgTypes context sub args
            (context, mir_args) <- processArgs context sub args
            fn <- HPO.getFunction context.hir_program qn
            case fn.kind of
                HF.ClassMember class_name -> do
                    member_name <- HPO.getShortName qn
                    class_type_info <- get context.state.class_store.class_type_info_map class_name
                    class_type_info <- Option.unwrap class_type_info // FIXME
                    class_type_info :: ClassTypeInfo <- class_type_info // FIXME
                    case get class_type_info.members member_name of
                        Some member -> do
                            member :: ClassMemberInfo <- member
                            state <- context.state
                            vars <- TUtil.collectVars [] member.type
                            (mapper, var_gen) <- TUtil.initMapper vars state.var_gen
                            state <- state { var_gen = var_gen }
                            member_type <- TUtil.remap mapper member.type
                            arg_type <- TUtil.remap mapper class_type_info.arg_type
                            (state, function_type, sub) <- getFunctionType state arg_types expr_type member_type
                            arg <- U.apply sub arg_type
                            processClassMemberCall context function_type arg class_name qn mir_args member.has_default_impl
                        None -> panic "class member {} not found" % member_name
                _ -> panic "ClassMember calls non class member"
        HE.VariantConstructorCall qn args -> do
            arg_types <- processArgTypes context sub args
            (context, mir_args) <- processArgs context sub args
            HD.VariantInfo qn index _ <- HPO.getVariantInfo context.hir_program qn
            variant <- HPO.getVariant context.hir_program qn index
            function_type <- HPO.getVariantCtor context.hir_program qn index
            (function_type, var_gen) <- TUtil.instantiateType function_type context.state.var_gen
            state <- context.state // FIXME
            state <- state { var_gen = var_gen }
            (state, function_type, _) <- getFunctionType state arg_types expr_type function_type
            context <- context { state = state }
            queue_item <- FQ.VariantCtor qn index variant.name function_type
            (context, function_id) <- FQ.insert context queue_item
            arg_count <- getLength variant.items
            processStaticFunctionCall context mir_args function_type function_id arg_count
        HE.RecordConstructorCall qn args -> do
            arg_types <- processArgTypes context sub args
            (context, mir_args) <- processArgs context sub args
            record <- HPO.getRecord context.hir_program qn
            (function_type, var_gen) <- TUtil.instantiateType record.record_ctor context.state.var_gen
            state <- context.state // FIXME
            state <- state { var_gen = var_gen }
            (state, function_type, _) <- getFunctionType state arg_types expr_type function_type
            context <- context { state = state }
            queue_item <- FQ.RecordCtor qn function_type
            (context, function_id) <- FQ.insert context queue_item
            arg_count <- getLength record.fields
            processStaticFunctionCall context mir_args function_type function_id arg_count
        HE.If cond true_branch false_branch -> do
            (context, mir_cond) <- processExpr context sub cond
            (context, mir_true_branch) <- processExpr context sub true_branch
            (context, mir_false_branch) <- processExpr context sub false_branch
            if_expr <- ME.Expr (ME.If mir_cond mir_true_branch mir_false_branch) mir_expr_type
            (context, if_expr)
        HE.Tuple args -> do
            arg_types <- processArgTypes context sub args
            (var_gen, function_type) <- TUtil.createGeneralFunction (getLength args) context.state.var_gen
            (context, mir_args) <- processArgs context sub args
            state <- context.state // FIXME
            state <- state { var_gen = var_gen }
            (state, function_type, _) <- getFunctionType state arg_types expr_type function_type
            context <- context { state = state }
            queue_item <- FQ.TupleCtor function_type
            (context, function_id) <- FQ.insert context queue_item
            tuple_ctor_call_expr <- ME.Expr (ME.StaticFunctionCall function_id mir_args) mir_expr_type
            (context, tuple_ctor_call_expr)
        HE.List args -> do
            (context, mir_args) <- processArgs context sub args
            list_expr <- ME.Expr (ME.List mir_args) mir_expr_type
            (context, list_expr)
        HE.IntegerLiteral lit -> do
            lit_expr <- ME.Expr (ME.IntegerLiteral lit) mir_expr_type
            (context, lit_expr)
        HE.FloatLiteral lit -> do
            lit_expr <- ME.Expr (ME.FloatLiteral lit) mir_expr_type
            (context, lit_expr)
        HE.StringLiteral lit -> do
            lit_expr <- ME.Expr (ME.StringLiteral lit) mir_expr_type
            (context, lit_expr)
        HE.CharLiteral lit -> do
            lit_expr <- ME.Expr (ME.CharLiteral lit) mir_expr_type
            (context, lit_expr)
        HE.Do args -> do
            (context, mir_args) <- processArgs context sub args
            mir_args <- removeMulti mir_args
            do_expr <- ME.Expr (ME.Do mir_args) mir_expr_type
            (context, do_expr)
        HE.Bind p arg -> do
            (context, mir_arg) <- processExpr context sub arg
            (context, exprs) <- processBind context sub p mir_arg
            multi_expr <- ME.Expr (ME.Multi exprs) mir_expr_type
            (context, multi_expr)
        HE.FieldAccess name receiver -> do
            Ident name _ <- name
            (context, mir_receiver) <- processExpr context sub receiver
            field_access_expr <- ME.Expr (ME.FieldAccess name mir_receiver) mir_expr_type
            (context, field_access_expr)
        HE.TupleFieldAccess index receiver -> do
            name <- getFieldName index
            (context, mir_receiver) <- processExpr context sub receiver
            field_access_expr <- ME.Expr (ME.FieldAccess name mir_receiver) mir_expr_type
            (context, field_access_expr)
        HE.Formatter fmt args -> do
            (context, exprs, mir_args) <- args |> List.iter |> fold (\(context, exprs, mir_args), arg -> do
                (HE.Expr _ id _) <- arg
                arg_type <- getMonomorphizedExprType context sub id
                (context, id) <- getNextVarId context
                var <- ME.Var "fmt{}" % id
                (context, mir_arg) <- processExpr context sub arg
                (context, show_result) <- callOpShow context arg_type mir_arg
                (context, unit_type) <- processType context (HT.Tuple [])
                ME.Expr _ show_result_type <- show_result
                var_decl <- ME.VarDecl var show_result
                var_decl_expr <- ME.Expr var_decl unit_type
                exprs <- exprs + [var_decl_expr]
                var_ref_expr <- ME.Expr (ME.VarRef var) show_result_type
                mir_args <- mir_args + [var_ref_expr]
                (context, exprs, mir_args)) (context, [], [])
            processFormatExpr context fmt exprs mir_args
        HE.CaseOf body hir_cases bind_groups -> do
            hir_case_bodies <- hir_cases |> List.iter |> map (\HE.Case _ body -> body) |> toList
            hir_guards <- hir_cases |> List.iter |> map (\HE.Case p _ -> do
                HP.Pattern p _ _ <- p
                case p of
                    HP.Guarded _ expr -> Some expr
                    _ -> None) |> toList
            (context, mir_case_bodies) <- processArgs context sub hir_case_bodies
            (context, mir_guards) <- hir_guards |> List.iter |> fold (\(context, mir_guards), guard_expr -> do
                (context, mir_guard_expr) <- case guard_expr of
                    Some expr -> do
                        (context, mir_guard_expr) <- processExpr context sub expr
                        (context, Some mir_guard_expr)
                    None -> (context, None)
                mir_guards <- mir_guards + [mir_guard_expr]
                (context, mir_guards)) (context, [])
            (context, mir_body) <- processExpr context sub body
            HE.Expr _ body_id _ <- body
            hir_body_type <- getMonomorphizedExprType context sub body_id
            (context, mir_body_type) <- processType context hir_body_type
            (context, match_expr) <- case get context.state.choice_tree_store.choice_trees expr_id of
                Some choice_tree -> do
                    p <- Option.unwrap (getValuePath choice_tree)
                    (path_info_map, _) <- insert empty p (ValuePathInfo mir_body_type mir_body)
                    processChoiceTree context choice_tree path_info_map mir_case_bodies mir_guards
                None -> panic "Choice tree not found"
            (context, match_expr)
        HE.RecordUpdate ref updates -> do
            HP.BindRef _ pattern_id <- ref
            var <- patternToVar pattern_id
            (context, mir_updates) <- updates |> List.iter
                    |> fold (\(context, mir_updates), update -> do
                        (context, mir_update_body) <- processExpr context sub update.body
                        Ident name _ <- update.field_name
                        mir_update <- ME.RecordUpdateItem name mir_update_body
                        mir_updates <- mir_updates + [mir_update]
                        (context, mir_updates)) (context, [])
            record_update_expr <- ME.Expr (ME.RecordUpdate var mir_updates) mir_expr_type
            (context, record_update_expr)
        HE.Return arg -> do
            (context, mir_arg) <- processExpr context sub arg
            return_expr <- ME.Expr (ME.Return mir_arg) mir_expr_type
            (context, return_expr)
        HE.Continue arg -> do
            (context, mir_arg) <- processExpr context sub arg
            continue_expr <- ME.Expr (ME.Continue mir_arg) mir_expr_type
            (context, continue_expr)
        HE.Break arg -> do
            (context, mir_arg) <- processExpr context sub arg
            break_expr <- ME.Expr (ME.Break mir_arg) mir_expr_type
            (context, break_expr)
        HE.Loop p initializer args _ _ -> do
            HP.Pattern _ pattern_id _ <- p
            var <- patternToVar pattern_id
            (context, mir_initializer) <- processExpr context sub initializer
            (context, exprs) <- processBind context sub p mir_initializer
            exprs <- Option.unwrap (tail exprs)
            (context, mir_args) <- processArgs context sub args
            mir_args <- removeMulti mir_args
            mir_args <- exprs + mir_args
            loop_expr <- ME.Expr (ME.Loop var mir_initializer mir_args) mir_expr_type
            (context, loop_expr)
        HE.ArgRef index -> do
            arg_ref_expr <- ME.Expr (ME.ArgRef index) mir_expr_type
            (context, arg_ref_expr)
        HE.ValueRef ref -> do
            HP.BindRef _ pattern_id <- ref
            var <- patternToVar pattern_id
            var_ref_expr <- ME.Expr (ME.VarRef var) mir_expr_type
            (context, var_ref_expr)