module Siko.Typechecker.Lowering.Function where

import Siko.Typechecker.Lowering
import Siko.Typechecker.FunctionStore
import Siko.Typechecker.Unification as U
import Siko.Typechecker.Lowering.FunctionQueue
import Siko.Typechecker.Lowering.Util
import Siko.Typechecker.Lowering.Expr
import Siko.HIR.Program as HP
import Siko.MIR.Program as MP
import Siko.HIR.Type as HT
import Siko.HIR.Function as HF
import Siko.MIR.Function as MF

processFunction :: Context -> HP.FullyQualifiedName -> CallContext -> MF.FunctionId -> FunctionQueue -> (Context, FunctionQueue)
processFunction context qn call_context mir_function_id queue = do
    hir_function <- HP.getFunction context.hir_program qn
    function_type_info <- getFunctionTypeInfo context.function_store qn
    (state, sub) <- getCallSubstitution context.state call_context.args call_context.result function_type_info
    context <- context { state = state }
    mir_function_type_info <- applyTypeInfo function_type_info sub
    (mir_function, queue) <- case hir_function.kind of
        HF.Normal -> do
            case hir_function.body of
                Some hir_body -> do
                    //println "Processing {} {}" % (hir_function.name, HT.toString function_type_info.function_type)
                    (queue, mir_body) <- processExpr context sub hir_body queue
                    mir_function <- MF.Function mir_function_id (MF.Normal mir_body)
                    (mir_function, queue)
                None -> do
                    //println "Processing extern {}" % (hir_function.name)
                    (MF.Function mir_function_id MF.Extern, queue)
        _ -> panic "processing of function kind {} is not implemented" % hir_function.kind
    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
    context <- context { mir_program = mir_program }
    (context, queue)
