module Siko.Typechecker.Lowering.FunctionQueue where

import Siko.HIR.Type as HT
import Siko.HIR.Data as HD
import Siko.HIR.Program as HP
import Siko.HIR.Function as HF
import Siko.MIR.Type as MT
import Siko.MIR.Expr as ME
import Siko.MIR.Function as MF
import Siko.MIR.Program as MP
import Siko.Typechecker
import Siko.Typechecker.DataStore as DS
import Siko.Typechecker.Unification as U
import Siko.Typechecker.Lowering
import Siko.Typechecker.FunctionStore
import Siko.Typechecker.Lowering.ClosureStore as CS
import Siko.Typechecker.Lowering.Expr
import Siko.Typechecker.Lowering.Util as Util
import Siko.Typechecker.Lowering.TypeStore as TS
import Siko.Typechecker.Util as TUtil
import Siko.Constants
import Map

data FunctionQueueItem = Normal HP.FullyQualifiedName HT.Type
                         | VariantCtor HP.FullyQualifiedName Int String HT.Type
                         | RecordCtor HP.FullyQualifiedName HT.Type
                         | TupleCtor HT.Type
                         | ClosureCtor Int HT.Type CS.ClosureInstance
                         | ClosureCall String HT.Type
                         | AutoDerive HT.Type HT.Type HP.FullyQualifiedName String
                         | ExternalCallImpl HP.FullyQualifiedName HT.Type String
                         deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data FunctionQueue = { pending :: [(FunctionQueueItem, MF.FunctionId)],
                       processed :: Map FunctionQueueItem MF.FunctionId,
                       next_id :: Int,
                     }

createFunctionQueue :: FunctionQueue
createFunctionQueue = FunctionQueue [] Map.empty 0

getItemName :: FunctionQueueItem -> String
getItemName item = case item of
    Normal n _ -> "{}" % n
    VariantCtor n _ vn _ -> "{}_{}" % (n, vn)
    RecordCtor n _ -> "{}" % n
    TupleCtor _ -> "TupleCtor"
    ClosureCtor _ _ closure_instance -> CS.getVariantCtorName closure_instance
    ClosureCall n _ -> "ClosureCall{}" % n
    AutoDerive _ _ qn n -> "{}/{}" % (qn, n)
    ExternalCallImpl _ _ n -> "{}" % n

insert :: FunctionQueue -> FunctionQueueItem -> (FunctionQueue, MF.FunctionId)
insert queue item = do
    case get queue.processed item of
        Some function_id -> (queue, function_id)
        None -> do
            id <- queue.next_id
            name <- getItemName item
            function_id <- MF.FunctionId name id
            (processed, _) <- Map.insert queue.processed item function_id
            pending <- queue.pending + [(item, function_id)]
            queue <- queue { processed = processed, pending = pending, next_id = id + 1 }
            (queue, function_id)

getFunctionType :: Context -> HT.Type -> Int -> (Context, MT.Type)
getFunctionType context hir_type arg_count = do
    if arg_count == 0
        then TS.processType context hir_type
        else do
            hir_args <- HT.getArgs hir_type
            (hir_args, _) <- List.split hir_args arg_count
            hir_result_type <- HT.getResultType hir_type arg_count
            (context, mir_args) <- hir_args |> List.iter |> fold (\(context, mir_args), hir_arg -> do
                            (context, mir_arg) <- TS.processType context hir_arg
                            mir_args <- mir_args + [mir_arg]
                            (context, mir_args)
                        ) (context, [])
            (context, mir_result_type) <- TS.processType context hir_result_type
            mir_type <- MT.Function mir_args mir_result_type
            (context, mir_type)

processNormalFunction :: FunctionQueue -> Context -> MF.FunctionId -> HT.Type -> HP.FullyQualifiedName -> HF.Function -> (Context, FunctionQueue)
processNormalFunction queue context mir_function_id hir_type qn hir_function =
    case hir_function.body of
        Some hir_body -> do
            state <- context.state
            function_type_info <- getFunctionTypeInfo context.function_store qn
            function_type <- HT.removeFixed function_type_info.function_type
            sub <- U.createSubstitution
            (state, sub) <- case U.unify state.var_gen sub state.data_store state.class_store
                                hir_type function_type of
                Ok (var_gen, sub) -> (state { var_gen = var_gen}, sub)
                Err _ -> panic "Failed to unify {} {} for normal function in MIR lowering" %
                            (HT.toString hir_type, HT.toString function_type)
            context <- context { state = state }
            (context, queue, mir_body) <- processExpr context queue sub hir_body
            (context, mir_type) <- getFunctionType context hir_type hir_function.arg_count
            mir_function <- MF.Function mir_function_id (MF.Normal mir_body) mir_type
            mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
            context <- context { mir_program = mir_program }
            (context, queue)
        None -> do
            //println "Processing extern {}" % (hir_function.name)
            (context, mir_type) <- getFunctionType context hir_type hir_function.arg_count
            mir_function <- MF.Function mir_function_id MF.Extern mir_type
            mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
            context <- context { mir_program = mir_program }
            (context, queue)

generateShowInstance :: Context -> FunctionQueue -> HT.Type -> HT.Type -> HP.FullyQualifiedName -> (Context, FunctionQueue, ME.Expr)
generateShowInstance context queue hir_type hir_function_type class_name = do
    (context, queue, body) <- case hir_type of
        HT.Named qn _ -> do
            case DS.getDataTypeInfo context.state.data_store qn of
                DS.Adt adt -> do
                    (context, adt) <- TS.instantiateAdt context adt hir_type
                    (context, id) <- getNextVarId context
                    var <- ME.Var "m{}" % id
                    decl <- ME.VarDecl var (ME.ArgRef 0)
                    (context, queue, cases) <- adt.variants |> List.iter |> fold (\(context, queue, cases), variant -> do
                        checker <- ME.VariantChecker (getLength cases) var
                        (context, queue, fmt_args, mir_items) <- variant.items |> List.iter
                                    |> fold (\(context, queue, fmt_args, mir_items), item -> do
                                        function_type <- HT.Function item (TUtil.getStringType)
                                        field_name <- Util.getFieldName (getLength mir_items)
                                        field_access <- ME.FieldAccess field_name (ME.VarRef var)
                                        show_qn <- HP.FullPath getStdOpsModuleName getShowClassMemberName
                                        (context, queue, mir_item) <- processClassMemberCall context queue function_type
                                                                      item class_name show_qn [field_access] False
                                        fmt_arg <- if HT.isSimple item then "{}" else "({})"
                                        fmt_args <- fmt_args + [fmt_arg]
                                        mir_items <- mir_items + [mir_item]
                                        (context, queue, fmt_args, mir_items)) (context, queue, [], [])
                        fmt <- if isEmpty fmt_args
                            then "{}" % variant.name
                            else "{} {}" % (variant.name, (join fmt_args " "))
                        body <- ME.Formatter fmt mir_items
                        c <- ME.MatchCase checker body
                        cases <- cases + [c]
                        (context, queue, cases)) (context, queue, [])
                    body <- ME.Match (ME.VarRef var) cases
                    (context, queue, ME.Do [decl, body])
                DS.Record record -> do
                    (context, record) <- TS.instantiateRecord context record hir_type
                    (context, id) <- getNextVarId context
                    var <- ME.Var "m{}" % id
                    decl <- ME.VarDecl var (ME.ArgRef 0)
                    (context, queue, fmt_args, mir_items) <- record.fields |> List.iter |> fold (\(context, queue, fmt_args, mir_items), field -> do
                        function_type <- HT.Function field.type (TUtil.getStringType)
                        field_access <- ME.FieldAccess field.name (ME.VarRef var)
                        show_qn <- HP.FullPath getStdOpsModuleName getShowClassMemberName
                        (context, queue, mir_item) <- processClassMemberCall context queue function_type
                                                        field.type class_name show_qn [field_access] False
                        fmt_arg <- if HT.isSimple field.type then "{}" else "({})"
                        fmt_args <- fmt_args + [fmt_arg]
                        mir_items <- mir_items + [mir_item]
                        (context, queue, fmt_args, mir_items)) (context, queue, [], [])
                    fmt <- if isEmpty fmt_args
                            then "{}" % record.name
                            else "{} {}" % (record.name, (join fmt_args " "))
                    body <- ME.Formatter fmt mir_items
                    (context, queue, ME.Do [decl, body])
        _ -> panic "Cannot auto derive show for type {}" % HT.toString hir_type
    (context, queue, body)

processItem :: FunctionQueue -> FunctionQueueItem -> MF.FunctionId -> Context -> (Context, FunctionQueue)
processItem queue item mir_function_id context = do
    case item of
        Normal qn hir_type -> do
            hir_function <- HP.getFunction context.hir_program qn
            case hir_function.kind of
                HF.Normal -> processNormalFunction queue context mir_function_id hir_type qn hir_function
                HF.InstanceMember _ -> processNormalFunction queue context mir_function_id hir_type qn hir_function
                HF.ClassMember _ -> processNormalFunction queue context mir_function_id hir_type qn hir_function
                _ -> panic "processing of function kind {} is not implemented" % hir_function.kind
        VariantCtor qn index _ hir_type -> do
                    adt <- HP.getAdt context.hir_program qn
                    variant <- atIndex adt.variants index
                    (context, mir_type) <- getFunctionType context hir_type (getLength variant.items)
                    mir_function <- if getLength adt.variants == 1
                        then MF.Function mir_function_id MF.RecordCtor mir_type
                        else MF.Function mir_function_id (MF.VariantCtor index) mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
        RecordCtor qn hir_type -> do
                    record <- HP.getRecord context.hir_program qn
                    (context, mir_type) <- getFunctionType context hir_type (getLength record.fields)
                    mir_function <- MF.Function mir_function_id MF.RecordCtor mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
        TupleCtor hir_type -> do
                    arg_count <- getLength (HT.getArgs hir_type)
                    (context, mir_type) <- getFunctionType context hir_type arg_count
                    mir_function <- MF.Function mir_function_id MF.RecordCtor mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
        ClosureCtor arg_count hir_type closure_instance -> do
                    (context, mir_type) <- getFunctionType context hir_type arg_count
                    CS.ClosureInstanceId id <- closure_instance.id
                    mir_function <- MF.Function mir_function_id (MF.VariantCtor id) mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
        ClosureCall name hir_type -> do
                    closure_store <- CS.addClosureCall context.closure_store name mir_function_id
                    context <- context { closure_store = closure_store }
                    arg_count <- getLength (HT.getArgs hir_type)
                    (context, mir_type) <- getFunctionType context hir_type 2
                    body <- ME.Do []
                    mir_function <- MF.Function mir_function_id (MF.Normal body) mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
        AutoDerive hir_type hir_function_type class_name member_name -> do
            case (show class_name, member_name) of
                ("Std.Ops.Show", "show") -> do
                    (context, mir_type) <- getFunctionType context hir_function_type 1
                    (context, queue, body) <- generateShowInstance context queue hir_type hir_function_type class_name
                    mir_function <- MF.Function mir_function_id (MF.Normal body) mir_type
                    mir_program <- MP.addFunction context.mir_program mir_function_id mir_function
                    context <- context { mir_program = mir_program }
                    (context, queue)
                _ -> panic "Auto derive not implemented for {} / {} / {}" % (class_name, member_name, HT.toString hir_type)
        _ -> panic "processItem: not yet implemented for {}" % item

processItems :: FunctionQueue -> Context -> Context
processItems queue context = do
    loop (context, queue) <- (context, queue) do
        queue :: FunctionQueue <- queue // FIXME
        case pop queue.pending of
            Some (first, pending) -> do
                (item, id) <- first
                queue <- queue { pending = pending }
                processItem queue item id context
            None -> break context
