module Siko.Syntax.Class where

import Json.Serialize
import Siko.Syntax.Ident
import Siko.Syntax.Function
import Siko.Syntax.TypeSignature (TypeSignature)

data Constraint = {
                    class_name :: Ident,
                    argument :: Ident,
                  } deriving (Show, ToJson, FromJson)

data Class = {
                name :: Ident,
                argument :: Ident,
                constraints :: [Constraint],
                member_functions :: [Function],
                member_function_type_signatures :: [FunctionSignature],
             } deriving (Show, ToJson, FromJson)

data Instance = {
                  class_name :: Ident,
                  type_signature :: TypeSignature,
                  constraints :: [Constraint],
                  member_functions :: [Function],
                  member_function_type_signatures :: [FunctionSignature],
                } deriving (Show, ToJson, FromJson)
