module Siko.Syntax.Pattern where

import Json.Serialize
import Siko.Syntax.Location
import Siko.Syntax.Ident
import Siko.Syntax.Expr as E
import Siko.Syntax.TypeSignature as T

data RangeKind = Exclusive
               | Inclusive deriving (Show, ToJson)

data RecordFieldPattern = {
                            name :: Ident,
                            pattern :: Pattern,
                          } deriving (Show, ToJson)

data Pattern = Pattern SimplePattern Location deriving (ToJson)

instance Show Pattern where
  show (Pattern p _) = show p

data SimplePattern = Binding Ident
                   | Tuple [Pattern]
                   | Constructor Ident [Pattern]
                   | Guarded Pattern E.Expr
                   | Wildcard
                   | IntegerLiteral String
                   | StringLiteral String
                   | CharLiteral Char
                   | CharRange Char Char RangeKind
                   | Typed Pattern T.TypeSignature
                   | Record Ident [RecordFieldPattern]
                   | Or [Pattern]
                   deriving (Show, ToJson)
