#!/usr/bin/env python3
"""Link Siko-generated C or LLVM IR read from stdin using clang."""

import os
import subprocess
import sys


USAGE = "usage: ... | link.py [--llvm] -o <output> [-O] [--debug] [--san] [--tsan]"

TARGET_TRIPLETS = {
    "linux": "x86_64-pc-linux-gnu",
    "macos": "arm64-apple-macosx26.0.0",
}


def parse_args(argv):
    output = ""
    optimize = False
    debug = False
    san = False
    tsan = False
    llvm = True

    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "-o":
            i += 1
            output = argv[i] if i < len(argv) else ""
        elif arg == "-O":
            optimize = True
        elif arg == "--debug":
            debug = True
        elif arg == "--san":
            san = True
        elif arg == "--tsan":
            tsan = True
        elif arg == "--llvm":
            llvm = True
        else:
            print(f"unknown argument: {arg}", file=sys.stderr)
            sys.exit(1)
        i += 1

    if not output:
        print(USAGE, file=sys.stderr)
        sys.exit(1)

    if san and tsan:
        print("error: --san and --tsan are mutually exclusive", file=sys.stderr)
        sys.exit(1)

    return output, optimize, debug, san, tsan, llvm


def get_gc_args(llvm):
    pkg_args = ["pkg-config"]
    if not llvm:
        pkg_args.append("--cflags")
    pkg_args.extend(["--libs", "bdw-gc"])

    result = subprocess.run(
        pkg_args,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    gc_flags = result.stdout if result.returncode == 0 else "-lgc"
    return gc_flags.split()


def build_clang_args(output, optimize, debug, san, tsan, llvm):
    args = ["clang"]

    if llvm:
        target_os = os.environ.get("SIKO_TARGET_OS", "")
        if target_os:
            try:
                args.extend(["-target", TARGET_TRIPLETS[target_os]])
            except KeyError:
                print(f"error: unsupported target os: {target_os}", file=sys.stderr)
                sys.exit(1)
        args.extend(["-x", "ir", "-", "-o", output])
    else:
        # Enum payloads live in uint buffers accessed through casted pointers,
        # which is type punning generated by lower-enums.
        args.extend(
            [
                "-fno-optimize-sibling-calls",
                "-fno-strict-aliasing",
                "-Wno-unused-value",
                "-Wno-pointer-sign",
                "-Wno-incompatible-pointer-types",
                "-x",
                "c",
                "-",
                "-o",
                output,
            ]
        )

    if optimize:
        args.append("-O3")

    if debug:
        args.extend(["-g", "-fno-omit-frame-pointer"])

    if san:
        args.extend(
            [
                "-fsanitize=address,undefined",
                "-fno-sanitize=leak",
                "-fno-omit-frame-pointer",
                "-g",
            ]
        )
    elif tsan:
        args.extend(["-fsanitize=thread", "-fno-omit-frame-pointer", "-g"])

    args.extend(get_gc_args(llvm))
    return args


def main(argv):
    output, optimize, debug, san, tsan, llvm = parse_args(argv)
    clang_args = build_clang_args(output, optimize, debug, san, tsan, llvm)
    os.execvp(clang_args[0], clang_args)


if __name__ == "__main__":
    main(sys.argv[1:])
