#!/usr/bin/env python3
"""Link Siko-generated LLVM IR (stdin) or object files (arguments) using clang."""

import os
import subprocess
import sys


USAGE = "usage: ... | link.py [--llvm] -o <output> [-O] [--debug] [objects...]"

TARGET_TRIPLETS = {
    "linux": "x86_64-pc-linux-gnu",
    "macos": "arm64-apple-macosx26.0.0",
}


def parse_args(argv):
    output = ""
    optimize = False
    debug = False
    llvm = True
    objects = []

    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "-o":
            i += 1
            output = argv[i] if i < len(argv) else ""
        elif arg == "-O":
            optimize = True
        elif arg == "--debug":
            debug = True
        elif arg == "--llvm":
            llvm = True
        elif arg.endswith(".o"):
            objects.append(arg)
        else:
            print(f"unknown argument: {arg}", file=sys.stderr)
            sys.exit(1)
        i += 1

    if not output:
        print(USAGE, file=sys.stderr)
        sys.exit(1)

    return output, optimize, debug, llvm, objects


def get_gc_args(llvm):
    pkg_args = ["pkg-config"]
    if not llvm:
        pkg_args.append("--cflags")
    pkg_args.extend(["--libs", "bdw-gc"])

    result = subprocess.run(
        pkg_args,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    gc_flags = result.stdout if result.returncode == 0 else "-lgc"
    return gc_flags.split()


def get_llvm_lib_args():
    """Linker flags for libLLVM, used by programs that call the LLVM-C API
    (such as the compiler itself). Returns no flags when llvm-config is not
    available; programs that do not use the LLVM-C API still link fine."""
    candidates = [os.environ.get("LLVM_CONFIG"), "llvm-config"]
    if sys.platform == "darwin":
        candidates.append("/opt/homebrew/opt/llvm/bin/llvm-config")
    for candidate in candidates:
        if not candidate:
            continue
        try:
            result = subprocess.run(
                [candidate, "--libdir"],
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                check=False,
            )
        except FileNotFoundError:
            continue
        if result.returncode == 0:
            libdir = result.stdout.strip()
            return [f"-L{libdir}", "-lLLVM", f"-Wl,-rpath,{libdir}"]
    return []


def build_clang_args(output, optimize, debug, llvm, objects):
    args = ["clang"]

    if objects:
        # Objects are already compiled; clang only acts as the linker driver.
        args.extend(objects + ["-o", output])
        args.extend(get_gc_args(True))
        args.extend(get_llvm_lib_args())
        return args

    if llvm:
        target_os = os.environ.get("SIKO_TARGET_OS", "")
        if target_os:
            try:
                args.extend(["-target", TARGET_TRIPLETS[target_os]])
            except KeyError:
                print(f"error: unsupported target os: {target_os}", file=sys.stderr)
                sys.exit(1)
        args.extend(["-x", "ir", "-", "-o", output])
    else:
        # Enum payloads live in uint buffers accessed through casted pointers,
        # which is type punning generated by lower-enums.
        args.extend(
            [
                "-fno-optimize-sibling-calls",
                "-fno-strict-aliasing",
                "-Wno-unused-value",
                "-Wno-pointer-sign",
                "-Wno-incompatible-pointer-types",
                "-x",
                "c",
                "-",
                "-o",
                output,
            ]
        )

    if optimize:
        args.append("-O3")

    if debug:
        args.extend(["-g", "-fno-omit-frame-pointer"])

    args.extend(get_gc_args(llvm))
    args.extend(get_llvm_lib_args())
    return args


def main(argv):
    output, optimize, debug, llvm, objects = parse_args(argv)
    clang_args = build_clang_args(output, optimize, debug, llvm, objects)
    os.execvp(clang_args[0], clang_args)


if __name__ == "__main__":
    main(sys.argv[1:])
