module Std.Ops where

class Show a where
    show a :: a -> String
    bla a :: a -> String
    bla a = show a

module Int where

data Int = extern

module String where

data String = extern

instance Show String where
    show a = a

module Main where

data Complex a = Complex a deriving (Show)

data Color = Red | Blue String | Green String (Complex String) (String, String) deriving (Show)

data Color2 = Red2 | Blue2 | Green2

instance Show Color2 where
    show :: Color2 -> String
    show c = "Color2"

data Color3 = Red3 | Blue3 | Green3

instance Show Color3 where
    show :: Color3 -> String
    show c = "Color3"

data Record a = { b :: a , f :: String, c :: Complex String, i :: (String, (String, )) } deriving (Show)

main = do
    a <- bla Red
    b <- show (Record "a" "b" (Complex "A") ("a", ("b",)))
    ()