module Main where

nextInt :: Int -> Option (Int, Int)
nextInt a = if a > 10 then None else Some (a + 1, a)

nextInt2 :: () -> Option ((), Int)
nextInt2 a = None

nextString :: String -> Option (String, String)
nextString a = None

main = do
    it1 <- createIterator 5 nextInt
    it2 <- createIterator () nextInt2
    sit <- createIterator "a" nextString
    fold (\x,y -> x + y) 0 it1
    getNext it1
    ()