#!/usr/bin/python3

import sys
import os
import errno
import subprocess
import time

def processFile(file):
    content = ""
    f = open(file)
    lines = f.readlines()
    for line in lines:
        l = line.rstrip()
        content += l + "\n"
    last = lines[-1]
    last = last.rstrip()
    if last != "":
        content += "\n"
    return content

def collect_tests(path, tests, parent, selected):
    if os.path.isdir(path):
        files = os.listdir(path)
        found = None
        skip = False
        for f in files:
            full_path = os.path.join(path, f)
            if os.path.isdir(full_path):
                collect_tests(full_path, tests, f, selected)
            else:
                if f == "main.sk":
                    found = (parent, path)
                if f == "SKIP":
                    skip = True
        if found:
            if len(selected) == 0:
                if not skip:
                    tests.append(found)
                else:
                    print("Skipping %s" % parent)
            else:
                if parent in selected:
                    tests.append(found)

def mkdir_safe(folder_name):
    try:
        os.mkdir(folder_name)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise

def run_command(args, name, verbose = False):
    try:
        args = filter(lambda arg: len(arg) > 0, args)
        args = list(args)
        #print("Running %s" % args)
        if verbose:
            subprocess.run(args, check=True)
        else:
            subprocess.run(args, check=True, stderr=subprocess.DEVNULL)
        return True
    except subprocess.CalledProcessError as e:
        print("%s failed" % name)
        return False
    except:
        print("%s failed" % name)
        return False

def getStd():
    return ["./std"]

def run(silent, verbose, debug, test_name, source_folder, index, total, target, pfi, mir_functions):
    if not silent:
        print("--- Running %s - %d/%d - " % (test_name, total, index), end = "", flush=True)
    mkdir_safe("test_runs")
    target_folder = os.path.join("test_runs", test_name)
    mkdir_safe(target_folder)
    std = getStd()
    if pfi:
        pfi_args = ["-pfi"]
    else:
        pfi_args = []
    mir_function_args = []
    for m in mir_functions:
        mir_function_args.append("-m")
        mir_function_args.append(m)
    if not run_command(["./%s" % target, debug, verbose] + std + pfi_args + mir_function_args + [source_folder, "-o", os.path.join(target_folder, test_name)], target, verbose = True):
        return False
    normal_output = os.path.join(target_folder, "normal")
    rc_output = os.path.join(target_folder, "rc")
    if not run_command(["rustc", "--edition=2018", os.path.join(target_folder, "%s.rs" % test_name), "-o", normal_output], "normal rustc", verbose):
        return False
    return run_command([normal_output], "normal build")

test_source_name = "./test"
tests = []
verbose = ""
debug = ""
silent = False
target = "stage0"
pfi = False
mir_functions = []
selected = set()
if len(sys.argv) != 1:
    for (index, t) in enumerate(sys.argv[1:]):
        if index == 0:
            target = t
            continue
        if t == "-v" or t == "-vv":
            verbose = t
            continue
        elif t == "-d":
            debug = "-d"
            continue
        elif t == "-s":
            silent = True
        else:
            selected.add(t)
print('Using target: %s' % target)
collect_tests(test_source_name, tests, None, selected)
total = len(tests)
success = 0
failure = 0
tests = sorted(tests)
for (index, (name, path)) in enumerate(tests):
    start_time = time.time()
    result = run(silent, verbose, debug, name, path, index + 1, total, target, pfi, mir_functions)
    end_time = time.time()
    elapsed_time = end_time - start_time
    if not silent:
        print("{:.2f}s".format(elapsed_time))
    if result:
        success += 1
    else:
        failure += 1
if not silent:
    print("Success %d, failure %d" % (success, failure))
if failure > 0:
    print("Tests failed")
    sys.exit(1)