module Other {

class Struct1 {

}

class Struct2 {
    field1: Struct1
}

}

module Main {

import Other as O
import Other

class Alma {
     field1: Unit
     field2: Unit2
}

fn main() -> Foo {
    let a = b(a, f, d)().foo(test.bar());
    let f = c().foo.alma;
}

fn main2() -> Foo {
    let a = b()().foo();
    let f = c();
    alma.foo();
    {
        alma();
        boo();
    };
    if a { korte(); } else { szilva(); if b { false }};
    loop alma = korte() {
        foo();
        if a { break alma; } else { return foo(); };
        continue pp;
    }
}

}
     
