module Bool {

class Bool {}

}

module Unit {

class Unit {
}

}

module Other {

class Struct1 {

}

class Struct2 {
    field1: Struct1
}

}

module Main {

import Other as O
import Other
import Bool
import Unit

class Alma {
     field1: Unit
     field2: Alma

     fn foo(alma: Bool) -> Unit {
        
     }
}

fn main() -> Bool {
    let a = false;
    let b = Alma();
    b.field2.foo(a);
    other(a, b);
    if true { a } else { a }
}

fn other(b: Bool, a: Alma) -> Bool {
    b
}

}
     
