module Bool {

enum Bool {
    False
    True,
}

}
module Int {

class Int {
    fn add(self, other: Int) -> Int = extern
}

}

module Other.Module {
    
fn siko_runtime_num(i: Int) = extern

fn siko_runtime_bool(i: Bool) = extern

}

module Main {

import Other.Module

fn main() {
    siko_runtime_num(6);
    let result = 6.add(4);
    let result2 = 5.add(6);
    siko_runtime_num(result);
    siko_runtime_num(result2);
    siko_runtime_bool(True);
    siko_runtime_bool(False);
    siko_runtime_bool(False);
    siko_runtime_bool(False);
    siko_runtime_bool(False);
    siko_runtime_bool(False);

}

}