module Siko.Config where

data FileName = FileName String deriving (Show)

data Config = { input_files :: [FileName],
                output_file_name :: Option String,
                verbose :: Bool,
                dump :: Bool }

data OutputFileType = Normal
                    | HIR String
                    | MIR String
                    | LIR Int
                    | MIRJson String

getDefaultConfig :: Config
getDefaultConfig = Config [] None False False

getOutputFileName :: Config -> OutputFileType -> String
getOutputFileName config type = do
    output_file <- case config.output_file_name of
        Some output_file -> output_file
        None -> "sikoc_output"
    case type of
        Normal -> "{}_normal.rs" % output_file
        HIR name -> "{}_hir_{}.sk" % (output_file, name)
        MIR name -> "{}_mir_{}.sk" % (output_file, name)
        LIR index -> "{}_lir_{}.sk" % (output_file, index)
        MIRJson name -> "{}_mir_{}.json" % (output_file, name)
