module Siko.MIR.Backend.Ownership.EqualitySolver(processEquals, addEqual, Equal(..), EqualityStore, Apply, apply) where

import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo
import Map
import List2 as List2
import List2 (List2)
import Map2 as Map2
import Map2 (Map2)

data Applier = { equals :: Map2 TypeVariable TypeVariable } deriving (Show)

addSingleEqual :: Applier -> Equal -> Applier
addSingleEqual applier (Equal id1 id2) = do
    min_id <- min id1 id2
    max_id <- max id1 id2
    if id1 != id2
    then do
        equals <- Map2.put applier.equals max_id min_id
        applier { equals = equals }
    else applier

class Apply a where
    apply a :: Applier -> a -> (Applier, a)

instance Apply TypeVariable where
    apply applier type_variable = do
        loop (applier, type_variable) <- (applier, type_variable) do
            applier :: Applier <- applier // FIXME
            case Map2.get applier.equals type_variable of
                Some t -> (applier, t)
                None -> do
                    break (applier, type_variable)

instance Apply Equal where
    apply applier equal =
        case equal of
            Equal id1 id2 -> do
                (applier, id1) <- apply applier id1
                (applier, id2) <- apply applier id2
                (applier, Equal id1 id2)

instance (Apply a) => Apply (List2 a) where
    apply applier items = List2.updateAllS applier items (\applier, item -> apply applier item)

instance Apply TypeVariableInfo where
    apply applier info = do
        (applier, ownership_var) <- apply applier info.ownership_var
        (applier, arg_group_var) <- apply applier info.arg_group_var
        (applier, TypeVariableInfo ownership_var arg_group_var)

instance Apply MemberInfo where
    apply applier info = case info of
        Variant index root info -> do
            (applier, root) <- apply applier root
            (applier, info) <- apply applier info
            (applier, Variant index root info)
        Member name root info -> do
            (applier, root) <- apply applier root
            (applier, info) <- apply applier info
            (applier, Member name root info)
        Extern index root info -> do
            (applier, root) <- apply applier root
            (applier, info) <- apply applier info
            (applier, Extern index root info)

instance Apply OwnershipInfo where
    apply applier info = case info of
        Unknown v -> do
            (applier, v) <- apply applier v
            (applier, Unknown v)
        Owner v -> do
            (applier, v) <- apply applier v
            (applier, Owner v)
        Borrower v i -> do
            (applier, v) <- apply applier v
            (applier, Borrower v i)

instance (Apply v, Ord k) => Apply Map2 k v where
    apply applier items = Map2.updateS applier items (\applier, (k, v) -> apply applier v)

data Equal = Equal TypeVariable TypeVariable deriving (Show)

addEquals :: List2 Equal -> Applier -> Applier
addEquals equals applier = do
    loop (applier, equals) <- (applier, equals) do
        if List2.isEmpty equals
        then break applier
        else do
            (equal, equals) <- List2.remove equals 0
            applier <- addSingleEqual applier equal
            apply applier equals

data MergeKey b = VariantKey Int b
                | MemberKey String b
                | ExternKey Int b deriving (PartialEq, Eq, PartialOrd, Ord)

addEqual :: List2 Equal -> TypeVariableInfo -> TypeVariableInfo -> List2 Equal
addEqual equals info1 info2 = do
    equals <- List2.push equals (Equal info1.ownership_var info2.ownership_var)
    equals <- List2.push equals (Equal info1.arg_group_var info2.arg_group_var)
    equals

processEquals a :: (EqualityStore a, Apply a) => List2 Equal -> a -> a
processEquals equals store = do
    applier <- addEquals equals (Applier Map2.empty)
    loop (member_infos, applier) <- (getMemberInfos store, applier) do
        (applier, member_infos) <- apply applier member_infos
        (member_infos, equals) <- getEqualsFromMemberInfos member_infos
        if List2.isEmpty equals
        then do
            (applier, store) <- apply applier store
            break store
        else (member_infos, addEquals equals applier)

getEqualsFromMemberInfos :: List2 MemberInfo -> (List2 MemberInfo, List2 Equal)
getEqualsFromMemberInfos members = do
        (members, root_map) <- List2.foldLinear Map.empty members (\root_map, member_info -> case member_info of
                Variant index root info -> do
                    (root_map, _) <- alter (add info) (VariantKey index root) root_map
                    root_map
                Member name root info -> do
                    (root_map, _) <- alter (add info) (MemberKey name root) root_map
                    root_map
                Extern index root info -> do
                    (root_map, _) <- alter (add info) (ExternKey index root) root_map
                    root_map)
        equals <- Map.fold List2.empty root_map (\equals, (_, infos) -> do
            if List2.getLength infos > 1
            then do
                first <- List2.atIndex infos 0
                List2.fold equals infos (\equals, info -> addEqual equals info first)
            else equals)
        (members, equals)
    where
        add info old = case old of
            Some infos -> Some (List2.dedup (List2.sort (List2.push infos info)))
            None -> Some (List2.single info)

class EqualityStore a where
    getMemberInfos a :: a -> List2 MemberInfo
    putMemberInfos a :: a -> List2 MemberInfo -> a
