module Siko.MIR.Backend.Ownership.Inference where

import Siko.MIR.Program as P
import Siko.LIR.Program as LP
import Siko.MIR.Function as F
import Siko.MIR.Expr as E
import Siko.MIR.Type as T
import Siko.MIR.Data as D
import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessor

import Siko.MIR.Backend.Ownership.Lowering
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.Initializer
import Siko.MIR.Backend.Ownership.EqualityGeneration
import Siko.MIR.Backend.Ownership.OwnershipInference
import Siko.MIR.Backend.Ownership.BorrowChecker
import Siko.MIR.Backend.Ownership.FunctionInfoStore
import Siko.MIR.Backend.Ownership.FunctionInfo
import Siko.MIR.Backend.Ownership.ExternProcessor
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo

import List2 as List2
import List2 (List2)

data Context = { config :: Config,
                 program :: P.Program,
                 function_info_store :: FunctionInfoStore }

createRecordCtorFunctionInfo :: Context -> T.Type -> FunctionInfo
createRecordCtorFunctionInfo context type =
    case type of
        T.Record id -> do
            record <- P.getRecord context.program id
            allocator <- createAllocator
            (allocator, result) <- getNextTypeVariableInfo allocator
            (allocator, args, members) <- List.fold (allocator, List2.empty, List2.empty) record.fields (\(allocator, args, members), field -> do
                    (allocator, arg_info) <- getNextTypeVariableInfo allocator
                    member <- Member field.name result.arg_group_var arg_info
                    members <- List2.push members member
                    args <- List2.push args arg_info
                    (allocator, args, members))
            FunctionInfo args result members List2.empty List2.empty
        _ -> panic "createRecordCtorFunctionInfo: not a record"

createVariantctorFunctionInfo :: Context -> Int -> T.Type -> FunctionInfo
createVariantctorFunctionInfo context index type =
    case type of
        T.Adt id -> do
            adt <- P.getAdt context.program id
            variant <- atIndex adt.variants index
            case variant.type of
                T.Record id -> do
                    record <- P.getRecord context.program id
                    allocator <- createAllocator
                    (allocator, adt_result) <- getNextTypeVariableInfo allocator
                    (allocator, record_result) <- getNextTypeVariableInfo allocator
                    (allocator, args, members) <- List.fold (allocator, List2.empty, List2.empty) record.fields (\(allocator, args, members), field -> do
                            (allocator, arg_info) <- getNextTypeVariableInfo allocator
                            member <- Member field.name record_result.arg_group_var arg_info
                            members <- List2.push members member
                            args <- List2.push args arg_info
                            (allocator, args, members))
                    variants <- List2.single (Variant index adt_result.arg_group_var record_result)
                    FunctionInfo args adt_result (members + variants) List2.empty List2.empty
                _ -> panic "createVariantctorFunctionInfo: not a record"
        _ -> panic "createVariantctorFunctionInfo: not an adt"

processFunctionInfo :: Context -> FunctionInfo -> P.Identity -> (Context, Bool)
processFunctionInfo context function_info function_id = do
    function_info <- normalizeFunctionInfo function_info
    function_info_store <- context.function_info_store
    //println "Function info added for {}/{}" % (function_id, getLength function_info.members)
    (function_info_store, added) <- addFunctionInfo function_info_store function_id function_info
    context <- context { function_info_store = function_info_store }
    (context, added)

processFunction :: Context -> [P.Identity] -> P.Identity -> (Context, Bool)
processFunction context group function_id = do
    function <- P.getFunction context.program function_id
    case function.kind of
        F.Normal info -> do
            trace context.config "Ownership inference - processing {}" % function_id
            arg_count <- getLength function.type.args
            inference_info <- createInferenceInfo arg_count
            trace context.config "initializeTypeVariables {}" % function_id
            inference_info <- initializeTypeVariables inference_info info.body
            function_info_store <- context.function_info_store
            trace context.config "processEqualities {}" % function_id
            inference_info <- processEqualities context.config group inference_info function_info_store context.program info.body
            trace context.config "checkBorrows {}" % function_id
            borrow_info <- checkBorrows context.program info.body
            trace context.config "inferOwnership {}" % function_id
            (inference_info, _) <- inferOwnership context.config group context.function_info_store inference_info
                              context.program info.body borrow_info
            trace context.config "Processing {}" % function_id
            function_info <- toFunctionInfo inference_info
            //println "id: {}" % function_id
            //println "inference_info {}" % inference_info
            //println "function_info {}" % function_info
            processFunctionInfo context function_info function_id
        F.VariantCtor index -> do
            function_info <- createVariantctorFunctionInfo context index function.type.result
            processFunctionInfo context function_info function_id
        F.RecordCtor -> do
            function_info <- createRecordCtorFunctionInfo context function.type.result
            processFunctionInfo context function_info function_id
        F.Extern type_mapping -> do
            function_info <- createExternFunctionInfo function_id type_mapping
            processFunctionInfo context function_info function_id

processFunctionGroup :: Int -> Int -> Context -> [P.Identity] -> (Int, Context)
processFunctionGroup index group_count context group = do
    trace context.config "processFunctionGroup {}/{} ({}%) {}" % (index, group_count, index * 100 / group_count, group)
    if getLength group == 1
        then do
            function_id <- atIndex group 0
            (context, _) <- processFunction context group function_id
            (index + 1, context)
        else do
            loop context <- context do
                (context, more) <- group |> List.iter |> Iterator.fold (\(context, more), function_id -> do
                    (context, added) <- processFunction context group function_id
                    more <- if added then True else more
                    (context, more)) (context, False)
                if more then context else break (index + 1, context)

processProgram :: Config -> P.Program -> [DependencyGroup P.Identity] -> LP.Program
processProgram config program function_groups = do
    trace config "Inference"
    context <- Context config program createFunctionInfoStore
    group_count <- getLength function_groups
    (_, context) <- List.fold (1, context) function_groups (\(index, context), group -> processFunctionGroup index group_count context group.items)
    lir_program <- lowerProgram program context.config context.function_info_store
    lir_program