module Siko.MIR.Backend.Ownership.Inference where

import Siko.MIR.Program as P
import Siko.LIR.Program as LP
import Siko.MIR.Function as F
import Siko.MIR.Expr as E
import Siko.MIR.Type as T
import Siko.MIR.Data as D
import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessor

import Siko.MIR.Backend.Ownership.Lowering
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.Initializer
import Siko.MIR.Backend.Ownership.EqualityGeneration
import Siko.MIR.Backend.Ownership.BorrowChecker
import Siko.MIR.Backend.Ownership.FunctionInfoStore
import Siko.MIR.Backend.Ownership.FunctionInfo
import Siko.MIR.Backend.Ownership.ExternProcessor
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Inference.ConstraintCollection
import Siko.MIR.Backend.Ownership.Inference.ConstraintProcessor
import Siko.MIR.Backend.Ownership.DumpOwnership

import List2 as List2
import List2 (List2)
import Map2 as Map2

data Context = { config :: Config,
                 program :: P.Program,
                 function_info_store :: FunctionInfoStore }

createRecordCtorFunctionInfo :: Context -> T.Type -> FunctionInfo
createRecordCtorFunctionInfo context type =
    case type of
        T.Record id -> do
            (program, record) <- P.getRecord context.program id
            context <- context { program = program }
            allocator <- createAllocator
            (allocator, result) <- getNextTypeVariableInfo allocator
            (allocator, args, members) <- List.fold (allocator, List2.empty, List2.empty) record.fields (\(allocator, args, members), field -> do
                    (allocator, arg_info) <- getNextTypeVariableInfo allocator
                    member <- M.MemberInfo (M.Field field.name) type result.arg_group_var arg_info
                    members <- List2.push members member
                    args <- List2.push args arg_info
                    (allocator, args, members))
            FunctionInfo args result members List2.empty List2.empty
        _ -> panic "createRecordCtorFunctionInfo: not a record"

createVariantctorFunctionInfo :: Context -> Int -> T.Type -> FunctionInfo
createVariantctorFunctionInfo context index type =
    case type of
        T.Adt id -> do
            (program, adt) <- P.getAdt context.program id
            context <- context { program = program }
            variant <- atIndex adt.variants index
            case variant.type of
                T.Record id -> do
                    (program, record) <- P.getRecord context.program id
                    context <- context { program = program }
                    allocator <- createAllocator
                    (allocator, adt_result) <- getNextTypeVariableInfo allocator
                    (allocator, record_result) <- getNextTypeVariableInfo allocator
                    (allocator, args, members) <- List.fold (allocator, List2.empty, List2.empty) record.fields (\(allocator, args, members), field -> do
                            (allocator, arg_info) <- getNextTypeVariableInfo allocator
                            member <- M.MemberInfo (M.Field field.name) variant.type record_result.arg_group_var arg_info
                            members <- List2.push members member
                            args <- List2.push args arg_info
                            (allocator, args, members))
                    variants <- List2.single (M.MemberInfo (M.Variant index) type adt_result.arg_group_var record_result)
                    ownershipinfos <- List2.single (M.OwnershipInfo record_result.ownership_var M.Owner)
                    FunctionInfo args adt_result (members + variants) List2.empty ownershipinfos
                _ -> panic "createVariantctorFunctionInfo: not a record"
        _ -> panic "createVariantctorFunctionInfo: not an adt"

processFunctionInfo :: Context -> FunctionInfo -> P.Identity -> (Context, Bool)
processFunctionInfo context function_info function_id = do
    //trace context.config "processFunctionInfo - processing {}" % function_id
    function_info <- normalizeFunctionInfo function_info
    //trace context.config "processFunctionInfo - normalization done"
    function_info_store <- context.function_info_store
    //println "Function info added for {}/{}" % (function_id, getLength function_info.members)
    (function_info_store, added) <- addFunctionInfo function_info_store function_id function_info
    //trace context.config "processFunctionInfo - added done"
    context <- context { function_info_store = function_info_store }
    (context, added)

processFunction :: Context -> [P.Identity] -> Option InferenceInfo -> P.Identity -> (Context, Bool, Option InferenceInfo)
processFunction context group inference_info function_id = do
    (program, function) <- P.getFunction context.program function_id
    context <- context { program = program }
    case function.kind of
        F.Normal info -> do
            //trace context.config "Ownership inference - processing {}" % function_id
            (context, inference_info) <- case inference_info of
                Some inference_info -> (context, inference_info)
                None -> do
                    arg_count <- getLength function.type.args
                    inference_info <- createInferenceInfo
                    inference_info <- addFunctionInferenceInfo inference_info function_id arg_count
                    //trace context.config "initializeTypeVariables {}" % function_id
                    inference_info <- initializeTypeVariables inference_info function_id info.body
                    function_info_store <- context.function_info_store
                    //trace context.config "processEqualities {}" % function_id
                    (program, equals, inference_info) <- processFunctionEqualities function_id context.config group List2.empty inference_info function_info_store context.program info.body
                    (program, inference_info) <- processEqualities context.config equals inference_info context.program
                    context <- context { program = program }
                    (context, inference_info)
            //trace context.config "checkBorrows {}" % function_id
            borrow_info <- checkBorrows context.program info.body
            //trace context.config "inferOwnership {}" % function_id
            (inference_info, constraints, invalid_borrow_map, ownership_expr_map) <- collectConstraints context.config function_id context.program borrow_info inference_info info.body
            inference_info <- processConstraints context.config function_id inference_info constraints invalid_borrow_map ownership_expr_map Partial
            //dumpOwnership inference_info function_id info.body
            //trace context.config "Processing {}" % function_id
            function_info <- toFunctionInfo context.config inference_info function_id
            function_info <- enforceUnknownArgOwnership function_info
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, Some inference_info)
        F.VariantCtor index -> do
            function_info <- createVariantctorFunctionInfo context index function.type.result
            //trace context.config "Variant ctor {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)
        F.RecordCtor -> do
            function_info <- createRecordCtorFunctionInfo context function.type.result
            //trace context.config "Record ctor {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)
        F.Extern type_mapping -> do
            function_info <- createExternFunctionInfo context.program function_id function.type type_mapping
            //trace context.config "Extern {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)

processFunctionGroup :: Int -> Int -> Context -> [P.Identity] -> (Int, Context)
processFunctionGroup index group_count context group = do
        trace context.config "processFunctionGroup {}/{} ({}%) {}" % (index, group_count, index * 100 / group_count, group)
        if getLength group == 1
            then do
                function_id <- atIndex group 0
                (context, _, _) <- processFunction context group None function_id
                (index + 1, context)
            else do
                (context, inference_info) <- prepareInferenceInfo context group
                loop (context, inference_info) <- (context, Some inference_info) do
                    (context, more, inference_info) <- List.fold (context, False, inference_info) group (\(context, more, inference_info), function_id -> do
                        (context, added, inference_info) <- processFunction context group inference_info function_id
                        more <- if added then True else more
                        (context, more, inference_info))
                    if more then (context, inference_info) else break (index + 1, context)
    where
        prepareInferenceInfo :: Context -> [P.Identity] -> (Context, InferenceInfo)
        prepareInferenceInfo context group = do
            inference_info <- createInferenceInfo
            (context, inference_info) <- List.fold (context, inference_info) group (\(context, inference_info), function_id -> do
                (program, function) <- P.getFunction context.program function_id
                context <- context { program = program }
                case function.kind of
                    F.Normal info -> do
                        arg_count <- getLength function.type.args
                        inference_info <- addFunctionInferenceInfo inference_info function_id arg_count
                        inference_info <- initializeTypeVariables inference_info function_id info.body
                        (context, inference_info)
                    _ -> panic "Groupped function is not normal!")
            (context, inference_info, equals) <- List.fold (context, inference_info, List2.empty) group
                (\(context, inference_info, equals), function_id -> do
                    function_info_store <- context.function_info_store
                    (program, function) <- P.getFunction context.program function_id
                    case function.kind of
                        F.Normal info -> do
                            (program, equals, inference_info) <- processFunctionEqualities function_id context.config group equals inference_info
                                function_info_store context.program info.body
                            context <- context { program = program }
                            (context, inference_info, equals)
                        _ -> panic "Groupped function is not normal!")
            inference_info <- List.fold inference_info group
                (\inference_info, function_id -> do
                    converters <- getFunctionConverters context.config inference_info function_id
                    group_function_converters <- Map2.put inference_info.group_function_converters function_id converters
                    inference_info { group_function_converters = group_function_converters })
            (program, inference_info) <- processEqualities context.config equals inference_info context.program
            context <- context { program = program }
            (context, inference_info)

processProgram :: Config -> P.Program -> [DependencyGroup P.Identity] -> LP.Program
processProgram config program function_groups = do
    trace config "Ownership inference started"
    context <- Context config program createFunctionInfoStore
    group_count <- getLength function_groups
    (_, context) <- List.fold (1, context) function_groups (\(index, context), group -> processFunctionGroup index group_count context group.items)
    trace config "Ownership inference ended"
    trace config "Lowering started"
    lir_program <- lowerProgram program context.config context.function_info_store
    trace config "Lowering ended"
    lir_program