module Siko.MIR.Backend.Ownership.OwnershipInference(inferOwnership) where

import Siko.MIR.Program as P
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.BorrowInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.OwnershipDependencyMap
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.FunctionInfoStore
import Siko.MIR.Backend.Traversal
import Siko.MIR.Backend.Ownership.BorrowId // FIXME: needed only for the linear hack
import Siko.MIR.Expr as E
import Siko.MIR.Type as T
import Siko.MIR.Function as F
import Siko.Config
import Siko.Trace

import Map
import Set
import List2 as List2
import List2 (List2)
import Map2 as Map2
import Map2 (Map2)

data Context = { config :: Config,
                 ownership_dep_map :: Map2 TypeVariable (List2 TypeVariable),
                 inference_info :: InferenceInfo,
                 program :: P.Program,
                 borrow_info :: BorrowInfo,
                 function_info_store :: FunctionInfoStore,
                 group :: [P.Identity],
                 invalid_borrows :: Set E.ExprId,
                 forced_clones :: Set TypeVariable,
                 cloning_converters :: Set E.ExprId,
                 needs_restart :: Bool }

addOwnershipValue :: Context -> TypeVariable -> OwnershipKind -> Context
addOwnershipValue context var kind = do
    inference_info <- addOwnership context.inference_info var kind
    context { inference_info = inference_info }

getOwnershipValue :: Context -> TypeVariable -> (Context, OwnershipKind) // FIXME
getOwnershipValue context var = do
    (inference_info, result) <- getOwnership context.inference_info var
    context <- context { inference_info = inference_info }
    case result of
        Some o -> (context, o)
        None -> panic "Ownership value not found for {}" % var

getOwnershipValueMaybe :: Context -> TypeVariable -> (Context, Option OwnershipKind) // FIXME
getOwnershipValueMaybe context var = do
    (inference_info, result) <- getOwnership context.inference_info var
    context <- context { inference_info = inference_info }
    (context, result)

getTypeVariableInfoByExprId2 :: Context -> E.ExprId -> (Context, TypeVariableInfo) // FIXME:
getTypeVariableInfoByExprId2 context expr_id = do
    (inference_info, info) <- getTypeVariableInfoByExprId context.inference_info expr_id
    (context { inference_info = inference_info }, info)

getTypeVariableInfoByVar2 :: Context -> E.Var -> (Context, TypeVariableInfo) // FIXME:
getTypeVariableInfoByVar2 context var = do
    (inference_info, info) <- getTypeVariableInfoByVar context.inference_info var
    (context { inference_info = inference_info }, info)

initializeExprOwnerships :: Context -> Context
initializeExprOwnerships context = do
    expr_ids <- Map2.getKeys context.inference_info.expr_type_variables
    List2.fold context expr_ids (\context, expr_id -> do
            (context, info) <- getTypeVariableInfoByExprId2 context expr_id
            TypeVariable index <- info.ownership_var
            case Map2.get context.inference_info.ownership_values info.ownership_var of
                Some _ -> context
                None -> addOwnershipValue context info.ownership_var Unknown
        )

processConverter :: Context -> Option E.ExprId -> Option E.ExprId -> TypeVariable -> TypeVariable -> Context
processConverter context converter_expr borrowed_expr from to = do
    (context, from_kind) <- getOwnershipValue context from
    (context, to_kind) <- getOwnershipValue context to
    //println "Checking converter {} {} / {} {}" % (from, to, from_kind, to_kind)
    case (from_kind, to_kind) of
        (Owner, Owner) ->
            case borrowed_expr of
                Some _ -> case converter_expr of
                            Some converter_expr -> do
                                cloning_converters <- Set.put context.cloning_converters converter_expr
                                context { cloning_converters = cloning_converters }
                            None -> context
                None -> context
        (Owner, Borrower id2) ->
            if Set.contains context.forced_clones to
            then do
                context <- case converter_expr of
                    Some converter_expr -> do
                        cloning_converters <- Set.put context.cloning_converters converter_expr
                        context { cloning_converters = cloning_converters }
                    None -> context
                addOwnershipValue context to Owner
            else case borrowed_expr of
                Some expr_id -> do
                    (inference_info, id1) <- createBorrowSetForExpr context.inference_info expr_id
                    (inference_info, id) <- mergeBorrowSets inference_info id1 id2
                    context <- context { inference_info = inference_info }
                    addOwnershipValue context to (Borrower id)
                None -> context
        (Owner, Unknown) -> if Set.contains context.forced_clones to
            then do
                context <- case converter_expr of
                    Some converter_expr -> do
                        cloning_converters <- Set.put context.cloning_converters converter_expr
                        context { cloning_converters = cloning_converters }
                    None -> context
                addOwnershipValue context to Owner
            else case borrowed_expr of
                Some expr_id -> do
                    (inference_info, id) <- createBorrowSetForExpr context.inference_info expr_id
                    context <- context { inference_info = inference_info }
                    addOwnershipValue context to (Borrower id)
                None -> addOwnershipValue context to from_kind
        (Borrower a, Owner) -> context
        (Borrower a, Borrower b) -> do
            if Set.contains context.forced_clones to
            then do
                context <- case converter_expr of
                    Some converter_expr -> do
                        cloning_converters <- Set.put context.cloning_converters converter_expr
                        context { cloning_converters = cloning_converters }
                    None -> context
                addOwnershipValue context to Owner
            else do
                (inference_info, id) <- mergeBorrowSets context.inference_info a b
                context <- context { inference_info = inference_info }
                addOwnershipValue context to (Borrower id)
        (Borrower a, Unknown) -> do
            if Set.contains context.forced_clones to
            then do
                context <- case converter_expr of
                    Some converter_expr -> do
                        cloning_converters <- Set.put context.cloning_converters converter_expr
                        context { cloning_converters = cloning_converters }
                    None -> context
                addOwnershipValue context to Owner
            else addOwnershipValue context to from_kind
        (Unknown, _) -> context

getBorrowSet2 :: Context -> BorrowId -> (Context, BorrowSet) // FIXME
getBorrowSet2 context id = do
    (inference_info, id) <- getBorrowSet context.inference_info id
    (context { inference_info = inference_info }, id)

processExpr :: Context -> E.Expr -> Context
processExpr context expr = do
    E.Expr s_expr expr_type expr_id <- expr
    (context, info) <- getTypeVariableInfoByExprId2 context expr_id
    context <- case s_expr of
        E.Do items -> List.fold context items processExpr
        E.Multi _ -> context
        E.StaticFunctionCall f_id args -> do
                context <- List.fold context args processExpr
                function <- P.getFunction context.program f_id
                case function.kind of
                    F.Normal _ | F.Extern _ -> do
                        case getFunctionInfo context.function_info_store f_id of
                            Some function_info -> do
                                //println "{}/function info {}" % (f_id, function_info)
                                case Map2.get context.inference_info.function_converters expr_id of
                                    Some function_converters -> do
                                        List2.fold context function_converters (\context, converter -> do
                                            //println "Running function converter"
                                            processConverter context None None converter.from converter.to)
                                    None -> panic "No function converters found for {} {}" % (f_id, expr_id)
                            None -> if List.contains context.group f_id
                                then context
                                else panic "No function info found for called fn {}" % f_id
                    F.VariantCtor _ -> addOwnershipValue context info.ownership_var Owner
                    F.RecordCtor -> addOwnershipValue context info.ownership_var Owner
        E.IntegerLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.StringLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.FloatLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.CharLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.VarDecl var rhs -> do
            context <- processExpr context rhs
            context <- addOwnershipValue context info.ownership_var Owner
            context
        E.VarRef _ -> context
        E.FieldAccess name receiver -> do
            context <- processExpr context receiver
            E.Expr _ _ receiver_id <- receiver
            (context, receiver_info) <- getTypeVariableInfoByExprId2 context receiver_id
            (context, receiver_kind) <- getOwnershipValue context receiver_info.ownership_var
            (context, expr_kind) <- getOwnershipValue context info.ownership_var
            member <- List2.filter context.inference_info.members (\m -> case m of
                    M.Member n root member_info -> n == name && receiver_info.arg_group_var == root
                    _ -> False)
            case List2.head member of
                Some (M.Member name root member_info) -> do
                    //println "Looking for ownership for {}" % info.ownership_var
                    (context, ownership) <- getOwnershipValueMaybe context member_info.ownership_var
                    case ownership of
                        Some member_kind -> do
                            case (receiver_kind, member_kind) of
                                (_, Borrower _) -> addOwnershipValue context info.ownership_var member_kind
                                (Borrower _, Owner) -> addOwnershipValue context info.ownership_var receiver_kind
                                (Owner, _) -> addOwnershipValue context info.ownership_var receiver_kind
                                _ -> context
                        None -> case (receiver_kind, expr_kind) of
                            (Borrower _, Owner) -> addOwnershipValue context info.ownership_var receiver_kind
                            (Borrower _, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                            (Owner, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                            _ -> context
                Some _ -> panic "member is not a member"
                None -> do
                    case (receiver_kind, expr_kind) of
                        (Borrower _, Owner) -> addOwnershipValue context info.ownership_var receiver_kind
                        (Borrower _, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                        (Owner, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                        _ -> context
        E.If cond true_branch false_branch -> do
            context <- processExpr context cond
            context <- processExpr context true_branch
            context <- processExpr context false_branch
            context
        E.List args -> do
            context <- List.fold context args processExpr
            addOwnershipValue context info.ownership_var Owner
        E.Return arg -> do
            context <- processExpr context arg
            addOwnershipValue context info.ownership_var Owner
        E.Continue arg -> do
            context <- processExpr context arg
            addOwnershipValue context info.ownership_var Owner
        E.Break arg -> do
            context <- processExpr context arg
            addOwnershipValue context info.ownership_var Owner
        E.RecordUpdate var updates -> panic "RecordUpdate in InferOwnership"
        E.Loop var initializer body _ _ -> do
            context <- processExpr context initializer
            context <- processExpr context body
            case expr_type of
                T.Never -> addOwnershipValue context info.ownership_var Owner
                _ -> context
        E.CaseOf body cases -> do
            context <- processExpr context body
            E.Expr _ _ body_id <- body
            (context, body_info) <- getTypeVariableInfoByExprId2 context body_id
            List.fold context cases (\context, c -> do
                    context <- case c.checker of
                        E.VariantChecker index var _ -> do
                            (context, var_info) <- getTypeVariableInfoByVar2 context var
                            (context, body_kind) <- getOwnershipValue context body_info.ownership_var
                            (context, ownership) <- getOwnershipValueMaybe context var_info.ownership_var
                            var_kind <- case ownership of
                                Some o -> o
                                None -> Unknown
                            case (body_kind, var_kind) of
                                (body_o, Unknown) -> addOwnershipValue context var_info.ownership_var body_o
                                _ -> context
                        _ -> context
                    processExpr context c.body
                )
        E.Clone arg -> panic "Clone in InferOwnership"
        E.Deref arg -> panic "Deref in InferOwnership"
        E.Ref arg -> panic "Ref in InferOwnership"
        E.Move arg -> panic "Move in InferOwnership"
        E.Box arg -> panic "Box in InferOwnership"
        E.Converter arg _  -> do
            context <- processExpr context arg
            E.Expr arg_s_expr _ arg_id <- arg
            (context, arg_info) <- getTypeVariableInfoByExprId2 context arg_id
            borrowed_var <- case arg_s_expr of
                E.VarRef var -> if isBorrow context.borrow_info arg_id
                        then Some arg_id
                        else None
                E.FieldAccess n _ -> if isBorrow context.borrow_info arg_id
                        then Some arg_id
                        else None
                _ -> None
            processConverter context (Some expr_id) borrowed_var arg_info.ownership_var info.ownership_var
    // trace context.config "updateInvalidBorrows"
    context <- updateInvalidBorrows context expr_id
    // trace context.config "checkBorrows"
    context <- checkBorrows context info
    // trace context.config "processExpr done"
    context

updateInvalidBorrows :: Context -> E.ExprId -> Context
updateInvalidBorrows context expr_id = do
    context <- case Map.get context.borrow_info.invalidations expr_id of
        Some invalidations -> do
            invalid_borrows <- List.fold context.invalid_borrows invalidations (\invalid_borrows, invalidation ->
                Set.put invalid_borrows invalidation)
            context { invalid_borrows = invalid_borrows }
        None -> context
    //println "Invalid borrows {} = {}" % (expr_id, context.invalid_borrows)
    context

checkBorrows :: Context -> TypeVariableInfo -> Context
checkBorrows context expr_info = do
        relevants <- case Map2.get context.ownership_dep_map expr_info.arg_group_var of
            Some vars -> List2.push vars expr_info.ownership_var
            None -> List2.single expr_info.ownership_var
        context <- if not context.needs_restart
        then do
            (context, new_forced_clones) <- List2.fold (context, List2.empty) relevants checkBorrowingVar
            new_forced_clones <- List2.dedup (List2.sort new_forced_clones)
            old_forced_clones <- context.forced_clones
            new_forced_clones <- List2.filter new_forced_clones (\v -> not (Set.contains old_forced_clones v))
            case List2.head new_forced_clones of
                Some first -> do
                    forced_clones <- Set.put context.forced_clones first
                    context { needs_restart = True, forced_clones = forced_clones }
                None -> context
        else context
        context
    where
        checkBorrowingVar :: (Context, List2 TypeVariable) -> TypeVariable -> (Context, List2 TypeVariable)
        checkBorrowingVar (context, forced_clones) var =
            case Map2.get context.inference_info.ownership_values var of
                Some ownership -> case ownership of
                        Borrower id -> do
                            (context, borrow_set) <- getBorrowSet2 context id
                            Set.fold (context, forced_clones) borrow_set.borrows (promoteBorrow var)
                        _ -> (context, forced_clones)
                None -> (context, forced_clones)

        promoteBorrow :: TypeVariable -> (Context, List2 TypeVariable) -> Borrow -> (Context, List2 TypeVariable)
        promoteBorrow var (context, forced_clones) borrow =
            case borrow of
                Local borrowed_expr -> do
                    if Set.contains context.invalid_borrows borrowed_expr
                    then (context, List2.push forced_clones var)
                    else (context, forced_clones)
                _ -> (context, forced_clones)

dumpExpr :: Context -> E.Expr -> (Context, E.Expr)
dumpExpr context expr = do
    E.Expr s_expr _ expr_id <- expr
    (context, info) <- getTypeVariableInfoByExprId2 context expr_id
    (context, o1) <- getOwnershipValue context info.ownership_var
    println "dumpOwnership {}/{} {} {}" % (expr_id, E.short expr, info, o1)
    (context, expr)

inferOwnership :: Config ->
                  [P.Identity] ->
                  FunctionInfoStore ->
                  InferenceInfo ->
                  P.Program ->
                  E.Expr ->
                  BorrowInfo ->
                  (InferenceInfo, Set E.ExprId)
inferOwnership config group function_info_store inference_info program body borrow_info = do
        (members, ownership_dep_map) <- calculateOwnershipDepMap config inference_info.members
        inference_info <- inference_info { members = members }
        //trace config "calculateOwnershipDepMap: calculateOwnershipDepMap end"
        loop (forced_clones, cloning_converters, ownership_dep_map, count) <- (Set.empty, Set.empty, ownership_dep_map, 0) do
            //trace config "inferOwnership: loop count {}" % count
            //dumpInferenceInfoStats config inference_info
            (inference_info, new_forced_clones, cloning_converters, ownership_dep_map) <- infer config ownership_dep_map group function_info_store inference_info
                                                        program body borrow_info forced_clones cloning_converters
            if new_forced_clones != forced_clones
            then (new_forced_clones, cloning_converters, ownership_dep_map, count + 1)
            else break (inference_info, cloning_converters)
    where
        infer :: Config ->
                 Map2 TypeVariable (List2 TypeVariable) ->
                 [P.Identity] ->
                 FunctionInfoStore ->
                 InferenceInfo ->
                 P.Program ->
                 E.Expr ->
                 BorrowInfo ->
                 Set TypeVariable ->
                 Set E.ExprId ->
                 (InferenceInfo, Set TypeVariable, Set E.ExprId, Map2 TypeVariable (List2 TypeVariable))
        infer config ownership_dep_map group function_info_store inference_info program body borrow_info forced_clones cloning_converters = do
        context <- Context config ownership_dep_map inference_info program borrow_info
                           function_info_store group Set.empty forced_clones cloning_converters False
        context <- initializeExprOwnerships context
        context <- processExpr context body
        // println "----------- BEGIN"
        // (context, body) <- traverse context body (Some dumpExpr) None None
        // println "----------- END"
        (context.inference_info, context.forced_clones, context.cloning_converters, context.ownership_dep_map)