module Siko.LLVM.Util {

pub fn mangle(name: String) -> String {
    let s = name.trim_start_matches("$");
    let result = "";
    let prev_sep = False;
    for c in s.chars() {
        match c {
            '(' => {
                result = result + "_lp_";
                prev_sep = False;
            }
            ')' => {
                result = result + "_rp_";
                prev_sep = False;
            }
            '*' => {
                result = result + "ptr_";
                prev_sep = False;
            }
            '.' | '[' | '{' | ',' | '-' | '<' | '>' | ':' | '!' | '@' | '&' | '+' | '='
            | '|' | '^' | '~' | '?' | '/' | '\\' | '#' => {
                if !prev_sep {
                    result = result + "_";
                }
                prev_sep = True;
            }
            ']' | '}' | ' ' | '\'' | '`' | '"' | ';' => {}
            _ => {
                result = result + String.from_byte(c);
                prev_sep = False;
            }
        }
    }
    loop {
        if !result.ends_with("__") { break; }
        result = result.strip_suffix("__").unwrap();
    }
    result
}

}
