module Siko.Resolver.Class where

import Siko.HIR.Type as HT
import Siko.HIR.Program as HP
import Siko.HIR.Class as HC
import Siko.Resolver
import Siko.Resolver.Module
import Siko.Resolver.Error
import Siko.Resolver.Function
import Siko.Resolver.Type
import Siko.Resolver.Import
import Siko.Syntax.Module as SM
import Siko.Syntax.TypeSignature as ST
import Siko.Syntax.Class as SC
import Siko.Syntax.Ident

/*
import Siko.Syntax.Function as SF

import Siko.Syntax.Pattern as SP

import Siko.HIR.Function as HF

import Siko.Resolver.Import


import Siko.Resolver.Expr
import Siko.Resolver.Pattern
import Siko.Resolver.Type
import Siko.Resolver.Environment
import Map
*/

processClassDependencies :: ResolverState -> ModuleResolver -> SC.Class -> String -> (ResolverState, [HP.FullyQualifiedName])
processClassDependencies state module_resolver c type_arg = do
    (state, class_constraints) <- c.constraints |> List.iter |> fold (\(state, constraints), constraint -> do
                state <- if (getString constraint.argument) != type_arg
                    then
                        addError state (UnknownTypeArg constraint.argument)
                    else
                        state
                (state, constraints) <- case resolveClass module_resolver constraint.class_name of
                    Ok class_name -> do
                        constraints <- constraints + [class_name]
                        (state, constraints)
                    Err err -> do
                        state <- addError state err
                        (state, constraints)
                (state, constraints)) (state, [])
    (state, class_constraints)

processClass :: ResolverState -> HP.Program -> ModuleResolver -> SC.Class -> (ResolverState, HP.Program)
processClass state hir_program module_resolver c = do
    module_name <- module_resolver.module_name
    name <- getString c.name
    qn <- fullyQualifiedName module_name name
    ST.TypeSignature type location <- c.argument
    type_resolver <- createTypeResolverState module_resolver True
    (state, type_resolver, class_constraints) <- case type of
        ST.TypeArg type_arg -> do
            type_arg_str <- getString type_arg
            self_constraint <- HT.ClassConstraint qn
            (type_resolver, state, hir_type) <- processTypeSignature type_resolver state c.argument
            (_, type_resolver) <- addTypeArgumentConstraint type_resolver type_arg_str self_constraint
            (state, class_constraints) <- processClassDependencies state module_resolver c type_arg_str
            (state, type_resolver, class_constraints)
        _ -> do
            state <- addError state (InvalidClassArgument location)
            (state, type_resolver, [])
    type_resolver <- disableImplicitTypeArgs type_resolver
    (state, members) <- processFunctionsAndSignatures state hir_program module_resolver type_resolver c.member_functions c.member_function_type_signatures
    println "Members: {}" % members
    hir_class <- HC.Class name module_name class_constraints members
    (state, hir_program)

processInstance :: ResolverState -> HP.Program -> ModuleResolver -> SC.Instance -> (ResolverState, HP.Program)
processInstance state hir_program module_resolver i = do
    type_resolver <- createTypeResolverState module_resolver True
    (type_resolver, state, hir_type) <- processTypeSignature type_resolver state i.type_signature
    (state, type_resolver) <- i.constraints |> List.iter |> fold (\(state, type_resolver), c ->
            processClassConstraint state type_resolver module_resolver c
        ) (state, type_resolver)
    type_resolver <- disableImplicitTypeArgs type_resolver
    (state, members) <- processFunctionsAndSignatures state hir_program module_resolver type_resolver i.member_functions i.member_function_type_signatures
    println "class name {}" % i.class_name
    (state, qn) <- case resolveClass module_resolver i.class_name of
        Ok qn -> (state, qn)
        Err err -> (addError state err, fullyQualifiedName "" "")
    println "Members: {}" % members
    (state, hir_program)

processClassesAndInstances :: ResolverState -> HP.Program -> ModuleResolver -> SM.Module -> (ResolverState, HP.Program)
processClassesAndInstances state hir_program module_resolver mod = do
    (state, hir_program) <- mod.items |> List.iter |> fold (\(state, hir_program), item -> do
        (state, hir_program) <- case item of
                SM.Class c -> processClass state hir_program module_resolver c
                SM.Instance i -> processInstance state hir_program module_resolver i
                _ -> (state, hir_program)
        (state, hir_program)) (state, hir_program)
    (state, hir_program)