module Siko.Resolver.Data where

import Siko.Resolver
import Siko.Resolver.Module
import Siko.Resolver.Type
import Siko.Resolver.Error
import Siko.Syntax.Ident
import Siko.Resolver.Import
import Siko.Resolver.ModuleResolver
import Siko.Syntax.Data as SD
import Siko.Syntax.Module as SM
import Siko.Syntax.TypeSignature as ST
import Siko.HIR.Data as HD
import Siko.HIR.Type
import Siko.HIR.Program as HP
import Map

processVariant :: ResolverState -> TypeResolverState -> SD.Variant -> (ResolverState, TypeResolverState, HD.Variant)
processVariant state type_resolver variant = do
    (Ident name location) <- variant.name
    (state, type_resolver, items) <-  variant.items |> List.iter |> Iterator.fold (\(state, type_resolver, items), item -> do
        (type_resolver, state, arg) <- processTypeSignature type_resolver state item
        items <- items + [arg]
        (state, type_resolver, items)) (state, type_resolver, [])
    (state, type_resolver, HD.Variant name location items)

processRecordField :: ResolverState ->
                      TypeResolverState ->
                      SD.RecordField ->
                      Map String [Ident] -> (ResolverState, TypeResolverState, HD.RecordField, Map String [Ident])
processRecordField state type_resolver (SD.RecordField name type_signature) field_names = do
    (type_resolver, state, type) <- processTypeSignature type_resolver state type_signature
    n <- getString name
    (field_names, _) <- alter (\names -> case names of
                    Some names -> Some (names + [name])
                    None -> Some [name]) n field_names
    (state, type_resolver, HD.RecordField n type, field_names)

processDerivedClasses :: ResolverState -> ModuleResolver -> [Ident] -> (ResolverState, [HD.DeriveInfo])
processDerivedClasses state module_resolver derived_classes = do
    (state, derived_classes) <- derived_classes |> List.iter |> Iterator.fold (\(state, derived_classes), derived_class -> do
            case resolveClass module_resolver derived_class of
                Ok name -> do
                    (Ident _ location) <- derived_class
                    (state, derived_classes + [HD.DeriveInfo name location])
                Err err -> do
                    (addError state err, derived_classes)) (state, [])
    (state, derived_classes)

createFunctionFromArgs :: [Type] -> Type -> Type
createFunctionFromArgs args result_ty = do
    case head args of
        Some from -> do
            args <- Option.unwrap (tail args)
            to <- createFunctionFromArgs args result_ty
            Function from to
        None -> result_ty

processAdt :: ResolverState -> HP.Program () -> ModuleResolver -> SD.AlgebraicDataType -> (ResolverState, HP.Program ())
processAdt state hir_program module_resolver (SD.AlgebraicDataType name type_arguments variants derived_classes) = do
    (type_resolver, state) <- initTypeResolver module_resolver state type_arguments
    (state, type_resolver, variants) <- variants |> List.iter |> Iterator.fold (\(state, type_resolver, variants), variant -> do
                (state, type_resolver, variant) <- processVariant state type_resolver variant
                variants <- variants + [variant]
                (state, type_resolver, variants)) (state, type_resolver, [])
    (state, type_args) <- processTypeArgs state type_resolver type_arguments True
    (state, derived_classes) <- processDerivedClasses state module_resolver derived_classes
    (Ident n location) <- name
    qn <- HP.FullPath module_resolver.module_name n
    type <- Named qn type_args
    variant_ctors <- variants |> List.iter |> Iterator.fold (\variant_ctors, (HD.Variant name location args) -> do
                                    ctor_type <- createFunctionFromArgs args type
                                    variant_ctors <- variant_ctors + [ctor_type]
                                    variant_ctors) []
    (hir_program, _, state) <- variants |> List.iter |> Iterator.fold (\(hir_program, index, state), (HD.Variant name location _) -> do
                                                variant_qn <- HP.FullPathWithVariant module_resolver.module_name n name
                                                info <- HD.VariantInfo qn index location
                                                (hir_program, other_item) <- HP.addItem hir_program variant_qn (HP.Variant info)
                                                state <- handleItemConflict state other_item location
                                                (hir_program, index + 1, state)) (hir_program, 0, state)
    adt <- HD.AlgebraicDataType qn location type_args variants variant_ctors derived_classes type
    (hir_program, other_item) <- HP.addItem hir_program qn (HP.Adt adt)
    state <- handleItemConflict state other_item location
    (state, hir_program)

processRecord :: ResolverState -> HP.Program () -> ModuleResolver -> SD.Record -> (ResolverState, HP.Program ())
processRecord state hir_program module_resolver (SD.Record name type_arguments fields external derived_classes) = do
    (type_resolver, state) <- initTypeResolver module_resolver state type_arguments
    (state, type_resolver, fields, field_names) <- fields |> List.iter |> Iterator.fold (\(state, type_resolver, fields, field_names), field -> do
                (state, type_resolver, field, field_names) <- processRecordField state type_resolver field field_names
                fields <- fields + [field]
                (state, type_resolver, fields, field_names)) (state, type_resolver, [], empty)
    state <- field_names |> Map.iter |> Iterator.fold (\state, (name, instances) -> if getLength instances > 1
                            then addError state (RecordFieldConflict instances)
                            else state) state
    (state, type_args) <- processTypeArgs state type_resolver type_arguments (not external)
    (state, derived_classes) <- processDerivedClasses state module_resolver derived_classes
    (Ident n location) <- name
    qn <- HP.FullPath module_resolver.module_name n
    type <- Named qn type_args
    ctor_arg_types <- fields |> List.iter |> Iterator.map (\(HD.RecordField _ type) -> type) |> toList
    ctor_type <- createFunctionFromArgs ctor_arg_types type
    record <- HD.Record qn location type_args fields external ctor_type derived_classes type
    (hir_program, other_item) <- HP.addItem hir_program qn (HP.Record record)
    state <- handleItemConflict state other_item location
    (state, hir_program)

processItem :: ResolverState -> HP.Program () -> ModuleResolver -> SM.Item -> (ResolverState, HP.Program ())
processItem state hir_program module_resolver item = do
    case item of
        SM.Adt adt -> do
            (state, hir_program) <- processAdt state hir_program module_resolver adt
            (state, hir_program)
        SM.Record record -> do
            (state, hir_program) <- processRecord state hir_program module_resolver record
            (state, hir_program)
        _ -> (state, hir_program)

processData :: ResolverState -> HP.Program () -> ModuleResolver -> SM.Module -> (ResolverState, HP.Program ())
processData state hir_program module_resolver mod = do
    (state, hir_program) <- mod.items
        |> List.iter
        |> Iterator.fold (\(state, hir_program), item -> processItem state hir_program module_resolver item) (state, hir_program)
    (state, hir_program)
