module Siko.Resolver.Error where

import Siko.Syntax.Ident
import Siko.Syntax.Location
import Siko.Resolver

data DefArgCount = DefArgCount Ident Int deriving (Show)

data ResolverError = ModuleConflict String [Ident]
                     | ModuleNotFound Ident
                     | UnknownType Ident
                     | AmbiguousType Ident [String]
                     | UnknownTypeArg Ident
                     | InvalidVariant Location
                     | NotAClassName Ident
                     | UnusedTypeArg Ident
                     | ConflictingSignatures [Ident]
                     | MissingImpl Ident
                     | InvalidExternArg Location
                     | ExternFnWithMultiDef Ident
                     | MultiDefArgCountMismatch [DefArgCount]
                     | NotAFunction Ident
                     | UnknownFunction Ident
                    deriving (Show)

addError :: ResolverState -> ResolverError -> ResolverState
addError state error =  do
    state <- state { errors = state.errors + [error] }
    state
