module Siko.Resolver.Function where

import Siko.Syntax.Function as SF
import Siko.Syntax.Ident
import Siko.Syntax.Pattern as SP
import Siko.Syntax.Class as SC
import Siko.Syntax.Module as SM
import Siko.HIR.Function as HF
import Siko.HIR.Program as HP
import Siko.Resolver
import Siko.Resolver.Module
import Siko.Resolver.Error
import Siko.HIR.Type as HT
import Siko.Resolver.Expr
import Siko.Resolver.Pattern
import Siko.Resolver.Type
import Map

data FunctionInfo = {
                        signatures :: [SF.FunctionSignature],
                        functions :: [SF.Function],
                    } deriving (Show)

addFunction :: SF.Function -> Option FunctionInfo -> Option FunctionInfo
addFunction function info = case info of
        Some info -> do
            info :: FunctionInfo <- info // FIXME: fix type inference
            info <- info { functions = info.functions + [function] }
            Some info
        None -> Some (FunctionInfo [] [function])

addFunctionSignature :: SF.FunctionSignature -> Option FunctionInfo -> Option FunctionInfo
addFunctionSignature signature info = case info of
        Some info -> do
            info :: FunctionInfo <- info // FIXME: fix type inference
            info <- info { signatures = info.signatures + [signature] }
            Some info
        None -> Some (FunctionInfo [signature] [])

processClassConstraint :: ResolverState -> TypeResolverState -> ModuleResolver -> SC.Constraint -> (ResolverState, TypeResolverState)
processClassConstraint state type_resolver module_resolver c = do
    (state, type_resolver) <- case resolveClass module_resolver c.class_name of
        Ok class_name -> do
            constraint <- HT.ClassConstraint class_name
            type_arg <- getString c.argument
            (success, type_resolver) <- addTypeArgumentConstraint type_resolver type_arg constraint
            if success
                then (state, type_resolver)
                else do
                    state <- addError state (UnknownTypeArg c.argument)
                    (state, type_resolver)
        Err err -> do
            state <- addError state err
            (state, type_resolver)
    (state, type_resolver)

processFunctionSignature :: ResolverState -> ModuleResolver -> SF.FunctionSignature -> (ResolverState, TypeResolverState, HT.Type)
processFunctionSignature state module_resolver signature = do
    type_arguments <- signature.type_arguments
    type_resolver <- initTypeResolver module_resolver type_arguments
    (state, type_resolver) <- signature.constraints |> List.iter |> fold (\(state, type_resolver), c ->
            processClassConstraint state type_resolver module_resolver c
        ) (state, type_resolver)
    (type_resolver, state, type) <- processTypeSignature type_resolver state signature.type_signature
    (state, type_args) <- processTypeArgs state type_resolver signature.type_arguments
    (state, type_resolver, type)

processFunction :: ResolverState -> HP.Program -> ModuleResolver -> TypeResolverState -> SF.Function -> Option HT.Type -> (ResolverState, HP.Program)
processFunction state hir_program module_resolver type_resolver function type = do
    (state, desugared_body) <- case function.body of
        Some body if isEmpty function.arguments -> (state, Some body)
        Some body -> (state, Some (desugarFunctionArgs function.arguments body))
        None -> do
            state <- function.arguments |> List.iter |> fold (\state, p -> case p of
                SP.Pattern (SP.Binding _) _ -> state
                SP.Pattern _ location -> do
                    addError state (InvalidExternArg location)) state
            (state, None)
    (state, hir_body) <- case desugared_body of
                Some expr -> do
                    context <- Context type_resolver state module_resolver hir_program
                    (context, expr) <- processExpr context expr
                    (context.state, Some expr)
                None -> (state, None)
    println "body {}" % hir_body
    println "Error {}" % state.errors
    function <- HF.Function (getString function.name) type hir_body
    (state, hir_program)

processFunctionMulti :: ResolverState -> HP.Program -> ModuleResolver -> TypeResolverState -> FunctionInfo -> Option HT.Type -> (ResolverState, HP.Program)
processFunctionMulti state hir_program module_resolver type_resolver function_info type = do
    (state, arg_count_map, err) <- function_info.functions |> List.iter |> fold (\(state, arg_count_map, err), f -> do
                (state, err) <- if isNone f.body
                    then do
                        state <- addError state (ExternFnWithMultiDef f.name)
                        (state, True)
                    else (state, err)
                (arg_count_map, _) <- alter (addArgCount f.name) (getLength (f.arguments)) arg_count_map
                (state, arg_count_map, err)) (state, empty, False)
    (state, err) <- if getSize arg_count_map != 1
        then do
            names <- function_info.functions |> List.iter |> map (\f -> DefArgCount f.name (getLength f.arguments)) |> toList
            state <- addError state (MultiDefArgCountMismatch names)
            (state, True)
        else (state, err)
    if not err
        then do
            arg_cases <- function_info.functions |> List.iter |> map (\f -> (f.arguments, Option.unwrap f.body)) |> toList
            desugared_body <- desugarFunctionArgsMulti arg_cases
            (state, hir_body) <- do
                context <- Context type_resolver state module_resolver hir_program
                (context, expr) <- processExpr context desugared_body
                (context.state, Some expr)
            name <- (atIndex function_info.functions 0).name
            function <- HF.Function (getString name) type hir_body
            (state, hir_program)
        else (state, hir_program)

addArgCount :: Ident -> Option [Ident] -> Option [Ident]
addArgCount name names = case names of
    Some names -> Some (names + [name])
    None -> Some [name]

processFunctionInfo :: ResolverState -> HP.Program -> ModuleResolver -> String -> FunctionInfo -> Bool -> (ResolverState, HP.Program)
processFunctionInfo state hir_program module_resolver name function_info allowMissingImpl = do
    (state, type, type_resolver) <- case getLength function_info.signatures of
        0 -> (state, None, initTypeResolver module_resolver [])
        1 -> do
            (state, type_resolver, type) <- processFunctionSignature state module_resolver (atIndex function_info.signatures 0)
            (state, Some type, type_resolver)
        _ ->
            do
            signatures <- function_info.signatures |> List.iter |> map (\s -> s.name) |> toList
            state <- addError state (ConflictingSignatures signatures)
            (state, None, initTypeResolver module_resolver [])
    (state, hir_program) <- case getLength function_info.functions of
        0 if not allowMissingImpl -> do
            first_signature <- atIndex function_info.signatures 0
            sig_name <- first_signature.name
            (addError state (MissingImpl sig_name), hir_program)
        0 if allowMissingImpl -> (state, hir_program)
        1 -> do
            (state, hir_program) <- processFunction state hir_program module_resolver type_resolver (atIndex function_info.functions 0) type
            (state, hir_program)
        _ -> processFunctionMulti state hir_program module_resolver type_resolver function_info type
    (state, hir_program)

processFunctionsAndSignatures :: ResolverState -> HP.Program -> ModuleResolver -> [SF.Function] -> [SF.FunctionSignature] -> (ResolverState, HP.Program)
processFunctionsAndSignatures state hir_program module_resolver functions signatures = do
    function_info_map <- empty
    function_info_map <- functions |> List.iter |> fold (\function_info_map, function -> do
                                    (function_info_map, _) <- alter (addFunction function) (getString function.name) function_info_map
                                    function_info_map) function_info_map
    function_info_map <- signatures |> List.iter |> fold (\function_info_map, signature -> do
                                    (function_info_map, _) <- alter (addFunctionSignature signature) (getString signature.name) function_info_map
                                    function_info_map) function_info_map
    (state, hir_program) <- function_info_map
        |> Map.iter
        |> fold (\(state, hir_program), (name, function_info) -> processFunctionInfo state hir_program module_resolver name function_info False) (state, hir_program)
    (state, hir_program)

processFunctions :: ResolverState -> HP.Program -> ModuleResolver -> SM.Module -> (ResolverState, HP.Program)
processFunctions state hir_program module_resolver mod = do
    (functions, signatures) <- mod.items |> List.iter |> fold (\(functions, signatures), item -> case item of
                                            SM.Function f -> (functions + [f], signatures)
                                            SM.FunctionSignature s -> (functions, signatures + [s])
                                            _ -> (functions, signatures)) ([], [])
    (state, hir_program) <- processFunctionsAndSignatures state hir_program module_resolver functions signatures
    (state, hir_program)