module Siko.Resolver.Function where

import Siko.Syntax.Function as SF
import Siko.Syntax.Ident
import Siko.Syntax.Pattern as SP
import Siko.Syntax.Class as SC
import Siko.Syntax.Module as SM
import Siko.HIR.Function as HF
import Siko.HIR.Program as HP
import Siko.HIR.Type as HT
import Siko.HIR.Expr as HE
import Siko.Resolver
import Siko.Resolver.Module
import Siko.Resolver.Import
import Siko.Resolver.Error
import Siko.Resolver.Expr
import Siko.Resolver.Pattern
import Siko.Resolver.Type
import Siko.Resolver.Environment
import Map

data FunctionInfo = {
                        signatures :: [SF.FunctionSignature],
                        functions :: [SF.Function],
                    } deriving (Show)

addFunction :: SF.Function -> Option FunctionInfo -> Option FunctionInfo
addFunction function info = case info of
        Some info -> do
            info :: FunctionInfo <- info // FIXME: fix type inference
            info <- info { functions = info.functions + [function] }
            Some info
        None -> Some (FunctionInfo [] [function])

addFunctionSignature :: SF.FunctionSignature -> Option FunctionInfo -> Option FunctionInfo
addFunctionSignature signature info = case info of
        Some info -> do
            info :: FunctionInfo <- info // FIXME: fix type inference
            info <- info { signatures = info.signatures + [signature] }
            Some info
        None -> Some (FunctionInfo [signature] [])

processFunctionSignature :: ResolverState -> ModuleResolver -> TypeResolverState -> SF.FunctionSignature -> (ResolverState, TypeResolverState, HT.Type)
processFunctionSignature state module_resolver type_resolver signature = do
    (type_resolver, state) <- addTypeArguments type_resolver state signature.type_arguments
    (state, type_resolver) <- signature.constraints |> List.iter |> fold (\(state, type_resolver), c ->
            processClassConstraint state type_resolver module_resolver c
        ) (state, type_resolver)
    (type_resolver, state, type) <- processTypeSignature type_resolver state signature.type_signature
    (state, type_args) <- processTypeArgs state type_resolver signature.type_arguments True
    (state, type_resolver, type)

processLambdas :: [HF.LambdaInfo] -> HP.FullyQualifiedName -> [HF.Function]
processLambdas lambdas qn =
    lambdas |> List.iter
            |> map (\lambda -> do
                    lambda_qn <- HP.FullPathWithLambda qn lambda.id
                    kind <- (HF.Lambda lambda.id)
                    arg_count <- lambda.arg_count
                    (HE.Expr _ _ location) <- lambda.body
                    HF.Function location lambda_qn arg_count kind None (Some lambda.body)) |> toList

processFunction :: ResolverState ->
                   HP.Program ->
                   ModuleResolver ->
                   TypeResolverState ->
                   HF.FunctionKind ->
                   SF.Function ->
                   Option HT.Type ->
                   (String -> String -> HP.FullyQualifiedName) -> (ResolverState, [HF.Function])
processFunction state hir_program module_resolver type_resolver kind function type qn_creator = do
    (state, desugared_body) <- case function.body of
        Some body if isEmpty function.arguments -> (state, Some body)
        Some body -> (state, Some (desugarFunctionArgs function.arguments body))
        None -> do
            state <- function.arguments |> List.iter |> fold (\state, p -> case p of
                SP.Pattern binding location -> case binding of
                    SP.Binding _ -> state
                    _ -> addError state (InvalidExternArg location)) state
            (state, None)
    (Ident name location) <- function.name
    qn <- qn_creator module_resolver.module_name name
    (state, hir_body, lambdas) <- case desugared_body of
                Some expr -> do
                    context <- createContext qn type_resolver state module_resolver hir_program
                    env <- createEnvironment (HF.LambdaId 0) None
                    (context, env, expr) <- processExpr context env expr
                    (context.state, Some expr, context.lambdas)
                None -> if isNone type && HF.isNormal kind
                        then do
                            state <- addError state (ExternFnWithoutType function.name)
                            (state, None, [])
                        else (state, None, [])
    arg_count <- getLength function.arguments
    function <- HF.Function location qn arg_count kind type hir_body
    lambdas <- processLambdas lambdas qn
    (state, [function] + lambdas)

processFunctionMulti :: ResolverState ->
                        HP.Program ->
                        ModuleResolver ->
                        TypeResolverState ->
                        HF.FunctionKind ->
                        FunctionInfo ->
                        Option HT.Type ->
                        (String -> String -> HP.FullyQualifiedName) -> (ResolverState, [HF.Function])
processFunctionMulti state hir_program module_resolver type_resolver kind function_info type qn_creator = do
    (state, arg_count_map, err) <- function_info.functions |> List.iter |> fold (\(state, arg_count_map, err), f -> do
                (state, err) <- if isNone f.body
                    then do
                        state <- addError state (ExternFnWithMultiDef f.name)
                        (state, True)
                    else (state, err)
                (state, err) <- if isEmpty f.arguments
                    then do
                        state <- addError state (MultiDefNoArg f.name)
                        (state, True)
                    else (state, err)
                (arg_count_map, _) <- alter (addArgCount f.name) (getLength (f.arguments)) arg_count_map
                (state, arg_count_map, err)) (state, empty, False)
    (state, err) <- if getSize arg_count_map != 1
        then do
            names <- function_info.functions |> List.iter |> map (\f -> DefArgCount f.name (getLength f.arguments)) |> toList
            state <- addError state (MultiDefArgCountMismatch names)
            (state, True)
        else (state, err)
    (Ident name location) <- (atIndex function_info.functions 0).name
    qn <- qn_creator module_resolver.module_name name
    if not err
        then do
            arg_cases <- function_info.functions |> List.iter |> map (\f -> (f.arguments, Option.unwrap f.body)) |> toList
            desugared_body <- desugarFunctionArgsMulti arg_cases
            (state, hir_body, lambdas) <- do
                context <- createContext qn type_resolver state module_resolver hir_program
                env <- createEnvironment (HF.LambdaId 0) None
                (context, env, expr) <- processExpr context env desugared_body
                (context.state, Some expr, context.lambdas)
            arg_count <- getLength (atIndex function_info.functions 0).arguments
            function <- HF.Function location qn arg_count kind type hir_body
            lambdas <- processLambdas lambdas qn
            (state, [function] + lambdas)
        else do
            function <- HF.Function location qn 0 kind type None
            (state, [function])

addArgCount :: Ident -> Option [Ident] -> Option [Ident]
addArgCount name names = case names of
    Some names -> Some (names + [name])
    None -> Some [name]

processFunctionInfo :: ResolverState ->
                       HP.Program ->
                       ModuleResolver ->
                       TypeResolverState ->
                       HF.FunctionKind ->
                       FunctionInfo ->
                       (String -> String -> HP.FullyQualifiedName) -> (ResolverState, [HF.Function])
processFunctionInfo state hir_program module_resolver type_resolver kind function_info qn_creator = do
    (state, type, type_resolver) <- case getLength function_info.signatures of
        0 -> (state, None, type_resolver)
        1 -> do

            (state, type_resolver, type) <- processFunctionSignature state module_resolver type_resolver (atIndex function_info.signatures 0)
            (state, Some type, type_resolver)
        _ ->
            do
            signatures <- function_info.signatures |> List.iter |> map (\s -> s.name) |> toList
            state <- addError state (ConflictingSignatures signatures)
            (state, None, type_resolver)
    (state, functions) <- case getLength function_info.functions of
        0 -> do
            first_signature <- atIndex function_info.signatures 0
            (Ident name location) <- first_signature.name
            qn <- qn_creator module_resolver.module_name name
            arg_count <- case type of
                Some t -> HT.getArgCount t
                None -> 0
            function <- HF.Function location qn arg_count kind type None
            (state, [function])
        1 -> processFunction state hir_program module_resolver type_resolver kind (atIndex function_info.functions 0) type qn_creator
        _ -> processFunctionMulti state hir_program module_resolver type_resolver kind function_info type qn_creator
    (state, functions)

processFunctionsAndSignatures :: ResolverState ->
                                 HP.Program ->
                                 ModuleResolver ->
                                 TypeResolverState ->
                                 HF.FunctionKind ->
                                 [SF.Function] ->
                                 [SF.FunctionSignature] ->
                                 (String -> String -> HP.FullyQualifiedName) -> (ResolverState, [HF.Function])
processFunctionsAndSignatures state hir_program module_resolver type_resolver kind functions signatures qn_creator = do
    function_info_map <- empty
    function_info_map <- functions |> List.iter |> fold (\function_info_map, function -> do
                                    (function_info_map, _) <- alter (addFunction function) (getString function.name) function_info_map
                                    function_info_map) function_info_map
    function_info_map <- signatures |> List.iter |> fold (\function_info_map, signature -> do
                                    (function_info_map, _) <- alter (addFunctionSignature signature) (getString signature.name) function_info_map
                                    function_info_map) function_info_map
    (state, functions) <- function_info_map
        |> Map.iter
        |> fold (\(state, functions), (_, function_info) -> do
            (state, fns) <- processFunctionInfo state hir_program module_resolver type_resolver kind function_info qn_creator
            functions <- functions + fns
            (state, functions)) (state, [])
    (state, functions)

processFunctions :: ResolverState -> HP.Program -> ModuleResolver -> SM.Module -> (ResolverState, HP.Program)
processFunctions state hir_program module_resolver mod = do
    (functions, signatures) <- mod.items |> List.iter |> fold (\(functions, signatures), item -> case item of
                                            SM.Function f -> (functions + [f], signatures)
                                            SM.FunctionSignature s -> (functions, signatures + [s])
                                            _ -> (functions, signatures)) ([], [])
    (type_resolver, state) <- initTypeResolver module_resolver state []
    (state, functions) <- processFunctionsAndSignatures state hir_program module_resolver type_resolver HF.Normal functions signatures HP.FullPath
    (state, hir_program) <- functions |> List.iter |> fold (\(state, hir_program), function -> do
        qn <- function.name
        location <- function.location
        f <- HP.Function function
        (hir_program, other_item) <- HP.addItem hir_program qn f
        state <- handleItemConflict state other_item location
        (state, hir_program)) (state, hir_program)
    (state, hir_program)