module Siko.Resolver where

import Siko.Syntax.Program
import Siko.Resolver.Error
import Siko.Resolver.Module
import Siko.Resolver.Import
import Siko.Resolver.Local
import Siko.Resolver.Export

data ResolverState = {
                        errors :: [ResolverError],
                     } deriving (Show)

emptyState :: ResolverState
emptyState = ResolverState []

processProgram :: Program -> Result () ResolverState
processProgram program = do
    state <- emptyState
    modules <- getModules program
    local_items <- processLocals modules
    //println "locals: {}" % local_items
    exported_items <- processExports local_items modules
    //println "exported items: {}" % exported_items
    imports <- getImports program
    //println "imports {}" % imports
    (state, imported_items) <- processImports state local_items exported_items imports
    println "imported item: {}" % imported_items

    Ok ()
