module Main {

fn erase[T](value: T) -> Any {
    Any(value)
}

struct Counter {
    count: Int
}

fn counted(counter: Counter) -> Any {
    counter.count = counter.count + 1;
    erase(True)
}

fn main() {
    let boolean = erase(True);
    if boolean is Bool {
        println("bool")
    }

    let number = erase(5);
    if number is Int {
        println(number + 5)
    }

    if !(boolean is String) {
        println("not string")
    }

    if erase([1, 2, 3]) is Vec[Int] {
        println("vec")
    }

    if erase(|| "closure") is fn() -> String {
        println("callable")
    }

    let counter = Counter(0);
    if counted(counter) is Bool {
        println(counter.count)
    }
}

}
