module Main {

import Std.IO.Writer
import Std.IO.Reader
import Std.IO.Async.Scheduler as Async
import Std.Net.Async.TcpListener
import Std.Net.Async.TcpStream

fn handler(conn: TcpStream) {
    let buf = Vec.with_value(1024, 0.as_u8());
    let n = conn.read(buf.slice()).unwrap();
    conn.write(buf.sub_slice(0, n)).unwrap();
}

fn server(port: U16) {
    let listener = TcpListener.bind(port).unwrap();
    let conn = listener.accept().unwrap();
    Async.spawn(|_| handler(conn));
}

fn client(port: U16) {
    let stream = TcpStream.connect("127.0.0.1", port).unwrap();
    stream.write("hello".as_slice()).unwrap();
    let buf = Vec.with_value(1024, 0.as_u8());
    let n = stream.read(buf.slice()).unwrap();
    println(String.from_slice(buf.sub_slice(0, n)));
    Async.stop()
}

fn main() {
    let port = 19878.as_u16();
    let s = Async.Scheduler.new();
    with Async.current = s {
        Async.spawn(|_| server(port));
        Async.spawn(|_| client(port));
        s.run_tasks();
    }
}

}
