module Main {

struct Foo {
    a: Int,
}

instance Drop[Foo] {
    fn drop(self) -> Self {
        println("Dropping Foo with a = ${self.a}");
        self
    }
}

fn doStuff(f: Foo) -> Foo {
    let b = f;
    b
}

fn main() {
    let mut foo = Foo(a: 42);
    println("Before doStuff");
    let b = doStuff(foo);
    println("After doStuff");
    foo = b;
    println("After reassigning foo");
}

}