module Siko.HIR.Backend.Cache where

import Siko.Cache

getHIRBackendFunctionCachePath :: String
getHIRBackendFunctionCachePath = getCachePath + "/hirbackend_functions"

getHIRBackendRecordCachePath :: String
getHIRBackendRecordCachePath = getCachePath + "/hirbackend_records"

getHIRBackendAdtCachePath :: String
getHIRBackendAdtCachePath = getCachePath + "/hirbackend_adts"

getHIRBackendExternalClassImplInfoDbCachePath :: String
getHIRBackendExternalClassImplInfoDbCachePath = getCachePath + "/hirbackend_external_class_impl_info_db"
