module Siko.Constants where

getFullListTypeName = "{}.{}" % (getListModuleName, getListTypeName)
getListTypeName = "List"


getResultTypeName = "Result"
getResultOkVariantName = "Ok"
getResultErrVariantName = "Err"

getIntTypeName = "Int"

getIntModuleName = "Int"
getFloatModuleName = "Float"
getStringModuleName = "String"
getBoolModuleName = "Bool"
getOrderingModuleName = "Ordering"
getOptionModuleName = "Option"
getResultModuleName = "Result"
getListModuleName = "List"
getIteratorModuleName = "Iterator"
getStdUtilBasicModuleName = "Std.Util.Basic"
getStdOpsModuleName = "Std.Ops"
getCharModuleName = "Char"
getEitherModuleName = "Either"

getImplicitModules = [
        getIntModuleName,
        getFloatModuleName,
        getStringModuleName,
        getBoolModuleName,
        getOptionModuleName,
        getOrderingModuleName,
        getResultModuleName,
        getListModuleName,
        getIteratorModuleName,
        getStdUtilBasicModuleName,
        getStdOpsModuleName,
        getCharModuleName,
        getEitherModuleName,
    ]
