module Siko.Constants where

getFullListTypeName = "{}.{}" % (getListModuleName, getListTypeName)
getListTypeName = "List"

getResultTypeName = "Result"
getResultOkVariantName = "Ok"
getResultErrVariantName = "Err"

getBoolTrueVariantName = "True"
getBoolFalseVariantName = "False"

getOrderingEqualVariantName = "Equal"
getOrderingGreaterVariantName = "Greater"
getOrderingLessVariantName = "Less"

getOptionSomeVariantName = "Some"
getOptionNoneVariantName = "None"

getFnGetDiscriminantName = "getDiscriminant"

getIntTypeName = "Int"
getFloatTypeName = "Float"
getStringTypeName = "String"
getCharTypeName = "Char"
getBoolTypeName = "Bool"
getOrderingTypeName = "Ordering"
getOptionTypeName = "Option"
getIteratorTypeName = "Iterator"

getInternalModuleName = "siko"

getIntModuleName = "Int"
getFloatModuleName = "Float"
getStringModuleName = "String"
getBoolModuleName = "Bool"
getOrderingModuleName = "Ordering"
getOptionModuleName = "Option"
getResultModuleName = "Result"
getListModuleName = "List"
getIteratorModuleName = "Iterator"
getStdUtilBasicModuleName = "Std.Util.Basic"
getStdOpsModuleName = "Std.Ops"
getCharModuleName = "Char"
getEitherModuleName = "Either"
getShowClassName = "Show"
getPartialEqClassName = "PartialEq"
getPartialOrdClassName = "PartialOrd"
getOrdClassName = "Ord"
getMainModuleName = "Main"
getMainFunctionName = "main"
getShowClassMemberName = "show"
getPartialEqClassMemberName = "opEq"
getPartialOrdClassMemberName = "partialCmp"
getOrdClassMemberName = "cmp"

getImplicitModules = [
        getIntModuleName,
        getFloatModuleName,
        getStringModuleName,
        getBoolModuleName,
        getOptionModuleName,
        getOrderingModuleName,
        getResultModuleName,
        getListModuleName,
        getIteratorModuleName,
        getStdUtilBasicModuleName,
        getStdOpsModuleName,
        getCharModuleName,
        getEitherModuleName,
    ]
