module Siko.Typechecker.InstanceResolver.Checks where

import Siko.HIR.Class
import Siko.HIR.Type as T
import Siko.HIR.TypeFormatter as TF
import Siko.HIR.Program as P
import Siko.Typechecker.InstanceResolver
import Siko.HIR.Unification.TypeVarGenerator
import Siko.Syntax.Location
import Siko.Typechecker
import Siko.Typechecker.ClassStore
import Siko.Typechecker.Error
import Siko.HIR.Unification as U
import Siko.HIR.Unification.Substitution as S
import Siko.HIR.TypeIsomorphism as HTI
import Map

checkConflicts :: TypecheckerState -> TypecheckerState
checkConflicts state = do
    instance_resolver <- state.instance_resolver
    state <- instance_resolver.instance_map |> Map.iter |> Iterator.fold (\state, (class_name, instance_info_map) -> do
        generic_instance_location <- case get instance_info_map Generic of
            Some i -> do
                Some (getLocation i instance_resolver)
            None -> None
        state <- instance_info_map |> Map.iter |> Iterator.fold (\state, (_, i) -> do
                case generic_instance_location of
                    Some generic_instance_location -> do
                        location <- getLocation i instance_resolver
                        state <- if generic_instance_location == location
                            then state
                            else addError state (ConflictingInstances ("{}" % class_name) generic_instance_location location)
                        state
                    None -> state
            ) state
        state) state
    state

checkInstanceDependenciesForInstance :: TypecheckerState -> T.Type -> P.FullyQualifiedName -> Location -> TypecheckerState
checkInstanceDependenciesForInstance state type class_name location = do
    deps <- case get state.class_store.classes class_name of
        Some class_info -> do
            class_info :: ClassInfo <- class_info // FIXME:
            class_info.direct_dependencies
        None -> panic "Class {} not found in class store" % class_name
    state <- deps |> List.iter |> Iterator.fold (\state, dep -> do
        state <- case checkInstance state type dep of
            Ok (state, cs) -> do
                state :: TypecheckerState <- state // FIXME
                sub <- S.createSubstitution
                (state, sub) <- mergeResolverConstraintsIntoSubstitution state cs sub
                new_type <- S.apply type sub
                if HTI.checkIsomorphicType new_type type state
                    then state
                    else addError state (MissingInstance ("{}" % dep) location)
            Err state -> do
                addError state (MissingInstance ("{}" % dep) location)
        state) state
    state

checkInstanceDependencies :: TypecheckerState -> TypecheckerState
checkInstanceDependencies state = do
    instance_resolver <- state.instance_resolver
    state <- instance_resolver.instance_map |> Map.iter |> Iterator.fold (\state, (class_name, instance_info_map) -> do
        state <- instance_info_map |> Map.iter |> Iterator.fold (\state, (_, i) -> do
                    location <- getLocation i instance_resolver
                    case i of
                        UserDefinedInstanceInfo instance_type id location -> do
                            checkInstanceDependenciesForInstance state instance_type class_name location
                        AutoDerivedInstanceInfo id -> do
                            AutoDerivedInstance instance_type location _ <- getAutoDerivedInstanceById instance_resolver id
                            checkInstanceDependenciesForInstance state instance_type class_name location
                 ) state
        state) state
    state

mergeResolverConstraintsIntoSubstitution :: TypecheckerState -> [(T.TypeVar, P.FullyQualifiedName)] -> S.Substitution -> (TypecheckerState, S.Substitution)
mergeResolverConstraintsIntoSubstitution state constraints sub = do
    constraints |> List.iter |> Iterator.fold (\(state, sub), (var, class_name) -> do
        (var_gen, new_var) <- getNewTypeVar state.var_gen
        state <- state { var_gen = var_gen }
        new_type <- T.Var new_var [T.ClassConstraint class_name]
        sub <- case S.add sub var new_type of
            Ok sub -> sub
            Err _ -> panic "Failed to merge new type var into sub {} {} {}" % (var, TF.toLongString new_type, sub)
        (state, sub)) (state, sub)
