module Siko.HIR.ClassInfoStore where

import Siko.HIR.Program as P
import Siko.HIR.Type as T
import Siko.HIR.Unification as U
import Siko.HIR.TypeIsomorphism as HTI

import Map

data ClassMemberInfo = { type :: T.Type,
                         has_default_impl :: Bool }

data ClassInfo = {  arg_type :: T.Type,
                    members :: Map String ClassMemberInfo,
                    dependencies :: [P.FullyQualifiedName] }

data ClassInfoStore = { classes :: Map P.FullyQualifiedName ClassInfo }

createClassInfoStore :: ClassInfoStore
createClassInfoStore = ClassInfoStore Map.empty

addClassInfo :: ClassInfoStore -> P.FullyQualifiedName -> ClassInfo -> ClassInfoStore
addClassInfo store class_name class_info = do
    (classes, _) <- Map.insert store.classes class_name class_info
    store { classes = classes }

getDependencies :: ClassInfoStore -> P.FullyQualifiedName -> [P.FullyQualifiedName]
getDependencies store class_name = case get store.classes class_name of
    Some class_info -> do
        class_info :: ClassInfo <- class_info // FIXME
        class_info.dependencies
    None -> panic "Class {} not found in class dependency store" % class_name

getClassInfo :: ClassInfoStore -> P.FullyQualifiedName -> ClassInfo
getClassInfo store class_name = case get store.classes class_name of
    Some class_info -> class_info
    None -> panic "Class {} not found in class dependency store" % class_name

instance U.ClassProvider ClassInfoStore where
    getAllClassDependencies store qn = getDependencies store qn

instance HTI.DependencyProvider ClassInfoStore where
    getAllDependencies store qn = getDependencies store qn
