module Siko.HIR.Data where

import Siko.HIR.Type
import Siko.HIR.Program as HP

data Variant = Variant String [Type] deriving (Show)

data AbstractDataType = { name :: String,
                          module_name :: String,
                          type_args :: [TypeVar],
                          variants :: [Variant],
                          derived_classes :: [HP.FullyQualifiedName],
                          type :: Type,
                        } deriving (Show)

data RecordField = RecordField String Type deriving (Show)

data Record = { name :: String,
                module_name :: String,
                type_args :: [TypeVar],
                fields :: [RecordField],
                external :: Bool,
                derived_classes :: [HP.FullyQualifiedName],
                type :: Type,
              } deriving (Show)