module Siko.HIR.Type(Type(..),
                     TypeVar(..),
                     Constraint(..),
                     RowKind(..),
                     collectVars,
                     getArgs,
                     getArgsLimited,
                     getResultType,
                     isConcreteType,
                     isFunction,
                     removeFixed,
                     removeOwnership) where

import Siko.HIR.Program as HP
import Map

data TypeVar = TypeVar Int deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data RowKind = NamedRow String
               | IndexedRow Int
               deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Constraint = ClassConstraint HP.FullyQualifiedName
                  | RowConstraint RowKind Type
                  deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Type = Var TypeVar [Constraint]
            | FixedTypeArg String TypeVar [Constraint]
            | Named HP.FullyQualifiedName [Type]
            | Function Type Type
            | Never TypeVar
            | Ref Type
            | Owner Type
            | Tuple [Type]
            deriving (Show, PartialEq, Eq, PartialOrd, Ord)

isFunction :: Type -> Bool
isFunction type = case type of
    Function _ _ -> True
    _ -> False

collectVarsFromConstraints :: [Constraint] -> [TypeVar]
collectVarsFromConstraints constraints = constraints |> List.iter |> Iterator.fold (\all, c -> case c of
                ClassConstraint _ -> all
                RowConstraint _ row_type -> all + collectVars row_type) []

collectVars :: Type -> [TypeVar]
collectVars type = case type of
    Var var constraints -> [var] + collectVarsFromConstraints constraints
    FixedTypeArg _ var constraints -> [var] + collectVarsFromConstraints constraints
    Named _ args -> args |> List.iter |> Iterator.fold (\vars, arg -> do
        vs <- collectVars arg
        vars + vs) []
    Function from to -> collectVars from + collectVars to
    Never var -> [var]
    Ref t -> collectVars t
    Owner t -> collectVars t
    Tuple args -> args |> List.iter |> Iterator.fold (\vars, arg -> do
        vs <- collectVars arg
        vars + vs) []

getArgs :: Type -> [Type]
getArgs type =
    case type of
        Function from to -> [from] + getArgs to
        _ -> []

getArgsLimited :: Type -> Int -> [Type]
getArgsLimited type limit = if limit == 0 then []
    else case type of
        Function from to -> [from] + getArgsLimited to (limit - 1)
        _ -> []

getResultType :: Type -> Int -> Type
getResultType type arg_count =
    case type of
        Function from to -> if arg_count == 0 then type else getResultType to (arg_count - 1)
        _ -> type

isConcreteType :: Type -> Bool
isConcreteType type = case type of
    Var _ _ -> False
    FixedTypeArg _ _ _ -> False
    Named _ args -> args |> List.iter |> Iterator.fold (\concrete, arg -> do
        concrete && isConcreteType arg) True
    Function from to -> isConcreteType from && isConcreteType to
    Never var -> True
    Ref t -> isConcreteType t
    Owner t -> isConcreteType t
    Tuple args -> args |> List.iter |> Iterator.fold (\concrete, arg -> do
        concrete && isConcreteType arg) True

removeFixed :: Type -> Type
removeFixed type = case type of
    Var _ _ -> type
    FixedTypeArg _ var constraints -> Var var constraints
    Named qn args -> do
        args <- args |> List.iter |> Iterator.map (\arg -> removeFixed arg) |> toList
        Named qn args
    Function from to -> do
        from <- removeFixed from
        to <- removeFixed to
        Function from to
    Never var -> type
    Ref t -> Ref (removeFixed t)
    Owner t -> Owner (removeFixed t)
    Tuple args -> do
        args <- args |> List.iter |> Iterator.map (\arg -> removeFixed arg) |> toList
        Tuple args

removeOwnership :: Type -> Type
removeOwnership type = case type of
    Var _ _ -> type
    FixedTypeArg _ _ _ -> type
    Named qn args -> do
        args <- args |> List.iter |> Iterator.map (\arg -> removeOwnership arg) |> toList
        Named qn args
    Function from to -> do
        from <- removeOwnership from
        to <- removeOwnership to
        Function from to
    Never var -> type
    Ref t -> removeOwnership t
    Owner t -> removeOwnership t
    Tuple args -> do
        args <- args |> List.iter |> Iterator.map (\arg -> removeOwnership arg) |> toList
        Tuple args
