module Siko.HIR.Type where

data TypeVar = TypeVar Int deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Constraint = ClassConstraint String deriving (Show)

data Type = TypeArg TypeVar [Constraint]
            | FixedTypeArg String TypeVar [Constraint]
            | Named String [Type]
            | Function Type Type
            | Never TypeVar
            | Ref Type
            | Tuple [Type]
            deriving (Show)
