module Siko.Resolver.Autoderive.Eq {

import Siko.Resolver.Autoderive.Utils
import Siko.AST.Data
import Siko.AST.Instances
import Siko.AST.Name
import Siko.AST.Type
import Siko.Constants.Builtins as B
import Siko.Interner as I

pub fn derive_eq_enum(enum_def: EnumDef, module_name: I.String) -> Option[InstanceDef] {
    let trait_name = get_resolved_trait_name();
    if !enum_def.has_derive(trait_name) {
        return None;
    }
    Some(build_eq_enum(enum_def, module_name))
}

pub fn build_eq_enum(enum_def: EnumDef, module_name: I.String) -> InstanceDef {
    let trait_name = get_resolved_trait_name();
    let loc = enum_def.name.location;
    let enum_qname = enum_def.qualified_name.unwrap();
    let (type_arg_defs, enum_type_args) =
        build_type_arg_defs(enum_def.type_arg_defs, trait_name, loc);
    let enum_type = TypeDef.Named(NamedInfo(Name.inner(enum_qname), enum_type_args));
    make_instance(trait_name, type_arg_defs, enum_type, [], [], module_name, loc)
}

pub fn derive_eq_struct(struct_def: StructDef, module_name: I.String) -> Option[InstanceDef] {
    let trait_name = get_resolved_trait_name();
    if !struct_def.has_derive(trait_name) {
        return None;
    }
    let loc = struct_def.name.location;
    let struct_qname = struct_def.qualified_name.unwrap();
    let (type_arg_defs, struct_type_args) =
        build_type_arg_defs(struct_def.type_arg_defs, trait_name, loc);
    let struct_type = TypeDef.Named(NamedInfo(Name.inner(struct_qname), struct_type_args));
    Some(make_instance(trait_name, type_arg_defs, struct_type, [], [], module_name, loc))
}

fn get_resolved_trait_name() -> Name {
    Name.inner(B.get_trait_eq_qn())
}

}
