module Siko.HIR.Backend.Core where

import IO
import Map
import Siko.Constants
import Siko.Format
import Siko.HIR.Backend.CaseTransformer
import Siko.HIR.Backend.ClosureConverter as CC
import Siko.HIR.Backend.EffectResolver as ER
import Siko.HIR.Backend.Inliner as Inliner
import Siko.HIR.Backend.InstanceResolver as IR
import Siko.HIR.Backend.Monomorphization as MO
import Siko.HIR.Backend.StateProvider
import Siko.HIR.Backend.TupleTransformer as TT
import Siko.HIR.Backend.Typechecker.ClassTypeInfo as TC
import Siko.HIR.Backend.Typechecker.FunctionTypeInfo as TF
import Siko.HIR.Backend.UpdateTransformer as UT
import Siko.HIR.Backend.Util
import Siko.HIR.Backend.VariantTransformer as VT
import Siko.HIR.Class as HC
import Siko.HIR.Closure
import Siko.HIR.Data as HD
import Siko.HIR.Effect as HE
import Siko.HIR.FullyQualifiedName as FQ
import Siko.HIR.Function as HF
import Siko.HIR.Type as HT
import Siko.Query.Lookup
import Siko.Trace
import Siko.Util.DependencyProcessor

data BackendStateProvider = { class_map :: Map FQ.FullyQualifiedName HC.Class,
                              class_type_info_map :: Map FQ.FullyQualifiedName TC.ClassTypeInfo,
                              instance_map :: Map FQ.FullyQualifiedName HC.Instance,
                              function_map :: Map FQ.FullyQualifiedName (HF.Function ()),
                              typed_function_map :: Map FQ.FullyQualifiedName (HF.Function HT.Type),
                              func_type_info_map :: Map FQ.FullyQualifiedName TF.FunctionTypeInfo,
                              checked_func_type_info_map :: Map FQ.FullyQualifiedName TF.FunctionTypeInfo,
                              record_map :: Map FQ.FullyQualifiedName HD.Record,
                              adt_map :: Map FQ.FullyQualifiedName HD.AlgebraicDataType,
                              effect_map :: Map FQ.FullyQualifiedName HE.Effect,
                              instance_info_map :: Map IR.InstanceKey IR.InstanceInfo
                            } deriving (Move)

instance ClassProvider BackendStateProvider where
    getClass p qn = case Map.get p.class_map qn of
        Some c -> c
        None -> panic "Class not found {}" % qn

    getClassTypeInfo p qn = case Map.get p.class_type_info_map qn of
        Some i -> i
        None -> panic "No class type info found"

    getAllDependencies p qn = (getClassTypeInfo p qn).all_dependencies

    getInstance p qn = case Map.get p.instance_map qn of
        Some i -> i
        None -> panic "Instance not found {}" % qn

instance FunctionProvider BackendStateProvider where
    getFunction p qn = case Map.get p.function_map qn of
        Some f -> f
        None -> panic "No function found {}" % qn

    getTypedFunction p qn = case Map.get p.typed_function_map qn of
        Some f -> f
        None -> panic "No typed function found {}" % qn

instance FunctionTypeInfoProvider BackendStateProvider where
    getFunctionTypeInfo p qn = case Map.get p.func_type_info_map qn of
        Some f -> f
        None -> panic "No functypeinfo found {}" % qn

instance CheckedFunctionTypeInfoProvider BackendStateProvider where
    getCheckedFunctionTypeInfo p qn = case Map.get p.checked_func_type_info_map qn of
        Some f -> f
        None -> panic "No checked functypeinfo found {}" % qn

    getCheckedFunctionTypeInfoOpt p qn = Map.get p.checked_func_type_info_map qn

instance RecordProvider BackendStateProvider where
    getRecord p qn = case Map.get p.record_map qn of
        Some r -> r
        None -> panic "No record found {}" % qn

    getRecordOpt p qn = Map.get p.record_map qn

instance AdtProvider BackendStateProvider where
    getAdt p qn = case Map.get p.adt_map qn of
        Some a -> a
        None -> panic "No adt found {}" % qn

    getAdtOpt p qn = Map.get p.adt_map qn

instance EffectProvider BackendStateProvider where
    getEffect p qn = case Map.get p.effect_map qn of
        Some e -> e
        None -> panic "No effect found {}" % qn

    getEffectOpt p qn = Map.get p.effect_map qn

instance RegisteredInstanceProvider BackendStateProvider where
    getRegisteredInstance p key = case Map.get p.instance_info_map key of
        Some i -> i
        None -> panic "No instance info found {}" % key

    getRegisteredInstanceOpt p key = Map.get p.instance_info_map key

resolveEffects provider entry_points = do
    empty_resolution_set <- HE.EffectResolutionSet Map.empty Map.empty
    entry_points <- List.map entry_points (\qn -> FQ.Effectless qn (Some empty_resolution_set))
    loop (resolved_fns, queue) <- (Map.empty, entry_points) do
        if List.isEmpty queue
        then break resolved_fns
        else do
            (last, queue) <- removeLast queue
            case Map.get resolved_fns last of
                Some _ -> (resolved_fns, queue)
                None -> do
                    //println "Resolving effects for {}" % last
                    case last of
                        FQ.Effectless qn (Some resolution_set) -> do
                            state <- createStateProvider provider
                            (state, resolved_fn, qns) <- ER.resolveEffects state qn resolution_set
                            queue <- queue + qns
                            (Map.put resolved_fns last resolved_fn, queue)
                        FQ.Effectless qn None -> do
                            state <- createStateProvider provider
                            (state, resolved_fn, qns) <- ER.resolveEffects state qn empty_resolution_set
                            queue <- queue + qns
                            (Map.put resolved_fns last resolved_fn, queue)
                        _ -> panic "Incorrect qn in effect resolver queue {}" % last

data MonomorphizationContext = { functions :: Map FQ.FullyQualifiedName (HF.Function HT.Type),
                                 records :: Map FQ.FullyQualifiedName HD.Record,
                                 adts :: Map FQ.FullyQualifiedName HD.AlgebraicDataType,
                                 external_class_impl_info_db :: HD.ExternalClassImplInfoDb
                               }

monomorphize provider base_main_qn unreachable_qn = do
    empty_resolution_set <- HE.EffectResolutionSet Map.empty Map.empty
    context <- MonomorphizationContext Map.empty Map.empty Map.empty HD.createExternalClassImplInfoDb
    monomorphized_unreachable_qn <- FQ.Monomorphized (FQ.Effectless unreachable_qn (Some empty_resolution_set)) (HT.Never)
    monomorphized_main_qn <- FQ.Monomorphized (FQ.Effectless base_main_qn (Some empty_resolution_set)) (HT.Tuple [])
    loop (context, queue) <- (context, [monomorphized_main_qn, monomorphized_unreachable_qn]) do
        if List.isEmpty queue
        then break context
        else do
            (last, queue) <- removeLast queue
            case last of
                FQ.Monomorphized orig_qn ty -> do
                    case Map.get context.functions last of
                        Some _ -> (context, queue)
                        None -> do
                            trace "MONO fn {} " % last
                            state <- createStateProvider provider
                            state <- state { ignore_never = True }
                            (state, monomorphized_fn, functions, records, adts, external_class_impls) <- MO.monomorphizeFunction state orig_qn ty
                            (state, external_class_impl_info_db, qns) <- List.fold (state, context.external_class_impl_info_db, []) external_class_impls (\(state, external_class_impl_info_db, qns), info -> do
                                (state, qn) <- MO.monomorphizeClassImpl state (info.external_class_impl, info.type)
                                qns <- case qn of
                                    Some qn -> List.push qns qn
                                    None -> qns
                                external_class_impl_info_db <- HD.addExternalClassImplInfo external_class_impl_info_db info qn
                                (state, external_class_impl_info_db, qns))
                            queue <- queue + functions + records + adts + qns
                            monomorphized_fn <- monomorphized_fn { name = last }
                            functions <- Map.put context.functions last monomorphized_fn
                            (context { functions = functions, external_class_impl_info_db = external_class_impl_info_db }, queue)
                FQ.Record orig_qn args -> do
                    case Map.get context.records last of
                        Some _ -> (context, queue)
                        None -> do
                            trace "MONO record {} " % last
                            state <- createStateProvider provider
                            (state, record, records, adts) <- MO.monomorphizeRecord state orig_qn args
                            queue <- queue + records + adts
                            record <- record { name = last }
                            records <- Map.put context.records last record
                            (context { records = records }, queue)
                FQ.Adt orig_qn args -> do
                    case Map.get context.adts last of
                        Some _ -> (context, queue)
                        None -> do
                            trace "MONO adt {} " % last
                            state <- createStateProvider provider
                            (state, adt, records, adts) <- MO.monomorphizeAdt state orig_qn args
                            queue <- queue + records + adts
                            adt <- adt { name = last }
                            adts <- Map.put context.adts last adt
                            (context { adts = adts }, queue)
                _ -> panic "Monomorphized qn is unexpected {}" % last

data ClosureConverterContext = { closure_names :: [FQ.FullyQualifiedName],
                                 closure_instances :: [ClosureInstance]
                               }

processClosureInstance closure_instance index = do
    adt_type <- CC.closureConvertType (CC.getClosureType closure_instance.closure_name)
    variant_qn <- FQ.ClosureInstance closure_instance
    record_type <- HT.Named variant_qn []
    arg_types <- List.map closure_instance.arg_types CC.closureConvertType
    (record, function) <- createVariantRecordFromTypes variant_qn index record_type adt_type arg_types
    (function, record)

convertClosures provider functions records = do
    context <- ClosureConverterContext [] []
    (context, functions) <- Map.mapS context functions (\context, (qn, fn) -> do
        state <- createStateProvider provider
        (state, fn, closure_names, closure_instances) <- CC.closureConvertFunction state fn
        closure_names <- context.closure_names + closure_names
        closure_instances <- context.closure_instances + closure_instances
        context <- context { closure_names = closure_names, closure_instances = closure_instances }
        (context, qn, fn))
    (context, records) <- Map.mapS context records (\context, (qn, record) -> do
        state <- createStateProvider provider
        (state, record, closure_names, closure_instances) <- CC.closureConvertRecord state record
        closure_names <- context.closure_names + closure_names
        closure_instances <- context.closure_instances + closure_instances
        context <- context { closure_names = closure_names, closure_instances = closure_instances }
        (context, qn, record))
    closures <- Map.empty
    closure_instances <- context.closure_instances |> List.sort |> List.dedup
    closure_names <- context.closure_names |> List.sort |> List.dedup
    context <- context { closure_instances = closure_instances, closure_names = closure_names }
    closures <- List.fold closures context.closure_names (\closures, closure_name -> Map.put closures closure_name [])
    closures <- List.fold closures context.closure_instances (\closures, closure_instance -> Map.add closures closure_instance.closure_name closure_instance)
    //println "found {} closures" % Map.getSize closures
    //println "closures: {}" % closures
    (functions, records, adts) <- Map.fold (functions, records, Map.empty) closures (\(functions, records, adts), (closure_name, closure_instances) -> do
        //println "Processing closure {} with {} instances" % (closure_name, List.getLength closure_instances)
        (functions, records) <- List.foldE (functions, records) closure_instances (\(functions, records), index, closure_instance -> do
            (function, record) <- processClosureInstance closure_instance index
            records <- Map.put records record.name record
            functions <- Map.put functions function.name function
            (functions, records))
        state <- createStateProvider provider
        (state, closure_call) <- CC.createClosureCall state closure_instances closure_name
        (state, closure_adt) <- CC.createClosureAdt state closure_instances closure_name
        adts <- Map.put adts closure_adt.name closure_adt
        functions <- Map.put functions closure_call.name closure_call
        (functions, records, adts))
    (functions, records, adts)

transformVariantsAndCases :: BackendStateProvider -> BackendStateProvider
transformVariantsAndCases provider = do
    vt_context <- VT.createContext
    (vt_context, adt_map) <- Map.mapS vt_context provider.adt_map (\vt_context, (qn, adt) -> do
        (vt_context, adt) <- VT.processAlgebraicDataType vt_context adt
        (vt_context, qn, adt))
    record_map <- Map.merge provider.record_map vt_context.records
    provider <- provider { record_map = record_map, adt_map = adt_map }
    typed_function_map <- Map.map provider.typed_function_map (\(qn, f) -> do
        state <- createStateProvider provider
        (state, f) <- transformCases state f
        (qn, f))
    provider <- provider { typed_function_map = typed_function_map }
    typed_function_map <- Map.merge provider.typed_function_map vt_context.functions
    record_map <- Map.merge provider.record_map vt_context.records
    provider { typed_function_map = typed_function_map, record_map = record_map }

process :: [HF.Function HT.Type] ->
           [HF.Function ()] ->
           [HC.Class] ->
           [HC.Instance] ->
           [HE.Effect] ->
           [HD.AlgebraicDataType] ->
           [HD.Record] -> ([HF.Function HT.Type],
                           [HD.Record],
                           [HD.AlgebraicDataType],
                           HD.ExternalClassImplInfoDb)
process typed_functions functions classes instances effects adts records = do
    class_map <- List.fold Map.empty classes (\class_map, c -> Map.put class_map c.name c)
    function_map <- List.fold Map.empty functions (\function_map, f -> Map.put function_map f.name f)
    typed_function_map <- List.fold Map.empty typed_functions (\typed_function_map, f -> Map.put typed_function_map f.name f)
    instance_map <- List.fold Map.empty instances (\instance_map, i -> Map.put instance_map i.name i)
    registered_instance_map <- List.fold Map.empty instances (\registered_instance_map, i -> do
        (key, info) <- TC.createInstanceInfo i
        Map.put registered_instance_map key info)
    adt_map <- List.fold Map.empty adts (\adt_map, adt -> Map.put adt_map adt.name adt)
    record_map <- List.fold Map.empty records (\record_map, record -> Map.put record_map record.name record)
    effect_map <- List.fold Map.empty effects (\effect_map, e -> Map.put effect_map e.name e)
    provider <- BackendStateProvider class_map
                                     Map.empty
                                     instance_map
                                     function_map
                                     typed_function_map
                                     Map.empty
                                     Map.empty
                                     record_map
                                     adt_map
                                     effect_map
                                     registered_instance_map
    class_type_info_map <- Map.map class_map (\(name, c) -> do
        state <- createStateProvider provider
        (state, class_type_info) <- TC.createClassTypeInfo state c
        (name, class_type_info))
    provider <- provider { class_type_info_map = class_type_info_map }
    provider <- transformVariantsAndCases provider
    typed_function_map <- Map.map provider.typed_function_map (\(qn, f) -> do
        state <- createStateProvider provider
        (state, f) <- UT.processFunction state f
        (qn, f))
    provider <- provider { typed_function_map = typed_function_map }
    base_main_qn <- FQ.FullPath getMainModuleName getMainFunctionName
    members <- Map.fold [] typed_function_map (\members, (qn, fn) -> case fn.kind of
        HF.Normal info -> if isSome info.source
            then List.push members qn
            else members
        HF.Interface _ -> List.push members qn
        _ -> members)
    unreachable_qn <- FQ.FullPath getStdUtilBasicModuleName getUnreachableName
    resolved_effect_fns <- resolveEffects provider ([base_main_qn, unreachable_qn] + members)
    provider <- provider { typed_function_map = resolved_effect_fns }
    monomorphize_context <- monomorphize provider base_main_qn unreachable_qn
    provider <- provider { typed_function_map = monomorphize_context.functions, record_map = monomorphize_context.records, adt_map = monomorphize_context.adts }
    //Map.forEach monomorphize_context.functions (\(qn, _) -> println "Mono func {}" % qn)
    (functions, records, closure_adts) <- convertClosures provider monomorphize_context.functions monomorphize_context.records
    //Map.forEach functions (\(qn, _) -> println "convertClosures func {}" % qn)
    provider <- provider { typed_function_map = functions }
    functions <- Map.fold Map.empty functions (\functions, (qn, fn) -> do
        if Inliner.willBeInlined fn
        then functions
        else do
            state <- createStateProvider provider
            (state, fn) <- Inliner.processFunction state fn
            functions <- Map.put functions qn fn
            functions)
    (tt_context, functions) <- TT.transform TT.createContext functions
    (tt_context, records) <- TT.transform tt_context records
    functions <- Map.merge functions tt_context.functions
    //Map.forEach functions (\(qn, _) -> println "final func {}" % qn)
    records <- Map.merge records tt_context.tuples
    adts <- Map.merge monomorphize_context.adts closure_adts
    lowered_fns <- functions |> Map.iter |> Iterator.map (\(key, f) -> f) |> toList
    lowered_records <- records |> Map.iter |> Iterator.map (\(key, r) -> r) |> toList
    lowered_adts <- adts |> Map.iter |> Iterator.map (\(key, a) -> a) |> toList
    (lowered_fns, lowered_records, lowered_adts, monomorphize_context.external_class_impl_info_db)
