module Int(Int, parse) where

data Int = extern

instance Add Int where
    opAdd a b = addInt a b

instance Sub Int where
    opSub a b = subInt a b

instance Mul Int where
    opMul a b = mulInt a b

instance Div Int where
    opDiv a b = divInt a b

instance PartialOrd Int where
    partialCmp a b = partialCmpInt a b

instance Ord Int where
    cmp a b = cmpInt a b

instance Eq Int

instance PartialEq Int where
    opEq a b = eqInt a b

instance Show Int where
    show a = showInt a

instance Negative Int where
    opNegative a = negativeInt a

addInt :: ~Int -> ~Int -> ~Int
addInt a b = extern

subInt :: ~Int -> ~Int -> ~Int
subInt a b = extern

mulInt :: ~Int -> ~Int -> ~Int
mulInt a b = extern

divInt :: ~Int -> ~Int -> ~Int
divInt a b = extern

eqInt :: ~Int -> ~Int -> ~Bool
eqInt a b = extern

showInt :: ~Int -> ~String
showInt a = extern

negativeInt :: ~Int -> ~Int
negativeInt a = extern

partialCmpInt :: ~Int -> ~Int -> ~Option (~Ordering)
partialCmpInt a b = extern

cmpInt :: ~Int -> ~Int -> ~Ordering
cmpInt a b = extern

parse :: String -> Option Int
parse s = extern