module Map where

data Map k v = extern

instance (Show k, Show v) => Show Map k v where
    show a = extern

instance (PartialEq k, PartialEq v) => PartialEq Map k v where
    opEq a b = extern

instance (Eq k, Eq v) => Eq Map k v

empty k v :: (Ord k) => Map k v
empty = extern

insert k v :: (Ord k) => Map k v -> k -> v -> (Map k v, Option v)
insert m k v = extern

get k v :: (Ord k) => Map k v -> k -> Option v
get m k = extern

remove k v :: (Ord k) => Map k v -> k -> (Map k v, Option v)
remove m k = extern

alter k v :: (Ord k) => (Option v -> Option v) -> k -> Map k v -> (Map k v, Option v)
alter f k m = // FIXME: make this builtin and much faster
    case f (get m k) of
        Some v -> insert m k v
        None -> remove m k

iter k v :: Map k v -> Iterator (k, v)
iter m = createIterator (intoIter m) nextItem

data MapIterator k v = extern

intoIter k v :: Map k v -> MapIterator k v
intoIter m = extern

nextItem k v :: MapIterator k v -> Option (MapIterator k v, (k, v))
nextItem iter = extern

toMap k v :: (Ord k) => Iterator (k, v) -> Map k v
toMap iter = fold (\m, (k, v) -> do
    (m, _) <- insert m k v
    m) empty iter

getSize k v :: Map k v -> Int
getSize m = extern