module Set where

data Set a = { items :: [a] } deriving (Show)

instance (Ord a) => Add Set a where
    opAdd a b = Set ((a.items + b.items) |> sort |> dedup)

instance (PartialEq a) => PartialEq Set a where
    opEq a b = a.items == b.items

empty a :: Set a
empty = Set []

contains a :: (PartialEq a) => Set a -> a -> Bool
contains set item = List.contains set.items item

insert a :: (Ord a) => Set a -> a -> (Set a, Bool)
insert set item = do
    len <- getLength set.items
    items <- set.items + [item]
    items <- items |> sort |> dedup
    inserted <- len != getLength items
    (set { items = items }, inserted)

remove a :: (PartialEq a) => Set a -> a -> Set a
remove set item = do
    items <- set.items |> List.iter |> Iterator.filter (\i -> i != item) |> toList
    set { items = items }

iter a :: Set a -> Iterator a
iter set = set.items |> List.iter

toSet a :: (Ord a) => Iterator a -> Set a
toSet items = Set (toList items |> sort |> dedup)

isEmpty a :: Set a -> Bool
isEmpty set = List.isEmpty set.items

collect a b :: [b] -> Set a -> (Set a -> b -> Set a) -> Set a
collect sources result f =
    loop result <- result do
        start_size <- Set.getSize result
        result <- List.fold result sources f
        if Set.getSize result != start_size
        then result
        else break result