module Siko.MIR.Backend.Ownership.CallContext where

import Map
import Siko.MIR.Backend.Ownership.GroupDependencyMap
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.Util.DependencyProcessor

data CallContext = { sub_map :: Map OwnershipTypeVariable [[OwnershipTypeVariable]] } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

mergeCallContexts :: CallContext -> CallContext -> CallContext
mergeCallContexts source dest = do
    dest <- dest.sub_map
    source <- source.sub_map
    dest <- Map.fold dest source (\dest, (var, parent_lists) -> do
        (dest, _) <- Map.alter2 (\dest_parent_lists -> case dest_parent_lists of
            Some dest_parent_lists -> do
                dest_parent_lists <- List.fold dest_parent_lists parent_lists (\dest_parent_lists, parents -> do
                    found <- List.fold False dest_parent_lists (\found, dest_parents -> do
                        if List.startsWith dest_parents parents
                        then True
                        else found)
                    if found
                    then dest_parent_lists
                    else List.push dest_parent_lists parents)
                Some dest_parent_lists
            None -> Some parent_lists) var dest
        dest)
    CallContext dest

addOwnershipVarToCallContext :: CallContext -> OwnershipTypeVariable -> CallContext
addOwnershipVarToCallContext call_context var = do
    sub_map <- Map.map call_context.sub_map (\(v, parent_lists) -> if List.isEmpty parent_lists
        then (v, [[var]])
        else do
            parent_lists <- List.map parent_lists (\parents -> List.push parents var)
            (v, parent_lists))
    CallContext sub_map

createCallContextForGroup :: GroupIndexMap GroupTypeVariable -> 
                             Map GroupTypeVariable [GroupTypeVariable] -> 
                             [M.MemberInfo] -> 
                             [CallContext] -> 
                             [GroupTypeVariable] -> [CallContext]
createCallContextForGroup group_index_map group_deps_map members base_call_contexts group_items = do
    deps <- List.fold [] group_items (\deps, item -> case Map.get group_deps_map item of
        Some ds -> deps + List.filter ds (\dep -> not (List.contains group_items dep))
        None -> deps)
    //println "group {} deps {}" % (group, deps)
    deps <- deps |> List.sort |> List.dedup
    call_context <- CallContext Map.empty
    (call_context, ownership_vars, group_locals) <- List.fold (call_context, [], []) members (\(call_context, ownership_vars, group_locals), member -> do
        group_locals <- if List.contains group_items member.root && List.contains group_items member.info.arg_group_var
        then List.push group_locals member.info.ownership_var
        else group_locals
        if List.contains group_items member.root && List.contains deps member.info.arg_group_var
        then do
            group_index <- getGroupIndex group_index_map member.info.arg_group_var
            //println "Looking up {} {}" % (member.info.arg_group_var, group_index)
            dep_call_context <- List.atIndex base_call_contexts group_index
            //println "dep cc {}" % dep_call_context
            // member.info.ownership_var will affect everything
            dep_call_context <- addOwnershipVarToCallContext dep_call_context member.info.ownership_var
            call_context <- mergeCallContexts dep_call_context call_context
            ownership_vars <- List.push ownership_vars member.info.ownership_var
            (call_context, ownership_vars, group_locals)
        else (call_context, ownership_vars, group_locals))
    // add all group vars as vars that can be affected by parents
    call_context <- List.fold call_context (ownership_vars + group_locals) (\call_context, var -> do
        sub_map <- Map.put call_context.sub_map var List.empty
        call_context { sub_map = sub_map })
    base_call_contexts <- List.push base_call_contexts call_context
    base_call_contexts

createBaseCallContexts :: InferenceInfo -> InferenceInfo
createBaseCallContexts inference_info = do
    group_deps_map <- inference_info.group_dep_map_info.deps_map
    groups <- inference_info.group_dep_map_info.groups
    group_index_map <- inference_info.group_dep_map_info.group_index_map
    // println "group_index_map {}" % group_index_map
    // println "members {}" % members
    // println "groups {}" % groups
    groups <- List.map groups (\g -> g.items)
    base_call_contexts <- List.fold List.empty groups (createCallContextForGroup group_index_map group_deps_map inference_info.members)
    //println "Full version {}" % base_call_contexts
    inference_info { base_call_contexts = base_call_contexts }
