module Main where

import Hack
import Siko.Parser
import Siko.Resolver as R
import Siko.Typechecker as TC
import Siko.Transpiler as Transpiler
import Siko.Diagnostics
import Siko.Backend as B
import Siko.Config
import Siko.Trace

processArgs :: [String] -> Config
processArgs args = loop (config, args) <- (getDefaultConfig, args) do
    case pop args of
        Some (arg, rest) -> do
            case arg of
                "-o" -> do
                    case pop rest of
                        Some (arg, rest) -> do
                            config <- config { output_file_name = Some arg }
                            (config, rest)
                        None -> do
                            panic "Missing output_file"
                "-v" -> (config { verbose = True }, rest)
                _ -> do
                        config :: Config <- config // FIXME: type inference
                        input_files <- config.input_files + [arg]
                        config <- config { input_files = input_files }
                        (config, rest)
        None -> break config

main = do
    args <- Option.unwrap (tail getArgs)
    config <- processArgs args
    trace config "Reading inputs.."
    source <- config.input_files |> List.iter |> fold (\source, arg -> do
        s <- readTextFile arg
        source + "\n" + s) ""
    trace config "Parsing.."
    (program, lexer_errors, parser_errors) <- parse source
    lexer_errors |> List.iter |> forEach \error -> printLexerError error
    parser_errors |> List.iter |> forEach \error -> printParserError error
    trace config "Resolving names.."
    (hir_program, var_gen, resolver_errors) <- R.processProgram program
    resolver_errors |> List.iter |> forEach \error -> printResolverError error
    trace config "Typechecking.."
    case TC.processProgram config hir_program var_gen of
        Ok mir_program -> do
            trace config "Optimizing.."
            lir_program <- B.processProgram config mir_program
            trace config "Transpiling.."
            rust_output <- Transpiler.transpile lir_program
            writeTextFile (getOutputFileName config Normal) rust_output
        Err typechecker_errors -> typechecker_errors |> List.iter |> forEach \error -> printTypecheckerError error
    ()
