module Siko.Util.Format where

data Indent = Indent Int

instance Show Indent where
    show (Indent i) = join (repeat "  " i) ""

inc :: Indent -> Indent
inc (Indent i) = Indent (i + 2)

escapeString :: String -> String
escapeString lit = do
    lit <- replace lit "\\" "\\\\"
    lit <- replace lit "\n"  "\\n"
    lit <- replace lit "\r" "\\r"
    lit <- replace lit "\t" "\\t"
    lit <- replace lit "\"" "\\\""
    lit