module Siko.MIR.Backend where

import Siko.MIR.Backend.Ownership.Inference as Inference
import Siko.MIR.Backend.Ownership.AddConverter2 as AddConverter
import Siko.MIR.Backend.SanityCheck as SanityCheck
import Siko.MIR.Backend.Rebinder as Rebinder
import Siko.MIR.Backend.Simplifier as Simplifier
import Siko.MIR.Backend.Simplification.TransformUpdates as TransformUpdates
import Siko.MIR.Backend.Inliner as Inliner
import Siko.MIR.Backend.FnArgVarCreator as FnArgVarCreator
import Siko.MIR.Backend.ConverterVarCreator as ConverterVarCreator
import Siko.MIR.Backend.Traversal
import Siko.MIR.Program as MP
import Siko.LIR.Program as LP
import Siko.MIR.Data
import Siko.MIR.Type as T
import Siko.MIR.Function as F
import Siko.MIR.Expr
import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessor
import Map
import Hack

collectDataDeps :: MP.Program -> Map MP.Identity [MP.Identity]
collectDataDeps mir_program = do
    dependencies <- empty
    dependencies <- Map.fold dependencies mir_program.adts (\dependencies, (id, adt) -> do
            dependencies <- Map.put dependencies id []
            List.fold dependencies adt.variants (\dependencies, variant ->
                Map.add dependencies id (T.getIdentity variant.type))
        )
    dependencies <- Map.fold dependencies mir_program.records (\dependencies, (id, record) -> do
            dependencies <- Map.put dependencies id []
            dependencies <- List.fold dependencies record.fields (\dependencies, field -> do
                Map.add dependencies id (T.getIdentity field.type))
            dependencies <- case record.external_info of
                Some external_record_info -> do
                    external_record_info :: ExternalRecordInfo <- external_record_info
                    List.fold dependencies external_record_info.type_args (\dependencies, type -> do
                        Map.add dependencies id (T.getIdentity type))
                None -> dependencies
            dependencies
        )
    dependencies

data Context = { deps :: [MP.Identity] }

processExpr :: Context -> Expr -> (Context, Expr)
processExpr context expr = do
    Expr s_expr _ _ <- expr
    case s_expr of
        StaticFunctionCall id _ -> do
            deps <- context.deps + [id]
            context <- context { deps = deps }
            (context, expr)
        _ -> (context, expr)

getDepsForFunction :: MP.Program -> F.Function -> [MP.Identity]
getDepsForFunction mir_program function = case function.kind of
    F.Normal info -> do
        context <- Context []
        (context, _) <- traverse context info.body (Some processExpr) None None
        context.deps
    _ -> []

collectFunctionDeps :: MP.Program -> Map MP.Identity [MP.Identity]
collectFunctionDeps mir_program = do
    dependencies <- empty
    dependencies <- mir_program.functions |> Map.iter |> Iterator.fold (\dependencies, (id, function) -> do
            deps <- getDepsForFunction mir_program function
            (dependencies, _) <- insert dependencies id deps
            dependencies
        ) dependencies
    dependencies

dumpProgram :: Config -> MP.Program -> OutputFileType -> ()
dumpProgram config mir_program type =
    if config.dump
    then do
        s <- MP.dump mir_program
        writeTextFile (getOutputFileName config type) s
    else ()

createGroups :: Config -> MP.Program -> ([DependencyGroup MP.Identity], [DependencyGroup MP.Identity])
createGroups config mir_program = do
    trace config "collectDataDeps.."
    data_dependencies <- collectDataDeps mir_program
    trace config "processing data deps.."
    data_groups <- processDependencies config data_dependencies
    trace config "collectFunctionDeps.."
    function_dependencies <- collectFunctionDeps mir_program
    trace config "processing function deps.."
    function_groups <- processDependencies config function_dependencies
    (data_groups, function_groups)

processDataGroups :: MP.Program -> [DependencyGroup MP.Identity] -> MP.Program
processDataGroups mir_program data_groups =
    List.fold mir_program data_groups processDataGroup
    where
        processDataGroup :: MP.Program -> DependencyGroup MP.Identity -> MP.Program
        processDataGroup mir_program data_group = do
            List.fold mir_program data_group.items (\mir_program, id -> do
                case get mir_program.records id of
                    Some record -> do
                        record :: Record <- record // FIXME
                        fields <- List.map record.fields (\field -> do
                            id <- T.getIdentity field.type
                            if List.contains data_group.items id
                            then field { grouped = True }
                            else field)
                        MP.updateRecordFields mir_program id fields
                    None -> mir_program)

processProgram :: Config -> MP.Program -> LP.Program
processProgram config mir_program = do
    trace config "TransformUpdates.."
    mir_program <- TransformUpdates.processProgram mir_program
    dumpProgram config mir_program (MIR "transformupdates")
    mir_program <- FnArgVarCreator.processProgram mir_program
    trace config "Rebinder.."
    mir_program <- Rebinder.processProgram mir_program
    dumpProgram config mir_program (MIR "rebinder")
    trace config "SanityCheck1.."
    SanityCheck.processProgram mir_program
    (data_groups, function_groups) <- createGroups config mir_program
    mir_program <- processDataGroups mir_program data_groups
    trace config "Inliner.."
    mir_program <- Inliner.processProgram mir_program function_groups
    dumpProgram config mir_program (MIR "inliner")
    //trace config "Simplifier.."
    //mir_program <- Simplifier.processProgram config mir_program
    dumpProgram config mir_program (MIR "simplifier")
    mir_program <- Rebinder.processProgram mir_program
    dumpProgram config mir_program (MIR "rebinder2")
    trace config "SanityCheck2.."
    SanityCheck.processProgram mir_program
    (data_groups, function_groups) <- createGroups config mir_program
    trace config "ConverterVarCreator.."
    mir_program <- ConverterVarCreator.processProgram mir_program
    dumpProgram config mir_program (MIR "convertervarcreator")
    mir_program <- Rebinder.processProgram mir_program
    dumpProgram config mir_program (MIR "rebinder3")
    trace config "AddConverter.."
    mir_program <- AddConverter.processProgram config mir_program
    dumpProgram config mir_program (MIR "addconverter")
    trace config "Inference start.."
    lir_program <- Inference.processProgram config mir_program data_groups function_groups
    trace config "Inference end.."
    return lir_program