module Siko.Resolver.Pattern where

import Siko.Syntax.Pattern as SP
import Siko.HIR.Pattern as HP
import Siko.HIR.Program as HPO
import Siko.HIR.Data as HD
import Siko.Syntax.Location
import Siko.Resolver.Expr
import Siko.Resolver.Environment
import Siko.Resolver.Error
import Siko.Resolver.Item as RI
import Siko.Resolver.Module
import Siko.Resolver.ModuleResolver
import Siko.Resolver.ResolvedItem
import Siko.Resolver.Type
import Siko.Syntax.Ident
import Siko.Resolver

resolveConstructor :: Context -> Ident -> Bool -> Result (Context, HPO.FullyQualifiedName) Context
resolveConstructor context name mustBeRecord = do
    case resolveItem context.module_resolver.term_names NotAVariant name of
        Ok (ResolvedItem qn item _) -> do
            case item of
                RI.Record _ _ -> Ok (context, qn)
                RI.Variant _ _ if not mustBeRecord -> Ok (context, qn)
                _ -> do
                    err <- if mustBeRecord then NotARecord name else NotAVariant name
                    Err (addErrorToContext context err)
        Err err -> Err (addErrorToContext context err)

processRecordFieldPattern :: [SP.RecordFieldPattern] -> (Context, PatternEnvironment, Environment, [HP.Pattern ()]) -> HD.RecordField -> (Context, PatternEnvironment, Environment, [HP.Pattern ()])
processRecordFieldPattern field_patterns (context, pattern_env, env, args) (HD.RecordField field_name _) = do
    field_pattern <- field_patterns |> List.iter |> Iterator.filter (\(SP.RecordFieldPattern name _) -> getString name == field_name) |> toList
    (SP.RecordFieldPattern name pattern) <- atIndex field_pattern 0
    (context, pattern_env, env, hir_pattern) <- processPattern context  pattern_env env pattern
    args <- args + [hir_pattern]
    (context, pattern_env, env, args)

processPatterns :: Context -> PatternEnvironment -> Environment -> [SP.Pattern] -> (Context, PatternEnvironment, Environment, [HP.Pattern ()])
processPatterns context pattern_env env patterns = do
    (context, pattern_env, env, hir_patterns) <- patterns |> List.iter |> Iterator.fold (\(context, pattern_env, env, hir_patterns), pattern -> do
                (context, pattern_env, env, hir_pattern) <- processPattern context pattern_env env pattern
                hir_patterns <- hir_patterns + [hir_pattern]
                (context, pattern_env, env, hir_patterns)) (context, pattern_env, env, [])
    (context, pattern_env, env, hir_patterns)

processPattern :: Context -> PatternEnvironment -> Environment -> SP.Pattern -> (Context, PatternEnvironment, Environment, HP.Pattern ())
processPattern context pattern_env env (SP.Pattern pattern location) = do
    (state, pattern_id) <- getNextPatternId context.state
    context <- context { state = state }
    (context, pattern_env, env, hir_pattern) <- case pattern of
        SP.Binding name -> do
            bind_ref <- HP.BindRef (getString name) pattern_id
            pattern_env <- addBindingToPatternEnv pattern_env name
            env <- addBinding env bind_ref
            (context, pattern_env, env, HP.Binding bind_ref)
        SP.Tuple items -> do
            (context, pattern_env, env, hir_items) <- items |> List.iter |> Iterator.fold (\(context, pattern_env, env, items), item -> do
                (context, pattern_env, env, hir_item) <- processPattern context pattern_env env item
                items <- items + [hir_item]
                (context, pattern_env, env, items)) (context, pattern_env, env, [])
            (context, pattern_env, env, HP.Tuple hir_items)
        SP.Constructor name args -> do
            (context, pattern_env, env, hir_args) <- processPatterns context pattern_env env args
            case resolveConstructor context name False of
                Ok (context, qn) -> do
                    context :: Context <- context // FIXME: type inference
                    case HPO.getItem context.program qn of
                        HPO.Variant (HD.VariantInfo adt_name index _) -> do
                            (HD.Variant _ _ items) <- HPO.getVariant context.program adt_name index
                            adt <- HPO.getAdt context.program adt_name
                            context <- if getLength adt.variants > 1 && pattern_env.irrefutable
                                then addErrorToContext context (NotIrrefutablePattern location)
                                else context
                            expected <- getLength items
                            found <- getLength args
                            if expected != found
                                then
                                    do
                                        context <- addErrorToContext context (InvalidVariantArgCountInPattern name expected found)
                                        (context, pattern_env, env, HP.Tuple [])
                                else
                                    (context, pattern_env, env, HP.Variant adt_name index hir_args)
                        HPO.Record record -> do
                            expected <- getLength record.fields
                            found <- getLength args
                            if expected != found
                                then
                                    do
                                        context <- addErrorToContext context (InvalidRecordArgCountInPattern name expected found)
                                        (context, pattern_env, env, HP.Tuple [])
                                else
                                    (context, pattern_env, env, HP.Record qn hir_args)
                        item -> panic "constructor name is not a variant or a record: {} {} {} " % (qn, location, item)
                Err context -> do
                    (context, pattern_env, env, HP.Tuple [])
        SP.Guarded p e -> do
            (context, pattern_env, env, hir_p) <- processPattern context pattern_env env p
            (context, env, hir_e) <- processExpr context env e
            (context, pattern_env, env, HP.Guarded hir_p hir_e)
        SP.Wildcard -> (context, pattern_env, env, HP.Wildcard)
        SP.IntegerLiteral lit -> do
            context <- if pattern_env.irrefutable
                then addErrorToContext context (NotIrrefutablePattern location)
                else context
            (context, pattern_env, env, HP.IntegerLiteral lit)
        SP.StringLiteral lit -> do
            context <- if pattern_env.irrefutable
                then addErrorToContext context (NotIrrefutablePattern location)
                else context
            (context, pattern_env, env, HP.StringLiteral lit)
        SP.CharLiteral lit -> do
            context <- if pattern_env.irrefutable
                then addErrorToContext context (NotIrrefutablePattern location)
                else context
            (context, pattern_env, env, HP.CharLiteral lit)
        SP.CharRange c1 c2 kind -> do
            context <- if pattern_env.irrefutable
                then addErrorToContext context (NotIrrefutablePattern location)
                else context
            kind <- case kind of
                SP.Exclusive -> HP.Exclusive
                SP.Inclusive -> HP.Inclusive
            (context, pattern_env, env, HP.CharRange c1 c2 kind)
        SP.Typed p t -> do
            (context, pattern_env, env, hir_p) <- processPattern context pattern_env env p
            (type_resolver, state, hir_type) <- processTypeSignature context.type_resolver context.state t
            context <- context { type_resolver = type_resolver, state = state }
            (context, pattern_env, env, HP.Typed hir_p hir_type)
        SP.Record name field_patterns -> do
            case resolveConstructor context name True of
                Ok (context, qn) -> do
                    context :: Context <- context // FIXME: type inference
                    case HPO.getItem context.program qn of
                        HPO.Record record -> do
                            used_fields <- field_patterns |> List.iter |> Iterator.map (\(SP.RecordFieldPattern field _) -> field) |> toList
                            case validateUsedFields used_fields record of
                                Ok () -> do
                                    (context, pattern_env, env, args) <- record.fields |> List.iter |> Iterator.fold (processRecordFieldPattern field_patterns) (context, pattern_env, env, [])
                                    (context, pattern_env, env, HP.Record qn args)
                                Err (unused_fields, not_real_fields, multi_used) -> do
                                    context <- if not (isEmpty unused_fields)
                                        then addErrorToContext context (UnusedFields unused_fields)
                                        else context
                                    context <- if not (isEmpty not_real_fields)
                                        then addErrorToContext context (UnknownUsedFields not_real_fields)
                                        else context
                                    context <- if not (isEmpty multi_used)
                                        then addErrorToContext context (MultiUsedFields multi_used)
                                        else context
                                    (context, pattern_env, env, HP.Tuple [])
                        _ -> panic "resolved record is not a record"
                Err context -> do
                    (context, pattern_env, env, HP.Tuple [])
        SP.Or _ -> panic "Or pattern in processPattern"
    (context, pattern_env, env, HP.Pattern hir_pattern pattern_id () location)