module Siko.AutoDerive.PartialOrd where

import Siko.AutoDerive.Util
import Siko.Syntax.Location
import Siko.Syntax.Ident
import Siko.Syntax.Data as D
import Siko.Syntax.Class as C
import Siko.Syntax.Expr as E
import Siko.Syntax.Pattern as P

deriveRecordPartialOrd :: D.Record -> Location -> C.Instance
deriveRecordPartialOrd record location = do
    class_name <- Ident "Std.Ops.PartialOrd" location
    fn_name <- Ident "partialCmp" location
    some_ident <- Ident "Option.Some" location
    equal_ident <- Ident "Ordering.Equal" location
    failure_value_ident <- Ident "failure_value" location
    equal_pattern <- P.Pattern (P.Constructor equal_ident []) location
    success_pattern <- P.Pattern (P.Constructor some_ident [equal_pattern]) location
    equal_ctor <- E.Expr (E.FunctionCall (E.Expr (E.Path equal_ident) location) []) location
    success_expr <- E.Expr (E.FunctionCall (E.Expr (E.Path some_ident) location) [equal_ctor]) location
    failure_expr <- E.Expr (E.Path failure_value_ident) location
    comparator <- RecordComparator class_name fn_name success_pattern success_expr failure_expr location
    deriveRecordGeneralCompare record comparator
