module Main where

effect Logger where
    log a :: (Show a) => a -> ()

data Foo = Foo deriving (Show)

someFunc :: () using (Logger)
someFunc = do
    log "string"
    log Foo

someFunc2 :: ()
someFunc2 = do
    log "string"
    log Foo

someFunc3 = do
    log "string"
    log Foo

myLogger a :: (Show a) => a -> ()
myLogger a = ()

main = do
    with { log = myLogger } do
        someFunc
        someFunc2
        someFunc3