module Main {

import App
import Std.Effects.Network
import Std.Effects.Spawn
import Std.Effects.Time
import Std.IO.Async.Scheduler as Async
import Std.Time as T

fn stopper() {
    Async.sleep(2.seconds());
    Async.stop();
}

fn main() {
    let port = 19875.as_u16();
    let s = Async.Scheduler.new();
    with Async.current = s,
         TcpNetwork = AsyncTcp,
         Spawn = AsyncSpawn,
         Time = AsyncTime {
        spawn(|| server(port));
        spawn(|| client(port));
        spawn(|| stopper());
        s.run_tasks();
    }
}

}
