module Siko.Syntax.Pattern where

import Siko.Syntax.Location
import Siko.Syntax.Ident
import Siko.Syntax.Expr as E

data RangeKind = Exclusive
               | Inclusive 

data RecordFieldPattern = {
                            name :: Ident,
                            pattern :: Pattern,
                          }

data Pattern = Pattern SimplePattern Location

data SimplePattern = Binding Ident
                   | Tuple [Pattern]
                   | Constructor Ident [Pattern]
                   | Guarded Pattern E.Expr
                   | Wildcard
                   | IntegerLiteral String
                   | StringLiteral String
                   | CharLiteral Char
                   | CharRange Char Char RangeKind
                   | Record Ident [RecordFieldPattern]
                   | Or [Pattern]
