module Main {

effect MyEff {
    type Foo

    fn create() -> Foo

    fn do(f: Foo)
}

struct Boo {

}

enum Q {
    Q1(a: Foo),
    Q2(Int)
}

instance I MyEff {
    type Foo = Boo

    fn create() -> Boo {
        Boo()
    }

    fn do(f: Boo) {

    }
}

fn main() {
    with MyEff = I {
        let a = create();
        let q = Q1(a);
        match q {
            Q1(a) => do(a),
            _ => (),
        }
    }
}

}