module Siko.MIR.Backend.Ownership.Lowering.Data where

import Siko.Config
import Siko.Trace
import Siko.MIR.Backend.Ownership.MemberInfo
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.Lowering.Context
import Siko.MIR.Backend.Ownership.Lowering.Naming
import Siko.MIR.Backend.Ownership.Lowering.Expr
import Siko.MIR.Backend.Ownership.FunctionInfoStore
import Siko.MIR.Backend.Ownership.Lowering.Type
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Program as MP
import Siko.LIR.Program as LP
import Siko.MIR.Data as MD
import Siko.MIR.Type as MT
import Siko.LIR.Data as LD
import Siko.LIR.Type as LT

import Map
import List2

lowerExternalRecordInfo :: TypeLoweringInfo -> Context -> MD.ExternalRecordInfo -> (Context, LD.ExternalRecordInfo)
lowerExternalRecordInfo lowering_info context mir_external_record_info = do
    (context, lir_type_args) <- List.mapSE context mir_external_record_info.type_args (\context, index, type_arg -> do
        lowering_info <- getLoweringInfoForExtern context.config lowering_info index
        lowerType context lowering_info type_arg)
    (context, LD.ExternalRecordInfo lir_type_args)

lowerField :: TypeLoweringInfo -> Context -> MD.RecordField -> (Context, LD.RecordField)
lowerField lowering_info context mir_field = do
    lowering_info <- getLoweringInfoForMember context.config lowering_info mir_field.name
    (context, lir_type) <- lowerType context lowering_info mir_field.type
    lir_type <- if mir_field.grouped
    then LT.Box lir_type
    else lir_type
    (context, LD.RecordField mir_field.name lir_type)

lowerVariant :: TypeLoweringInfo -> Context -> Int -> MD.Variant -> (Context, LD.Variant)
lowerVariant lowering_info context index mir_variant = do
    lowering_info <- getLoweringInfoForVariant context.config lowering_info index
    (context, lir_type) <- lowerType context lowering_info mir_variant.type
    (context, LD.Variant mir_variant.name lir_type)

processExternalClassImpl :: MP.Identity -> TypeLoweringInfo -> Context -> MD.ExternalClassImpl -> (Context, LD.ExternalClassImpl)
processExternalClassImpl mir_id lowering_info context mir_class_impl =
    case mir_class_impl of
        MD.Show id -> do
            (context, lir_id) <- processClassImplCall context mir_id lowering_info id
            (context, LD.Show lir_id)
        MD.PartialEq id -> do
            (context, lir_id) <- processClassImplCall context mir_id lowering_info id
            (context, LD.PartialEq lir_id)
        MD.Eq -> do
            (context, LD.Eq)
        MD.PartialOrd id -> do
            (context, lir_id) <- processClassImplCall context mir_id lowering_info id
            (context, LD.PartialOrd lir_id)
        MD.Ord id -> do
            (context, lir_id) <- processClassImplCall context mir_id lowering_info id
            (context, LD.Ord lir_id)
    where
        processClassImplCall :: Context -> MP.Identity -> TypeLoweringInfo -> MP.Identity -> (Context, LP.Identity)
        processClassImplCall context mir_id lowering_info id = do
            (allocator, result) <- getNextTypeVariableInfo lowering_info.allocator
            (allocator, arg) <- getNextTypeVariableInfo lowering_info.allocator
            (allocator, borrow_id) <- getNextBorrowId allocator
            arg <- arg { arg_group_var = lowering_info.root.arg_group_var }
            args <- List2.single arg
            args <- List2.push args arg
            ownershipinfos <- List2.push lowering_info.ownershipinfos (Borrower arg.ownership_var borrow_id)
            ownershipinfos <- List2.push ownershipinfos (Owner result.ownership_var)
            lowering_info <- FunctionLoweringInfo lowering_info.members args result ownershipinfos allocator
            lir_key <- FunctionKey id lowering_info
            (context, lir_id) <- getLIRId context lir_key
            context <- addItem context lir_key
            (context, lir_id)

lowerRecord :: Context -> TypeLoweringInfo -> MP.Identity -> LP.Identity -> Context
lowerRecord context lowering_info mir_id lir_id = do
    trace context.config "Lowering record {} {} {}" % (mir_id, lir_id, lowering_info)
    (mir_program, mir_record) <- MP.getRecord context.mir_program mir_id
    context <- context { mir_program = mir_program }
    (context, fields) <- List.mapS context mir_record.fields (lowerField lowering_info)
    lifetimes <- collectLifetimes lowering_info.ownershipinfos
    (context, external_info) <- case mir_record.external_info of
        Some external_info -> do
            (context, external_info) <- lowerExternalRecordInfo lowering_info context external_info
            (context, Some external_info)
        None -> (context, None)
    (context, external_class_impls) <- List.mapS context mir_record.external_class_impls (processExternalClassImpl mir_id lowering_info)
    lir_record <- LD.Record lir_id lifetimes fields external_info external_class_impls
    context <- addRecord context lir_record
    context

lowerAdt :: Context -> TypeLoweringInfo -> MP.Identity -> LP.Identity -> Context
lowerAdt context lowering_info mir_id lir_id = do
    trace context.config "Lowering adt {} {} {}" % (mir_id, lir_id, lowering_info)
    (mir_program, mir_adt) <- MP.getAdt context.mir_program mir_id
    context <- context { mir_program = mir_program }
    (context, variants) <- List.mapSE context mir_adt.variants (lowerVariant lowering_info)
    lifetimes <- collectLifetimes lowering_info.ownershipinfos
    external_class_impls <- []
    lir_adt <- LD.AlgebraicDataType lir_id lifetimes variants external_class_impls
    context <- addAdt context lir_adt
    context
