module Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.Filter where

import Siko.Config
import Siko.Util.DependencyProcessor
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo

import Map
import Set
import List2 as List2
import List2 (List2)

getDependencyMap :: LoweringInfo -> Map TypeVariableInfo [TypeVariableInfo]
getDependencyMap lowering_info =
    case lowering_info of
        Function function -> do
            sources <- List2.push function.args function.result
            M.getDependencyMap sources function.members
        Type type -> do
            sources <- List2.single type.root
            M.getDependencyMap sources type.members

isBorrower :: LoweringInfo -> TypeVariableInfo -> Bool
isBorrower lowering_info info =
    case lowering_info of
        Function function -> List2.fold False function.ownershipinfos (\is_borrower, ownershipinfo ->
            case ownershipinfo of
                M.Borrower v _ -> if v == info.ownership_var
                    then True
                    else is_borrower
                _ -> is_borrower
            )
        Type type -> List2.fold False type.ownershipinfos (\is_borrower, ownershipinfo ->
            case ownershipinfo of
                M.Borrower v _ -> if v == info.ownership_var
                    then True
                    else is_borrower
                _ -> is_borrower
            )

isDepBorrower :: [TypeVariableInfo] -> Map TypeVariableInfo Bool -> Map TypeVariableInfo [TypeVariableInfo] -> TypeVariableInfo -> LoweringInfo -> Bool
isDepBorrower group borrower_map deps_map item lowering_info = do
    case get deps_map item of
        Some deps -> do
            List.fold False deps (\is_borrower, dep ->
                if List.contains group dep
                then is_borrower
                else do
                    case get borrower_map dep of
                        Some b -> is_borrower || b
                        None -> panic "dep {} not found in borrower_map" % dep)
        None -> panic "{} not found in deps_map" % item

isBorrowerGroup :: Map TypeVariableInfo Bool -> Map TypeVariableInfo [TypeVariableInfo] -> [TypeVariableInfo] -> LoweringInfo -> Bool
isBorrowerGroup borrower_map deps_map group lowering_info = do
    List.fold False group (\is_borrower, item -> do
        if isBorrower lowering_info item || isDepBorrower group borrower_map deps_map item lowering_info
        then True
        else is_borrower)

filterInfo :: Config -> LoweringInfo -> List2 TypeVariableInfo -> LoweringInfo
filterInfo config lowering_info sources = do
        //println "------------ start filterInfo {} / {}-----------" % (lowering_info, sources)
        source_group_vars <- List2.fold Set.empty sources (\vars, source -> Set.put vars source.arg_group_var)
        all_group_vars <- case lowering_info of
            Function function -> Set.collect function.members source_group_vars M.collectMember
            Type type -> Set.collect type.members source_group_vars M.collectMember
        lowering_info <- case lowering_info of
            Function function -> do
                members <- List2.filter function.members (M.isSubMember all_group_vars)
                Function (function { members = members })
            Type type -> do
                members <- List2.filter type.members (M.isSubMember all_group_vars)
                Type (type { members = members })
        deps_map <- getDependencyMap lowering_info
        groups <- processDependencies config deps_map
        //println "Groups {}, {}" % (groups, deps_map)
        borrower_map <- List.fold Map.empty groups (\borrower_map, group -> do
            is_borrower <- isBorrowerGroup borrower_map deps_map group.items lowering_info
            List.fold borrower_map group.items (\borrower_map, item -> Map.put borrower_map item is_borrower))
        borrowers <- Map.getKeys (Map.filter borrower_map (\(k, v) -> v))
        borrowers <- List2.toList2 borrowers
        relevants <- borrowers + sources
        //println "relevants {}" % relevants
        group_vars <- List2.map relevants (\info -> info.arg_group_var)
        ownership_vars <- List2.map relevants (\info -> info.ownership_var)
        lowering_info <- case lowering_info of
            Function function -> do
                members <- List2.filter function.members (filterMember relevants group_vars)
                ownershipinfos <- List2.filter function.ownershipinfos (M.filterOwnershipInfo ownership_vars)
                Function (function { members = members, ownershipinfos = ownershipinfos})
            Type type -> do
                members <- List2.filter type.members (filterMember relevants group_vars)
                ownershipinfos <- List2.filter type.ownershipinfos (M.filterOwnershipInfo ownership_vars)
                Type (type { members = members, ownershipinfos = ownershipinfos })
        //println "------------ end filterInfo {} / {}-----------" % (lowering_info, sources)
        lowering_info
    where
        filterMember :: List2 TypeVariableInfo -> List2 TypeVariable -> M.MemberInfo -> Bool
        filterMember infos vars member =
            case member of
                M.Variant index root info -> List2.contains infos info && List2.contains vars root
                M.Member name root info -> List2.contains infos info && List2.contains vars root
                M.Extern index root info -> List2.contains infos info && List2.contains vars root
