module Siko.MIR.Backend.Ownership.Lowering.LoweringInfo where

import Siko.Config
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.BorrowId
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.Duplicator
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.Filter

import Map
import Set

import List2 as List2
import List2 (List2)

data FunctionLoweringInfo = { members :: List2 M.MemberInfo,
                              args :: List2 TypeVariableInfo,
                              result :: TypeVariableInfo,
                              ownershipinfos :: List2 M.OwnershipInfo,
                              allocator :: Allocator,
                            } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data TypeLoweringInfo = { members :: List2 M.MemberInfo,
                          root :: TypeVariableInfo,
                          ownershipinfos :: List2 M.OwnershipInfo,
                          allocator :: Allocator,
                        } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

convertToFunctionLoweringInfo :: Config -> InferenceInfo -> [TypeVariableInfo] -> TypeVariableInfo -> (InferenceInfo, FunctionLoweringInfo)
convertToFunctionLoweringInfo config inference_info args result = do
    //println "Creating function lowering info"
    args <- List2.toList2 args
    lowering_info <- FunctionLoweringInfo inference_info.members args result
            (toOwnershipInfo inference_info.ownership_values) inference_info.allocator
    //println "Unfiltered {}" % lowering_info
    sources <- List2.push args result
    lowering_info <- filterFunctionLoweringInfo config lowering_info sources
    (inference_info, lowering_info)

createTypeLoweringInfoFromInferenceInfo :: Config -> InferenceInfo -> TypeVariableInfo -> (InferenceInfo, TypeLoweringInfo)
createTypeLoweringInfoFromInferenceInfo config inference_info root = do
    //println "Creating type lowering info"
    lowering_info <- TypeLoweringInfo inference_info.members root
            (toOwnershipInfo inference_info.ownership_values) inference_info.allocator
    lowering_info <- filterTypeLoweringInfo config lowering_info (List2.single root)
    (inference_info, lowering_info)

createTypeLoweringInfoFromFunctionLoweringInfo :: Config -> FunctionLoweringInfo -> TypeVariableInfo -> TypeLoweringInfo
createTypeLoweringInfoFromFunctionLoweringInfo config lowering_info root = do
    //println "Creating type lowering info"
    output <- TypeLoweringInfo lowering_info.members root lowering_info.ownershipinfos lowering_info.allocator
    filterTypeLoweringInfo config output (List2.single root)

createTypeLoweringInfoFromTypeLoweringInfo :: Config -> TypeLoweringInfo -> TypeVariableInfo -> TypeLoweringInfo
createTypeLoweringInfoFromTypeLoweringInfo config lowering_info root = do
    //println "Creating type lowering info"
    output <- TypeLoweringInfo lowering_info.members root lowering_info.ownershipinfos lowering_info.allocator
    filterTypeLoweringInfo config output (List2.single root)

normalizeRef :: TypeLoweringInfo -> (TypeLoweringInfo, Option BorrowId)
normalizeRef lowering_info = do
    ownershipinfos <- lowering_info.ownershipinfos
    (ownershipinfos, ref, found) <- List2.fold ((List2.withCapacity (List2.getLength ownershipinfos)), None, False)
                                                ownershipinfos
        (\(ownershipinfos, ref, found), ownershipinfo ->
            case ownershipinfo of
                M.Unknown v -> if v == lowering_info.root.ownership_var
                    then (List2.push ownershipinfos (M.Owner v), None, True)
                    else (List2.push ownershipinfos (M.Owner v), ref, found)
                M.Borrower v id -> if v == lowering_info.root.ownership_var
                    then (List2.push ownershipinfos (M.Owner v), Some id, True)
                    else (List2.push ownershipinfos ownershipinfo, ref, found)
                M.Owner v -> if v == lowering_info.root.ownership_var
                    then (List2.push ownershipinfos ownershipinfo, None, True)
                    else (List2.push ownershipinfos ownershipinfo, ref, found))
    ownershipinfos <- if not found
    then List2.push ownershipinfos (M.Owner lowering_info.root.ownership_var)
    else ownershipinfos
    allocator <- lowering_info.allocator
    allocator <- allocator { borrow = 0 }
    (ownershipinfos, allocator) <- List2.foldLinear allocator ownershipinfos (\allocator, o -> case o of
        M.Borrower v id -> addBorrowId allocator id
        M.Owner _ -> allocator
        M.Unknown _ -> allocator)
    lowering_info <- lowering_info { ownershipinfos = ownershipinfos, allocator = allocator }
    (lowering_info, ref)

normalizeFunctionLoweringInfo :: FunctionLoweringInfo -> (FunctionLoweringInfo, Duplicator)
normalizeFunctionLoweringInfo lowering_info = do
    // FIXME: we need a better normalization algorithm
    // that is more robust and does not care about ordering
    duplicator <- createNormalizer
    (duplicator, args) <- List2.mapS duplicator lowering_info.args duplicate
    (duplicator, result) <- duplicate duplicator lowering_info.result
    (duplicator, members) <- List2.mapS duplicator lowering_info.members duplicate
    (duplicator, ownershipinfos) <- List2.mapS duplicator lowering_info.ownershipinfos duplicate
    members <- members |> List2.sort
    ownershipinfos <- ownershipinfos |> List2.sort
    (FunctionLoweringInfo members args result ownershipinfos duplicator.allocator, duplicator)

normalizeTypeLoweringInfo :: TypeLoweringInfo -> (TypeLoweringInfo, Duplicator)
normalizeTypeLoweringInfo lowering_info = do
    // FIXME: we need a better normalization algorithm
    // that is more robust and does not care about ordering
    duplicator <- createNormalizer
    (duplicator, root) <- duplicate duplicator lowering_info.root
    (duplicator, members) <- List2.mapS duplicator lowering_info.members duplicate
    (duplicator, ownershipinfos) <- List2.mapS duplicator lowering_info.ownershipinfos duplicate
    members <- members |> List2.sort
    ownershipinfos <- ownershipinfos |> List2.sort
    (TypeLoweringInfo members root ownershipinfos duplicator.allocator, duplicator)

getLoweringInfoForArg :: Config -> FunctionLoweringInfo -> Int -> TypeLoweringInfo
getLoweringInfoForArg config lowering_info index = do
    arg <- List2.atIndex lowering_info.args index
    createTypeLoweringInfoFromFunctionLoweringInfo config lowering_info arg

getLoweringInfoForResult :: Config -> FunctionLoweringInfo -> TypeLoweringInfo
getLoweringInfoForResult config lowering_info = do
    createTypeLoweringInfoFromFunctionLoweringInfo config lowering_info lowering_info.result

createEmptyTypeLoweringInfo :: TypeLoweringInfo
createEmptyTypeLoweringInfo = do
    allocator <- createAllocator
    (allocator, root) <- getNextTypeVariableInfo allocator
    TypeLoweringInfo List2.empty root (List2.single (M.Owner root.ownership_var)) allocator

getLoweringInfoForMember :: Config -> TypeLoweringInfo -> String -> TypeLoweringInfo
getLoweringInfoForMember config lowering_info name = do
    member <- List2.filter lowering_info.members (\constraint -> case constraint of
            M.Member n root member_info -> n == name && lowering_info.root.arg_group_var == root
            _ -> False)
    case List2.head member of
        Some (M.Member name root member_info) -> createTypeLoweringInfoFromTypeLoweringInfo config lowering_info member_info
        Some _ -> panic "member is not a member"
        None -> createEmptyTypeLoweringInfo

getLoweringInfoForVariant :: Config -> TypeLoweringInfo -> Int -> TypeLoweringInfo
getLoweringInfoForVariant config lowering_info index = do
    variant <- List2.filter lowering_info.members (\constraint -> case constraint of
            M.Variant i root member_info -> i == index && lowering_info.root.arg_group_var == root
            _ -> False)
    case List2.head variant of
        Some (M.Variant index root member_info) -> createTypeLoweringInfoFromTypeLoweringInfo config lowering_info member_info
        Some _ -> panic "variant is not a variant"
        None -> createEmptyTypeLoweringInfo

getLoweringInfoForExtern :: Config -> TypeLoweringInfo -> Int -> TypeLoweringInfo
getLoweringInfoForExtern config lowering_info index = do
    variant <- List2.filter lowering_info.members (\constraint -> case constraint of
            M.Extern i root member_info -> i == index && lowering_info.root.arg_group_var == root
            _ -> False)
    case List2.head variant of
        Some (M.Extern index root member_info) -> createTypeLoweringInfoFromTypeLoweringInfo config lowering_info member_info
        Some _ -> panic "extern is not a extern"
        None -> createEmptyTypeLoweringInfo