module Main {

fn main() {
    let num = 55345;
    let str = "The value of num is ${num}";
    assert(str == "The value of num is 55345");
    let num1 = 55345;
    let num2 = 21474836;
    let str = "The value of num1 is ${num1} and the value of num2 is ${num2}";
    assert(str == "The value of num1 is 55345 and the value of num2 is 21474836");
    let sumStr = "The sum of ${num1} and ${num2} is ${num1 + num2}";
    assert(sumStr == "The sum of 55345 and 21474836 is 21530181");
}

}