module Siko.HIR.Backend.InstanceResolver where

import Siko.HIR.Class
import Siko.HIR.Type as T
import Siko.HIR.TypeFormatter as TF
import Siko.HIR.Program as P
import Siko.Syntax.Location
import Siko.HIR.Backend.Unification as U
import Siko.HIR.Backend.Util as BUtil
import Siko.HIR.Util as Util
import Siko.HIR.Backend.Unification.Substitution as S
import Map

data BaseType = Tuple Int
              | Named P.FullyQualifiedName
              | Function
              | Generic
              deriving (Show, PartialEq, Eq, PartialOrd, Ord)

getBaseType :: T.Type -> BaseType
getBaseType type = case type of
    T.Tuple args -> Tuple (getLength args)
    T.Named qn _ -> Named qn
    T.Function _ _ -> Function
    T.Var _ _ -> Generic
    T.FixedTypeArg _ _ _ -> Generic
    T.Ref t -> getBaseType t
    T.Owner t -> getBaseType t
    T.Never _ -> Generic

data InstanceInfo = { instance_type :: T.Type,
                      associated_types :: [T.Type],
                      id :: InstanceId,
                      location :: Location
                    } deriving (Show)

instantiateInstanceInfo a :: (U.TypeVarGenerator a, U.DataProvider a, U.ClassProvider a, U.Context a) => a -> InstanceInfo -> (a, InstanceInfo)
instantiateInstanceInfo context instance_info = do
    vars <- Util.collectVars [] instance_info.instance_type
    vars <- List.fold vars instance_info.associated_types Util.collectVars
    (mapper, context) <- BUtil.initMapper vars context
    type <- BUtil.remap mapper instance_info.instance_type
    associated_types <- List.map instance_info.associated_types (BUtil.remap mapper)
    (context, InstanceInfo type associated_types instance_info.id instance_info.location)

data CacheEntry = CacheEntry T.Type P.FullyQualifiedName deriving (PartialEq, Eq, PartialOrd, Ord)

data InstanceResolver = { instance_map :: Map P.FullyQualifiedName (Map BaseType InstanceInfo),
                          cache :: Map CacheEntry InstanceInfo, }

createInstanceResolver :: InstanceResolver
createInstanceResolver = InstanceResolver empty empty

addInstanceInfoToResolver :: InstanceResolver -> P.FullyQualifiedName -> BaseType -> InstanceInfo -> Result InstanceResolver Location
addInstanceInfoToResolver instance_resolver class_name base_type instance_info = do
    case get instance_resolver.instance_map class_name of
        Some instance_info_map -> case get instance_info_map base_type of
            Some instance_info -> do
                instance_info :: InstanceInfo <- instance_info // FIXME
                return Err instance_info.location
            _ -> ()
        _ -> ()
    (instance_map, _) <- alter (\instance_info_map -> case instance_info_map of
            Some instance_info_map -> do
                (instance_info_map, _) <- insert instance_info_map base_type instance_info
                Some instance_info_map
            None -> do
                (instance_info_map, _) <- insert empty base_type instance_info
                Some instance_info_map) class_name instance_resolver.instance_map
    Ok (instance_resolver { instance_map = instance_map })

addUserDefinedInstance :: InstanceResolver -> P.FullyQualifiedName -> InstanceInfo -> Result InstanceResolver Location
addUserDefinedInstance instance_resolver class_name instance_info = do
    //println "Added user defined instance for {} {}" % (class_name, T.toLongString instance_info.instance_type)
    base_type <- getBaseType instance_info.instance_type
    addInstanceInfoToResolver instance_resolver class_name base_type instance_info

unifyTypes a :: (U.DataProvider a, U.ClassProvider a, U.TypeVarGenerator a, U.Context a) => a -> S.Substitution -> T.Type -> T.Type -> (a, S.Substitution, Bool)
unifyTypes context sub type1 type2 =
    case U.unify context sub type1 type2 of
        Ok (contains, sub) -> (context, sub, True)
        Err _ -> do
            //println "instance check, unifyTypes failed: {} {}" % (T.toLongString type1, T.toLongString type2)
            (context, sub, False)

checkInstancesForBaseType a :: (U.DataProvider a, U.ClassProvider a, U.TypeVarGenerator a, U.Context a) => a ->
                             InstanceResolver ->
                             S.Substitution ->
                             T.Type ->
                             BaseType ->
                             Map BaseType InstanceInfo ->
                             P.FullyQualifiedName ->
                             Result (InstanceResolver, a, S.Substitution, InstanceInfo) ()
checkInstancesForBaseType context instance_resolver sub type base_type instance_info_map class_name = do
    //println "checkInstancesForBaseType {} {}" % (TF.toLongString type, base_type)
    case get instance_info_map base_type of
        Some instance_info -> do
                (context, instance_info) <- instantiateInstanceInfo context instance_info
                (context, sub, success) <- unifyTypes context sub type instance_info.instance_type
                instance_resolver <- if success && T.isConcreteType type
                    then do
                        entry <- CacheEntry type class_name
                        (cache, _) <- insert instance_resolver.cache entry instance_info
                        instance_resolver { cache = cache }
                    else instance_resolver
                Ok (instance_resolver, context, sub, instance_info)
        None -> do
            //println "checkInstancesForBaseType: not found"
            Err ()

hasInstance a :: (U.DataProvider a, U.ClassProvider a, U.TypeVarGenerator a, U.Context a) => a ->
                 InstanceResolver ->
                 S.Substitution ->
                 T.Type ->
                 P.FullyQualifiedName ->
                 Result (InstanceResolver, a, S.Substitution, InstanceInfo) ()
hasInstance context instance_resolver sub type class_name = do
    base_type <- getBaseType type
    case get instance_resolver.instance_map class_name of
        Some instance_info_map -> do
            case checkInstancesForBaseType context instance_resolver sub type base_type instance_info_map class_name of
                Ok (instance_resolver, context, sub, instance_info) -> Ok (instance_resolver, context, sub, instance_info)
                Err _ -> checkInstancesForBaseType context instance_resolver sub type Generic instance_info_map class_name
        None -> do
            //println "Class {} has no instances, at all" % (class_name)
            Err ()

checkInstance a :: (U.DataProvider a, U.ClassProvider a, U.TypeVarGenerator a, U.Context a) => a ->
                    S.Substitution ->
                    InstanceResolver ->
                    T.Type ->
                    P.FullyQualifiedName ->
                    Result (InstanceResolver, a, S.Substitution, InstanceInfo) ()
checkInstance context sub instance_resolver type class_name = do
    constraints <- sub.constraints
    sub <- sub { constraints = [] }
    //println "checkInstance: type: {}, class_name: {}" % (TF.toLongString type, class_name)
    case type of
        T.Var var _ -> panic "Check instance called on var"
        T.Never var -> panic "Check instance called on never"
        _ -> do
            case hasInstance context instance_resolver sub type class_name of
                Ok (instance_resolver, context, sub, instance_info) -> do
                    sub :: S.Substitution <- sub // FIXME
                    (instance_resolver, context, sub, success) <- List.fold (instance_resolver, context, sub, True)
                            sub.constraints (\(instance_resolver, context, sub, success), c -> do
                                    S.UnificationConstraint c_name c_type c_associated_types <- c
                                    if c_name == class_name && c_type == type
                                        then (instance_resolver, context, sub, success)
                                        else do
                                            case checkInstance context sub instance_resolver c_type c_name of
                                                Ok (instance_resolver, context, sub, _) -> (instance_resolver, context, sub, success)
                                                Err _ -> do
                                                    //println "Sub checkInstance failed: {} {}" % (T.toLongString c_type, c_name)
                                                    (instance_resolver, context, sub, False)
                                )
                    if success
                        then do
                            sub <- sub { constraints = sub.constraints + constraints }
                            Ok (instance_resolver, context, sub, instance_info)
                        else Err ()
                Err _ -> do
                    //println "checkInstance: hasInstance failed"
                    Err ()
