module Siko.MIR.Backend.Ownership.V3.BorrowChecker(checkBorrows) where

import Siko.MIR.Program as P
import Siko.MIR.Backend.Ownership.V3.InferenceInfo
import Siko.MIR.Backend.Ownership.V3.BorrowInfo
import Siko.MIR.Backend.Traversal
import Siko.MIR.Expr as E
import Siko.MIR.Function as F

import Set
import Map

data Path = Whole | Partial [String] deriving (Show)

data Usage = { expr_id :: E.ExprId, path :: Path }

data UsageStore = { usages :: Map E.Var [Usage] }

data Invalidation = { subject :: E.ExprId, object :: E.ExprId } deriving (Show)

data Context = { program :: P.Program,
                 borrows :: [E.ExprId],
                 forbidden_borrows :: Map E.Var [E.Var],
                 forbidden_borrows2 :: Map E.ExprId [E.ExprId],
                 invalidations :: [Invalidation] }

data ExecutionMode = Normal
                   | DoesNotReturn

invalidates :: Path -> Path -> Bool
invalidates current other = do
    case (current, other) of
        (Whole , _) -> True
        (Partial  _, Whole) -> True
        (Partial current_path, Partial other_path) -> do
            c_len <- getLength current_path
            o_len <- getLength other_path
            min_len <- min c_len o_len
            (c_start, _) <- List.split current_path min_len
            (o_start, _) <- List.split other_path min_len
            c_start == o_start

checkUsages :: [Usage] -> Usage ->  E.ExprId -> ([E.ExprId], [Invalidation])
checkUsages usages usage expr_id = do
    List.fold ([], []) usages (\(borrows, invalidations), prev_usage ->
        if invalidates usage.path prev_usage.path
        then do
            borrows <- push borrows prev_usage.expr_id
            invalidations <- push invalidations (Invalidation expr_id prev_usage.expr_id)
            (borrows, invalidations)
        else (borrows, invalidations))

addUsage :: Context -> UsageStore -> E.Var -> E.ExprId -> Path -> (Context, UsageStore)
addUsage context usage_store var expr_id path = do
    usage <- Usage expr_id path
    usages <- case Map.get usage_store.usages var of
        Some usages -> usages
        None -> []
    (borrows, invalidations) <- checkUsages usages usage expr_id
    borrows <- context.borrows + borrows
    invalidations <- context.invalidations + invalidations
    context <- context { borrows = borrows |> sort |> dedup, invalidations = invalidations }
    usages <- push usages usage
    (usages, _) <- Map.insert usage_store.usages var usages
    (context, usage_store { usages = usages })

collectBlockBorrows :: Context -> UsageStore -> [E.Expr] -> (Context, UsageStore, ExecutionMode)
collectBlockBorrows context usage_store items =
    List.fold (context, usage_store, Normal) items (\(context, usage_store,  mode), item -> do
                (context, usage_store, exec_mode) <- collectBorrows context usage_store item
                exec_mode <- case (exec_mode, mode) of
                    (Normal, Normal) -> Normal
                    _ -> DoesNotReturn
                (context, usage_store, exec_mode))

processBranches :: Context -> UsageStore -> [E.Expr] -> (Context, UsageStore, ExecutionMode)
processBranches context usage_store branches =
    List.fold (context, usage_store, DoesNotReturn) branches (\(context, usage_store, exec_mode), branch -> do
            saved <- usage_store
            (context, usage_store, exec_mode) <- collectBorrows context usage_store branch
            case exec_mode of
                Normal -> (context, usage_store, Normal)
                DoesNotReturn -> (context, saved, exec_mode))

collectBorrows :: Context -> UsageStore -> E.Expr -> (Context, UsageStore, ExecutionMode)
collectBorrows context usage_store expr = do
    E.Expr s_expr _ expr_id <- expr
    (context, usage_store, exec_mode) <- case s_expr of
        E.Do items -> collectBlockBorrows context usage_store items
        E.Multi _ -> panic "Multi in borrow checker"
        E.StaticFunctionCall f_id args -> collectBlockBorrows context usage_store args
        E.IntegerLiteral _ -> (context, usage_store, Normal)
        E.StringLiteral _ -> (context, usage_store, Normal)
        E.FloatLiteral _ -> (context, usage_store, Normal)
        E.CharLiteral _ -> (context, usage_store, Normal)
        E.VarDecl var rhs -> collectBorrows context usage_store rhs
        E.VarRef var -> do
            path <- Whole
            (context, usage_store) <- addUsage context usage_store var expr_id path
            (context, usage_store, Normal)
        E.FieldAccess name receiver -> do
            loop (context, usage_store, path, receiver) <- (context, usage_store, [name], receiver) do
                E.Expr s_receiver _ _ <- receiver
                case s_receiver of
                    E.FieldAccess name receiver ->
                        continue (context, usage_store, List.push path name, receiver)
                    E.VarRef var -> do
                        (context, usage_store) <- addUsage context usage_store var expr_id (Partial path)
                        break (context, usage_store, Normal)
                    _ -> break collectBorrows context usage_store receiver
        E.If cond true_branch false_branch -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store cond
            processBranches context usage_store [true_branch, false_branch]
        E.List args -> collectBlockBorrows context usage_store args
        E.Return arg -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store arg
            (context, usage_store, DoesNotReturn)
        E.Continue arg -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store arg
            (context, usage_store, DoesNotReturn)
        E.Break arg -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store arg
            (context, usage_store, DoesNotReturn)
        E.RecordUpdate var updates -> panic "RecordUpdate in MIR borrow checker"
        E.Loop var initializer body _ _ -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store initializer
            (context, usage_store, exec_mode) <- collectBorrows context usage_store body
            (context, usage_store, exec_mode) <- collectBorrows context usage_store body
            (context, usage_store, exec_mode)
        E.CaseOf body cases -> do
            (context, usage_store, exec_mode) <- collectBorrows context usage_store body
            branches <- List.map cases (\c -> c.body)
            processBranches context usage_store branches
        E.Clone arg -> panic "Clone in MIR borrow checker"
        E.Deref arg -> panic "Deref in MIR borrow checker"
        E.Ref arg -> panic "Ref in MIR borrow checker"
        E.Move arg -> panic "Move in MIR borrow checker"
        E.Box arg -> panic "Box in MIR borrow checker"
        E.Converter arg _ -> collectBorrows context usage_store arg
    (context, usage_store, exec_mode)

addForbiddenBorrow :: Context -> E.Var -> E.Var -> Context
addForbiddenBorrow context dying_var live_var = do
        (forbidden_borrows, _) <- alter (add dying_var) live_var context.forbidden_borrows
        context { forbidden_borrows = forbidden_borrows }
    where
        add :: E.Var -> Option [E.Var] -> Option [E.Var]
        add new old_vars = case old_vars of
            Some old_vars -> Some ((push old_vars new) |> sort |> dedup)
            None -> Some [new]

data LiveSet = { live_vars :: Set E.Var } deriving (Show)

addLiveVar :: LiveSet -> E.Var -> LiveSet
addLiveVar live_set var = do
    live_vars <- Set.put live_set.live_vars var
    live_set { live_vars = live_vars }

removeLiveVar :: LiveSet -> E.Var -> LiveSet
removeLiveVar live_set var = do
    live_vars <- Set.remove live_set.live_vars var
    live_set { live_vars = live_vars }

checkVar :: Context -> LiveSet -> E.Var -> E.ExprId -> (Context, LiveSet)
checkVar context live_set var expr_id = do
    if List.contains context.borrows expr_id
    then (context, live_set)
    else do
        live_set <- removeLiveVar live_set var
        context <- live_set.live_vars |> Set.iter |> Iterator.fold (\context, live_var -> addForbiddenBorrow context var live_var) context
        (context, live_set)

checkVarsInBlock :: Context -> LiveSet -> [E.Expr] -> (Context, LiveSet,)
checkVarsInBlock context live_set items =
    List.fold (context, live_set) items (\(context, live_set), item -> checkVars context live_set item)

checkVars :: Context -> LiveSet -> E.Expr -> (Context, LiveSet)
checkVars context live_set expr = do
    E.Expr s_expr _ expr_id <- expr
    (context, live_set) <- case s_expr of
        E.Do items -> checkVarsInBlock context live_set items
        E.Multi _ -> panic "Multi in borrow checker"
        E.StaticFunctionCall f_id args -> checkVarsInBlock context live_set args
        E.IntegerLiteral _ -> (context, live_set)
        E.StringLiteral _ -> (context, live_set)
        E.FloatLiteral _ -> (context, live_set)
        E.CharLiteral _ -> (context, live_set)
        E.VarDecl var rhs -> do
            (context, live_set) <- checkVars context live_set rhs
            live_set <- addLiveVar live_set var
            (context, live_set)
        E.VarRef var -> checkVar context live_set var expr_id
        E.FieldAccess name receiver -> checkVars context live_set receiver
        E.If cond true_branch false_branch -> do
            // FIXME, TODO: double check this!!
            (context, live_set) <- checkVars context live_set cond
            (context, live_set) <- checkVars context live_set true_branch
            (context, live_set) <- checkVars context live_set false_branch
            (context, live_set)
        E.List args -> checkVarsInBlock context live_set args
        E.Return arg -> checkVars context live_set arg
        E.Continue arg -> checkVars context live_set arg
        E.Break arg -> checkVars context live_set arg
        E.RecordUpdate var updates -> panic "RecordUpdate in MIR borrow checker"
        E.Loop var initializer body _ _ -> do
            (context, live_set) <- checkVars context live_set initializer
            live_set <- addLiveVar live_set var
            (context, live_set) <- checkVars context live_set body
            (context, live_set)
        E.CaseOf body cases -> do
            // FIXME, TODO: double check this!!
            (context, live_set) <- checkVars context live_set body
            (context, live_set) <- List.fold (context, live_set) cases (\(context, live_set), c ->
                checkVars context live_set c.body)
            (context, live_set)
        E.Clone arg -> panic "Clone in MIR borrow checker"
        E.Deref arg -> panic "Deref in MIR borrow checker"
        E.Ref arg -> panic "Ref in MIR borrow checker"
        E.Move arg -> panic "Move in MIR borrow checker"
        E.Box arg -> panic "Box in MIR borrow checker"
        E.Converter arg _ -> checkVars context live_set arg
    (context, live_set)

checkBorrows :: P.Program -> E.Expr -> BorrowInfo
checkBorrows program body = do
    context <- Context program [] Map.empty Map.empty []
    usage_store <- UsageStore Map.empty
    (context, usage_store, exec_mode) <- collectBorrows context usage_store body
    live_set <- LiveSet Set.empty
    (context, live_set) <- checkVars context live_set body
    invalidations <- List.filter context.invalidations (\invalidation -> not (List.contains context.borrows invalidation.subject))
    invalidations <- List.fold Map.empty invalidations (\invalidations, invalidation -> do
        (invalidations, _) <- alter (\old -> case old of
            Some invalidations -> Some (push invalidations invalidation.object)
            None -> Some [invalidation.object]) invalidation.subject invalidations
        invalidations)
    BorrowInfo context.borrows context.forbidden_borrows invalidations