module Siko.MIR.Backend.Ownership.V3.OwnershipInference(inferOwnership) where

import Siko.MIR.Program as P
import Siko.MIR.Backend.Ownership.V3.InferenceInfo
import Siko.MIR.Backend.Ownership.V3.BorrowInfo
import Siko.MIR.Backend.Ownership.V3.MemberInfo as M
import Siko.MIR.Backend.Ownership.V3.TypeVariableInfo
import Siko.MIR.Backend.Ownership.V3.FunctionInfoStore
import Siko.MIR.Backend.Traversal
import Siko.MIR.Expr as E
import Siko.MIR.Function as F

import Map

data Context = { inference_info :: InferenceInfo,
                 program :: P.Program,
                 borrow_info :: BorrowInfo,
                 function_info_store :: FunctionInfoStore,
                 group :: [P.Identity], }

addOwnershipValue :: Context -> TypeVariable -> OwnershipKind -> Context
addOwnershipValue context var kind = do
    inference_info <- addOwnership context.inference_info var kind
    context { inference_info = inference_info }

getOwnershipValue :: Context -> TypeVariable -> OwnershipKind
getOwnershipValue context var =
    case getOwnership context.inference_info var of
        Some o -> o
        None -> panic "Ownership value not found for {}" % var

initializeExpr :: Context -> E.Expr -> (Context, E.Expr)
initializeExpr context expr = do
    E.Expr s_expr _ expr_id <- expr
    info <- getTypeVariableInfoByExprId context.inference_info expr_id
    TypeVariable index <- info.ownership_var
    case Map.get context.inference_info.ownership_values info.ownership_var of
        Some _ -> (context, expr)
        None -> do
            context <- addOwnershipValue context info.ownership_var Unknown
            (context, expr)

processConverter :: Context -> Option E.Var -> TypeVariable -> TypeVariable -> Context
processConverter context borrowed_var from to = do
    from_kind <- getOwnershipValue context from
    to_kind <- getOwnershipValue context to
    case (from_kind, to_kind) of
        (Owner, Owner) -> context
        (Borrower a, Borrower b) -> context //panic "NYI converter rule borrower -> borrower" // FIXME
        (Owner, Unknown) -> case borrowed_var of
            Some var -> addOwnershipValue context to (Borrower var)
            None -> addOwnershipValue context to from_kind
        (Borrower a, Unknown) -> addOwnershipValue context to from_kind
        (Borrower a, Owner) -> context
        (Unknown, Unknown) -> addOwnershipValue context to from_kind
        (Unknown, Owner) -> context
        _ -> panic "NYI converter rule {} => {}" % (from_kind, to_kind)

processExpr :: Context -> E.Expr -> (Context, E.Expr)
processExpr context expr = do
    E.Expr s_expr _ expr_id <- expr
    info <- getTypeVariableInfoByExprId context.inference_info expr_id
    context <- case s_expr of
        E.Do _ -> context
        E.Multi _ -> context
        E.StaticFunctionCall f_id args -> do
                function <- P.getFunction context.program f_id
                case function.kind of
                    F.Normal _ | F.Extern _ -> do
                        case getFunctionInfo context.function_info_store f_id of
                            Some function_info -> do
                                case Map.get context.inference_info.function_converters expr_id of
                                    Some function_converters -> do
                                        List.fold context function_converters (\context, converter -> do
                                            processConverter context None converter.from converter.to)
                                    None -> panic "No function converters found for {} {}" % (f_id, expr_id)
                            None -> if List.contains context.group f_id
                                then context
                                else panic "No function info found for called fn {}" % f_id
                    F.VariantCtor _ -> addOwnershipValue context info.ownership_var Owner
                    F.RecordCtor -> addOwnershipValue context info.ownership_var Owner
        E.IntegerLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.StringLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.FloatLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.CharLiteral _ -> addOwnershipValue context info.ownership_var Owner
        E.VarDecl var rhs -> do
            //println "VarDecl {}" % var
            context <- addOwnershipValue context info.ownership_var Owner
            E.Expr _ _ rhs_id <- rhs
            rhs_info <- getTypeVariableInfoByExprId context.inference_info rhs_id
            rhs_kind <- getOwnershipValue context rhs_info.ownership_var
            var_info <- getTypeVariableInfoByVar context.inference_info var
            case rhs_kind of
                Owner -> addOwnershipValue context var_info.ownership_var Owner
                Borrower b ->
                    if isBorrowAllowed context.borrow_info b var
                    then addOwnershipValue context var_info.ownership_var (Borrower b)
                    else do
                        //println "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! {} {}" % (var, b)
                        context <- addOwnershipValue context rhs_info.ownership_var Owner
                        addOwnershipValue context var_info.ownership_var Owner
                _ -> context
        E.VarRef _ -> context
        E.FieldAccess name receiver -> do
            E.Expr _ _ receiver_id <- receiver
            receiver_info <- getTypeVariableInfoByExprId context.inference_info receiver_id
            receiver_kind <- getOwnershipValue context receiver_info.ownership_var
            expr_kind <- getOwnershipValue context info.ownership_var
            case (receiver_kind, expr_kind) of
                (Borrower _, Owner) -> addOwnershipValue context info.ownership_var receiver_kind
                (Borrower _, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                (Owner, Unknown) -> addOwnershipValue context info.ownership_var receiver_kind
                _ -> context
        E.If _ _ _ -> context
        E.List args -> addOwnershipValue context info.ownership_var Owner
        E.Return arg -> addOwnershipValue context info.ownership_var Owner
        E.Continue arg -> addOwnershipValue context info.ownership_var Owner
        E.Break arg -> addOwnershipValue context info.ownership_var Owner
        E.RecordUpdate var updates -> panic "RecordUpdate in InferOwnership"
        E.Loop _ _ _ _ _ -> context
        E.CaseOf body cases -> do
            E.Expr _ _ body_id <- body
            body_info <- getTypeVariableInfoByExprId context.inference_info body_id
            List.fold context cases (\context, c -> case c.checker of
                E.VariantChecker index var _ -> do
                    var_info <- getTypeVariableInfoByVar context.inference_info var
                    variant <- List.find context.inference_info.members (\member -> case member of
                        M.Variant i root member_info -> i == index && member_info == var_info
                        _ -> False)
                    case variant of
                        Some (M.Variant i root member_info) -> do
                            body_kind <- getOwnershipValue context body_info.ownership_var
                            member_kind <- case getOwnership context.inference_info member_info.ownership_var of
                                Some o -> o
                                None -> Unknown
                            case (body_kind, member_kind) of
                                (body_o, Unknown) -> addOwnershipValue context member_info.ownership_var body_o
                                _ -> context
                        _ -> panic "No variant found for variant checker's var {}" % var
                _ -> context)
        E.Clone arg -> panic "Clone in InferOwnership"
        E.Deref arg -> panic "Deref in InferOwnership"
        E.Ref arg -> panic "Ref in InferOwnership"
        E.Move arg -> panic "Move in InferOwnership"
        E.Box arg -> panic "Box in InferOwnership"
        E.Converter arg _  -> do
            E.Expr arg_s_expr _ arg_id <- arg
            arg_info <- getTypeVariableInfoByExprId context.inference_info arg_id
            borrowed_var <- case arg_s_expr of
                E.VarRef var -> if isBorrow context.borrow_info arg_id
                        then Some var
                        else None
                _ -> None
            processConverter context borrowed_var arg_info.ownership_var info.ownership_var
    //o1 <- getOwnershipValue context info.ownership_var
    //println "InferOwnership {} {} {}" % (E.short expr, info, o1)
    (context, expr)

dumpExpr :: Context -> E.Expr -> (Context, E.Expr)
dumpExpr context expr = do
    E.Expr s_expr _ expr_id <- expr
    info <- getTypeVariableInfoByExprId context.inference_info expr_id
    o1 <- getOwnershipValue context info.ownership_var
    println "dumpOwnership {} {} {}" % (E.short expr, info, o1)
    (context, expr)

inferOwnership :: [P.Identity] -> FunctionInfoStore -> InferenceInfo -> P.Program -> E.Expr -> BorrowInfo -> InferenceInfo
inferOwnership group function_info_store inference_info program body borrow_info = do
    context <- Context inference_info program borrow_info function_info_store group
    (context, body) <- traverse context body (Some initializeExpr) None
    (context, body) <- traverse context body (Some processExpr) None
    //(context, body) <- traverse context body (Some dumpExpr) None
    //println "end of infer {}" % context.inference_info
    context.inference_info