module Siko.HIR.Backend.Typechecker.InstanceResolver.Checks where

import Siko.HIR.Class
import Siko.HIR.Type as T
import Siko.HIR.TypeFormatter as TF
import Siko.HIR.Program as P
import Siko.HIR.Backend.InstanceResolver
import Siko.Syntax.Location
import Siko.HIR.Backend.Typechecker
import Siko.HIR.Backend.Typechecker.ClassStore
import Siko.HIR.Backend.Typechecker.Error
import Siko.HIR.Backend.Unification as U
import Siko.HIR.Backend.Unification.Substitution as S
import Siko.HIR.Backend.TypeIsomorphism as HTI
import Map

checkConflicts :: TypecheckerState -> InstanceResolver -> TypecheckerState
checkConflicts state instance_resolver = do
    state <- instance_resolver.instance_map |> Map.iter |> Iterator.fold (\state, (class_name, instance_info_map) -> do
        generic_instance_location <- case get instance_info_map Generic of
            Some instance_info -> do
                instance_info :: InstanceInfo <- instance_info // FIXME
                Some instance_info.location
            None -> None
        state <- instance_info_map |> Map.iter |> Iterator.fold (\state, (_, i) -> do
                case generic_instance_location of
                    Some generic_instance_location -> do
                        location <- i.location
                        state <- if generic_instance_location == location
                            then state
                            else addError state (ConflictingInstances ("{}" % class_name) generic_instance_location location)
                        state
                    None -> state
            ) state
        state) state
    state

checkInstanceDependenciesForInstance :: TypecheckerState -> InstanceResolver -> T.Type -> P.FullyQualifiedName -> Location -> (TypecheckerState, InstanceResolver)
checkInstanceDependenciesForInstance state instance_resolver type class_name location = do
    deps <- case get state.class_store.classes class_name of
        Some class_info -> do
            class_info :: ClassInfo <- class_info // FIXME:
            class_info.direct_dependencies
        None -> panic "Class {} not found in class store" % class_name
    List.fold (state, instance_resolver) deps (\(state, instance_resolver), dep ->
        case checkInstance state instance_resolver type dep of
            Ok (instance_resolver, state, instance_info) -> do
                (state, instance_resolver)
            Err _ -> do
                state <- addError state (MissingInstance ("{}" % dep) location)
                (state, instance_resolver))

checkInstanceDependencies :: TypecheckerState -> InstanceResolver -> (TypecheckerState, InstanceResolver)
checkInstanceDependencies state instance_resolver =
    Map.fold (state, instance_resolver) instance_resolver.instance_map (\(state, instance_resolver), (class_name, instance_info_map) -> do
        Map.fold (state, instance_resolver) instance_info_map (\(state, instance_resolver), (_, i) -> do
                checkInstanceDependenciesForInstance state instance_resolver i.instance_type class_name i.location
            )
    )
