module Siko.AST.Macros {

import Siko.AST.Function
import Siko.AST.Identifier
import Siko.AST.Name
import Siko.AST.QualifiedName
import Siko.Interner as I

pub struct MacroDef {
    pub public: Bool,
    pub name: Identifier,
    pub qualified_name: Option[QualifiedName],
    pub functions: Vec[FunctionDef],
    pub module_name: I.String,
}

@derive(Clone, PartialEq, Eq)
pub struct AttachedMacroApplication {
    pub provider: Name,
    pub trait_name: Option[Name],
}

@derive(Clone, PartialEq, Eq)
pub struct ExternalMacroApplication {
    pub provider: Name,
}

}
