module Siko.AST.Module {

import Siko.AST.Data
import Siko.AST.Effects
import Siko.AST.Function
import Siko.AST.Identifier
import Siko.AST.Implicits
import Siko.AST.Traits
import Siko.AST.Instances
import Siko.AST.Annotations
import Siko.AST.Globals
import Siko.Package.Collector as PC
import Siko.AST.Macros

pub struct ImportDef {
    pub module_name: Identifier,
    pub alias: Option[Identifier],
    pub is_implicit: Bool,
    pub used: Bool,
}

pub enum ModuleItem {
    Struct(StructDef),
    Enum(EnumDef),
    Function(FunctionDef),
    Import(ImportDef),
    Trait(TraitDef),
    Instance(InstanceDef),
    Effect(EffectDef),
    Implicit(ImplicitDef),
    Global(GlobalDef),
    Macro(MacroDef),
}

pub struct Module {
    pub annotations: Vec[Annotation],
    pub name: Identifier,
    pub items: Vec[ModuleItem],
    pub source_package: PC.SourcePackage,
}

}
