module Siko.Parser.Class where

import Siko.Parser
import Siko.Parser.Error
import Siko.Parser.Function
import Siko.Parser.Token as T
import Siko.Parser.Token.Kind as Kind
import Siko.Parser.Type
import Siko.Syntax.Class
import Siko.Syntax.Function
import Siko.Syntax.Ident
import Siko.Syntax.TypeSignature

parseClassConstraint :: ParserState -> Result (ParserState, Constraint) (ParserState, ParserError)
parseClassConstraint state = do
   (state, name) <- try parseQualifiedTypeName state "class name"
   (state, arg) <- try expectVarIdent state "type argument"
   (state, associated_types) <- if check state Kind.GreaterThan
   then do
      state <- try expect state Kind.GreaterThan
      loop (state, associated_types) <- (state, []) do
         (state, ty) <- try parseTypeSignature state False False
         associated_types <- List.push associated_types ty
         if check state Kind.RParen || check state Kind.Comma
         then break (state, associated_types)
         else (state, associated_types)
   else (state, [])
   Ok (state, Constraint name arg associated_types)

parseClassConstraints :: ParserState -> Result (ParserState, [Constraint]) (ParserState, ParserError)
parseClassConstraints state = if check state Kind.LParen && classConstraintFollows state
   then do
      (state, constraints) <- try parseList state parseClassConstraint Kind.LParen Kind.RParen
      state <- try expect state Kind.DoubleRightArrow
      Ok (state, constraints)
   else Ok (state, [])
   where
      classConstraintFollows :: ParserState -> Bool
      classConstraintFollows state = do
         loop index <- state.index do
            ti <- peekAt state index
            case ti.token of
               T.EndOfItem -> return False
               T.DoubleRightArrow -> return True
               _ -> index + 1

parseBody :: ParserState -> Result (ParserState, [Function], [FunctionSignature]) (ParserState, ParserError)
parseBody state = do
   state <- try expect state Kind.KeywordWhere
   (state, fns, fn_sigs) <- loop (state, fns, fns_sigs) <- (state, [], []) do
      if check state Kind.EndOfBlock
      then break (state, fns, fns_sigs)
      else case try parseFunction state of
         (state, Left fn) -> (state, push fns fn, fns_sigs)
         (state, Right fn_sig) -> (state, fns, push fns_sigs fn_sig)
   state <- try expect state Kind.EndOfBlock
   Ok (state, fns, fn_sigs)

parseAssociatedTypeArgs :: ParserState -> Result (ParserState, [Ident]) (ParserState, ParserError)
parseAssociatedTypeArgs state = do
   state <- try expect state Kind.GreaterThan
   (state, associated_types) <- loop (state, associated_types) <- (state, []) do
      (state, ty) <- try expectVarIdent state "class associated type"
      associated_types <- List.push associated_types ty
      if check state Kind.KeywordWhere
      then break (state, associated_types)
      else (state, associated_types)
   Ok (state, associated_types)

parseAssociatedTypes :: ParserState -> Result (ParserState, [TypeSignature]) (ParserState, ParserError)
parseAssociatedTypes state = do
   state <- try expect state Kind.GreaterThan
   (state, associated_types) <- loop (state, associated_types) <- (state, []) do
      (state, ty) <- try parseTypeSignature state False False
      associated_types <- List.push associated_types ty
      if check state Kind.KeywordWhere
      then break (state, associated_types)
      else (state, associated_types)
   Ok (state, associated_types)

parseClass :: ParserState -> Result (ParserState, Class) (ParserState, ParserError)
parseClass state = do
   state <- try expect state Kind.KeywordClass
   (state, constraints) <- try parseClassConstraints state
   (state, name) <- try expectTypeIdent state "class name"
   (state, argument) <- try expectVarIdent state "class argument"
   (state, associated_types) <- if check state Kind.GreaterThan
   then try parseAssociatedTypeArgs state
   else (state, [])
   (state, functions, function_type_signatures) <- if check state Kind.KeywordWhere
   then try parseBody state
   else (state, [], [])
   state <- try expect state Kind.EndOfItem
   clazz <- Class { name = name,
                    argument = argument,
                    associated_types = associated_types,
                    constraints = constraints,
                    member_functions = functions,
                    member_function_type_signatures = function_type_signatures }
   Ok (state, clazz)

parseInstance :: ParserState -> Result (ParserState, Instance) (ParserState, ParserError)
parseInstance state = do
   state <- try expect state Kind.KeywordInstance
   (state, constraints) <- if check state Kind.LParen
   then do
      (state, constraints) <- try parseList state parseClassConstraint Kind.LParen Kind.RParen
      state <- try expect state Kind.DoubleRightArrow
      (state, constraints)
   else (state, [])
   (state, class_name) <- try parseQualifiedTypeName state "class name"
   (state, type_signature) <- try parseTypeSignature state False False
   (state, associated_types) <- if check state Kind.GreaterThan
   then try parseAssociatedTypes state
   else (state, [])
   (state, functions, function_type_signatures) <- if check state Kind.KeywordWhere
   then try parseBody state
   else (state, [], [])
   state <- try expect state Kind.EndOfItem
   inst <- Instance { class_name = class_name,
                      type_signature = type_signature,
                      associated_types = associated_types,
                      constraints = constraints,
                      member_functions = functions,
                      member_function_type_signatures = function_type_signatures }
   Ok (state, inst)
