module Siko.Backend.Ownership.ExprUnification where

import Siko.MIR.Program as P
import Siko.MIR.Function as F
import Siko.MIR.Type as T
import Siko.MIR.Expr as E
import Siko.MIR.Data as D
import Siko.Backend.Traversal
import Siko.Backend.Ownership.Initialization as Initialization
import Siko.Backend.Ownership.Unification as U
import Siko.Util.DependencyProcessor
import Std.Util
import Map

data FunctionTypeStore = { functions :: Map P.Identity F.FunctionType }

data FunctionVar = FunctionVar P.Identity E.Var deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data Context = { function_type_store :: FunctionTypeStore,
                 adts :: Map P.Identity D.AlgebraicDataType,
                 records :: Map P.Identity D.Record,
                 expr_types :: Map E.ExprId T.Type,
                 function_vars :: Map FunctionVar T.Type,
                 var_gen :: U.OwnershipVarGenerator }

getNextOwnershipVar :: Context -> (Context, T.OwnershipKind)
getNextOwnershipVar context = do
    (var_gen, v) <- U.getNextOwnershipVar context.var_gen
    context <- context { var_gen = var_gen }
    (context, v)

instance U.Apply Context where
    //apply :: Context -> Substitution -> Context
    apply context sub = do
        expr_types <- context.expr_types |> Map.iter |> map (\(expr_id, type) -> do
            new_type <- U.apply type sub
            //if expr_id == (E.ExprId 8)
            //    then println "{} -> {}" % (type, new_type)
            //    else ()
            (expr_id, new_type)) |> toMap
        function_vars <- context.function_vars |> Map.iter |> map (\(v, type) -> (v, U.apply type sub )) |> toMap
        function_type_store <- context.function_type_store
        functions <- function_type_store.functions |> Map.iter |> map (\(id, function_type) -> (id, U.apply function_type sub)) |> toMap
        function_type_store <- function_type_store { functions = functions } // FIXME
        context <- context { expr_types = expr_types,
                             function_vars = function_vars,
                             function_type_store = function_type_store }
        context

getExprType :: Context -> E.ExprId -> T.Type
getExprType context expr_id = case get context.expr_types expr_id of
    Some t -> t
    None -> panic "Could not get expr type for {}" % expr_id

getVarType :: Context -> FunctionVar -> T.Type
getVarType context var = case get context.function_vars var of
    Some t -> t
    None -> panic "Could not get var type for {}" % var

dump :: Context -> String -> ()
dump context msg = do
    println "-------{}---------" % msg
    context.expr_types |> Map.iter |> forEach (\(v, t) -> println "{} - {}" % (v, t))
    context.function_vars |> Map.iter |> forEach (\(v, t) -> println "{} - {}" % (v, t))

initExpr :: P.Identity -> Context -> E.Expr -> (Context, E.Expr)
initExpr function_id context expr = do
    E.Expr s_expr type expr_id <- expr
    (expr_types, prev) <- insert context.expr_types expr_id type
    if isSome prev then panic "Duplicated expr id! {} - {}" % (expr_id, s_expr) else ()
    context <- context { expr_types = expr_types }
    context <- case s_expr of
        E.VarDecl v rhs -> do
            E.Expr _ rhs_type _ <- rhs
            var <- FunctionVar function_id v
            (function_vars, _) <- insert context.function_vars var rhs_type
            context { function_vars = function_vars }
        E.Loop v initializer _ _ _ -> do
            E.Expr _ initializer_type _ <- initializer
            var <- FunctionVar function_id v
            (function_vars, _) <- insert context.function_vars var initializer_type
            context { function_vars = function_vars }
        E.CaseOf body cases -> do
            context <- cases |> List.iter |> fold (\context, c -> do
                case c.checker of
                    E.VariantChecker index v type -> do
                        var <- FunctionVar function_id v
                        adt <- getAdtType context type
                        variant <- atIndex adt.variants index
                        (function_vars, _) <- insert context.function_vars var variant.type
                        context { function_vars = function_vars }
                    _ -> context) context
            context
        _ -> context
    (context, expr)

unifyExprs :: Context -> E.Expr -> E.Expr -> Context
unifyExprs context expr1 expr2 = do
    E.Expr _ _ id1 <- expr1
    E.Expr _ _ id2 <- expr2
    type1 <- getExprType context id1
    type2 <- getExprType context id2
    sub <- U.createSubstitution
    sub <- U.unify sub type1 type2
    context <- U.apply context sub
    context

unifyExprIds :: Context -> E.ExprId -> E.ExprId -> Context
unifyExprIds context id1 id2 = do
    type1 <- getExprType context id1
    type2 <- getExprType context id2
    sub <- U.createSubstitution
    sub <- U.unify sub type1 type2
    context <- U.apply context sub
    context

unifyExprWithVar :: Context -> E.ExprId -> FunctionVar -> Context
unifyExprWithVar context expr_id var = do
    type1 <- getExprType context expr_id
    type2 <- getVarType context var
    sub <- U.createSubstitution
    sub <- U.unify sub type1 type2
    context <- U.apply context sub
    context

cloneFunctionType :: Context -> F.FunctionType -> (Context, F.FunctionType)
cloneFunctionType context function_type = do
    ownership_vars <- function_type.args |> List.iter |> fold (\ownership_vars, arg_type -> do
        vs <- T.collectOwnershipVars arg_type
        ownership_vars + vs) []
    ownership_vars <- ownership_vars + T.collectOwnershipVars function_type.result
    (context, clones) <- ownership_vars |> List.iter |> fold (\(context, clones), ownership_var -> do
        (context, clone) <- getNextOwnershipVar context
        (context, clones + [clone])) (context, [])
    sub <- U.batch ownership_vars clones
    function_type <- U.apply function_type sub
    (context, function_type)

getRecordType :: Context -> T.Type -> D.Record
getRecordType context type = do
    record_id <- T.getIdentity type
    record <- case get context.records record_id of
        Some r -> r
        None -> panic "Could not find record {}" % record_id
    ownership_vars <- T.collectOwnershipArgs type
    sub <- U.batch record.ownership_vars ownership_vars
    record <- U.apply record sub
    record

getAdtType :: Context -> T.Type -> D.AlgebraicDataType
getAdtType context type = do
    adt_id <- T.getIdentity type
    adt <- case get context.adts adt_id of
        Some adt -> adt
        None -> panic "Could not find adt {}" % adt_id
    ownership_vars <- T.collectOwnershipArgs type
    sub <- U.batch adt.ownership_vars ownership_vars
    adt <- U.apply adt sub
    adt

getRecordFieldType :: D.Record -> String -> T.Type
getRecordFieldType record name =
    case find record.fields (\f -> f.name == name) of
        Some f -> do
            f :: D.RecordField <- f // FIXME
            f.type
        None -> panic "No field named {}" % name

getFunctionType :: Context -> P.Identity -> F.FunctionType
getFunctionType context id =
    case get context.function_type_store.functions id of
        Some function_type -> function_type
        None -> panic "No function type found for {}" % id

checkExpr :: P.Identity -> [P.Identity] -> Context -> E.Expr -> (Context, E.Expr)
checkExpr function_id functions context expr = do
    E.Expr s_expr t id <- expr
    context <- case s_expr of
        E.Do items -> do
            last_index <- getLength items - 1
            last <- atIndex items last_index
            context <- unifyExprs context expr last
            context
        E.Multi _ -> panic "Multi found in checkExpr"
        E.StaticFunctionCall f_id args -> do
            function_type <- getFunctionType context f_id
            function_type :: F.FunctionType <- function_type // FIXME
            (context, function_type) <- if contains functions f_id
                then (context, function_type)
                else cloneFunctionType context function_type
            (context, function_type, index) <- args |> List.iter |> fold (\(context, function_type, index), arg -> do
                E.Expr _ _ arg_id <- arg
                arg_type <- getExprType context arg_id
                func_arg_type <- atIndex function_type.args index
                sub <- U.createSubstitution
                sub <- U.unify sub arg_type func_arg_type
                context <- U.apply context sub
                function_type <- U.apply function_type sub
                (context, function_type, index + 1)) (context, function_type, 0)
            sub <- U.createSubstitution
            result_type <- getExprType context id
            sub <- U.unify sub function_type.result result_type
            context <- U.apply context sub
            result_type <- getExprType context id
            context
        E.IntegerLiteral lit -> context
        E.StringLiteral lit -> context
        E.FloatLiteral lit -> context
        E.CharLiteral lit -> context
        E.VarDecl v rhs -> do
            E.Expr _ _ rhs_expr_id <- rhs
            var <- FunctionVar function_id v
            unifyExprWithVar context rhs_expr_id var
        E.VarRef arg -> do
            var <- FunctionVar function_id arg
            unifyExprWithVar context id var
        E.FieldAccess name rhs -> do
            E.Expr _ _ rhs_expr_id <- rhs
            rhs_type <- getExprType context rhs_expr_id
            record <- getRecordType context rhs_type
            field_type <- getRecordFieldType record name
            sub <- U.createSubstitution
            type <- getExprType context id
            sub <- U.unify sub field_type type
            context <- U.apply context sub
            context
        E.If cond true_branch false_branch -> do
            context <- unifyExprs context true_branch false_branch
            context <- unifyExprs context expr true_branch
            context
        E.List items -> do
            case head items of
                Some first -> do
                    E.Expr _ _ first_id <- first
                    list_type <- getExprType context id
                    first_type <- getExprType context first_id
                    list_ownership_vars <- T.collectOwnershipArgs list_type
                    first_ownership_vars <- T.collectOwnershipVars first_type
                    sub <- U.batch list_ownership_vars first_ownership_vars
                    context <- U.apply context sub
                    context <- items |> List.iter |> fold (\context, item -> do
                        unifyExprs context first item) context
                    context
                None -> context
        E.Return arg -> do
            function_type <- getFunctionType context function_id
            E.Expr _ _ arg_id <- arg
            arg_type <- getExprType context arg_id
            sub <- U.createSubstitution
            sub <- U.unify sub function_type.result arg_type
            context <- U.apply context sub
            context
        E.Continue arg -> context
        E.Break arg -> context
        E.RecordUpdate v updates -> do
            var <- FunctionVar function_id v
            record_type <- getVarType context var
            sub <- U.createSubstitution
            type <- getExprType context id
            sub <- U.unify sub record_type type
            context <- U.apply context sub
            record <- getRecordType context record_type
            (context, record) <- updates |> List.iter |> fold (\(context, record), update -> do
                field_type <- getRecordFieldType record update.field_name
                sub <- U.createSubstitution
                E.Expr _ _ body_id <- update.body
                body_type <- getExprType context body_id
                sub <- U.unify sub field_type body_type
                context <- U.apply context sub
                record <- U.apply record sub
                (context, record)) (context, record)
            context
        E.Loop v initializer _ continues breaks -> do
            E.Expr _ _ initializer_id <- initializer
            var <- FunctionVar function_id v
            context <- unifyExprWithVar context initializer_id var
            context <- continues |> List.iter |> fold (\context, cont -> unifyExprIds context initializer_id cont) context
            context <- breaks |> List.iter |> fold (\context, brk -> unifyExprIds context id brk) context
            context
        E.CaseOf body cases -> cases |> List.iter |> fold (\context, c -> do
            context <- case c.checker of
                    E.VariantChecker index v type -> do
                        var <- FunctionVar function_id v
                        E.Expr _ _ body_id <- body
                        body_type <- getExprType context body_id
                        adt <- getAdtType context body_type
                        variant <- atIndex adt.variants index
                        sub <- U.createSubstitution
                        var_type <- getVarType context var
                        sub <- U.unify sub var_type variant.type
                        context <- U.apply context sub
                        context
                    _ -> context
            unifyExprs context c.body expr) context
        E.Clone args -> panic "Clone in checkExpr"
        E.Deref args -> panic "Deref in checkExpr"
        E.Ref args -> panic "Ref in checkExpr"
        E.Move args -> panic "Move in checkExpr"
        E.Box args -> panic "Box in checkExpr"
    (context, expr)

initFunction :: Context -> F.Function -> Context
initFunction context function = case function.kind of
    F.Normal body -> do
        (context, _) <- function.type.args |> List.iter |> fold (\(context, index), arg_type -> do
            var <- FunctionVar function.id (E.Arg index)
            (function_vars, _) <- insert context.function_vars var arg_type
            context <- context { function_vars = function_vars }
            (context, index + 1)) (context, 0)
        //println "Processing {} - init" % function.id
        (context, _) <- traverse context body (Some (initExpr function.id)) None
        context
    _ -> context

checkFunction :: Context -> F.Function -> [P.Identity] -> Context
checkFunction context function functions = case function.kind of
    F.Normal body -> do
        //println "Processing {} - check" % function.id
        (context, _) <- traverse context body (Some (checkExpr function.id functions)) None
        E.Expr _ _ body_id <- body
        body_type <- getExprType context body_id
        sub <- U.createSubstitution
        sub <- U.unify sub function.type.result body_type
        context <- U.apply context sub
        context
    _ -> context

updateExpr :: Context -> E.Expr -> (Context, E.Expr)
updateExpr context expr = do
    E.Expr s_expr t expr_id <- expr
    case get context.expr_types expr_id of
        Some t -> (context, E.Expr s_expr t expr_id)
        None -> panic "Expr {} not found in context" % expr_id

updateFunctionKind :: Context -> F.FunctionKind -> F.FunctionKind
updateFunctionKind context kind = case kind of
    F.Normal body -> do
        (context, body) <- traverse context body (Some updateExpr) None
        F.Normal body
    k -> k

processFunctions :: P.Program -> Map P.Identity F.FunctionType -> FunctionTypeStore -> [P.Identity] -> U.OwnershipVarGenerator -> (P.Program, FunctionTypeStore, U.OwnershipVarGenerator)
processFunctions program saved_function_types function_type_store functions var_gen = do
    context <- Context function_type_store program.adts program.records empty empty var_gen
    context <- functions |> List.iter |> fold (\context, id -> do
        function <- P.getFunction program id
        context <- initFunction context function
        context) context
    //dump context "after init"
    context <- functions |> List.iter |> fold (\context, id -> do
        function <- P.getFunction program id
        context <- checkFunction context function functions
        context) context
    //dump context "after check"
    program <- functions |> List.iter |> fold (\program, id -> do
        function <- P.getFunction program id
        kind <- updateFunctionKind context function.kind
        type <- case get context.function_type_store.functions id of
            Some type -> type
            None -> panic "No function type found!"
        (kind, type) <- case function.kind of
            F.Normal body -> do
                (context, body) <- traverse context body (Some updateExpr) None
                (F.Normal body, type)
            kind -> do
                type <- case get saved_function_types id of
                    Some type -> type
                    None -> type
                (kind, type)
        program <- P.updateFunctionType program id type
        program <- P.updateFunctionKind program id kind
        program) program
    (program, context.function_type_store, context.var_gen)

processProgram :: P.Program -> [DependencyGroup P.Identity] -> [DependencyGroup P.Identity] -> P.Program
processProgram program data_groups function_groups = do
    (var_gen, saved_function_types, program) <- Initialization.processDataTypes program data_groups
    function_type_store <- program.functions |> Map.iter |> fold (\function_type_store, (id, function) -> do
        (functions, _) <- insert function_type_store.functions id function.type
        function_type_store { functions = functions } ) (FunctionTypeStore empty)
    (program, function_type_store, var_gen) <- function_groups |> List.iter |> fold (\(program, function_type_store, var_gen), group -> do
        processFunctions program saved_function_types
             function_type_store group.items var_gen) (program, function_type_store, var_gen)
    program