module Main where

import Map

data Identity = Identity deriving (PartialEq, Eq, PartialOrd, Ord)

data Type = Adt Identity
          | Record Identity
          | Ref Int Type
          | Never
          deriving (PartialEq, Eq, PartialOrd, Ord)


data Equal = EqualGroup GroupTypeVariable GroupTypeVariable
           | EqualOwnership OwnershipTypeVariable OwnershipTypeVariable

data BorrowId = BorrowId Int deriving (PartialEq, Eq, PartialOrd, Ord)

data OwnershipKind = Unknown
                   | Owner
                   | Borrower BorrowId

data MemberKind = Variant Int
                | Field String
                | Extern Int

data MemberInfo = { kind :: MemberKind,
                    type :: Type,
                    root :: GroupTypeVariable,
                    info :: TypeVariableInfo
                }

data OwnershipInfo = { var :: OwnershipTypeVariable, kind :: OwnershipKind }

data OwnershipTypeVariable = OwnershipTypeVariable Int deriving (PartialEq, Eq, PartialOrd, Ord)
data GroupTypeVariable = GroupTypeVariable Int deriving (PartialEq, Eq, PartialOrd, Ord)

data TypeVariableInfo = { ownership_var :: OwnershipTypeVariable,
                          arg_group_var :: GroupTypeVariable,
                        } deriving (PartialEq, Eq, PartialOrd, Ord)

data TypeInfo = TypeInfo Type TypeVariableInfo deriving (PartialEq, Eq, PartialOrd, Ord)

mergeTypes :: List MemberInfo -> (List MemberInfo, List Equal)
mergeTypes members = do
    (members, type_info_map) :: (List MemberInfo , Map GroupTypeVariable (List TypeInfo)) <- (members, Map.empty)
    inverse_type_info_map <- Map.fold Map.empty type_info_map (\inverse_type_info_map, (root, type_infos) -> Map.add inverse_type_info_map type_infos root)
    equals <- Map.fold List.empty inverse_type_info_map (\equals, (type_infos, roots) -> do
        first <- List.atIndex roots 0
        if List.getLength roots > 1
        then List.fold equals roots (\equals, var ->
            if first != var
            then List.push equals (EqualGroup first var)
            else equals)
        else equals)
    (members, equals)

main = do
    mergeTypes List.empty
    ()
