module Main where

import Map2
import List2 as List2
import List2 (List2)


data Identity = Identity deriving (PartialEq, Eq, PartialOrd, Ord)

data Type = Adt Identity
          | Record Identity
          | Ref Int Type
          | Never
          deriving (PartialEq, Eq, PartialOrd, Ord)


data Equal = EqualGroup GroupTypeVariable GroupTypeVariable
           | EqualOwnership OwnershipTypeVariable OwnershipTypeVariable

data BorrowId = BorrowId Int deriving (PartialEq, Eq, PartialOrd, Ord)

data OwnershipKind = Unknown
                   | Owner
                   | Borrower BorrowId

data MemberKind = Variant Int
                | Field String
                | Extern Int

data MemberInfo = { kind :: MemberKind,
                    type :: Type,
                    root :: GroupTypeVariable,
                    info :: TypeVariableInfo
                }

data OwnershipInfo = { var :: OwnershipTypeVariable, kind :: OwnershipKind }

data OwnershipTypeVariable = OwnershipTypeVariable Int deriving (PartialEq, Eq, PartialOrd, Ord)
data GroupTypeVariable = GroupTypeVariable Int deriving (PartialEq, Eq, PartialOrd, Ord)

data TypeVariableInfo = { ownership_var :: OwnershipTypeVariable,
                          arg_group_var :: GroupTypeVariable,
                        } deriving (PartialEq, Eq, PartialOrd, Ord)

data TypeInfo = TypeInfo Type TypeVariableInfo deriving (PartialEq, Eq, PartialOrd, Ord)

mergeTypes :: List2 MemberInfo -> (List2 MemberInfo, List2 Equal)
mergeTypes members = do
    (members, type_info_map) :: (List2 MemberInfo , Map2 GroupTypeVariable (List2 TypeInfo)) <- (members, Map2.empty)
    inverse_type_info_map <- Map2.fold Map2.empty type_info_map (\inverse_type_info_map, (root, type_infos) -> Map2.add inverse_type_info_map type_infos root)
    equals <- Map2.fold List2.empty inverse_type_info_map (\equals, (type_infos, roots) -> do
        first <- List2.atIndex roots 0
        if List2.getLength roots > 1
        then List2.fold equals roots (\equals, var ->
            if first != var
            then List2.push equals (EqualGroup first var)
            else equals)
        else equals)
    (members, equals)

main = do
    mergeTypes List2.empty
    ()
