module Main {

enum Wrap {
    Some(Int),
    None
}

trait MyMap[T] {
    fn my_map(a: T) -> T
}

instance MyMap[Int] {
    fn my_map(a: Int) -> Int { a + 1 }
}

instance MyMap[Wrap] = auto2(Map)

fn main() {
    let x = Wrap.Some(5);
    let y = my_map(x);
    match y {
        Some(n) => println(n),
        None => println("none")
    };
    let z = my_map(Wrap.None);
    match z {
        Some(n) => println(n),
        None => println("none")
    };
}

}
