module Siko.Parser.Error where

import Siko.Syntax.Location

data ParserError = GeneralError
                | UnexpectedToken String String Span
                | Context ParserError String
                | InvalidTypeArgument Span
                deriving (Show)

data LexerError = InvalidEscapeSequence Span
                  | UnsupportedCharacter Span
                  | InvalidOperator Span
            deriving (Show)
