module Siko.Parser where

import Siko.Parser.Type
import Siko.Parser.Class
import Siko.Parser.Function
import Siko.Parser.Module

import Siko.Syntax.Ident
import Siko.Syntax.Program
import Siko.Syntax.Module
import Siko.Syntax.TypeSignature
import Siko.Syntax.Location
import Siko.Parser.Token
import Siko.Parser.Token.Kind as Kind
import Siko.Parser.Layout
import Siko.Parser.Lexer

data ParserError = GeneralError
                | UnexpectedToken String String Span
                | Context ParserError String
                deriving (Show)

data ParserState =
    {
        tokens :: [TokenInfo],
        index :: Int,
        errors :: [ParserError],
        modules :: [Module],
        file_id :: FileId
    }

initState file_id tokens = ParserState tokens 0 [] [] file_id

getLocation :: Span -> ParserState -> Location
getLocation span state = Location state.file_id span

isDone :: ParserState -> Bool
isDone state = state.index >= getLength state.tokens

peek :: ParserState -> TokenInfo
peek state = atIndex state.tokens state.index

step :: ParserState -> ParserState
step state = do
    state { index = state.index + 1 }

addError :: ParserState -> ParserError -> ParserState
addError state error = state { errors = state.errors + [error] }

addModule :: ParserState -> Module -> ParserState
addModule state mod = state { modules = state.modules + [mod] }

unexpectedToken :: ParserState -> String -> ParserError
unexpectedToken state expected = do
    ti <- peek state
    found <- show ti.token
    UnexpectedToken expected found ti.span

expect :: ParserState -> Kind.TokenKind -> Result ParserState (ParserState, ParserError)
expect state kind = do
    ti <- peek state
    if getKind ti.token == kind
        then
            Ok (step state)
        else
            Err (state, unexpectedToken state (show kind))

check :: ParserState -> Kind.TokenKind -> Bool
check state kind = do
    ti <- peek state
    getKind ti.token == kind

expectTypeIdent :: ParserState -> String -> Result (ParserState, Ident) (ParserState, ParserError)
expectTypeIdent state msg = do
    ti <- peek state
    case ti.token of
        TypeIdentifier id -> Ok (step state, Ident id (getLocation ti.span state))
        _ -> Err (state, unexpectedToken state msg)

expectVarIdent :: ParserState -> String -> Result (ParserState, Ident) (ParserState, ParserError)
expectVarIdent state msg = do
    ti <- peek state
    case ti.token of
        VarIdentifier id -> Ok (step state, Ident id (getLocation ti.span state))
        _ -> Err (state, unexpectedToken state msg)

data ParenParse a = Single a | Multi [a]

parseParens a :: ParserState -> (ParserState -> Result (ParserState, a) (ParserState, ParserError)) -> String -> Result (ParserState, ParenParse a) (ParserState, ParserError)
parseParens state parser msg = do
    state <- try expect state Kind.LParen
    (state, parts, comma_found) <- loop (state, parts, comma_found) <- (state, [], False) do
            if check state Kind.RParen
                then
                    break (state, parts, comma_found)
                else
                    do
                        (state, item) <- try parser state
                        parts <- parts + [item]
                        if check state Kind.Comma
                            then
                                do
                                    state <- try expect state Kind.Comma
                                    (state, parts, True)
                            else
                                if check state Kind.RParen
                                    then
                                        break (state, parts, comma_found)
                                    else
                                        return Err (state, unexpectedToken state msg)
    state <- try expect state Kind.RParen
    if comma_found || getLength parts == 0 // FIXME: isEmpty
        then
            Ok (state, Multi parts)
        else
            Ok (state, Single (atIndex parts 0))

processTokens :: ParserState -> (Program, [ParserError])
processTokens state = do
    state <- loop state <- state do
        if not (isDone state)
            then
                do
                    case parseModule state of
                        Ok state -> state
                        Err (state, err) -> do
                            state <- addError state err
                            break state
            else
                break state
    (Program state.modules, state.errors)

printErr err = do
            case err of
            GeneralError -> println "General error"
            UnexpectedToken expected found span -> println "Expected {}, found {} at {}" % (expected, found, span)
            Context err msg -> do
                println msg
                printErr err

parse :: String -> (Program, [LexerError], [ParserError])
parse input =
    do
        (tokens, lexer_errors) <- lex input
        println "Tokens: {}" % tokens
        println "Errors: {}" % lexer_errors
        state <- initState (FileId 0) tokens
        (program, parser_errors) <- processTokens state
        parser_errors |> List.iter |> forEach \x -> printErr x
        (program, lexer_errors, parser_errors)
