module Siko.Parser.Token.Kind where

data TokenKind = VarIdentifier
    | TypeIdentifier
    | Equal
    | DoubleEqual
    | NotEqual
    | LessThan
    | GreaterThan
    | LessOrEqualThan
    | GreaterOrEqualThan
    | Add
    | Sub
    | Mul
    | Div
    | LParen
    | RParen
    | LBracket
    | RBracket
    | LCurly
    | RCurly
    | StringLiteral
    | IntegerLiteral
    | CharLiteral
    | Dot
    | DoubleDot
    | Comma
    | Colon
    | DoubleColon
    | ExclamationMark
    | Ampersand
    | Pipe
    | Percent
    | Backslash
    | Wildcard
    | And
    | Or
    | KeywordModule
    | KeywordWhere
    | KeywordDo
    | KeywordClass
    | KeywordInstance
    | KeywordExtern
    | KeywordData
    | KeywordDeriving
    | KeywordImport
    | KeywordHiding
    | KeywordAs
    | KeywordIf
    | KeywordThen
    | KeywordElse
    | KeywordReturn
    | KeywordTry
    | KeywordLoop
    | KeywordContinue
    | KeywordBreak
    | KeywordCase
    | KeywordOf
    | RightArrow
    | LeftArrow
    | InclusiveRange
    | DoubleRightArrow
    | PipeForward
    | EndOfItem
    | EndOfBlock
    | EndOfModule
    deriving (Show, PartialEq, Eq)

module Siko.Parser.Token where

import Siko.Syntax.Location
import Siko.Parser.Token.Kind as Kind

data Token = VarIdentifier String
    | TypeIdentifier String
    | Equal
    | DoubleEqual
    | NotEqual
    | LessThan
    | GreaterThan
    | LessOrEqualThan
    | GreaterOrEqualThan
    | Add
    | Sub
    | Mul
    | Div
    | LParen
    | RParen
    | LBracket
    | RBracket
    | LCurly
    | RCurly
    | StringLiteral String
    | IntegerLiteral String
    | CharLiteral Char
    | Dot
    | DoubleDot
    | Comma
    | Colon
    | DoubleColon
    | ExclamationMark
    | Ampersand
    | Pipe
    | Percent
    | Backslash
    | Wildcard
    | And
    | Or
    | KeywordModule
    | KeywordWhere
    | KeywordDo
    | KeywordClass
    | KeywordInstance
    | KeywordExtern
    | KeywordData
    | KeywordDeriving
    | KeywordImport
    | KeywordHiding
    | KeywordAs
    | KeywordIf
    | KeywordThen
    | KeywordElse
    | KeywordReturn
    | KeywordTry
    | KeywordLoop
    | KeywordContinue
    | KeywordBreak
    | KeywordCase
    | KeywordOf
    | RightArrow
    | LeftArrow
    | InclusiveRange
    | DoubleRightArrow
    | PipeForward
    | EndOfItem
    | EndOfBlock
    | EndOfModule
    deriving (Show)


data TokenInfo = {
        token :: Token,
        span :: Span
    }

instance Show TokenInfo where
    show a = show a.token

getKind :: Token -> Kind.TokenKind
getKind token = case token of
    VarIdentifier _ -> Kind.VarIdentifier
    TypeIdentifier _ -> Kind.TypeIdentifier
    Equal -> Kind.Equal
    DoubleEqual -> Kind.DoubleEqual
    NotEqual -> Kind.NotEqual
    LessThan -> Kind.LessThan
    GreaterThan -> Kind.GreaterThan
    LessOrEqualThan -> Kind.LessOrEqualThan
    GreaterOrEqualThan -> Kind.GreaterOrEqualThan
    Add -> Kind.Add
    Sub -> Kind.Sub
    Mul -> Kind.Mul
    Div -> Kind.Div
    LParen -> Kind.LParen
    RParen -> Kind.RParen
    LBracket -> Kind.LBracket
    RBracket -> Kind.RBracket
    LCurly -> Kind.LCurly
    RCurly -> Kind.RCurly
    StringLiteral _ -> Kind.StringLiteral
    IntegerLiteral _ -> Kind.IntegerLiteral
    CharLiteral _ -> Kind.CharLiteral
    Dot -> Kind.Dot
    DoubleDot -> Kind.DoubleDot
    Comma -> Kind.Comma
    Colon -> Kind.Colon
    DoubleColon -> Kind.DoubleColon
    ExclamationMark -> Kind.ExclamationMark
    Ampersand -> Kind.Ampersand
    Pipe -> Kind.Pipe
    Percent -> Kind.Percent
    Backslash -> Kind.Backslash
    Wildcard -> Kind.Wildcard
    And -> Kind.And
    Or -> Kind.Or
    KeywordModule -> Kind.KeywordModule
    KeywordWhere -> Kind.KeywordWhere
    KeywordDo -> Kind.KeywordDo
    KeywordClass -> Kind.KeywordClass
    KeywordInstance -> Kind.KeywordInstance
    KeywordExtern -> Kind.KeywordExtern
    KeywordData -> Kind.KeywordData
    KeywordDeriving -> Kind.KeywordDeriving
    KeywordImport -> Kind.KeywordImport
    KeywordHiding -> Kind.KeywordHiding
    KeywordAs -> Kind.KeywordAs
    KeywordIf -> Kind.KeywordIf
    KeywordThen -> Kind.KeywordThen
    KeywordElse -> Kind.KeywordElse
    KeywordReturn -> Kind.KeywordReturn
    KeywordTry -> Kind.KeywordTry
    KeywordLoop -> Kind.KeywordLoop
    KeywordContinue -> Kind.KeywordContinue
    KeywordBreak -> Kind.KeywordBreak
    KeywordCase -> Kind.KeywordCase
    KeywordOf -> Kind.KeywordOf
    RightArrow -> Kind.RightArrow
    LeftArrow -> Kind.LeftArrow
    InclusiveRange -> Kind.InclusiveRange
    DoubleRightArrow -> Kind.DoubleRightArrow
    PipeForward -> Kind.PipeForward
    EndOfItem -> Kind.EndOfItem
    EndOfBlock -> Kind.EndOfBlock
    EndOfModule -> Kind.EndOfModule
