module Siko.Parser.Type(parseTypeSignature) where

import Siko.Parser
import Siko.Syntax.TypeSignature
import Siko.Syntax.Ident
import Siko.Parser.Token as T
import Siko.Parser.Token.Kind as Kind
import Siko.Parser.Error

buildTypeSignature :: SimpleTypeSignature -> Int -> ParserState -> (ParserState, TypeSignature)
buildTypeSignature ty start_index state = do
    ty <- TypeSignature ty (buildLocation start_index state)
    (state, ty)

parseTypeSignature :: ParserState -> Bool -> Bool -> Result (ParserState, TypeSignature) (ParserState, ParserError)
parseTypeSignature state parsingVariant allowWildcard = do
    start_index <- state.index
    if parsingVariant
    then do
        (state, name) <- try expectTypeIdent state "variant name"
        (state, items) <- loop (state, items) <- (state, []) do
            ti <- peek state
            case ti.token of
                T.EndOfItem | T.Pipe | T.KeywordDeriving -> break (state, items)
                _ -> do
                    (state, item) <- try parseTypeSignaturePart state False
                    (state, items + [item])
        Ok (buildTypeSignature (Named name items) start_index state)
    else do
        (state, from) <- try parseTypeSignaturePart state allowWildcard
        loop (state, from) <- (state, from) do
                ti <- peek state
                case ti.token of
                    T.RightArrow -> do
                        state <- try expect state Kind.RightArrow
                        (state, to) <- try parseTypeSignature state False allowWildcard
                        buildTypeSignature (Function from to) start_index state
                    _ -> break Ok (state, from)

parseTupleType :: ParserState -> Bool -> Result (ParserState, TypeSignature) (ParserState, ParserError)
parseTupleType state allowWildcard = do
    start_index <- state.index
    case try parseParens state (\state -> parseTypeSignature state False allowWildcard) "type signature" of
        (state, Single ty) -> Ok (state, ty)
        (state, Multi types) -> Ok (buildTypeSignature (Tuple types) start_index state)

parseTypeSignaturePart :: ParserState -> Bool -> Result (ParserState, TypeSignature) (ParserState, ParserError)
parseTypeSignaturePart state allowWildcard = do
    start_index <- state.index
    ti <- peek state
    case ti.token of
        T.LParen -> parseTupleType state allowWildcard
        T.LBracket -> do
            state <- try expect state Kind.LBracket
            (state, ty) <- try parseTypeSignature state False allowWildcard
            state <- try expect state Kind.RBracket
            Ok (buildTypeSignature (List ty) start_index state)
        T.VarIdentifier id -> do
            (state, ident) <- try expectVarIdent state "type argument"
            Ok (buildTypeSignature (TypeArg ident) start_index state)
        T.TypeIdentifier id -> do
            (state, name) <- try parseQualifiedTypeName state "type name"
            (state, args) <- loop (state, args) <- (state, []) do
                    ti  <- peek state
                    case ti.token of
                        T.LParen
                         | T.LBracket
                         | T.Wildcard
                         | T.ExclamationMark
                         | T.Ampersand-> do
                            (state, arg) <- try (parseTypeSignaturePart state allowWildcard)
                            args <- args + [arg]
                            (state, args)
                        T.VarIdentifier id -> do
                            (state, ident) <- try expectVarIdent state "type argument"
                            (state, arg) <- buildTypeSignature (TypeArg ident) start_index state
                            args <- args + [arg]
                            (state, args)
                        T.TypeIdentifier id -> do
                            (state, name) <- try parseQualifiedTypeName state "type name"
                            (state, arg) <- buildTypeSignature (Named name []) start_index state
                            args <- args + [arg]
                            (state, args)
                        _ -> break (state, args)
            Ok (buildTypeSignature (Named name args) start_index state)
        T.Wildcard -> do
            state <- try expect state Kind.Wildcard
            Ok (buildTypeSignature Wildcard start_index state)
        T.ExclamationMark -> do
            state <- try expect state Kind.ExclamationMark
            Ok (buildTypeSignature Never start_index state)
        T.Ampersand -> do
            state <- try expect state Kind.Ampersand
            (state, ty) <- try parseTypeSignaturePart state allowWildcard
            Ok (buildTypeSignature (Ref ty) start_index state)
        T.Tilde -> do
            state <- try expect state Kind.Tilde
            (state, ty) <- try parseTypeSignaturePart state allowWildcard
            Ok (buildTypeSignature (Owner ty) start_index state)
        _ -> return Err (state, unexpectedToken state "type signature")
