module Main where

import Siko.Cache
import Siko.Config
import Siko.MIR.Program
import Siko.MIR.Backend
import Siko.MIR.Backend.Cache
import Siko.LIR.Backend.Cache
import Map

main = do
    println "Siko MIR backend"
    with { getConfig = \_ -> getDefaultConfig } do
        programs :: [Program] <- loadCache getMIRBackendCachePath
        mir_program <- atIndex programs 0
        lir_program <- processProgram mir_program
        updateCache getLIRBackendCachePath [lir_program]
        ()
