module Siko.Constants.Map {

import Siko.AST.QualifiedName
import Siko.Constants.Util

pub struct MapNames {
    pub type_qn: QualifiedName,
    pub new_qn: QualifiedName,
    pub insert_qn: QualifiedName,
}

pub fn build_map_names() -> MapNames {
    let parent_name = m("Std.Map.Map");
    MapNames(
        type_qn: QualifiedName.new_struct(m("Std.Map"), m("Map")),
        new_qn: QualifiedName.new_method(parent_name, m("new")),
        insert_qn: QualifiedName.new_method(parent_name, m("insert")),
    )
}

}
