module Siko.Constants.String {

import Siko.AST.QualifiedName
import Siko.Constants.Util

pub struct StringNames {
    pub type_qn: QualifiedName,
    pub eq_qn: QualifiedName,
    pub from_literal_qn: QualifiedName,
}

pub fn build_string_names() -> StringNames {
    let parent_name = m("Std.String.String");
    StringNames(
        type_qn: QualifiedName.new_struct(m("Std.String"), m("String")),
        eq_qn: QualifiedName.new_method(parent_name, m("eq")),
        from_literal_qn: QualifiedName.new_method(parent_name, m("from_literal")),
    )
}

}
