module Main where

import IO
import Siko.Cache
import Siko.Diagnostics.Typechecker
import Siko.FileManager.Cache
import Siko.HIR.Class as HC
import Siko.HIR.Data as HD
import Siko.HIR.Effect as HE
import Siko.HIR.Function as HF
import Siko.Resolver.Cache
import Siko.Typechecker.Cache
import Siko.Typechecker.Core
import Siko.Util.DependencyProcessor

main = do
    functions :: [HF.Function ()] <- loadCache getResolvedFunctionCachePath
    classes :: [HC.Class] <- loadCache getResolvedClassCachePath
    instances :: [HC.Instance] <- loadCache getResolvedInstanceCachePath
    effects :: [HE.Effect] <- loadCache getResolvedEffectCachePath
    adts :: [HD.AlgebraicDataType] <- loadCache getResolvedAdtCachePath
    records :: [HD.Record] <- loadCache getResolvedRecordCachePath
    file_manager <- loadCache getFileManagerCachePath
    file_manager <- atIndex file_manager 0
    (typed_functions, errors) <- typecheck functions classes instances effects adts records
    if List.isEmpty errors
    then updateCache getTypedFunctionCachePath typed_functions
    else do
        printTypecheckerErrors file_manager errors
        exit 1
