module Siko.MIR.Backend.Ownership.Inference.ConstraintProcessor(processConstraints, InferenceMode(..)) where

import Siko.MIR.Backend.Ownership.Inference.Constraint as C
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.BorrowId

import Siko.MIR.Program as P
import Siko.MIR.Expr as E
import Siko.Config
import Siko.Trace
import List2 as List2
import List2 (List2)
import Map2
import Map
import Set

data InferenceMode = Partial
                   | Full
                   deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data Context = { config :: Config,
                 inference_info :: InferenceInfo,
                 function_id :: P.Identity,
                 changed_ownership_vars :: Bool,
                 invalid_borrow_map :: Map2 E.ExprId (List2 E.ExprId),
                 ownership_expr_map :: Map2 OwnershipTypeVariable (List2 E.ExprId),
                 group_expr_map :: Map2 GroupTypeVariable (List2 E.ExprId),
                 ownership_group_map :: Map2 OwnershipTypeVariable (List2 GroupTypeVariable),
                 call_context_map :: Map E.ExprId C.CallContextSet,
                 mode :: InferenceMode,
                 result_vars :: List2 OwnershipTypeVariable,
                 allow_guess :: Bool,
                 function_converter_borrows :: Map2 Int (List2 FunctionConverterBorrow),
                 function_converter_borrow_keys :: Map2 Int E.ExprId,
                 call_args :: Map2 E.ExprId (List2 OwnershipTypeVariable) } deriving (Move)

isDebug :: Context -> (Context, Bool)
isDebug context = do
    r <- P.isDebugged context.config context.function_id
    (context, r)

debugPrint :: Context -> String -> Context
debugPrint context msg = do
    (context, r) <- isDebug context
    if r
    then do
        println msg
        context
    else context

getTypeVariableInfoByExprId2 :: Context -> E.ExprId -> (Context, TypeVariableInfo) // FIXME:
getTypeVariableInfoByExprId2 context expr_id = do
    (inference_info, info) <- getTypeVariableInfoByExprId context.inference_info expr_id context.function_id
    (context { inference_info = inference_info }, info)

dumpConstraints :: List2 C.Constraint -> ()
dumpConstraints constraints = do
    println "Constraints:"
    constraints |> List2.iter |> Iterator.forEach (\c -> println c)

getOwnershipValue :: Context -> OwnershipTypeVariable -> (Context, M.OwnershipKind) // FIXME
getOwnershipValue context var = do
    (inference_info, result) <- getOwnership context.inference_info var
    context <- context { inference_info = inference_info }
    case result of
        Some o -> (context, o)
        None -> (context, M.Unknown)

updateOwnership :: Context -> OwnershipTypeVariable -> M.OwnershipKind -> Context
updateOwnership context ownership_var kind = do
    (context, kind) <- case context.mode of
        Partial -> do
            is_result_var <- List2.contains context.result_vars ownership_var
            case (is_result_var, kind) of
                (True, M.Owner) -> (context, kind)
                (True, M.Unknown) -> (context, kind)
                (True, M.Borrower id) -> (context, M.Owner)
                _ -> (context, kind)
        Full -> (context, kind)
    (context, old_kind) <- getOwnershipValue context ownership_var
    if old_kind != kind
    then do
        (inference_info, changed) <- addInferredOwnership context.inference_info ownership_var kind
        context <- context { inference_info = inference_info }
        if changed
        then do
            context <- debugPrint context "UpdateOwnership {} {}" % (ownership_var, kind)
            context { changed_ownership_vars = True }
        else context
    else context

isValidBorrow :: Context -> OwnershipTypeVariable -> E.ExprId -> (Context, Bool)
isValidBorrow context ownership_var expr_id = do
        context <- debugPrint context "isValidBorrow {} {}" % (ownership_var, expr_id)
        is_valid_borrow <- True
        (context, is_valid_borrow) <- case Map2.get context.ownership_expr_map ownership_var of
            Some expr_ids -> checkExprs context is_valid_borrow expr_ids expr_id
            None -> (context, is_valid_borrow)
        if is_valid_borrow
        then case Map2.get context.ownership_group_map ownership_var of
            Some groups -> List2.fold (context, is_valid_borrow) groups (\(context, is_valid_borrow), group -> do
                    case Map2.get context.group_expr_map group of
                        Some expr_ids -> checkExprs context is_valid_borrow expr_ids expr_id
                        None -> (context, is_valid_borrow)
                )
            None -> (context, True)
        else (context, is_valid_borrow)
    where
        checkExprs :: Context -> Bool -> List2 E.ExprId -> E.ExprId -> (Context, Bool)
        checkExprs context is_valid_borrow expr_ids expr_id = List2.fold (context, is_valid_borrow) expr_ids (\(context, is_valid_borrow), dep -> do
            if is_valid_borrow
            then checkExpr context expr_id dep
            else (context, is_valid_borrow))

        checkExpr :: Context -> E.ExprId -> E.ExprId -> (Context, Bool)
        checkExpr context expr_id dep =
            case Map2.get context.invalid_borrow_map dep of
                Some invalid_borrows -> do
                    is_valid_borrow <- not (List2.contains invalid_borrows expr_id)
                    (context, is_valid_borrow)
                None -> (context, True)

isInternal :: Context -> BorrowId -> (Context, Bool)
isInternal context borrow_id = do
    (inference_info, borrow_set) <- getBorrowSet context.inference_info borrow_id
    context <- context { inference_info = inference_info }
    borrows <- borrow_set.borrows |> Set.iter |> List2.toList
    is_internal <- List2.fold True borrows (\is_internal, borrow -> case borrow of
        Internal _ -> is_internal
        _ -> False)
    (context, is_internal)

canPropagateBorrow :: Context -> OwnershipTypeVariable -> BorrowId -> (Context, Bool)
canPropagateBorrow context ownership_var borrow_id = do
    (inference_info, borrow_set) <- getBorrowSet context.inference_info borrow_id
    context <- context { inference_info = inference_info }
    borrows <- borrow_set.borrows |> Set.iter |> List2.toList
    expr_ids <- List2.filterMap borrows (\borrow -> case borrow of
        Local expr_id -> Some expr_id
        _ -> None)
    List2.fold (context, True) expr_ids (\(context, can_propagate), expr_id -> do
        (context, is_valid) <- isValidBorrow context ownership_var expr_id
        (context, can_propagate && is_valid))

getParentKind :: Context -> [OwnershipTypeVariable] -> (Context, M.OwnershipKind)
getParentKind context parents = do
    (context, kinds) <- List.mapS context parents getOwnershipValue
    context <- debugPrint context "getParentKind kinds {}" % kinds
    if List.contains kinds M.Unknown
    then (context, M.Unknown)
    else do
        first_borrower <- List.find kinds (\k -> case k of
                    M.Borrower _ -> True
                    _ -> False)
        case first_borrower of
            Some b -> (context, b)
            None -> (context, M.Owner)

processCallContext :: Context -> E.ExprId -> Int -> OwnershipTypeVariable -> OwnershipTypeVariable -> Option BorrowId -> Context
processCallContext context call_id index from to to_borrow = do
    context <- eraseFunctionConverterBorrow context index
    case Map.get context.call_context_map call_id of
        Some call_context_set -> do
            call_args <- case Map2.get context.call_args call_id of
                Some call_args -> call_args
                None -> panic "Call args not found for call {}" % call_id
            (context, borrows, owners, unknowns) <- if List2.contains call_args from
            then do
                (context, from_kind) <- getOwnershipValue context from
                args <- context.call_args
                context <- debugPrint context "using {} from {} as that is a call_arg {}" % (from_kind, from, args)
                case from_kind of
                    M.Owner -> (context, List2.empty, List2.single from_kind, List2.empty)
                    M.Borrower _ -> (context, List2.single from_kind, List2.empty, List2.empty)
                    M.Unknown -> (context, List2.empty, List2.empty, List2.single from_kind)
            else do
                call_context_set :: C.CallContextSet <- call_context_set // FIXME
                context <- debugPrint context "Call context set {}" % call_context_set
                List.fold (context, List2.empty, List2.empty, List2.empty) call_context_set.call_contexts (\(context, borrows, owners, unknowns), call_context -> do
                        case Map.get call_context.sub_map from of
                            Some parents -> do
                                context <- debugPrint context "Checking parents {}" % parents
                                (context, parent_kind) <- getParentKind context parents
                                context <- debugPrint context "Parent kind {}" % parent_kind
                                case parent_kind of
                                    M.Borrower _ -> do
                                        borrows <- List2.push borrows parent_kind
                                        (context, borrows, owners, unknowns)
                                    M.Owner -> do
                                        owners <- List2.push owners parent_kind
                                        (context, borrows, owners, unknowns)
                                    M.Unknown -> do
                                        unknowns <- List2.push unknowns parent_kind
                                        (context, borrows, owners, unknowns)
                            None -> (context, borrows, owners, unknowns))
            context <- debugPrint context "After checking parents {}/{}/{}" % (borrows, owners, unknowns)
            if not (List2.isEmpty unknowns)
            then context
            else do
                if not (List2.isEmpty owners)
                then do
                    context <- debugPrint context "in some context ownership required, promoting {}" % to
                    updateOwnership context to M.Owner
                else do
                    borrows <- borrows |> List2.sort |> List2.dedup
                    borrows <- List2.map borrows (\borrow -> case borrow of
                                M.Borrower id -> id
                                _ -> panic "Borrow is not a borrow?!")
                    case List2.getLength borrows of
                        0 -> do
                            context <- debugPrint context "Cannot borrow anything, do nothing"
                            context
                        _ -> do
                            (context, can_propagate) <- List2.fold (context, True) borrows (\(context, can_propagate), borrow -> do
                                        (context, c) <- canPropagateBorrow context to borrow
                                        can_propagate <- can_propagate && c
                                        (context, can_propagate))
                            if can_propagate
                            then do
                                (context, contains) <- case to_borrow of
                                    Some to_borrow -> do
                                        List2.fold (context, True) borrows (\(context, contains), borrow -> do
                                            (inference_info, c) <- containsBorrows context.inference_info borrow to_borrow
                                            context <- context { inference_info = inference_info }
                                            contains <- contains  && c
                                            (context, contains))
                                    None -> (context, False)
                                if contains
                                then do
                                    to_borrow <- Option.unwrap to_borrow
                                    borrows <- List2.fold List2.empty borrows (\borrows, borrow -> if borrow == to_borrow
                                        then borrows
                                        else List2.push borrows (FunctionConverterBorrow borrow to_borrow))
                                    context <- debugPrint context "propagation possible to target, borrows {}, adding to {}" % (borrows, index)
                                    function_converter_borrows <- Map2.put context.function_converter_borrows index borrows
                                    context <- context { function_converter_borrows = function_converter_borrows }
                                    context
                                else do
                                    borrows <- case to_borrow of
                                        Some to_borrow -> List2.push borrows to_borrow
                                        None -> borrows
                                    first <- List2.atIndex borrows 0
                                    if List2.getLength borrows == 1
                                    then do
                                        context <- debugPrint context "propagation not possible to target (single), setting borrow {} at {}" % (first,  index)
                                        updateOwnership context to (M.Borrower first) 
                                    else do
                                        (context, merged) <- List2.fold (context, first) borrows (\(context, current), borrow -> do
                                            (inference_info, id) <- mergeBorrowSets context.inference_info current borrow
                                            context <- context { inference_info = inference_info }
                                            (context, id))
                                        borrows <- List2.map borrows (\borrow -> FunctionConverterBorrow borrow merged)
                                        function_converter_borrows <- Map2.put context.function_converter_borrows index borrows
                                        context <- debugPrint context "propagation not possible to target, borrows {}, adding to {}" % (borrows, index)
                                        context <- context { function_converter_borrows = function_converter_borrows }
                                        updateOwnership context to (M.Borrower merged)
                            else do
                                context <- debugPrint context "Cannot propagate one of borrows {}, promote {} to owner" % (borrows, to)
                                updateOwnership context to M.Owner
        None -> do
            context <- debugPrint context "no callcontext for callid {}" % (index)
            updateOwnership context to M.Owner

eraseFunctionConverterBorrow :: Context -> Int -> Context
eraseFunctionConverterBorrow context index = do
    (function_converter_borrows, _) <- Map2.remove context.function_converter_borrows index
    context { function_converter_borrows = function_converter_borrows }

addFunctionConverterBorrow :: Context -> Int -> BorrowId -> BorrowId -> Context
addFunctionConverterBorrow context index a b = do
    context <- debugPrint context "addFunctionConverterBorrow {} {} {}" % (index, a, b)
    function_converter_borrows <- Map2.put context.function_converter_borrows index (List2.single (FunctionConverterBorrow a b))
    context { function_converter_borrows = function_converter_borrows }

processFunctionConverter :: Context -> C.FunctionConverterConstraint -> Int -> Context
processFunctionConverter context converter index = do
    context <- eraseFunctionConverterBorrow context index
    from <- converter.from
    to <- converter.to
    function_converter_borrow_keys <- Map2.put context.function_converter_borrow_keys index converter.call
    context <- context { function_converter_borrow_keys = function_converter_borrow_keys }
    (context, from_kind) <- getOwnershipValue context from
    (context, to_kind) <- getOwnershipValue context to
    context <- debugPrint context "Checking function converter {} {} {} / {} {}" % (converter.call, from, to, from_kind, to_kind)
    case (from_kind, to_kind) of
        (M.Owner, M.Unknown) -> processCallContext context converter.call index from to None
        (M.Borrower a, M.Borrower b) -> do
            if a == b
            then context
            else do
                (context, can_propagate) <- canPropagateBorrow context to a
                if can_propagate
                then do
                    (inference_info, contains) <- containsBorrows context.inference_info a b
                    context <- context { inference_info = inference_info }
                    if contains
                    then do
                        context <- addFunctionConverterBorrow context index a b
                        context
                    else do
                        (inference_info, id) <- mergeBorrowSets context.inference_info a b
                        context <- context { inference_info = inference_info }
                        context <- addFunctionConverterBorrow context index a id
                        updateOwnership context to (M.Borrower id)
                else updateOwnership context to M.Owner
        (M.Borrower a, M.Unknown) -> do
            (context, can_propagate) <- canPropagateBorrow context to a
            if can_propagate
            then do
                (inference_info, id) <- cloneBorrowSet context.inference_info a
                context <- context { inference_info = inference_info }
                context <- addFunctionConverterBorrow context index a id
                updateOwnership context to (M.Borrower id)
            else updateOwnership context to M.Owner
        (M.Owner, M.Borrower b) -> processCallContext context converter.call index from to (Some b)
        (M.Unknown, M.Unknown) if context.allow_guess -> do
            context <- context { allow_guess = False }
            updateOwnership context from M.Owner
        (M.Unknown, _) if context.allow_guess -> do
            context <- context { allow_guess = False }
            updateOwnership context from to_kind
        (_, _) -> context

processFieldAccess :: Context -> C.FieldAccessConstraint -> Context
processFieldAccess context access = do
    receiver_info <- access.receiver_info
    member_info <- access.member_info
    expr_info <- access.expr_info
    (context, receiver_kind) <- getOwnershipValue context receiver_info.ownership_var
    (context, member_kind) <- getOwnershipValue context member_info.ownership_var
    (context, expr_kind) <- getOwnershipValue context expr_info.ownership_var
    context <- debugPrint context "processFieldAccess: expr {} receiverkind {} memberkind {} exprkind {}" % (access.expr_id, receiver_kind, member_kind, expr_kind)
    case (receiver_kind, member_kind) of
        (M.Borrower _, M.Borrower _) -> updateOwnership context expr_info.ownership_var member_kind
        (M.Owner, M.Borrower _) -> updateOwnership context expr_info.ownership_var member_kind
        (M.Borrower _, M.Owner) -> updateOwnership context expr_info.ownership_var receiver_kind
        (M.Owner, M.Owner) -> updateOwnership context expr_info.ownership_var receiver_kind
        (M.Owner, M.Unknown) if expr_kind != M.Unknown -> updateOwnership context member_info.ownership_var expr_kind
        (_, M.Unknown) if context.allow_guess -> do
            context <- context { allow_guess = False }
            updateOwnership context member_info.ownership_var M.Owner
        _ -> context

processConverter :: Context -> C.ConverterConstraint -> Context
processConverter context converter = do
    arg_info <- converter.arg_info
    expr_info <- converter.expr_info
    (context, arg_kind) <- getOwnershipValue context arg_info.ownership_var
    (context, expr_kind) <- getOwnershipValue context expr_info.ownership_var
    context <- debugPrint context "Converter {} {}, {} -> {}" % (arg_kind, expr_kind, arg_info.ownership_var, expr_info.ownership_var)
    case (arg_kind, expr_kind) of
        (M.Owner, M.Unknown) ->
            if converter.borrower
            then do
                (context, valid) <- isValidBorrow context expr_info.ownership_var converter.arg_id
                if valid
                then do
                    (inference_info, id) <- createBorrowSetForExpr context.inference_info converter.arg_id
                    context <- debugPrint context "Borrowing owner at {} {}" % (converter.arg_id, id)
                    context <- context { inference_info = inference_info }
                    updateOwnership context expr_info.ownership_var (M.Borrower id)
                else do
                    updateOwnership context expr_info.ownership_var M.Owner
            else updateOwnership context expr_info.ownership_var arg_kind
        (M.Borrower a, M.Unknown) -> do
            (context, can_propagate) <- canPropagateBorrow context expr_info.ownership_var a
            if can_propagate
            then do
                (inference_info, id) <- cloneBorrowSet context.inference_info a
                context <- context { inference_info = inference_info }
                updateOwnership context expr_info.ownership_var (M.Borrower id)
            else updateOwnership context expr_info.ownership_var M.Owner
        (M.Owner, M.Borrower a) -> do
            if converter.borrower
            then do
                (context, valid) <- isValidBorrow context expr_info.ownership_var converter.arg_id
                if valid
                then do
                    (context, is_internal) <- isInternal context a
                    if is_internal
                    then do
                        (inference_info, id) <- createBorrowSetForExpr context.inference_info converter.arg_id
                        context <- context { inference_info = inference_info }
                        updateOwnership context expr_info.ownership_var (M.Borrower id)
                    else context
                else updateOwnership context expr_info.ownership_var M.Owner
            else updateOwnership context expr_info.ownership_var M.Owner
        (M.Borrower a, M.Borrower b) -> do
            (context, can_propagate) <- canPropagateBorrow context expr_info.ownership_var a
            if can_propagate
            then do
                (inference_info, contains) <- containsBorrows context.inference_info a b
                context <- context { inference_info = inference_info }
                if contains
                then context
                else do
                    (inference_info, id) <- mergeBorrowSets context.inference_info a b
                    context <- context { inference_info = inference_info }
                    updateOwnership context expr_info.ownership_var (M.Borrower id)
            else updateOwnership context expr_info.ownership_var M.Owner
        (M.Unknown, M.Borrower a) -> updateOwnership context arg_info.ownership_var expr_kind
        (M.Unknown, _) if context.allow_guess -> do
            context <- context { allow_guess = False }
            updateOwnership context arg_info.ownership_var M.Owner
        _ -> context

processVariantAccess :: Context -> C.VariantConstraint -> Context
processVariantAccess context variant = do
    var_info <- variant.var_info
    body_info <- variant.body_info
    expr_info <- variant.expr_info
    (context, var_kind) <- getOwnershipValue context var_info.ownership_var
    (context, body_kind) <- getOwnershipValue context body_info.ownership_var
    case (body_kind, var_kind) of
        (_, M.Unknown) -> updateOwnership context var_info.ownership_var body_kind
        (M.Borrower _, M.Owner) -> updateOwnership context var_info.ownership_var body_kind
        _ -> context

processConstraint :: (Context, Int) -> C.Constraint -> (Context, Int)
processConstraint (context, index) constraint = do
    context <- debugPrint context "Processing constraint {}" % constraint
    context <- case constraint of
        C.FieldAccess access -> processFieldAccess context access
        C.Converter converter -> processConverter context converter
        C.Variant variant -> processVariantAccess context variant
        C.FunctionConverter converter -> processFunctionConverter context converter index
    (context, index + 1)

dumpOwnership :: Context -> Context
dumpOwnership context = do
    expr_ids <- Map2.getKeys context.inference_info.expr_type_variables
    function_id <- context.function_id
    expr_ids <- List2.filterMap expr_ids (\(GlobalExprId f_id expr_id) -> if f_id == function_id then Some expr_id else None)
    List2.fold context expr_ids (\context, expr_id -> do
            (context, info) <- getTypeVariableInfoByExprId2 context expr_id
            (context, o1) <- getOwnershipValue context info.ownership_var
            println "dumpOwnership {} {} {}" % (expr_id, info, o1)
            context
        )

processConstraints :: Config -> P.Identity -> InferenceInfo -> List2 C.Constraint ->
                      Map2 E.ExprId (List2 E.ExprId) -> Map2 OwnershipTypeVariable (List2 E.ExprId) ->
                      Map2 GroupTypeVariable (List2 E.ExprId) -> Map2 OwnershipTypeVariable (List2 GroupTypeVariable) ->
                      List2 OwnershipTypeVariable -> Map E.ExprId C.CallContextSet -> InferenceMode -> Map2 E.ExprId (List2 OwnershipTypeVariable) -> InferenceInfo
processConstraints config function_id inference_info constraints invalid_borrow_map ownership_expr_map 
                    group_expr_map ownership_group_map result_vars call_context_map mode call_args = do
    // println "Invalid borrow map {}" % (invalid_borrow_map)
    // println "InferenceInfo {}" % inference_info
    context <- Context config inference_info function_id True invalid_borrow_map
                       ownership_expr_map group_expr_map ownership_group_map call_context_map mode result_vars False Map2.empty Map2.empty call_args
    //dumpConstraints constraints
    context <- loop context <- context do
        context :: Context <- context // FIXME
        if not context.changed_ownership_vars
        then case context.mode of
                Partial -> break context
                Full -> do
                    if context.allow_guess
                    then break context
                    else context { allow_guess = True, changed_ownership_vars = True }
        else do
            context <- context { changed_ownership_vars = False }
            (context, _) <- List2.fold (context, 0) constraints processConstraint
            context
    // println "----------- BEGIN"
    // dumpOwnership context
    // println "----------- END"
    expr_id_map <- Map2.fold Map2.empty context.function_converter_borrow_keys (\expr_id_map, (index, expr_id) -> Map2.add expr_id_map expr_id index)
    (context, function_converter_borrows) <- Map2.mapS context expr_id_map (\context, (expr_id, indices) -> do
            (context, borrows) <- List2.fold (context, List2.empty) indices (\(context, borrows), index -> case Map2.get context.function_converter_borrows index of
                        Some bs -> (context, borrows + bs)
                        None -> (context, borrows))
            (context, expr_id, borrows)
        )
    inference_info <- context.inference_info
    inference_info { function_converter_borrows = function_converter_borrows }
