module Siko.Constants.Iterator {

import Siko.AST.QualifiedName
import Siko.Constants.Util

pub struct IteratorNames {
    pub into_iter_qn: QualifiedName,
    pub next_qn: QualifiedName,
}

pub fn build_iterator_names() -> IteratorNames {
    IteratorNames(
        into_iter_qn: QualifiedName.new_method(m("Std.Iterator.IntoIterator"), m("into_iter")),
        next_qn: QualifiedName.new_method(m("Std.Iterator.Iterator"), m("next")),
    )
}

}
