module Driver where

import Map
import Siko.Parser as P
import IO
import Item as I
import Siko.Syntax.SourceFile
import Siko.Syntax.Module
import Siko.Syntax.Location
import Siko.Syntax.Ident
import Database as DB
import Resolver as R
import Siko.Util.SharedString as SS
import Siko.Resolver.Local
import Siko.Resolver.Export
import Siko.Resolver.Import
import Siko.Resolver.Item as RI

data Driver = { sources :: Map String SourceFile,
                resolver :: R.Resolver,
                db :: DB.Database,
                pending_commands :: [I.Command] }

createDriver :: Driver
createDriver = do
    db <- DB.createDatabase
    db <- DB.addCommandGenerator db I.UnresolvedModuleKind I.CollectLocalItems
    db <- DB.addCommandGenerator db I.LocalItemsKind I.CollectExports
    db <- DB.addCommandGenerator db I.ExportedItemsKind I.ProcessImports
    resolver <- R.createResolver
    Driver Map.empty resolver db []

addModule :: String -> Driver -> Module -> Driver
addModule file_name driver mod = do
    resolver <- R.addModule driver.resolver file_name mod.name
    driver { resolver = resolver }

addSource :: Driver -> String -> Driver
addSource driver file_name = do
    driver <- removeSource driver file_name
    content <- readTextFile file_name
    (source_file, lexer_errors, parser_errors) <- P.parse (FileId 0) file_name content
    driver <- List.fold driver source_file.modules (addModule file_name)
    sources <- Map.put driver.sources file_name source_file
    driver { sources = sources }

removeSource :: Driver -> String -> Driver
removeSource driver file_name = do
    resolver <- R.purgeFile driver.resolver file_name
    driver { resolver = resolver }

addCommand :: Driver -> I.Command -> Driver
addCommand driver cmd = do
    pending_commands <- List.push driver.pending_commands cmd
    driver { pending_commands = pending_commands }

executeCommands :: Driver -> Driver
executeCommands driver = do
    loop driver <- driver do
        driver :: Driver <- driver // FIXME
        if List.isEmpty driver.pending_commands
        then break driver
        else do
            pending_commands <- driver.pending_commands
            pending_commands <- pending_commands |> List.sort |> List.dedup
            driver <- driver { pending_commands = [] }
            List.fold driver pending_commands executeCommand

getExports :: Driver -> SS.SharedString -> Option [RI.Item]
getExports driver name = do
    name <- SS.get name
    key <- I.ExportedItemsKey name
    case DB.getOpt driver.db key of
        Some exported_items -> Some (I.asExportedItems exported_items)
        None -> None

executeCommand :: Driver -> I.Command -> Driver
executeCommand driver cmd = do
    case cmd of
        I.CollectLocalItems key -> do
            mod <- DB.get driver.db key
            mod <- I.asUnresolvedModule mod
            name <- SS.get (getString mod.name)
            local_items <- collectLocals mod
            key <- I.LocalItemsKey name
            item <- I.LocalItems local_items
            addToDb driver key item
        I.CollectExports key -> do
            local_items <- DB.get driver.db key
            local_items <- I.asLocalItems local_items
            name <- I.getModuleName key
            mod <- DB.get driver.db (I.UnresolvedModuleKey name)
            mod <- I.asUnresolvedModule mod
            exported_items <- collectExports local_items mod
            key <- I.ExportedItemsKey name
            item <- I.ExportedItems exported_items
            addToDb driver key item
        I.ProcessImports key -> do
            name <- I.getModuleName key
            mod <- DB.get driver.db (I.UnresolvedModuleKey name)
            mod <- I.asUnresolvedModule mod
            local_items <- DB.get driver.db (I.LocalItemsKey name)
            local_items <- I.asLocalItems local_items
            (imported_items, errors) <- processImports mod (ExportProvider (getExports driver)) local_items
            if List.isEmpty errors
            then do
                module_resolver <- createModuleResolver (SS.create name) imported_items
                driver
            else driver

addToDb :: Driver -> I.Key -> I.Item -> Driver
addToDb driver key item = do
    (db, cmd) <- DB.addItem driver.db key item
    driver <- driver { db = db }
    case cmd of
        Some cmd -> addCommand driver cmd
        None -> driver

commitChanges :: Driver -> Driver
commitChanges driver = do
    (resolver, updates) <- R.processModuleUpdates driver.resolver
    driver <- driver { resolver = resolver }
    driver <- List.fold driver updates (\driver, update ->
        case update of
            R.UpdatedModule unresolved_module -> do
                driver :: Driver <- driver // FIXME
                case Map.get driver.sources unresolved_module.file of
                    Some source_file -> do
                        mod <- List.filter source_file.modules (\mod -> mod.name == unresolved_module.name)
                        mod <- List.atIndex mod 0
                        name <- SS.get (getString mod.name)
                        key <- I.UnresolvedModuleKey name
                        item <- I.UnresolvedModule mod
                        addToDb driver key item
                    None -> panic "Updated module not found in sources!"
            R.RemovedModule name -> do
                key <- I.UnresolvedModuleKey name
                db <- DB.removeItem driver.db key
                driver { db = db }
        )
    executeCommands driver
