module Item where

import Siko.Syntax.Module as M

data ItemKind = UnresolvedModuleKind
              deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Item = UnresolvedModule M.Module deriving (Show, PartialEq, Eq)

data Key = UnresolvedModuleKey String deriving (Show, PartialEq, Eq, PartialOrd, Ord)

getKind :: Item -> ItemKind
getKind item = case item of
    UnresolvedModule _ -> UnresolvedModuleKind