module Siko.MIR.Backend.Ownership.Inference where

import Map
import Siko.Config
import Siko.LIR.Program as LP
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.BorrowChecker
import Siko.MIR.Backend.Ownership.CallContext as CC
import Siko.MIR.Backend.Ownership.Converter
import Siko.MIR.Backend.Ownership.DumpOwnership
import Siko.MIR.Backend.Ownership.EqualityGeneration
import Siko.MIR.Backend.Ownership.ExternProcessor
import Siko.MIR.Backend.Ownership.FunctionInfo
import Siko.MIR.Backend.Ownership.FunctionInfoStore
import Siko.MIR.Backend.Ownership.Inference.ConstraintCollection
import Siko.MIR.Backend.Ownership.Inference.ConstraintProcessor
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.Initializer
import Siko.MIR.Backend.Ownership.Lowering
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Query as Q
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Data as D
import Siko.MIR.Expr as E
import Siko.MIR.Function as F
import Siko.MIR.Identity as I
import Siko.MIR.Program as P
import Siko.MIR.Type as T
import Siko.Trace
import Siko.Util.DependencyProcessor

data Context = { function_info_store :: FunctionInfoStore } deriving (Move)

createRecordCtorFunctionInfo :: T.Type -> FunctionInfo
createRecordCtorFunctionInfo type = case type of
    T.Record id -> do
        record <- Q.getRecord id
        allocator <- createAllocator
        (allocator, result) <- getNextTypeVariableInfo allocator
        ownershipinfos <- []
        (allocator, args, members, ownershipinfos) <- List.fold (allocator, [], [], ownershipinfos) record.fields (\(allocator, args, members, ownershipinfos), field -> do
            (allocator, arg_info) <- getNextTypeVariableInfo allocator
            member <- M.MemberInfo (M.Field field.index) result.arg_group_var arg_info
            members <- List.push members member
            args <- List.push args arg_info
            ownershipinfos <- if Q.isCopyable (T.getIdentity field.type)
            then List.push ownershipinfos (M.OwnershipInfo arg_info.ownership_var M.Owner)
            else ownershipinfos
            (allocator, args, members, ownershipinfos))
        FunctionInfo args result members [] ownershipinfos
    t -> panic "createRecordCtorFunctionInfo: not a record: {}" % t

createVariantctorFunctionInfo :: Int -> T.Type -> FunctionInfo
createVariantctorFunctionInfo index type = case type of
    T.Adt id -> do
        adt <- Q.getAdt id
        allocator <- createAllocator
        (allocator, result) <- getNextTypeVariableInfo allocator
        (allocator, args, members, ownershipinfos, current) <- List.fold (allocator, [], [], [], 0) adt.variants (\(allocator, args, members, ownershipinfos, current), variant -> case variant.type of
            T.Record id -> do
                (allocator, record_result) <- getNextTypeVariableInfo allocator
                ownershipinfos <- List.push ownershipinfos (M.OwnershipInfo record_result.ownership_var M.Owner)
                members <- List.push members (M.MemberInfo (M.Variant current) result.arg_group_var record_result)
                if current == index
                then do
                    record <- Q.getRecord id
                    (allocator, args, members, ownershipinfos) <- List.fold (allocator, args, members, ownershipinfos) record.fields (\(allocator, args, members, ownershipinfos), field -> do
                        (allocator, arg_info) <- getNextTypeVariableInfo allocator
                        member <- M.MemberInfo (M.Field field.index) record_result.arg_group_var arg_info
                        members <- List.push members member
                        args <- List.push args arg_info
                        ownershipinfos <- if Q.isCopyable (T.getIdentity field.type)
                        then List.push ownershipinfos (M.OwnershipInfo arg_info.ownership_var M.Owner)
                        else ownershipinfos
                        (allocator, args, members, ownershipinfos))
                    (allocator, args, members, ownershipinfos, current + 1)
                else (allocator, args, members, ownershipinfos, current + 1)
            _ -> panic "createVariantctorFunctionInfo: not a record")
        FunctionInfo args result members [] ownershipinfos
    _ -> panic "createVariantctorFunctionInfo: not an adt"

processFunctionInfo :: Context -> FunctionInfo -> I.Identity -> (Context, Bool)
processFunctionInfo context function_info function_id = do
    //trace "processFunctionInfo - processing {}" % function_id
    function_info <- normalizeFunctionInfo function_info
    //trace "processFunctionInfo - normalization done"
    function_info_store <- context.function_info_store
    config <- getConfig ()
    if config.print_function_info
    then println "Function info added for {}/{}" % (function_id, function_info)
    else ()
    (function_info_store, added) <- addFunctionInfo function_info_store function_id function_info
    //trace "processFunctionInfo - added done"
    context <- context { function_info_store = function_info_store }
    (context, added)

processFunction :: Context ->
                   [I.Identity] ->
                   Option InferenceInfo ->
                   I.Identity -> (Context, Bool, Option InferenceInfo)
processFunction context group inference_info function_id = do
    function <- Q.getFunction function_id
    case function.kind of
        F.Normal info -> do
            //trace "Ownership inference - processing {}" % function_id
            (context, inference_info) <- case inference_info of
                Some inference_info -> (context, inference_info)
                None -> do
                    arg_count <- getLength function.type.args
                    inference_info <- createInferenceInfo
                    inference_info <- addFunctionInferenceInfo inference_info function_id arg_count
                    //trace "initializeTypeVariables {}" % function_id
                    inference_info <- initializeTypeVariables inference_info function_id info.body
                    function_info_store <- context.function_info_store
                    //trace "processEqualities {}" % function_id
                    (equals, inference_info) <- processFunctionEqualities function_id group [] inference_info function_info_store info.body
                    inference_info <- processEqualities equals inference_info
                    inference_info <- updateOwnershipDepMap inference_info
                    inference_info <- updateGroupDependencyMapInfo inference_info
                    inference_info <- CC.createBaseCallContexts inference_info
                    converter_merge_info_base <- createConverterMergeInfoBase inference_info.converters
                    inference_info <- createFunctionInfoBase inference_info function_id converter_merge_info_base
                    (context, inference_info)
            //trace "checkBorrows {}" % function_id
            borrow_info <- checkBorrows info.body
            //trace "inferOwnership {}" % function_id
            (inference_info, constraints, invalid_borrow_map, ownership_expr_map, group_expr_map, ownership_group_map, result_vars, call_context_map, call_args) <- collectConstraints function_id borrow_info inference_info info.body
            inference_info <- processConstraints function_id
                                                 inference_info
                                                 constraints
                                                 invalid_borrow_map
                                                 ownership_expr_map
                                                 group_expr_map
                                                 ownership_group_map
                                                 result_vars
                                                 call_context_map
                                                 Partial
                                                 call_args
            //trace "Processing {}" % function_id
            no_return <- T.isNever function.type.result
            function_info <- toFunctionInfo inference_info function_id no_return
            if P.isDebugged function_id
            then do
                println "Function info {}" % function_info
                println "Inference info {}" % inference_info
                dumpOwnership inference_info function_id info.body
            else ()
            function_info <- enforceUnknownArgOwnership function_info
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, Some inference_info)
        F.VariantCtor index -> do
            function_info <- createVariantctorFunctionInfo index function.type.result
            //trace2 "Variant ctor {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)
        F.RecordCtor -> do
            function_info <- createRecordCtorFunctionInfo function.type.result
            //trace2 "Record ctor {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)
        F.Extern type_mapping -> do
            function_info <- createExternFunctionInfo function_id function.type type_mapping
            //trace2 "Extern {} = {}" % (function_id, function_info)
            (context, added) <- processFunctionInfo context function_info function_id
            (context, added, None)

processFunctionGroup :: Int ->
                        Int ->
                        Context ->
                        [I.Identity] -> (Int, Context)
processFunctionGroup index group_count context group = do
    trace2 "processFunctionGroup {}/{} ({}%) {}" % (index, group_count, index * 100 / group_count, group)
    if getLength group == 1
    then do
        function_id <- atIndex group 0
        (context, _, _) <- processFunction context group None function_id
        (index + 1, context)
    else do
        inference_info <- prepareInferenceInfo context.function_info_store group
        loop (context, inference_info) <- (context, Some inference_info) do
            (context, more, inference_info) <- List.fold (context, False, inference_info) group (\(context, more, inference_info), function_id -> do
                (context, added, inference_info) <- processFunction context group inference_info function_id
                more <- if added then True else more
                (context, more, inference_info))
            if more
            then (context, inference_info)
            else break (index + 1, context)
    where
        prepareInferenceInfo :: FunctionInfoStore -> [I.Identity] -> InferenceInfo
        prepareInferenceInfo function_info_store group = do
            inference_info <- createInferenceInfo
            inference_info <- List.fold inference_info group (\inference_info, function_id -> do
                function <- Q.getFunction function_id
                case function.kind of
                    F.Normal info -> do
                        arg_count <- getLength function.type.args
                        inference_info <- addFunctionInferenceInfo inference_info function_id arg_count
                        inference_info <- initializeTypeVariables inference_info function_id info.body
                        inference_info
                    _ -> panic "Groupped function is not normal!")
            (equals, inference_info) <- List.fold ([], inference_info) group (\(equals, inference_info), function_id -> do
                function <- Q.getFunction function_id
                case function.kind of
                    F.Normal info -> processFunctionEqualities function_id group equals inference_info function_info_store info.body
                    _ -> panic "Groupped function is not normal!")
            inference_info <- processEqualities equals inference_info
            converter_merge_info_base <- createConverterMergeInfoBase inference_info.converters
            inference_info <- updateOwnershipDepMap inference_info
            inference_info <- updateGroupDependencyMapInfo inference_info
            inference_info <- List.fold inference_info group (\inference_info, function_id -> createFunctionInfoBase inference_info function_id converter_merge_info_base)
            inference_info <- CC.createBaseCallContexts inference_info
            inference_info

processProgram :: [DependencyGroup I.Identity] -> LP.Program
processProgram function_groups = do
    trace "Ownership inference started"
    context <- Context createFunctionInfoStore
    group_count <- getLength function_groups
    (_, context) <- List.fold (1, context) function_groups (\(index, context), group -> processFunctionGroup index group_count context group.items)
    trace "Ownership inference ended"
    trace "Lowering started"
    lir_program <- lowerProgram context.function_info_store
    trace "Lowering ended"
    lir_program
