module Siko.MIR.Backend.Lowering.TypeLoweringInfo where

import Map
import Map
import Set
import Siko.MIR.Backend.Allocator
import Siko.MIR.Backend.Duplicator
import Siko.MIR.Backend.Lowering.FunctionLoweringInfo
import Siko.MIR.Backend.Lowering.LoweringDataProvider
import Siko.MIR.Backend.Lowering.LoweringInfo.Filter
import Siko.MIR.Backend.Lowering.LoweringInfo.FilterInfo
import Siko.MIR.Backend.MemberInfo as M
import Siko.MIR.Backend.Ownership.Borrow
import Siko.MIR.Backend.OwnershipDependencyMap
import Siko.MIR.Backend.TypeVariableInfo

data TypeLoweringInfo = { members :: [M.MemberInfo],
                          root :: TypeVariableInfo,
                          ownershipinfos :: [M.OwnershipInfo],
                          allocator :: Allocator
                        } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

createTypeLoweringInfoFromInferenceInfo a :: (LoweringDataProvider a) => a -> TypeVariableInfo -> FilterInfo -> TypeLoweringInfo
createTypeLoweringInfoFromInferenceInfo provider root filter_info = do
    //println "Creating type lowering info"
    lowering_info <- TypeLoweringInfo (getMembers provider) root (getOwnershipInfo provider) (getAllocator provider)
    filterTypeLoweringInfo lowering_info [root] filter_info

createTypeLoweringInfoFromFunctionLoweringInfo :: FunctionLoweringInfo -> TypeVariableInfo -> FilterInfo -> TypeLoweringInfo
createTypeLoweringInfoFromFunctionLoweringInfo lowering_info root filter_info = do
    //println "Creating type lowering info"
    output <- TypeLoweringInfo lowering_info.members root lowering_info.ownershipinfos lowering_info.allocator
    filterTypeLoweringInfo output [root] filter_info

createTypeLoweringInfoFromTypeLoweringInfo :: TypeLoweringInfo -> TypeVariableInfo -> FilterInfo -> TypeLoweringInfo
createTypeLoweringInfoFromTypeLoweringInfo lowering_info root filter_info = do
    //println "Creating type lowering info"
    output <- TypeLoweringInfo lowering_info.members root lowering_info.ownershipinfos lowering_info.allocator
    filterTypeLoweringInfo output [root] filter_info

normalizeRef :: TypeLoweringInfo -> (TypeLoweringInfo, Option BorrowId)
normalizeRef lowering_info = do
    ownershipinfos <- lowering_info.ownershipinfos
    rootvar <- lowering_info.root.ownership_var
    (ownershipinfos, ref, found) <- List.fold ((List.withCapacity (List.getLength ownershipinfos)), None, False) ownershipinfos (\(ownershipinfos, ref, found), ownershipinfo -> normalize rootvar (ownershipinfos, ref, found) ownershipinfo)
    ownershipinfos <- if not found
    then List.push ownershipinfos (M.OwnershipInfo rootvar M.Owner)
    else ownershipinfos
    lowering_info <- lowering_info { ownershipinfos = ownershipinfos }
    (lowering_info, ref)
    where
        normalize rootvar (ownershipinfos, ref, found) ownershipinfo = case ownershipinfo of
            M.OwnershipInfo v M.Unknown -> if v == rootvar
                then (List.push ownershipinfos (M.OwnershipInfo v M.Owner), None, True)
                else (List.push ownershipinfos (M.OwnershipInfo v M.Owner), ref, found)
            M.OwnershipInfo v (M.Borrower id) -> if v == rootvar
                then (List.push ownershipinfos (M.OwnershipInfo v M.Owner), Some id, True)
                else (List.push ownershipinfos ownershipinfo, ref, found)
            M.OwnershipInfo v M.Owner -> if v == rootvar
                then (List.push ownershipinfos ownershipinfo, None, True)
                else (List.push ownershipinfos ownershipinfo, ref, found)

createEmptyTypeLoweringInfo :: TypeLoweringInfo
createEmptyTypeLoweringInfo = do
    allocator <- createAllocator
    (allocator, root) <- getNextTypeVariableInfo allocator
    TypeLoweringInfo [] root [M.OwnershipInfo root.ownership_var M.Owner] allocator

getInfoForField :: TypeLoweringInfo -> Int -> Option TypeVariableInfo
getInfoForField lowering_info index = do
    member <- List.filter lowering_info.members (\member -> case member.kind of
        M.Field i -> i == index && lowering_info.root.arg_group_var == member.root
        _ -> False)
    case List.head member of
        Some m -> Some m.info
        None -> None

getLoweringInfoForField :: TypeLoweringInfo -> Int -> FilterInfo -> TypeLoweringInfo
getLoweringInfoForField lowering_info index filter_info = do
    case getInfoForField lowering_info index of
        Some info -> createTypeLoweringInfoFromTypeLoweringInfo lowering_info info filter_info
        None -> createEmptyTypeLoweringInfo

getLoweringInfoForVariant :: TypeLoweringInfo -> Int -> FilterInfo -> TypeLoweringInfo
getLoweringInfoForVariant lowering_info index filter_info = do
    variant <- List.filter lowering_info.members (\member -> case member.kind of
        M.Variant i -> i == index && lowering_info.root.arg_group_var == member.root
        _ -> False)
    case List.head variant of
        Some m -> createTypeLoweringInfoFromTypeLoweringInfo lowering_info m.info filter_info
        None -> createEmptyTypeLoweringInfo

getLoweringInfoForExtern :: TypeLoweringInfo ->
                            Int ->
                            FilterInfo ->
                            Option TypeVariableInfo -> TypeLoweringInfo
getLoweringInfoForExtern lowering_info index filter_info implicit_info = do
    info <- case implicit_info of
        Some info -> info
        None -> lowering_info.root
    variant <- List.filter lowering_info.members (\member -> case member.kind of
        M.Extern i -> i == index && info.arg_group_var == member.root
        _ -> False)
    case List.head variant of
        Some m -> createTypeLoweringInfoFromTypeLoweringInfo lowering_info m.info filter_info
        None -> createEmptyTypeLoweringInfo
