module Main {

struct Foo {}

fn foo() -> (Foo, Foo) {
    // this must be parsed as an if expression in a standalone expr statement
    // otherwise it will parsed as the if is the receiver for a dynamic function call
    // and the tuples are the args
    if True {

    }
    (Foo(), Foo())
}

fn foo2() -> (Foo, Foo) {
    // this must be parsed as a match expression in a standalone expr statement
    // otherwise it will parsed as the match is the receiver for a dynamic function call
    // and the tuples are the args
    match True {
        _ => ()
    }
    (Foo(), Foo())
}

fn foo3() -> (Foo, Foo) {
    // this must be parsed as a block expression in a standalone expr statement
    // otherwise it will parsed as the block is the receiver for a dynamic function call
    // and the tuples are the args
    {
        Foo();
    }
    (Foo(), Foo())
}

fn main() {

}

}