module Siko.Util.DependencyProcessorLinear where

import Map
import Siko.Config
import Siko.Trace
import Siko.Util.SCC as SCC

data DependencyGroup a = { items :: List a } deriving (Show)

createIdMaps a :: (PartialEq a, Ord a) => SCC.Graph -> Map a (List a) -> (SCC.Graph, Map a SCC.NodeId, Map SCC.NodeId a)
createIdMaps graph all_dependencies = do
        keys <- getKeys all_dependencies
        (graph, item_id_map) <- List.fold (graph, Map.empty) keys mapKey
        id_item_map <- Map.fold Map.empty item_id_map (\id_item_map, (k, v) -> Map.put id_item_map v k)
        (graph, item_id_map, id_item_map)
    where
        mapKey a :: (PartialEq a, Ord a) => (SCC.Graph, Map a SCC.NodeId) -> a -> (SCC.Graph, Map a SCC.NodeId)
        mapKey (graph, id_map) id = do
            (graph, _, id_map) <- Map.addS graph id id_map (\graph, id -> SCC.addNode graph)
            (graph, id_map)

initGraph a :: (PartialEq a, Ord a) => SCC.Graph -> Map a SCC.NodeId -> Map a (List a) -> (Map a SCC.NodeId, SCC.Graph)
initGraph graph item_id_map all_dependencies =
    Map.fold (item_id_map, graph) all_dependencies processDeps
        where
            processDeps a :: (PartialEq a, Ord a) => (Map a SCC.NodeId, SCC.Graph) -> (a, List a) -> (Map a SCC.NodeId, SCC.Graph)
            processDeps (item_id_map, graph) (item, deps) = do
                List.fold (item_id_map, graph) deps (processDep item)

            processDep a :: (PartialEq a, Ord a) => a -> (Map a SCC.NodeId, SCC.Graph) -> a -> (Map a SCC.NodeId, SCC.Graph)
            processDep item (item_id_map, graph) dep = do
                item <- Option.unwrap (get item_id_map item)
                dep <- Option.unwrap (get item_id_map dep)
                (item_id_map, SCC.addNeighbour graph item dep)

processDependencies a :: (PartialEq a, Ord a, Show a) => Config -> Map a (List a) -> List (DependencyGroup a)
processDependencies config all_dependencies = do
        //trace config "new processDependencies {}" % getSize all_dependencies
        graph <- SCC.createGraph
        (graph, item_id_map, id_item_map) <- createIdMaps graph all_dependencies
        (_, graph) <- initGraph graph item_id_map all_dependencies
        sccs <- SCC.collectSCCs graph
        (_, ordered_groups) <- List.mapS id_item_map sccs mapSCC
        //trace config "new processDependencies done"
        ordered_groups
    where
        mapSCC a :: Map SCC.NodeId a -> List SCC.NodeId -> (Map SCC.NodeId a, DependencyGroup a)
        mapSCC id_item_map scc = do
            (id_item_map, items) <- List.mapS id_item_map scc (\id_item_map, id -> do
                item <- Option.unwrap (Map.get id_item_map id)
                (id_item_map, item))
            (id_item_map, DependencyGroup items)