module Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.FilterInfo where

import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessorLinear
import Siko.MIR.Backend.Ownership.GroupDependencyMap
import Siko.MIR.Backend.Ownership.OwnershipDependencyMap
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.OrderedDependencyMap

import Map
import Map
import Set

data FilterInfo = { ordered_dep_map :: Map GroupTypeVariable (List TypeVariableInfo),
                    ownership_dep_map :: Map GroupTypeVariable (List OwnershipTypeVariable),
                    deps_map :: Map GroupTypeVariable (List TypeVariableInfo),
                    group_index_map :: Map TypeVariableInfo Int,
                    group_borrow_map :: Map Int Bool,
                    group_dep_map :: Map Int (List Int),
                    groups :: List (DependencyGroup TypeVariableInfo)
                   }

buildFilterInfoFromTypeLoweringInfo :: Config -> TypeLoweringInfo -> (TypeLoweringInfo, FilterInfo)
buildFilterInfoFromTypeLoweringInfo config lowering_info = do
    (members, ownershipinfos, filter_info) <- buildFilterInfo config lowering_info.members lowering_info.ownershipinfos ([lowering_info.root])
    (lowering_info { members = members, ownershipinfos = ownershipinfos }, filter_info)

buildFilterInfoFromFunctionLoweringInfo :: Config -> FunctionLoweringInfo -> (FunctionLoweringInfo, FilterInfo)
buildFilterInfoFromFunctionLoweringInfo config lowering_info = do
    (members, ownershipinfos, filter_info) <- buildFilterInfo config lowering_info.members lowering_info.ownershipinfos (List.push lowering_info.args lowering_info.result)
    (lowering_info { members = members, ownershipinfos = ownershipinfos }, filter_info)

buildFilterInfo :: Config -> List M.MemberInfo -> List M.OwnershipInfo -> List TypeVariableInfo -> (List M.MemberInfo, List M.OwnershipInfo, FilterInfo)
buildFilterInfo config members ownershipinfos sources = do
    (members, ordered_dep_map) <- getOrderedDependencyMap members
    (members, ownership_dep_map) <- calculateOwnershipDepMap config members
    (members, deps_map) <- M.getInfoDependencyMap members
    kind_map <- M.toOwnershipKind ownershipinfos
    (members, info_dep_map, deps_map) <- getInfoDependencyMap sources members deps_map
    groups <- processDependencies config info_dep_map
    // println "-------------"
    // println "sources {}" % sources
    // println "members {}" % members
    // println "kind_map {}" % kind_map
    // println "Groups {}" % groups
    (groups, group_index_map) <- getGroupIndexMap groups
    //println "group_index_map {}" % group_index_map
    (kind_map, info_dep_map, group_index_map, group_borrow_map) <- getGroupBorrowMap groups info_dep_map kind_map group_index_map
    //println "group_borrow_map {}" % group_borrow_map
    (group_index_map, info_dep_map, group_dep_map) <- loop (group_index_map, info_dep_map, group_dep_map, group_index) <- (group_index_map, info_dep_map, Map.empty, 0) do
        if group_index >= List.getLength groups
        then break (group_index_map, info_dep_map, group_dep_map)
        else do
            group <- List.atIndex groups group_index
            (group_index_map, info_dep_map, group_dep_map) <- getGroupDepMap group group_index info_dep_map group_index_map group_dep_map
            (group_index_map, info_dep_map, group_dep_map, group_index + 1)
    group_dep_map <- Map.map group_dep_map (\(k, v) -> (k, v |> List.sort |> List.dedup))
    //println "group_dep_map {}" % group_dep_map
    filter_info <- FilterInfo ordered_dep_map ownership_dep_map deps_map group_index_map group_borrow_map group_dep_map groups
    (members, ownershipinfos, filter_info)

getGroupIndexMap a :: (Ord a) => List (DependencyGroup a) -> (List (DependencyGroup a), Map a Int)
getGroupIndexMap groups =
    loop (groups, group_index_map, index) <- (groups, Map.empty, 0) do
        if index >= List.getLength groups
        then break (groups, group_index_map)
        else do
            group :: DependencyGroup a <- List.atIndex groups index // FIXME: type annotation
            group_index_map <- List.fold group_index_map group.items (\group_index_map, item -> do
                Map.put group_index_map item index)
            (groups, group_index_map, index + 1)

getInfoDependencyMap :: List TypeVariableInfo -> List M.MemberInfo -> Map GroupTypeVariable (List TypeVariableInfo) ->
                        (List M.MemberInfo, Map TypeVariableInfo (List TypeVariableInfo), Map GroupTypeVariable (List TypeVariableInfo))
getInfoDependencyMap sources members deps_map = do
    full_info_deps_map <- Map.empty
    (deps_map, full_info_deps_map) <- List.fold (deps_map, full_info_deps_map) sources (\(deps_map, full_info_deps_map), source -> do
        full_info_deps_map <- case Map.get deps_map source.arg_group_var of
            Some deps -> Map.put full_info_deps_map source deps
            None -> Map.put full_info_deps_map source List.empty
        (deps_map, full_info_deps_map))
    (deps_map, full_info_deps_map) <- List.fold (deps_map, full_info_deps_map) members (\(deps_map, full_info_deps_map), member -> do
        info <- member.info
        full_info_deps_map <- case Map.get deps_map info.arg_group_var of
            Some deps -> Map.put full_info_deps_map info deps
            None -> Map.put full_info_deps_map info List.empty
        (deps_map, full_info_deps_map))
    (members, full_info_deps_map, deps_map)

isVarBorrower :: Map OwnershipTypeVariable M.OwnershipKind -> OwnershipTypeVariable -> (Map OwnershipTypeVariable M.OwnershipKind, Bool)
isVarBorrower kind_map var =
    case Map.get kind_map var of
        Some (M.Borrower _) -> (kind_map, True)
        _ -> (kind_map, False)

getGroupIndex :: Map TypeVariableInfo Int -> TypeVariableInfo -> (Map TypeVariableInfo Int, Int)
getGroupIndex group_index_map info = do
    case Map.get group_index_map info of
        Some index -> (group_index_map, index)
        None -> panic "Info not found in group_index_map"

getGroupIndex2 :: FilterInfo -> TypeVariableInfo -> (FilterInfo, Int) // FIXME
getGroupIndex2 filter_info info = do
    case Map.get filter_info.group_index_map info of
        Some index -> (filter_info, index)
        None -> panic "Info not found in group_index_map"

isGroupBorrower :: List TypeVariableInfo ->
                   Map OwnershipTypeVariable M.OwnershipKind ->
                   Map TypeVariableInfo (List TypeVariableInfo) ->
                   Map TypeVariableInfo Int ->
                   Map Int Bool ->
                   (Map OwnershipTypeVariable M.OwnershipKind,
                    Map TypeVariableInfo (List TypeVariableInfo),
                    Map TypeVariableInfo Int,
                    Map Int Bool,
                    Bool)
isGroupBorrower group_items kind_map info_dep_map group_index_map group_borrow_map =
    List.fold (kind_map, info_dep_map, group_index_map, group_borrow_map, False) group_items (\(kind_map, info_dep_map, group_index_map, group_borrow_map, borrower), item -> do
        (kind_map, b) <- isVarBorrower kind_map item.ownership_var
        borrower <- borrower || b
        case Map.get info_dep_map item of
            Some deps -> List.fold (kind_map, info_dep_map, group_index_map, group_borrow_map, borrower) deps (\(kind_map, info_dep_map, group_index_map, group_borrow_map, borrower), dep -> do
                borrower <- if List.contains group_items dep
                then borrower
                else case Map.get group_index_map dep of
                    Some index -> do
                        case Map.get group_borrow_map index of
                            Some b -> borrower || b
                            None -> panic "Group index not found in group_borrow_map"
                    None -> panic "Info not found in group_index_map"
                (kind_map, info_dep_map, group_index_map, group_borrow_map, borrower))
            None -> panic "Info not found in info_dep_map")


getGroupBorrowMap :: List (DependencyGroup TypeVariableInfo) ->
                     Map TypeVariableInfo (List TypeVariableInfo) ->
                     Map OwnershipTypeVariable M.OwnershipKind ->
                     Map TypeVariableInfo Int ->
                     (Map OwnershipTypeVariable M.OwnershipKind,
                      Map TypeVariableInfo (List TypeVariableInfo),
                      Map TypeVariableInfo Int,
                      Map Int Bool)
getGroupBorrowMap groups info_dep_map kind_map group_index_map = do
    loop (kind_map, info_dep_map, group_index_map, group_borrow_map, index) <- (kind_map, info_dep_map, group_index_map, Map.empty, 0) do
        if index >= List.getLength groups
        then break (kind_map, info_dep_map, group_index_map, group_borrow_map)
        else do
            group <- List.atIndex groups index
            (kind_map, info_dep_map, group_index_map, group_borrow_map, borrower) <- isGroupBorrower group.items kind_map info_dep_map group_index_map group_borrow_map
            group_borrow_map <- Map.put group_borrow_map index borrower
            (kind_map, info_dep_map, group_index_map, group_borrow_map, index + 1)

getGroupDepMap :: DependencyGroup TypeVariableInfo ->
                  Int ->
                  Map TypeVariableInfo (List TypeVariableInfo) ->
                  Map TypeVariableInfo Int ->
                  Map Int (List Int) ->
                  (Map TypeVariableInfo Int, Map TypeVariableInfo (List TypeVariableInfo), Map Int (List Int))
getGroupDepMap group group_index info_dep_map group_index_map group_dep_map = do
    List.fold (group_index_map, info_dep_map, group_dep_map) group.items (\(group_index_map, info_dep_map, group_dep_map), item ->
        case Map.get info_dep_map item of
            Some deps -> List.fold (group_index_map, info_dep_map, group_dep_map) deps (\(group_index_map, info_dep_map, group_dep_map), dep -> do
                (group_index_map, index) <- getGroupIndex group_index_map dep
                group_dep_map <- if index == group_index
                then group_dep_map
                else Map.add group_dep_map group_index index
                (group_index_map, info_dep_map, group_dep_map))
            None -> (group_index_map, info_dep_map, group_dep_map))

collectBorrows :: FilterInfo -> List TypeVariableInfo -> Int -> (FilterInfo, List TypeVariableInfo)
collectBorrows filter_info relevants group_index = do
    //println "collectBorrows: group_index {}" % group_index
    case Map.get filter_info.group_borrow_map group_index of
        Some True -> do
            group <- List.atIndex filter_info.groups group_index
            relevants <- relevants + group.items
            case Map.get filter_info.group_dep_map group_index of
                Some deps -> List.fold (filter_info, relevants) deps (\(filter_info, relevants), dep -> do
                    //println "collectBorrows: {} = dep {}" % (group_index, dep)
                    collectBorrows filter_info relevants dep)
                None -> (filter_info, relevants)
        _ -> (filter_info, relevants)

getRelevants :: FilterInfo -> List TypeVariableInfo -> (FilterInfo, List TypeVariableInfo)
getRelevants filter_info sources = do
    (filter_info, relevants) <- List.fold (filter_info, sources) sources (\(filter_info, relevants), source -> do
        (filter_info, group_index) <- getGroupIndex2 filter_info source
        (filter_info, relevants) <- collectBorrows filter_info relevants group_index
        (filter_info, relevants))
    (filter_info, relevants)