module Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.Filter where

import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessorLinear
import Siko.MIR.Backend.Ownership.GroupDependencyMap
import Siko.MIR.Backend.Ownership.OwnershipDependencyMap
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.OrderedDependencyMap
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.FilterInfo

import Map
import Map
import Set

filterMember :: List TypeVariableInfo -> List GroupTypeVariable -> M.MemberInfo -> Bool
filterMember infos vars member = List.contains infos member.info && List.contains vars member.root

filterTypeLoweringInfo :: Config -> TypeLoweringInfo -> List TypeVariableInfo -> FilterInfo -> (TypeLoweringInfo, FilterInfo)
filterTypeLoweringInfo config lowering_info sources filter_info = do
    //trace config "------------ start filterInfo {} / {}-----------" % (lowering_info, sources)
    (members, ownershipinfos, allocator, filter_info) <- filterLoweringInfo config sources lowering_info.members lowering_info.ownershipinfos filter_info
    lowering_info <- lowering_info { members = members, ownershipinfos = ownershipinfos, allocator = allocator }
    //trace config "------------ end filterInfo {} / {}-----------" % (lowering_info, sources)
    (lowering_info, filter_info)

filterFunctionLoweringInfo :: Config -> FunctionLoweringInfo -> List TypeVariableInfo -> FilterInfo -> (FunctionLoweringInfo, FilterInfo)
filterFunctionLoweringInfo config lowering_info sources filter_info = do
    //trace config "------------ start filterInfo {} / {}-----------" % (lowering_info, sources)
    (members, ownershipinfos, allocator, filter_info) <- filterLoweringInfo config sources lowering_info.members lowering_info.ownershipinfos filter_info
    lowering_info <- lowering_info { members = members, ownershipinfos = ownershipinfos, allocator = allocator }
    //trace config "------------ end filterInfo {} / {}-----------" % (lowering_info, sources)
    (lowering_info, filter_info)

filterLoweringInfo :: Config -> List TypeVariableInfo ->
                      List M.MemberInfo -> List M.OwnershipInfo ->
                      FilterInfo ->
                      (List M.MemberInfo, List M.OwnershipInfo, Allocator, FilterInfo)
filterLoweringInfo config sources members ownershipinfos filter_info = do
    (filter_info, relevants) <- getRelevants filter_info sources
    //println "borrower_map {}" % borrower_map
    //println "relevants {}" % relevants
    group_vars <- List.map relevants (\info -> info.arg_group_var)
    ownership_vars <- List.map relevants (\info -> info.ownership_var)
    members <- List.filter members (filterMember relevants group_vars)
    (_, ownershipinfos) <- List.filterS ownership_vars ownershipinfos M.filterOwnershipInfo
    allocator <- List.fold createAllocator members (\allocator, m -> do
            allocator <- addGroupTypeVariable allocator m.root
            allocator <- addTypeVariableInfo allocator m.info
            allocator)
    allocator <- List.fold allocator sources (\allocator, info -> addTypeVariableInfo allocator info)
    allocator <- List.fold allocator ownershipinfos (\allocator, o -> case o of
        M.OwnershipInfo _ (M.Borrower id) -> addBorrowId allocator id
        _ -> allocator)
    (members, ownershipinfos, allocator, filter_info)