module Siko.MIR.Backend.Ownership.Lowering.Expr where

import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.FilterInfo
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.Normalizer
import Siko.MIR.Backend.Ownership.Lowering.Context
import Siko.MIR.Backend.Ownership.Lowering.Naming
import Siko.MIR.Backend.Ownership.Lowering.Type
import Siko.MIR.Backend.Ownership.InferenceInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Expr as ME
import Siko.MIR.Data as MD
import Siko.MIR.Function as MF
import Siko.MIR.Type as MT
import Siko.MIR.Program as MP
import Siko.LIR.Type as LT
import Siko.LIR.Expr as LE

import Map

data LoweringContext = { function_id :: MP.Identity,
                         inference_info :: InferenceInfo,
                         borrowers :: List ME.ExprId,
                         filter_info :: FilterInfo,
                       }

getOwnershipValue :: LoweringContext -> OwnershipTypeVariable -> (LoweringContext, M.OwnershipKind) // FIXME
getOwnershipValue lowering_context var = do
    (inference_info, result) <- getOwnership lowering_context.inference_info var
    lowering_context <- lowering_context { inference_info = inference_info }
    case result of
        Some o -> (lowering_context, o)
        None -> panic "Ownership value not found for {}" % var

lowerVar :: ME.Var -> LE.Var
lowerVar var = case var of
    ME.Named n -> LE.Named n
    ME.Temp i -> LE.Temp i
    ME.Arg i -> LE.Arg i
    ME.FnArg _ -> panic "FnArg found in lowering"

lowerRangeKind :: ME.RangeKind -> LE.RangeKind
lowerRangeKind range_kind = case range_kind of
    ME.Inclusive -> LE.Inclusive
    ME.Exclusive -> LE.Exclusive

lowerChecker :: TypeLoweringInfo -> Context -> ME.Checker -> (Context, LE.Checker)
lowerChecker lowering_info context checker = do
    case checker of
        ME.IntegerChecker lit -> (context, LE.IntegerChecker lit)
        ME.StringChecker lit -> (context, LE.StringChecker lit)
        ME.CharChecker lit -> (context, LE.CharChecker lit)
        ME.CharRangeChecker s e kind -> (context, LE.CharRangeChecker s e (lowerRangeKind kind))
        ME.VariantChecker index var ty -> do
            (lowering_info, _) <- normalizeRef lowering_info
            (context, type) <- lowerType context lowering_info ty
            (context, LE.VariantChecker index (lowerVar var) type)
        ME.WildcardChecker -> (context, LE.WildcardChecker)

lowerCase :: (LoweringContext, TypeLoweringInfo, Context) -> ME.Case -> ((LoweringContext, TypeLoweringInfo, Context), LE.Case)
lowerCase (lowering_context, lowering_info, context) c = do
    (context, checker) <- lowerChecker lowering_info context c.checker
    (lowering_context, context, body) <- lowerExpr lowering_context context c.body
    ((lowering_context, lowering_info, context), LE.Case checker body)

lowerExpr :: LoweringContext -> Context -> ME.Expr -> (LoweringContext, Context, LE.Expr)
lowerExpr lowering_context context expr = do
    ME.Expr s_expr expr_type expr_id <- expr
    (inference_info, expr_info) <- getTypeVariableInfoByExprId lowering_context.inference_info expr_id lowering_context.function_id
    lowering_context <- lowering_context { inference_info = inference_info }
    (inference_info, lowering_info, filter_info) <- createTypeLoweringInfoFromInferenceInfo context.config
                                       lowering_context.inference_info expr_info lowering_context.filter_info
    (lowering_info, _) <- normalizeTypeLoweringInfo context.config lowering_info
    //println "expr {} type {} {}" % (ME.short expr, expr_type, lowering_info)
    (context, lir_type) <- lowerType context lowering_info expr_type
    lowering_context <- lowering_context { inference_info = inference_info, filter_info = filter_info }
    (lowering_context, context, lir_s_expr) <- case s_expr of
        ME.Do items -> do
            ((lowering_context, context), items) <- List.mapS (lowering_context, context) items (\(lowering_context, context), item -> do
                (lowering_context, context, item) <- lowerExpr lowering_context context item
                ((lowering_context, context), item))
            (lowering_context, context, LE.Do items)
        ME.Multi _ -> panic "Multi in MIR -> LIR lowering"
        ME.StaticFunctionCall f_id args -> do
            (lowering_context, args_info) <- List.mapS lowering_context args (\lowering_context, arg -> do
                ME.Expr _ arg_type arg_id <- arg
                (inference_info, info) <- getTypeVariableInfoByExprId lowering_context.inference_info arg_id lowering_context.function_id
                (lowering_context { inference_info = inference_info }, info))
            function_converters <- Option.unwrap (Map.get inference_info.function_converters expr_id)
            (inference_info, lifetime_dependencies) <- List.fold (inference_info, List.empty) function_converters (\(inference_info, lifetime_dependencies), converter -> do
                (inference_info, from_kind) <- getOwnership inference_info converter.from
                (inference_info, to_kind) <- getOwnership inference_info converter.to
                lifetime_dependencies <- case (from_kind, to_kind) of
                    (Some (M.Borrower a), Some (M.Borrower b)) -> do
                        if a == b
                        then lifetime_dependencies
                        else List.push lifetime_dependencies (LifetimeDependency a b)
                    _ -> lifetime_dependencies
                (inference_info, lifetime_dependencies))
            (inference_info, lowering_info, filter_info) <- convertToFunctionLoweringInfo context.config lowering_context.inference_info args_info
                                               expr_info lowering_context.filter_info lifetime_dependencies
            lowering_context <- lowering_context { inference_info = inference_info, filter_info = filter_info }
            // println "-----------------------------------------"
            // println "---------------{} from {} ---------------" % (f_id, lowering_context.function_id)
            // println "-----------------------------------------"
            // println "Full inference info {}" % lowering_context.inference_info
            // println "Calling {} Lowering info {}" % (f_id, lowering_info)
            // println "-----------------------------------------"
            (lowering_info, _) <- normalizeFunctionLoweringInfo context.config lowering_info
            lir_key <- FunctionKey f_id lowering_info
            (context, lir_id) <- getLIRId context lir_key
            context <- addItem context lir_key
            ((lowering_context, context), lir_args) <- List.mapS (lowering_context, context) args (\(lowering_context, context), arg -> do
                (lowering_context, context, arg) <- lowerExpr lowering_context context arg
                ((lowering_context, context), arg))
            (mir_program, function) <- MP.getFunction context.mir_program f_id
            context <- context { mir_program = mir_program }
            lir_args <- case function.kind of
                    MF.VariantCtor index -> do
                        adt_id <- MT.getIdentity function.type.result
                        (mir_program, adt) <- MP.getAdt context.mir_program adt_id
                        variant <- List.atIndex adt.variants index
                        record_id <- MT.getIdentity variant.type
                        (mir_program, record) <- MP.getRecord mir_program record_id
                        context <- context { mir_program = mir_program }
                        List.zipS [] lir_args record.fields (\lir_args, arg, field -> do
                            if field.grouped
                            then do
                                LE.Expr _ arg_type _ <- arg
                                arg <- LE.Expr (LE.Box arg) (LT.Box arg_type) (LE.ExprId 0)
                                List.push lir_args arg
                            else List.push lir_args arg)
                    MF.RecordCtor -> do
                        record_id <- MT.getIdentity function.type.result
                        (mir_program, record) <- MP.getRecord context.mir_program record_id
                        context <- context { mir_program = mir_program }
                        List.zipS [] lir_args record.fields (\lir_args, arg, field -> do
                            if field.grouped
                            then do
                                LE.Expr _ arg_type _ <- arg
                                arg <- LE.Expr (LE.Box arg) (LT.Box arg_type) (LE.ExprId 0)
                                List.push lir_args arg
                            else List.push lir_args arg)
                    _ -> lir_args
            (lowering_context, context, LE.StaticFunctionCall lir_id lir_args)
        ME.IntegerLiteral lit -> (lowering_context, context, LE.IntegerLiteral lit)
        ME.StringLiteral lit -> (lowering_context, context, LE.StringLiteral lit)
        ME.FloatLiteral lit -> (lowering_context, context, LE.FloatLiteral lit)
        ME.CharLiteral lit -> (lowering_context, context, LE.CharLiteral lit)
        ME.VarDecl var rhs -> do
            (lowering_context, context, lir_rhs) <- lowerExpr lowering_context context rhs
            lir_var <- lowerVar var
            (lowering_context, context, LE.VarDecl lir_var lir_rhs)
        ME.VarRef var -> do
            lir_var <- lowerVar var
            (lowering_context, context, LE.VarRef lir_var)
        ME.FieldAccess name receiver -> do
            ME.Expr _ receiver_type _ <- receiver
            record_id <- MT.getIdentity receiver_type
            (mir_program, record) <- MP.getRecord context.mir_program record_id
            context <- context { mir_program = mir_program }
            field <- Option.unwrap (MD.getFieldByName record name)
            (lowering_context, context, lir_receiver) <- lowerExpr lowering_context context receiver
            if field.grouped
            then do
                case lir_type of
                    LT.Ref _ _ -> do
                        field_access <- LE.Expr (LE.FieldAccess name lir_receiver) lir_type (LE.ExprId 0)
                        field_access <- LE.Expr (LE.Deref field_access) lir_type (LE.ExprId 0)
                        (lowering_context, context, LE.Ref field_access)
                    _ -> do
                        field_access <- LE.Expr (LE.FieldAccess name lir_receiver) lir_type (LE.ExprId 0)
                        (lowering_context, context, LE.Deref field_access)
            else case lir_type of
                LT.Ref _ _ -> do
                    field_access <- LE.Expr (LE.FieldAccess name lir_receiver) lir_type (LE.ExprId 0)
                    (lowering_context, context, LE.Ref field_access)
                _ -> (lowering_context, context, LE.FieldAccess name lir_receiver)
        ME.If cond true_branch false_branch -> do
            (lowering_context, context, lir_cond) <- lowerExpr lowering_context context cond
            (lowering_context, context, lir_true_branch) <- lowerExpr lowering_context context true_branch
            (lowering_context, context, lir_false_branch) <- lowerExpr lowering_context context false_branch
            (lowering_context, context, LE.If lir_cond lir_true_branch lir_false_branch)
        ME.List args -> do
            ((lowering_context, context), lir_args) <- List.mapS (lowering_context, context) args (\(lowering_context, context), arg -> do
                (lowering_context, context, arg) <- lowerExpr lowering_context context arg
                ((lowering_context, context), arg))
            (lowering_context, context, LE.List lir_args)
        ME.Return arg -> do
            (lowering_context, context, lir_arg) <- lowerExpr lowering_context context arg
            (lowering_context, context, LE.Return lir_arg)
        ME.Continue arg -> do
            (lowering_context, context, lir_arg) <- lowerExpr lowering_context context arg
            (lowering_context, context, LE.Continue lir_arg)
        ME.Break arg -> do
            (lowering_context, context, lir_arg) <- lowerExpr lowering_context context arg
            (lowering_context, context, LE.Break lir_arg)
        ME.Loop var initializer body _ _ -> do
            lir_var <- lowerVar var
            (lowering_context, context, lir_initializer) <- lowerExpr lowering_context context initializer
            (lowering_context, context, lir_body) <- lowerExpr lowering_context context body
            (lowering_context, context, LE.Loop lir_var lir_initializer lir_body)
        ME.CaseOf body cases -> do
            ME.Expr _ _ body_id <- body
            (inference_info, body_info) <- getTypeVariableInfoByExprId lowering_context.inference_info body_id lowering_context.function_id
            lowering_context <- lowering_context { inference_info = inference_info }
            (inference_info, lowering_info, filter_info) <- createTypeLoweringInfoFromInferenceInfo context.config
                                                lowering_context.inference_info body_info lowering_context.filter_info
            (lowering_info, _) <- normalizeTypeLoweringInfo context.config lowering_info
            lowering_context <- lowering_context { inference_info = inference_info, filter_info = filter_info }
            (lowering_context, context, lir_body) <- lowerExpr lowering_context context body
            ((lowering_context, lowering_info, context), lir_cases) <- List.mapS (lowering_context, lowering_info, context) cases lowerCase
            (lowering_context, context, LE.CaseOf lir_body lir_cases)
        ME.Clone arg -> panic "Clone in MIR -> LIR lowering"
        ME.Deref arg -> panic "Deref in MIR -> LIR lowering"
        ME.Ref arg -> panic "Ref in MIR -> LIR lowering"
        ME.Move arg -> panic "Move in MIR -> LIR lowering"
        ME.Box arg -> panic "Box in MIR -> LIR lowering"
        ME.Converter arg _ -> do
            ME.Expr _ _ arg_id <- arg
            (inference_info, arg_info) <- getTypeVariableInfoByExprId lowering_context.inference_info arg_id lowering_context.function_id
            lowering_context <- lowering_context { inference_info = inference_info }
            (lowering_context, from) <- getOwnershipValue lowering_context arg_info.ownership_var
            (lowering_context, to) <- getOwnershipValue lowering_context expr_info.ownership_var
            (lowering_context, context, lir_arg) <- lowerExpr lowering_context context arg
            case (from, to) of
                (M.Owner, M.Owner) ->
                    if List.contains lowering_context.borrowers arg_id
                    then (lowering_context, context, LE.Clone lir_arg)
                    else (lowering_context, context, LE.Move lir_arg)
                (M.Owner, M.Borrower _) -> (lowering_context, context, LE.Ref lir_arg)
                (M.Borrower _, M.Borrower _) -> (lowering_context, context, LE.Move lir_arg)
                (M.Borrower _, M.Owner) -> (lowering_context, context, LE.DerefClone lir_arg)
                (from, to) -> panic "Invalid converter in LIR lowering {}/{}" % (from, to)
    //println "Transforming EXPR {} {}" % ((ME.short expr), expr_info)
    lir_expr <- LE.Expr lir_s_expr lir_type (LE.ExprId 0)
    (lowering_context, context, lir_expr)
