module Std.Arch.Process {

import Std.Fs.Path
import Std.Libc.String

@extern("C")
fn _NSGetExecutablePath(buf: *U8, size: *U32) -> I32

@safe
pub fn get_executable_path() -> Option[String] {
    let size = 256;
    loop {
        let buf: Vec[U8] = Vec.with_value(size.as_int(), 0);
        if _NSGetExecutablePath(buf.as_ptr(), &size) == 0 {
            let path = from_cstring(buf.as_ptr());
            return Some(match Std.Fs.Path.canonicalize(path.clone()) {
                Ok(resolved) => resolved,
                Err(_) => path,
            });
        }
        if size.as_int() <= buf.len() {
            return None;
        }
    }
}

}
