module Siko.Typechecker.Checker {

import Siko.AST.QualifiedName
import Siko.HIR.Program
import Siko.Instances.InstanceResolver
import Siko.Typechecker.Collector
import Siko.Typechecker.Error
import Siko.Typechecker.Finalize
import Siko.Typechecker.Sanity
import Siko.Typechecker.Solver
import Siko.Typechecker.Statistics
import Siko.Config

pub fn typecheck_function(key: QualifiedName, program: Program, instance_resolver: InstanceResolver) -> Result[(), Vec[TypeError]] {
    stats.function();
    let func = program.functions.get(key).unwrap().clone();
    let collector = Collector.new(program);
    let annotated = {
        stats.collector_start();
        defer stats.collector_end();
        collector.collect_function(func)
    };
    if !collector.errors.is_empty() {
        stats.failed_function();
        return Err(collector.errors);
    }
    let allocator = collector.get_allocator();
    let constraints = collector.into_constraints();
    let solver = Solver.new(program, instance_resolver, func, constraints, allocator).with_debug(get_config().debug_typecheck);
    let solve_result = {
        stats.solver_start();
        defer stats.solver_end();
        solver.solve()
    };
    match solve_result {
        Err(e) => {
            stats.failed_function();
            return Err([e]);
        }
        Ok(_) => {}
    }
    let method_resolutions = solver.get_method_resolutions();
    let witness_map = solver.get_witness_map();
    let finalizer = Finalizer.new(solver.into_subst(), program, method_resolutions, witness_map);
    let finalized = {
        stats.finalizer_start();
        defer stats.finalizer_end();
        finalizer.finalize_function(annotated)
    };
    let sanity_errors = {
        stats.sanity_start();
        defer stats.sanity_end();
        sanity_check(finalized)
    };
    if !sanity_errors.is_empty() {
        stats.failed_function();
        return Err(sanity_errors);
    }
    program.functions.insert(key, finalized);
    Ok(())
}

pub fn typecheck_program(program: Program) -> Result[(), Vec[TypeError]] {
    let keys: Vec[QualifiedName] = program.functions.keys().collect();
    let errors: Vec[TypeError] = Vec.new();
    for key in keys {
        if let Err(errs) = typecheck_function(key, program, program.instance_resolver) {
            for e in errs {
                errors.push(e);
            }
        }
    }
    if errors.is_empty() { Ok(()) } else { Err(errors) }
}

}
