module Siko.Typechecker.Pattern where

import Siko.Typechecker.Expr
import Siko.HIR.Pattern

initializePatternType :: Context -> Pattern -> Context
initializePatternType context (Pattern pattern id location) = do
    println "Initializing pattern {} {}" % (pattern, id)
    context

checkPatternType :: Context -> Pattern -> Context
checkPatternType context (Pattern pattern id location) = do
    println "Checking pattern {} {}" % (pattern, id)
    context