module Siko.Typechecker where


import Siko.Typechecker.Expr
import Siko.Typechecker.Error
import Siko.Typechecker.Pattern
import Siko.Typechecker.TypeStore as TS
import Siko.Typechecker.FunctionStore as FS
import Siko.Typechecker.Class
import Siko.Typechecker.Function
import Siko.Typechecker.Unification as U
import Siko.Util.DependencyProcessor
import Siko.HIR.Program as P
import Siko.HIR.Function as F
import Siko.HIR.Traversal
import Siko.HIR.Expr
import Map

data TypecheckerState = { errors :: [TypecheckerError],
                          var_gen :: U.TypeVarGenerator,
                        }

emptyState :: TypecheckerState
emptyState = TypecheckerState [] U.createTypeVarGenerator

addError :: TypecheckerState -> TypecheckerError -> TypecheckerState
addError state error = do
    errors <- state.errors + [error]
    state { errors = errors }

initializeFunctionType :: [P.FullyQualifiedName] -> Context -> F.Function -> Context
initializeFunctionType group_items context fn = do
    case fn.body of
        Some body -> traverse context (initializeExprType group_items fn.name) initializePatternType body
        None -> context

checkFunctionType :: Context -> F.Function -> Context
checkFunctionType context fn = do
    case fn.body of
        Some body -> do
            context <- traverse context checkExprType checkPatternType body
            func_type_info <- getFunctionTypeInfo context fn.name
            (Expr _ body_id location) <- body
            (context, _) <- matchExprWith context body_id func_type_info.result_type location
            context <- context.returns |> List.iter |> fold (\context, (arg_id, arg_location) -> do
                    (context, _) <- matchExprWith context arg_id func_type_info.result_type arg_location
                    context) context
            context <- context { returns = [] }
            context
        None -> context

processGroup :: TypecheckerState -> DependencyGroup P.FullyQualifiedName -> P.Program -> FS.FunctionStore -> (TypecheckerState, FS.FunctionStore)
processGroup state group program function_store = do
    context <- initializeContext state program function_store
    context <- group.items |> List.iter |> fold (\context, name -> do
                        fn <- P.getFunction program name
                        context <- initializeFunctionType group.items context fn
                        context) context
    //println "After init"
    //TS.dump context.type_store
    context <- group.items |> List.iter |> fold (\context, name -> do
                        fn <- P.getFunction program name
                        context <- checkFunctionType context fn
                        context) context
    //println "After check"
    //TS.dump context.type_store
    (context.state, context.function_store)

processProgram :: P.Program -> [TypecheckerError]
processProgram program = do
    state <- emptyState
    (state, program) <- processClassesAndInstances state program
    (state, function_store, groups) <- processFunctions state program
    (state, function_store) <- groups |> List.iter |> fold (\(state, function_store), group -> do
        (state, function_store) <- processGroup state group program function_store
        (state, function_store) ) (state, function_store)
    FS.dump function_store
    state.errors