module Siko.Typechecker.TypeStore where

import Siko.Syntax.Location
import Siko.HIR.Type as T
import Siko.HIR.Expr as E
import Siko.HIR.Pattern as P
import Siko.Typechecker.Unification as U
import Siko.Typechecker.DataStore as DS
import Map

data ExprTypeState = ExprType T.Type
                     | FunctionCall T.Type T.Type
                     deriving (Show)

data PatternTypeState = PatternType T.Type
                        | PatternWithRecordType DS.RecordTypeInfo
                        | PatternWithAdtType DS.AdtTypeInfo
                        deriving (Show)

data TypeStore = { expr_types :: Map E.ExprId ExprTypeState,
                   pattern_types :: Map P.PatternId PatternTypeState,
                   pattern_locations :: Map P.PatternId Location
                 } deriving (Show)

instance U.Apply ExprTypeState where
    //apply :: ExprTypeState -> U.Substitution -> ExprTypeState
    apply ets sub = case ets of
                    ExprType ty -> ExprType (U.apply ty sub)
                    FunctionCall ty fn_ty -> FunctionCall (U.apply ty sub) (U.apply fn_ty sub)

instance U.Apply PatternTypeState where
    //apply :: PatternTypeState -> U.Substitution -> PatternTypeState
    apply pts sub = case pts of
        PatternType ty -> PatternType (U.apply ty sub)
        PatternWithRecordType record_type_info -> PatternWithRecordType (U.apply record_type_info sub)
        PatternWithAdtType adt_type_info -> PatternWithAdtType (U.apply adt_type_info sub)

initializeTypeStore :: TypeStore
initializeTypeStore = TypeStore empty empty empty

addExprType :: TypeStore -> E.ExprId -> ExprTypeState -> TypeStore
addExprType store expr_id expr_type = do
    (expr_types, prev) <- insert store.expr_types expr_id expr_type
    if isSome prev
    then panic "Exprid is not unique!"
    else ()
    store { expr_types = expr_types }

addPatternType :: TypeStore -> P.PatternId -> PatternTypeState -> TypeStore
addPatternType store pattern_id pattern_type = do
    (pattern_types, prev) <- insert store.pattern_types pattern_id pattern_type
    if isSome prev
    then panic "Patternid is not unique!"
    else ()
    store { pattern_types = pattern_types }

addPatternLocation :: TypeStore -> P.PatternId -> Location -> TypeStore
addPatternLocation store pattern_id location = do
    (pattern_locations, _) <- insert store.pattern_locations pattern_id location
    store { pattern_locations = pattern_locations }

getPatternLocation :: TypeStore -> P.PatternId -> Location
getPatternLocation store pattern_id =
    case get store.pattern_locations pattern_id of
        Some l -> l
        None -> panic "Pattern not found in pattern locatios map"

getTypeFromExprTypeState :: ExprTypeState -> T.Type
getTypeFromExprTypeState expr_type =
    case expr_type of
        ExprType type -> type
        FunctionCall type _ -> type

getTypeFromPatternTypeState :: PatternTypeState -> T.Type
getTypeFromPatternTypeState pattern_type =
    case pattern_type of
        PatternType type -> type
        PatternWithRecordType record_type_info -> record_type_info.type
        PatternWithAdtType adt_type_info -> adt_type_info.type

getExprType :: TypeStore -> E.ExprId -> T.Type
getExprType store expr_id = do
    case get store.expr_types expr_id of
        Some type -> getTypeFromExprTypeState type
        _ -> panic "No type found for {}" % expr_id

getExprAndFunctionCallType :: TypeStore -> E.ExprId -> (T.Type, T.Type)
getExprAndFunctionCallType store expr_id = do
    case get store.expr_types expr_id of
        Some (FunctionCall ty fn_ty) -> (ty, fn_ty)
        _ -> panic "No fn call type found for {}" % expr_id

getPatternType :: TypeStore -> P.PatternId -> T.Type
getPatternType store pattern_id = do
    case get store.pattern_types pattern_id of
        Some (PatternType type) -> type
        Some (PatternWithRecordType record_type_info) -> record_type_info.type
        Some (PatternWithAdtType adt_type_info) -> adt_type_info.type
        _ -> panic "No type found for {}" % pattern_id

getRecordTypeInfo :: TypeStore -> P.PatternId -> DS.RecordTypeInfo
getRecordTypeInfo store pattern_id = do
    case get store.pattern_types pattern_id of
        Some (PatternWithRecordType record_type_info) -> record_type_info
        _ -> panic "No record type info found for {}" % pattern_id

getAdtTypeInfo :: TypeStore -> P.PatternId -> DS.AdtTypeInfo
getAdtTypeInfo store pattern_id = do
    case get store.pattern_types pattern_id of
        Some (PatternWithAdtType adt_type_info) -> adt_type_info
        _ -> panic "No adt type info found for {}" % pattern_id

instance U.Apply TypeStore where
    apply store sub = do
        expr_types <- Map.update store.expr_types (\(id, expr_ty) -> U.apply expr_ty sub)
        pattern_types <- Map.update store.pattern_types (\(id, pattern_ty) -> U.apply pattern_ty sub)
        store { expr_types = expr_types, pattern_types = pattern_types }

dump :: TypeStore -> ()
dump store = do
    store.expr_types |> Map.iter |> forEach (\(expr_id, state) -> case state of
        ExprType ty -> println "E{}: {}" % (expr_id, T.toString ty)
        FunctionCall ty fn_type -> println "E{}: {}" % (expr_id, T.toString ty))
    store.pattern_types |> Map.iter |> forEach (\(pattern_id, state) -> case state of
        (PatternType ty) -> println "P{}: {}" % (pattern_id, T.toString ty)
        (PatternWithRecordType record_type_info) -> println "P{}: {}" % (pattern_id, T.toString record_type_info.type)
        (PatternWithAdtType adt_type_info) -> println "P{}: {}" % (pattern_id, T.toString adt_type_info.type))
