module Siko.Typechecker.Util where

import Siko.HIR.Type
import Siko.HIR.Program as P
import Siko.Typechecker.Unification
import Siko.Constants

import Map

getIntType :: Type
getIntType = Named (P.FullPath getIntModuleName getIntTypeName) []

getFloatType :: Type
getFloatType = Named (P.FullPath getFloatModuleName getFloatTypeName) []

getStringType :: Type
getStringType = Named (P.FullPath getStringModuleName getStringTypeName) []

getCharType :: Type
getCharType = Named (P.FullPath getCharModuleName getCharTypeName) []

getBoolType :: Type
getBoolType = Named (P.FullPath getBoolModuleName getBoolTypeName) []

collectVars :: [TypeVar] -> Type -> [TypeVar]
collectVars vars type = Siko.HIR.Type.collectVars type + vars |> sort |> dedup

data Mapper = Mapper (Map TypeVar TypeVar)

initMapper :: [TypeVar] -> TypeVarGenerator -> (Mapper, TypeVarGenerator)
initMapper vars var_gen = do
    (vars, var_gen) <- vars |> List.iter |> fold (\(vars, var_gen), old_var -> do
            (var_gen, new_var) <- getNewTypeVar var_gen
            (vars, _) <- insert vars old_var new_var
            (vars, var_gen)) (empty, var_gen)
    (Mapper vars, var_gen)

instantiateType :: Type -> TypeVarGenerator -> (Type, TypeVarGenerator)
instantiateType type var_gen = do
    vars <- Siko.HIR.Type.collectVars type |> sort |> dedup
    (mapper, var_gen) <- initMapper vars var_gen
    type <- remap mapper type
    (type, var_gen)

remap :: Mapper -> Type -> Type
remap mapper type = do
    (Mapper vars) <- mapper
    case type of
        Var var constraints -> case get vars var of
            Some new_var -> Var new_var constraints
            None -> panic "old var {} not found" % var
        FixedTypeArg _ var constraints -> case get vars var of
            Some new_var -> Var new_var constraints
            None -> panic "old var {} not found" % var
        Named n args -> do
            args <- args |> List.iter |> map (\arg -> remap mapper arg) |> toList
            Named n args
        Function from to -> do
            from <- remap mapper from
            to <- remap mapper to
            Function from to
        Never var -> case get vars var of
            Some new_var -> Never new_var
            None -> panic "old var {} not found" % var
        Ref t -> Ref (remap mapper t)
        Tuple args -> do
            args <- args |> List.iter |> map (\arg -> remap mapper arg) |> toList
            Tuple args
