module Siko.Transpiler.Externals where

import Siko.MIR.Data
import Siko.MIR.Program
import Siko.MIR.Type as MT
import Siko.Transpiler.Rust as R
import Siko.Transpiler
import Map

getVariantRecordType :: Program -> MT.Type -> String -> Identity
getVariantRecordType program mir_type name = do
    adt_id <- case mir_type of
        MT.Adt adt_id -> adt_id
        _ -> panic "Not an ADT"
    adt <- getAdt program adt_id
    loop index <- 0 do
        variant <- atIndex adt.variants index
        if variant.name == name
            then return variant.type
            else index + 1

generatePrintStr :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generatePrintStr program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    print_call <- R.FunctionCall "print!" [R.StringLiteral "{}", field_access]
    unit <- R.StructCtor (show rust_type) []
    R.Block [print_call, unit]

generateStringAdd :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateStringAdd program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    clone_call <- R.MethodCall deref0 cloneName []
    new <- "new"
    new_decl <- R.VarDecl True new clone_call None
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    extend_call <- R.MethodCall (R.VarRef new) "push_str" [R.Ref field_access1]
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, extend_call, struct_ctor]

generateAdd :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateAdd program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    add_call <- R.FunctionCall stdOpsAdd [deref0, deref1]
    new <- "new"
    new_decl <- R.VarDecl False new add_call None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, struct_ctor]

generateSub :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateSub program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    sub_call <- R.FunctionCall stdOpsSub [deref0, deref1]
    new <- "new"
    new_decl <- R.VarDecl False new sub_call None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, struct_ctor]

generateMul :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateMul program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    mul_call <- R.FunctionCall stdOpsMul [deref0, deref1]
    new <- "new"
    new_decl <- R.VarDecl False new mul_call None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, struct_ctor]

generateDiv :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateDiv program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    div_call <- R.FunctionCall stdOpsDiv [deref0, deref1]
    new <- "new"
    new_decl <- R.VarDecl False new div_call None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, struct_ctor]

generateNegative :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateNegative program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    new <- "new"
    new_decl <- R.VarDecl False new (R.FunctionCall "-" [deref0]) None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]
    R.Block [new_decl, struct_ctor]

generateShow :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateShow program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    format <- R.FunctionCall "format!" [(R.StringLiteral "{}"), field_access]
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [format])]
    R.Block [struct_ctor]


generatePartialCmp :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generatePartialCmp program type_store arg_types result_type = do
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    partial_cmp_call <- R.MethodCall field_access0 "partial_cmp" [R.Ref field_access1]
    rust_result_type <- convertType result_type
    some_record_type <- getVariantRecordType program result_type "Some"
    none_record_type <- getVariantRecordType program result_type "None"
    rust_some_record_type <- convertType (MT.Record some_record_type)
    rust_none_record_type <- convertType (MT.Record none_record_type)
    some_record <- getRecord program some_record_type
    ordering_field <- atIndex some_record.fields 0
    ordering_type <- ordering_field.type
    greater_record_type <- getVariantRecordType program ordering_type "Greater"
    equal_record_type <- getVariantRecordType program ordering_type "Equal"
    less_record_type <- getVariantRecordType program ordering_type "Less"
    rust_ordering_type <- convertType ordering_type
    ordering_var <- "o"
    greater_ctor <- R.StructCtor (show (convertType (MT.Record greater_record_type))) []
    equal_ctor <- R.StructCtor (show (convertType (MT.Record equal_record_type))) []
    less_ctor <- R.StructCtor (show (convertType (MT.Record less_record_type))) []
    greater_ctor <- R.FunctionCall ("{}::Greater" % rust_ordering_type) [greater_ctor]
    equal_ctor <- R.FunctionCall ("{}::Equal" % rust_ordering_type) [equal_ctor]
    less_ctor <- R.FunctionCall ("{}::Less" % rust_ordering_type) [less_ctor]
    greater_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Greater" None) (R.FunctionCall rcNew [greater_ctor])
    equal_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Equal" None) (R.FunctionCall rcNew [equal_ctor])
    less_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Less" None) (R.FunctionCall rcNew [less_ctor])
    init <- R.FieldInitItem ordering_field.name (R.Match (R.VarRef ordering_var) [greater_case, equal_case, less_case])
    some_struct_ctor <- R.StructCtor (show rust_some_record_type) [init]
    none_struct_ctor <- R.StructCtor (show rust_none_record_type) []
    result_some_ctor <- R.FunctionCall ("{}::Some" % rust_result_type) [some_struct_ctor]
    result_none_ctor <- R.FunctionCall ("{}::None" % rust_result_type) [none_struct_ctor]
    some_case <- R.MatchCase (R.VariantPattern "std::option::Option::Some" (Some ordering_var)) result_some_ctor
    none_case <- R.MatchCase (R.VariantPattern "std::option::Option::None" None) result_none_ctor
    match <- R.Match partial_cmp_call [some_case, none_case]
    R.Block [match]

generateCmp :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateCmp program type_store arg_types result_type = do
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    cmp_call <- R.MethodCall field_access0 "cmp" [R.Ref field_access1]
    rust_ordering_type <- convertType result_type
    greater_record_type <- getVariantRecordType program result_type "Greater"
    equal_record_type <- getVariantRecordType program result_type "Equal"
    less_record_type <- getVariantRecordType program result_type "Less"
    greater_ctor <- R.StructCtor (show (convertType (MT.Record greater_record_type))) []
    equal_ctor <- R.StructCtor (show (convertType (MT.Record equal_record_type))) []
    less_ctor <- R.StructCtor (show (convertType (MT.Record less_record_type))) []
    greater_ctor <- R.FunctionCall ("{}::Greater" % rust_ordering_type) [greater_ctor]
    equal_ctor <- R.FunctionCall ("{}::Equal" % rust_ordering_type) [equal_ctor]
    less_ctor <- R.FunctionCall ("{}::Less" % rust_ordering_type) [less_ctor]
    greater_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Greater" None) greater_ctor
    equal_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Equal" None) equal_ctor
    less_case <- R.MatchCase (R.VariantPattern "std::cmp::Ordering::Less" None) less_ctor
    match <- R.Match cmp_call [greater_case, equal_case, less_case]
    R.Block [match]

rustBoolToSikoBool :: Program -> R.Expr -> MT.Type -> R.Expr
rustBoolToSikoBool program bool_expr bool_type = do
    rust_bool_type <- convertType bool_type
    true_record_type <- getVariantRecordType program bool_type "True"
    false_record_type <- getVariantRecordType program bool_type "False"
    true_pattern <- R.VariantPattern "true" None
    false_pattern <- R.VariantPattern "false" None
    rust_true_record_type <- convertType (MT.Record true_record_type)
    rust_false_record_type <- convertType (MT.Record false_record_type)
    true_ctor <- R.StructCtor (show (rust_true_record_type)) []
    false_ctor <- R.StructCtor (show (rust_false_record_type)) []
    true_case <- R.MatchCase true_pattern (R.FunctionCall ("{}::True" % rust_bool_type) [true_ctor])
    false_case <- R.MatchCase false_pattern (R.FunctionCall ("{}::False" % rust_bool_type) [false_ctor])
    cases <- [true_case, false_case]
    R.Match bool_expr cases

sikoBoolToRustBool :: R.Expr -> R.Type -> R.Expr
sikoBoolToRustBool bool_expr bool_type = do
    true_pattern <- R.VariantPattern ("{}::True" % bool_type) (Some "_")
    false_pattern <- R.VariantPattern ("{}::False" % bool_type) (Some "_")
    true_case <- R.MatchCase true_pattern (R.BoolLiteral True)
    false_case <- R.MatchCase false_pattern (R.BoolLiteral False)
    cases <- [true_case, false_case]
    R.Match bool_expr cases

sikoOrderingToRustOrdering :: R.Expr -> R.Type -> R.Expr
sikoOrderingToRustOrdering ord_expr ordering_type = do
    greater_pattern <- R.VariantPattern ("{}::Greater" % ordering_type) (Some "_")
    equal_pattern <- R.VariantPattern ("{}::Equal" % ordering_type) (Some "_")
    less_pattern <- R.VariantPattern ("{}::Less" % ordering_type) (Some "_")
    greater_case <- R.MatchCase greater_pattern (R.EnumCtor "std::cmp::Ordering::Greater")
    equal_case <- R.MatchCase equal_pattern (R.EnumCtor "std::cmp::Ordering::Equal")
    less_case <- R.MatchCase less_pattern (R.EnumCtor "std::cmp::Ordering::Less")
    cases <- [greater_case, equal_case, less_case]
    R.Match ord_expr cases

sikoOptionalOrderingToRustOptionalOrdering :: Program -> R.Expr -> MT.Type -> R.Expr
sikoOptionalOrderingToRustOptionalOrdering program partial_ord_expr optional_ordering_type = do
    rust_optional_ordering_type <- convertType optional_ordering_type
    some_ordering <- "some_ordering"
    some_pattern <- R.VariantPattern ("{}::Some" % rust_optional_ordering_type) (Some some_ordering)
    none_pattern <- R.VariantPattern ("{}::None" % rust_optional_ordering_type) (Some "_")
    some_record_type <- getVariantRecordType program optional_ordering_type "Some"
    some_record <- getRecord program some_record_type
    ordering_type_field <- atIndex some_record.fields 0
    rust_some_record_type <- convertType ordering_type_field.type
    field_access <- R.FieldAccess ordering_type_field.name (R.VarRef some_ordering)
    deref <- R.FunctionCall derefName [R.Ref field_access]
    some_match <- sikoOrderingToRustOrdering (R.MethodCall deref cloneName []) rust_some_record_type
    some_case <- R.MatchCase some_pattern (R.FunctionCall "Some" [some_match])
    none_case <- R.MatchCase none_pattern (R.EnumCtor "None")
    cases <- [some_case, none_case]
    R.Match partial_ord_expr cases

generateEq :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateEq program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    eq_call <- R.MethodCall field_access0 "eq" [R.Ref field_access1]
    match <- rustBoolToSikoBool program eq_call result_type
    R.Block [match]

generateOpAnd :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateOpAnd program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    rust_result_type <- convertType result_type
    arg_type <- atIndex arg_types 0
    true_record_type <- getVariantRecordType program arg_type "True"
    false_record_type <- getVariantRecordType program arg_type "False"
    true_pattern <- R.VariantPattern "true" None
    false_pattern <- R.VariantPattern "false" None
    rust_true_record_type <- convertType (MT.Record true_record_type)
    rust_false_record_type <- convertType (MT.Record false_record_type)
    true_ctor <- R.StructCtor (show (rust_true_record_type)) []
    false_ctor <- R.StructCtor (show (rust_false_record_type)) []

    true_pattern <- R.VariantPattern ("{}::True" % rust_result_type) (Some "_")
    false_pattern <- R.VariantPattern ("{}::False" % rust_result_type) (Some "_")

    true_case <- R.MatchCase true_pattern (R.FunctionCall ("{}::True" % rust_result_type) [true_ctor])
    false_case <- R.MatchCase false_pattern (R.FunctionCall ("{}::False" % rust_result_type) [false_ctor])
    cases <- [true_case, false_case]
    match_true <- R.Match (R.VarRef (getArgName 1)) cases

    true_case <- R.MatchCase true_pattern (R.FunctionCall ("{}::False" % rust_result_type) [false_ctor])
    false_case <- R.MatchCase false_pattern (R.FunctionCall ("{}::False" % rust_result_type) [false_ctor])
    cases <- [true_case, false_case]
    match_false <- R.Match (R.VarRef (getArgName 1)) cases

    true_case <- R.MatchCase true_pattern match_true
    false_case <- R.MatchCase false_pattern match_false
    cases <- [true_case, false_case]
    match <- R.Match (R.VarRef (getArgName 0)) cases

    R.Block [match]

generateOpOr :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateOpOr program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    rust_result_type <- convertType result_type
    arg_type <- atIndex arg_types 0
    true_record_type <- getVariantRecordType program arg_type "True"
    false_record_type <- getVariantRecordType program arg_type "False"
    true_pattern <- R.VariantPattern "true" None
    false_pattern <- R.VariantPattern "false" None
    rust_true_record_type <- convertType (MT.Record true_record_type)
    rust_false_record_type <- convertType (MT.Record false_record_type)
    true_ctor <- R.StructCtor (show (rust_true_record_type)) []
    false_ctor <- R.StructCtor (show (rust_false_record_type)) []

    true_pattern <- R.VariantPattern ("{}::True" % rust_result_type) (Some "_")
    false_pattern <- R.VariantPattern ("{}::False" % rust_result_type) (Some "_")

    true_case <- R.MatchCase true_pattern (R.FunctionCall ("{}::True" % rust_result_type) [true_ctor])
    false_case <- R.MatchCase false_pattern (R.FunctionCall ("{}::True" % rust_result_type) [true_ctor])
    cases <- [true_case, false_case]
    match_true <- R.Match (R.VarRef (getArgName 1)) cases

    true_case <- R.MatchCase true_pattern (R.FunctionCall ("{}::True" % rust_result_type) [true_ctor])
    false_case <- R.MatchCase false_pattern (R.FunctionCall ("{}::False" % rust_result_type) [false_ctor])
    cases <- [true_case, false_case]
    match_false <- R.Match (R.VarRef (getArgName 1)) cases

    true_case <- R.MatchCase true_pattern match_true
    false_case <- R.MatchCase false_pattern match_false
    cases <- [true_case, false_case]
    match <- R.Match (R.VarRef (getArgName 0)) cases

    R.Block [match]

generateGetDiscriminant :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateGetDiscriminant program type_store arg_types result_type = do
    arg_type <- atIndex arg_types 0
    case arg_type of
        MT.Adt adt_id -> do
            adt <- getAdt program adt_id
            var_ref <- R.VarRef (getArgName 0)
            rust_type <- convertType arg_type
            rust_result_type <- convertType result_type
            cases <- adt.variants |> List.iter |> fold (\cases, variant -> do
                index <- getLength cases
                name <- "{}::{}" % (rust_type, variant.name)
                pattern <- R.VariantPattern name (Some "_")
                struct_ctor <- R.StructCtor (show rust_result_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.IntegerLiteral "{}" % index])]
                c <- R.MatchCase pattern struct_ctor
                cases <- cases + [c]
                cases) []
            R.Block [R.Match var_ref cases]
        MT.Record _ -> do
            rust_result_type <- convertType result_type
            struct_ctor <- R.StructCtor (show rust_result_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.IntegerLiteral "0"])]
            R.Block [struct_ctor]
        _ -> panic "getDiscriminant not implemented for special types"

generateAssert :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateAssert program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    arg_type <- atIndex arg_types 0
    rust_type <- convertType arg_type
    rust_result_type <- convertType result_type
    true_pattern <- R.VariantPattern ("{}::True" % rust_type) (Some "_")
    false_pattern <- R.VariantPattern ("{}::False" % rust_type) (Some "_")
    true_case <- R.MatchCase true_pattern (R.StructCtor (show rust_result_type) [])
    false_case <- R.MatchCase false_pattern (R.Block [R.FunctionCall "panic!" [R.StringLiteral "Assertion failed"]])
    cases <- [true_case, false_case]
    match <- R.Match (R.VarRef (getArgName 0)) cases
    R.Block [match]

generateIsUppercase :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateIsUppercase program type_store arg_types result_type = do
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    call <- R.MethodCall field_access0 "is_uppercase" []
    match <- rustBoolToSikoBool program call result_type
    R.Block [match]

generateReadTextFile :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateReadTextFile program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    read_call <- R.FunctionCall "std::fs::read" [deref0]
    read_call <- R.MethodCall read_call "expect" [R.StringLiteral "ReadTextFile failed"]
    convert <- R.FunctionCall "String::from_utf8_lossy" [R.Ref read_call]
    to_string_call <- R.MethodCall convert "to_string" []
    struct_ctor <- R.StructCtor (show rust_result_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [to_string_call])]
    R.Block [struct_ctor]

generateWriteTextFile :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateWriteTextFile program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    write_call <- R.FunctionCall "std::fs::write" [deref0, deref1]
    write_call <- R.MethodCall write_call "expect" [R.StringLiteral "WriteTextFile failed"]
    struct_ctor <- R.StructCtor (show rust_result_type) []
    R.Block [write_call, struct_ctor]

generateIntParse :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateIntParse program type_store arg_types result_type = do
    rust_result_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    parse_call <- R.MethodCall deref0 "parse::<i64>" []
    rust_result_type <- convertType result_type
    some_record_type <- getVariantRecordType program result_type "Some"
    none_record_type <- getVariantRecordType program result_type "None"
    rust_some_record_type <- convertType (MT.Record some_record_type)
    rust_none_record_type <- convertType (MT.Record none_record_type)
    some_record <- getRecord program some_record_type
    int_field <- atIndex some_record.fields 0
    rust_int_type <- convertType int_field.type
    int_ctor <- R.StructCtor (show rust_int_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef "v"])]
    some_ctor <- R.StructCtor (show rust_some_record_type) [R.FieldInitItem int_field.name (R.FunctionCall rcNew [int_ctor])]
    none_ctor <- R.StructCtor (show rust_none_record_type) []
    ok_pattern <- R.VariantPattern ("Ok") (Some "v")
    err_pattern <- R.VariantPattern ("Err") (Some "_")
    ok_case <- R.MatchCase ok_pattern (R.FunctionCall ("{}::Some" % rust_result_type) [some_ctor])
    err_case <- R.MatchCase err_pattern (R.FunctionCall ("{}::None" % rust_result_type) [none_ctor])
    cases <- [ok_case, err_case]
    match <- R.Match parse_call cases
    R.Block [match]

generateListShow :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListShow program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    inner <- R.FieldAccess innerValueField arg0
    iter <- R.MethodCall inner "iter" []
    map_body <- R.Lambda "|item|" (R.FunctionCall "format!" [R.StringLiteral "{}", R.VarRef "item"])
    map <- R.MethodCall iter "map" [map_body]
    collect <- R.MethodCall map "collect" []
    subs <- "subs"
    subs_decl <- R.VarDecl False subs collect (Some (R.Type "Vec<_>"))
    fmt_arg <- R.StringLiteral "[{}]"
    join_call <- R.MethodCall (R.VarRef subs) "join" [R.StringLiteral (", ")]
    value_decl <- R.VarDecl False innerValueField (R.FunctionCall "format!" [fmt_arg, join_call]) None
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef innerValueField])]
    R.Block [subs_decl, value_decl, struct_ctor]

generateListAtIndex :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListAtIndex program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    arg1 <- R.VarRef (getArgName 1)
    inner0 <- R.FieldAccess innerValueField arg0
    inner1 <- R.FieldAccess innerValueField arg1
    deref1 <- R.FunctionCall derefName [R.Ref inner1]
    index <- R.FunctionCall "std::ops::Index::index" [R.Ref (R.Deref (inner0)), R.As (R.Deref deref1) "usize"]
    R.Block [R.MethodCall index cloneName []]

generateListGetLength :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListGetLength program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    inner0 <- R.FieldAccess innerValueField arg0
    len_call <- R.MethodCall inner0 "len" []
    R.Block [R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.As len_call "i64"])]]

generateListDedup :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListDedup program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    inner0 <- R.FieldAccess innerValueField arg0
    deref0 <- R.FunctionCall derefName [R.Ref inner0]
    new <- "new"
    new_decl <- R.VarDecl True new (R.MethodCall deref0 cloneName []) None
    dedup_call <- R.MethodCall (R.VarRef new) "dedup" []
    R.Block [new_decl, dedup_call, R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]]

generateListIsEmpty :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListIsEmpty program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    inner0 <- R.FieldAccess innerValueField arg0
    empty_call <- R.MethodCall inner0 "is_empty" []
    R.Block [rustBoolToSikoBool program empty_call result_type]

generateListSort :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListSort program type_store arg_types result_type = do
    rust_type <- convertType result_type
    arg0 <- R.VarRef (getArgName 0)
    inner0 <- R.FieldAccess innerValueField arg0
    deref0 <- R.FunctionCall derefName [R.Ref inner0]
    new <- "new"
    new_decl <- R.VarDecl True new (R.MethodCall deref0 cloneName []) None
    sort_call <- R.MethodCall (R.VarRef new) "sort" []
    R.Block [new_decl, sort_call, R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new])]]

generateListHead :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListHead program type_store arg_types result_type = do
    arg0 <- R.VarRef (getArgName 0)
    inner0 <- R.FieldAccess innerValueField arg0
    first_call <- R.MethodCall inner0 "first" []
    item <- "item"
    some_pattern <- R.VariantPattern "Some" (Some item)
    none_pattern <- R.VariantPattern "None" None
    rust_result_type <- convertType result_type
    some_record_type <- getVariantRecordType program result_type "Some"
    none_record_type <- getVariantRecordType program result_type "None"
    rust_some_record_type <- convertType (MT.Record some_record_type)
    rust_none_record_type <- convertType (MT.Record none_record_type)
    some_record <- getRecord program some_record_type
    item_field <- atIndex some_record.fields 0
    rust_item_type <- convertType item_field.type
    clone_call <- R.MethodCall (R.VarRef item) cloneName []
    some_ctor <- R.StructCtor (show rust_some_record_type) [R.FieldInitItem item_field.name (R.FunctionCall rcNew [clone_call])]
    none_ctor <- R.StructCtor (show rust_none_record_type) []
    some_case <- R.MatchCase some_pattern (R.FunctionCall ("{}::Some" % rust_result_type) [some_ctor])
    none_case <- R.MatchCase none_pattern (R.FunctionCall ("{}::None" % rust_result_type) [none_ctor])
    cases <- [some_case, none_case]
    match <- R.Match first_call cases
    R.Block [match]

generateListAdd :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListAdd program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    field_access1 <- R.FieldAccess innerValueField (R.VarRef (getArgName 1))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    deref1 <- R.FunctionCall derefName [R.Ref field_access1]
    new0 <- "new0"
    new0_decl <- R.VarDecl True new0 (R.MethodCall deref0 cloneName []) None
    new1 <- "new1"
    new1_decl <- R.VarDecl False new1 (R.MethodCall deref1 cloneName []) None
    add_call <- R.MethodCall (R.VarRef new0) "extend" [R.VarRef new1]
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef new0])]
    R.Block [new0_decl, new1_decl, add_call, struct_ctor]

generateListIntoIter :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListIntoIter program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    new0 <- "new0"
    new0_decl <- R.VarDecl False new0 (R.MethodCall deref0 cloneName []) None
    into_iter_call <- R.MethodCall (R.VarRef new0) "into_iter" []
    struct_ctor <- R.StructCtor (show rust_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [into_iter_call])]
    R.Block [new0_decl, struct_ctor]

generateListNextItem :: Program -> TypeStore -> [MT.Type] -> MT.Type -> R.Expr
generateListNextItem program type_store arg_types result_type = do
    rust_type <- convertType result_type
    field_access0 <- R.FieldAccess innerValueField (R.VarRef (getArgName 0))
    deref0 <- R.FunctionCall derefName [R.Ref field_access0]
    state <- "state"
    state_decl <- R.VarDecl True state (R.MethodCall deref0 cloneName []) None
    value <- "value"
    value_decl <- R.VarDecl False value (R.MethodCall (R.VarRef state) "next" []) None
    item <- "item"
    some_pattern <- R.VariantPattern "Some" (Some item)
    none_pattern <- R.VariantPattern "None" None
    rust_result_type <- convertType result_type
    some_record_type <- getVariantRecordType program result_type "Some"
    none_record_type <- getVariantRecordType program result_type "None"
    rust_some_record_type <- convertType (MT.Record some_record_type)
    rust_none_record_type <- convertType (MT.Record none_record_type)
    some_record <- getRecord program some_record_type
    item_field <- atIndex some_record.fields 0
    rust_item_type <- convertType item_field.type
    tuple_record <- case item_field.type of
        MT.Record record_id -> getRecord program record_id
        _ -> panic "Tuple is not a record"
    state_field <- atIndex tuple_record.fields 0
    value_field <- atIndex tuple_record.fields 1
    rust_state_type <- convertType state_field.type
    clone_call <- R.MethodCall (R.VarRef item) cloneName []
    state_ctor <- R.StructCtor (show rust_state_type) [R.FieldInitItem innerValueField (R.FunctionCall rcNew [R.VarRef state])]
    tuple_ctor <- R.StructCtor (show rust_item_type) [R.FieldInitItem state_field.name (R.FunctionCall rcNew [state_ctor]),
                                                      R.FieldInitItem value_field.name (R.FunctionCall rcNew [R.VarRef item])]
    some_ctor <- R.StructCtor (show rust_some_record_type) [R.FieldInitItem item_field.name (R.FunctionCall rcNew [tuple_ctor])]
    none_ctor <- R.StructCtor (show rust_none_record_type) []
    some_case <- R.MatchCase some_pattern (R.FunctionCall ("{}::Some" % rust_result_type) [some_ctor])
    none_case <- R.MatchCase none_pattern (R.FunctionCall ("{}::None" % rust_result_type) [none_ctor])
    cases <- [some_case, none_case]
    match <- R.Match (R.VarRef value) cases
    R.Block [state_decl, value_decl, match]

initializeExternalFunctions :: Map ExternalId ExternFnBuilder
initializeExternalFunctions = do
    externals <- Map.empty
    (externals, _) <- insert externals (ExternalId "Std.Util.Basic" "printStr") (ExternFnBuilder generatePrintStr)

    (externals, _) <- insert externals (ExternalId "Std.Ops" "getDiscriminant") (ExternFnBuilder generateGetDiscriminant)
    (externals, _) <- insert externals (ExternalId "Std.Ops" "opAnd") (ExternFnBuilder generateOpAnd)
    (externals, _) <- insert externals (ExternalId "Std.Ops" "opOr") (ExternFnBuilder generateOpOr)

    (externals, _) <- insert externals (ExternalId "Std.Util" "assert") (ExternFnBuilder generateAssert)

    (externals, _) <- insert externals (ExternalId "Hack" "readTextFile") (ExternFnBuilder generateReadTextFile)
    (externals, _) <- insert externals (ExternalId "Hack" "writeTextFile") (ExternFnBuilder generateWriteTextFile)

    (externals, _) <- insert externals (ExternalId "String" "opAdd") (ExternFnBuilder generateStringAdd)
    (externals, _) <- insert externals (ExternalId "String" "partialCmp") (ExternFnBuilder generatePartialCmp)
    (externals, _) <- insert externals (ExternalId "String" "cmp") (ExternFnBuilder generateCmp)
    (externals, _) <- insert externals (ExternalId "String" "opEq") (ExternFnBuilder generateEq)

    (externals, _) <- insert externals (ExternalId "Int" "opAdd") (ExternFnBuilder generateAdd)
    (externals, _) <- insert externals (ExternalId "Int" "opSub") (ExternFnBuilder generateSub)
    (externals, _) <- insert externals (ExternalId "Int" "opMul") (ExternFnBuilder generateMul)
    (externals, _) <- insert externals (ExternalId "Int" "opDiv") (ExternFnBuilder generateDiv)
    (externals, _) <- insert externals (ExternalId "Int" "show") (ExternFnBuilder generateShow)
    (externals, _) <- insert externals (ExternalId "Int" "partialCmp") (ExternFnBuilder generatePartialCmp)
    (externals, _) <- insert externals (ExternalId "Int" "cmp") (ExternFnBuilder generateCmp)
    (externals, _) <- insert externals (ExternalId "Int" "opEq") (ExternFnBuilder generateEq)
    (externals, _) <- insert externals (ExternalId "Int" "opNegative") (ExternFnBuilder generateNegative)
    (externals, _) <- insert externals (ExternalId "Int" "parse") (ExternFnBuilder generateIntParse)

    (externals, _) <- insert externals (ExternalId "Float" "opAdd") (ExternFnBuilder generateAdd)
    (externals, _) <- insert externals (ExternalId "Float" "opSub") (ExternFnBuilder generateSub)
    (externals, _) <- insert externals (ExternalId "Float" "opMul") (ExternFnBuilder generateMul)
    (externals, _) <- insert externals (ExternalId "Float" "opDiv") (ExternFnBuilder generateDiv)
    (externals, _) <- insert externals (ExternalId "Float" "show") (ExternFnBuilder generateShow)
    (externals, _) <- insert externals (ExternalId "Float" "partialCmp") (ExternFnBuilder generatePartialCmp)
    (externals, _) <- insert externals (ExternalId "Float" "opEq") (ExternFnBuilder generateEq)
    (externals, _) <- insert externals (ExternalId "Float" "opNegative") (ExternFnBuilder generateNegative)

    (externals, _) <- insert externals (ExternalId "Char" "partialCmp") (ExternFnBuilder generatePartialCmp)
    (externals, _) <- insert externals (ExternalId "Char" "cmp") (ExternFnBuilder generateCmp)
    (externals, _) <- insert externals (ExternalId "Char" "opEq") (ExternFnBuilder generateEq)
    (externals, _) <- insert externals (ExternalId "Char" "isUppercase") (ExternFnBuilder generateIsUppercase)

    (externals, _) <- insert externals (ExternalId "List" "show") (ExternFnBuilder generateListShow)
    (externals, _) <- insert externals (ExternalId "List" "opEq") (ExternFnBuilder generateEq)
    (externals, _) <- insert externals (ExternalId "List" "atIndex") (ExternFnBuilder generateListAtIndex)
    (externals, _) <- insert externals (ExternalId "List" "getLength") (ExternFnBuilder generateListGetLength)
    (externals, _) <- insert externals (ExternalId "List" "dedup") (ExternFnBuilder generateListDedup)
    (externals, _) <- insert externals (ExternalId "List" "isEmpty") (ExternFnBuilder generateListIsEmpty)
    (externals, _) <- insert externals (ExternalId "List" "sort") (ExternFnBuilder generateListSort)
    (externals, _) <- insert externals (ExternalId "List" "head") (ExternFnBuilder generateListHead)
    (externals, _) <- insert externals (ExternalId "List" "opAdd") (ExternFnBuilder generateListAdd)
    (externals, _) <- insert externals (ExternalId "List" "intoIter") (ExternFnBuilder generateListIntoIter)
    (externals, _) <- insert externals (ExternalId "List" "nextItem") (ExternFnBuilder generateListNextItem)

    externals

generateStringFields :: [MT.Type] -> [R.StructField]
generateStringFields args = [R.StructField innerValueField (typeToRcType (R.Type "std::string::String"))]

generateIntFields :: [MT.Type] -> [R.StructField]
generateIntFields args = [R.StructField innerValueField (typeToRcType (R.Type "i64"))]

generateFloatFields :: [MT.Type] -> [R.StructField]
generateFloatFields args = [R.StructField innerValueField (typeToRcType (R.Type "f64"))]

generateCharFields :: [MT.Type] -> [R.StructField]
generateCharFields args = [R.StructField innerValueField (typeToRcType (R.Type "char"))]

generateListFields :: [MT.Type] -> [R.StructField]
generateListFields args = do
    first <- atIndex args 0
    rust_type_arg <- convertType first
    [R.StructField innerValueField (typeToRcType (R.Type "std::vec::Vec<{}>" % rust_type_arg))]

generateListIteratorFields :: [MT.Type] -> [R.StructField]
generateListIteratorFields args = do
    first <- atIndex args 0
    rust_type_arg <- convertType first
    [R.StructField innerValueField (typeToRcType (R.Type "std::vec::IntoIter<{}>" % rust_type_arg))]

initializeExternalStructFields :: Map ExternalId ExternStructBuilder
initializeExternalStructFields = do
    externals <- Map.empty
    (externals, _) <- insert externals (ExternalId "String" "String") (ExternStructBuilder generateStringFields)
    (externals, _) <- insert externals (ExternalId "Int" "Int") (ExternStructBuilder generateIntFields)
    (externals, _) <- insert externals (ExternalId "Float" "Float") (ExternStructBuilder generateFloatFields)
    (externals, _) <- insert externals (ExternalId "Char" "Char") (ExternStructBuilder generateCharFields)
    (externals, _) <- insert externals (ExternalId "List" "List") (ExternStructBuilder generateListFields)
    (externals, _) <- insert externals (ExternalId "List" "ListIterator") (ExternStructBuilder generateListIteratorFields)
    externals
