module Siko.Transpiler.Rust where

import Siko.Util.Format

data Attribute = Clone

data Variant = { name :: String, type :: Type }

data Enum = { name :: String, variants :: [Variant], attributes :: [Attribute] }

data StructField = { name :: String, type :: Type }

data Struct = { name :: String, fields :: [StructField], attributes :: [Attribute] }

data Type = Type String deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show Type where
    show (Type t) = t

data Function = { name :: String, args :: [Type], result :: Type, body :: Expr }

data FieldInitItem = { name :: String,
                       body :: Expr }

data RangeKind = Inclusive | Exclusive deriving (Show)

data Pattern = IntegerPattern String
               | StringPattern String
               | CharPattern Char
               | CharRangePattern Char Char RangeKind
               | VariantPattern String (Option String)
               | RecordPattern String
               | WildcardPattern

data MatchCase = { pattern :: Pattern, body :: Expr }

data Expr = Block [Expr]
            | FunctionCall String [Expr]
            | IntegerLiteral String
            | StringLiteral String
            | MethodCall Expr String [Expr]
            | FloatLiteral String
            | CharLiteral Char
            | VarDecl Bool String Expr (Option Type)
            | VarRef String
            | FieldAccess String Expr
            | List [Expr]
            | Return Expr
            | Continue Expr
            | Break Expr
            | Ref Expr
            | RecordUpdate String [FieldInitItem]
            | Loop [Expr]
            | Match Expr [MatchCase]
            | StructCtor String [FieldInitItem]
            | Assign Expr Expr

data Program = { structs :: [Struct], enums :: [Enum], functions :: [Function] }

generatePattern :: Pattern -> String
generatePattern pattern = case pattern of
    IntegerPattern lit -> "a if *a.value == {}" % lit
    StringPattern lit -> "a if *a.value == \"{}\"" % lit
    CharPattern lit -> "a if *a.value == '{}'" % lit
    CharRangePattern start end kind -> case kind of
        Exclusive -> "a if std::ops::Range{ start: '{}', end: '{}' }.contains(&a.value)" % (start, end)
        Inclusive -> "a if std::ops::RangeInclusive::new('{}', '{}').contains(&a.value)" % (start, end)
    VariantPattern variant_name var_name -> case var_name of
        Some var_name -> "{}({})" % (variant_name, var_name)
        None -> "{}" % variant_name
    RecordPattern record_name -> "{}{..}" % (record_name)
    WildcardPattern -> "_"

generateExpr :: Expr -> Indent -> String
generateExpr expr indent = case expr of
    Block args -> do
            inner <- inc indent
            args <- args |> List.iter |> map (\arg -> do
                "{}{}" % (inner, generateExpr arg inner)) |> toList
            s <- "{\n{}\n{}}" % (join args ";\n", indent)
            s
    FunctionCall name args -> do
        args <- args |> List.iter |> map (\arg -> generateExpr arg (Indent 0)) |> toList
        "{}({})" % (name, join args ", ")
    StructCtor name fields -> do
        fields <- fields |> List.iter |> map (\field -> do
            "{}: {}" % (field.name, generateExpr field.body (Indent 0))) |> toList
        "{} { {} }" % (name, join fields ", ")
    MethodCall receiver name args -> do
        args <- args |> List.iter |> map (\arg -> generateExpr arg (Indent 0)) |> toList
        receiver <- generateExpr receiver (Indent 0)
        "{}.{}({})" % (receiver, name, join args ", ")
    IntegerLiteral lit -> lit
    FloatLiteral lit -> lit
    StringLiteral lit -> do
        lit <- replace lit "\n" "\\n"
        "\"{}\"" % lit
    CharLiteral lit -> do
        "'{}'" % lit
    VarDecl mutable n rhs type -> case type of
        Some type -> if mutable
                then "let mut {}: {} = {}" % (n, type, generateExpr rhs (Indent 0))
                else "let {}: {} = {}" % (n, type, generateExpr rhs (Indent 0))
        None -> if mutable
                then "let mut {} = {}" % (n, generateExpr rhs (Indent 0))
                else "let {} = {}" % (n, generateExpr rhs (Indent 0))
    VarRef n -> n
    Match body cases -> do
        body <- generateExpr body (Indent 0)
        inner <- inc indent
        cases <- cases |> List.iter |> map (\c -> do
            "{}{} => {{}}" % (inner, generatePattern c.pattern, generateExpr c.body inner)) |> toList
        "match {} {\n{}\n{}}" % (body, join cases "\n", indent)
    FieldAccess name receiver -> do
        receiver <- generateExpr receiver (Indent 0)
        "{}.{}" % (receiver, name)
    Ref rhs -> "&{}" % generateExpr rhs (Indent 0)
    Loop args -> do
            inner <- inc indent
            args <- args |> List.iter |> map (\arg -> do
                "{}{}" % (inner, generateExpr arg inner)) |> toList
            s <- "loop {\n{}\n{}}" % (join args ";\n", indent)
            s
    Break expr -> do
        body <- generateExpr expr (Indent 0)
        "break {}" % body
    Continue expr -> do
        body <- generateExpr expr (Indent 0)
        "continue {}" % body
    Return expr -> do
        body <- generateExpr expr (Indent 0)
        "return {}" % body
    Assign lhs rhs -> do
        "{} = {}" % (generateExpr lhs (Indent 0), generateExpr rhs (Indent 0))
    List args -> do
        args <- args |> List.iter |> map (\arg -> do
                "{}" % generateExpr arg (Indent 0)) |> toList
        "vec![{}]" % (join args ", ")
    _ -> "NYI"

generateStruct :: Struct -> String
generateStruct struct = do
    indent <- Indent 2
    fields <- struct.fields |> List.iter |> fold (\fields, field -> do
        f <- "{}{}: {}," % (indent, field.name, field.type)
        fields <- fields + [f]
        fields) []
    content <- ""
    content <- struct.attributes |> List.iter |> fold (\content, attribute -> do
        case attribute of
            Clone -> content + "#[derive(Clone)]\n") content
    content + "struct {} {\n{}\n}" % (struct.name, join fields "\n")

generateEnum :: Enum -> String
generateEnum enum = do
    indent <- Indent 2
    variants <- enum.variants |> List.iter |> fold (\variants, variant -> do
        v <- "{}{}({})," % (indent, variant.name, variant.type)
        variants <- variants + [v]
        variants) []
    content <- ""
    content <- enum.attributes |> List.iter |> fold (\content, attribute -> do
        case attribute of
            Clone -> content + "#[derive(Clone)]\n") content
    content + "enum {} {\n{}\n}" % (enum.name, join variants "\n")

generateFunction :: Function -> String
generateFunction function = do
    (args, _) <- function.args |> List.iter |> fold (\(args, index), arg -> do
        s <- "arg{}: {}" % (index, arg)
        args <- args + [s]
        (args, index + 1)) ([], 0)
    signature <- "fn {}({}) -> {}" % (function.name, join args ", ", function.result)
    indent <- Indent 0
    body <- generateExpr function.body indent
    signature + " " + body

generateProgram :: Program -> String
generateProgram program = do
    content <- ""
    content <- content + "#![allow(non_snake_case)]\n"
    content <- content + "#![allow(non_camel_case_types)]\n"
    content <- content + "#![allow(unused_variables)]\n"
    content <- content + "#![allow(dead_code)]\n"
    content <- content + "#![allow(unused_parens)]\n"
    content <- program.structs |> List.iter |> fold (\content, s -> content + "\n\n" + generateStruct s) content
    content <- program.enums |> List.iter |> fold (\content, e -> content + "\n\n" + generateEnum e) content
    content <- program.functions |> List.iter |> fold (\content, f -> content + "\n\n" + generateFunction f) content
    content <- content + "\n\nfn main() {\n{}Main_main_0();\n}" % (Indent 2)
    content