module Std.Arch.Fs {

pub let O_RDONLY : I32 = 0x0.as_i32();
pub let O_WRONLY : I32 = 0x1.as_i32();
pub let O_RDWR   : I32 = 0x2.as_i32();
pub let O_CREAT  : I32 = 0x200.as_i32();
pub let O_TRUNC  : I32 = 0x400.as_i32();
pub let O_APPEND    : I32 = 0x8.as_i32();
pub let O_NONBLOCK  : I32 = 0x4.as_i32();
pub let O_CLOEXEC   : I32 = 0x01000000.as_i32();

pub let F_GETFL : I32 = 3.as_i32();
pub let F_SETFL : I32 = 4.as_i32();

}
