module Siko.MIR.Cache where

import Json
import Json.Serialize
import Siko.Cache
import Siko.MIR.Program
import Siko.MIR.Data as MD
import Siko.MIR.Function as MF

instance CacheEntry MF.Function where
    getCacheFileName f = "{}.json" % f.id

instance CacheEntry MD.AlgebraicDataType where
    getCacheFileName adt = "{}.json" % adt.id

instance CacheEntry MD.Record where
    getCacheFileName record = "{}.json" % record.id

instance CacheEntry Program where
    getCacheFileName p = "program.json"
