module Siko.CBackend.Util {

import Siko.AST.Expr
import Siko.AST.QualifiedName
import Siko.AST.Data
import Siko.Interner as I

pub fn mangle(name: String) -> String {
    let s = name.trim_start_matches("$");
    let result = "";
    let prev_sep = False;
    for c in s.chars() {
        match c {
            '(' => {
                result = result + "_lp_";
                prev_sep = False;
            }
            ')' => {
                result = result + "_rp_";
                prev_sep = False;
            }
            '*' => {
                result = result + "ptr_";
                prev_sep = False;
            }
            '.' | '[' | '{' | ',' | '-' | '<' | '>' | ':' | '!' | '@' | '&' | '+' | '='
            | '|' | '^' | '~' | '?' | '/' | '\\' | '#' => {
                if !prev_sep {
                    result = result + "_";
                }
                prev_sep = True;
            }
            ']' | '}' | ' ' | '\'' | '`' | '"' | ';' => {}
            _ => {
                result = result + String.from_byte(c);
                prev_sep = False;
            }
        }
    }
    loop {
        if !result.ends_with("__") { break; }
        result = result.strip_suffix("__").unwrap();
    }
    result
}

pub fn var_name(n: VariableName) -> String {
    mangle(n.format())
}

pub fn fn_name(qualified_name: QualifiedName) -> String {
    mangle(qualified_name.hashed())
}

pub fn variant_struct_name(edef: EnumDef, variant: VariantDef) -> String {
    mangle("${edef.qualified_name.unwrap().hashed()}.${variant.name.name()}")
}

pub fn variant_payload_name(variant: VariantDef) -> String {
    "v_${I.resolve(variant.name.name())}"
}

pub fn variant_field_name(index: Int) -> String {
    "field_${index}"
}

}