module Siko.HIR.FullyQualifiedName where

import Siko.Syntax.Location
import Siko.HIR.Function as F
import Siko.HIR.Effect as Eff
import Siko.HIR.Class as C
import Siko.HIR.Type as T
import Siko.HIR.TypeFormatter as TF
import Siko.Util.SharedString as SS

data FullyQualifiedName = FullPath SS.SharedString SS.SharedString
                        | FullPathWithVariant SS.SharedString SS.SharedString SS.SharedString
                        | FullPathWithLambda FullyQualifiedName F.LambdaId
                        | FullPathInstance SS.SharedString Location
                        | FullPathWithInstanceId SS.SharedString SS.SharedString FullyQualifiedName
                        | ModulePath SS.SharedString
                        | SubItem FullyQualifiedName SS.SharedString
                        | Effectless FullyQualifiedName Eff.EffectResolutionSet
                        | Monomorphized FullyQualifiedName T.Type
                        deriving (PartialEq, Eq, PartialOrd, Ord)

instance Show FullyQualifiedName where
    show f = case f of
        FullPath m n -> "{}.{}" % (m, n)
        FullPathWithVariant m n v -> "{}.{}/{}" % (m, n, v)
        FullPathWithLambda n i -> "{}/{}" % (n, i)
        FullPathInstance m l -> "{}/{}" % (m, l)
        FullPathWithInstanceId m n i -> "{}.{}/#{}" % (m, n, i)
        ModulePath m -> "{}" % m
        SubItem p n -> "{}/{}" % (p, n)
        Effectless n s -> "{}=[{}]" % (n, s)
        Monomorphized n type -> "{}=[{}]" % (n, TF.toString type)

getResolvableName :: FullyQualifiedName -> SS.SharedString
getResolvableName f = do
    s <- case f of
        FullPath m n -> "{}.{}" % (m, n)
        FullPathWithVariant m n v -> "{}.{}" % (m, v)
        FullPathWithLambda n i -> panic "getResolvableName called for a lambda"
        FullPathInstance m l -> panic "getResolvableName called for a instance"
        FullPathWithInstanceId m n i -> panic "getResolvableName called for a instance member"
        ModulePath m -> panic "getResolvableName called for a module"
        SubItem p n -> panic "getResolvableName called for a sub item"
        Effectless n s -> return getResolvableName n
        Monomorphized n type -> return getResolvableName n
    SS.create s

getShortName :: FullyQualifiedName -> SS.SharedString
getShortName f = case f of
        FullPath m n -> n
        FullPathWithVariant m n v -> n
        FullPathWithLambda n i -> SS.create "{}_lambda" % getShortName n
        FullPathInstance m l -> SS.create "{}/#{}" % (m, l)
        FullPathWithInstanceId m n i -> n
        ModulePath m -> m
        SubItem p n -> n
        Effectless n s -> getShortName n
        Monomorphized n type -> getShortName n

getModuleName :: FullyQualifiedName -> SS.SharedString
getModuleName f = case f of
        FullPath m n -> m
        FullPathWithVariant m n v -> m
        FullPathWithLambda n i -> getModuleName n
        FullPathInstance m l -> m
        FullPathWithInstanceId m n i -> m
        ModulePath m -> m
        SubItem p n -> getModuleName p
        Effectless n s -> getModuleName n
        Monomorphized n type -> getModuleName n
