module Main where

data TypeVar = TypeVar Int

data Foo = Foo

data VarGen = { index :: Int }

getNewTypeVar :: VarGen -> (VarGen, TypeVar)
getNewTypeVar var_gen = (VarGen 0, TypeVar 0)

main = do
    state <- VarGen 0
    fn <- (\var_gen -> getNewTypeVar var_gen)
    (_, items) <- loop (state, items, c) <- (state, Foo, 0) do
        if c < 10
            then do
                (state, item) <- fn state
                (state, items, c + 1)
            else break (state, items)
    state
    ()