module Siko.Syntax.Effect where

import Siko.Syntax.Class
import Siko.Syntax.Function
import Siko.Syntax.Ident
import Siko.Syntax.Module as M
import Siko.Syntax.TypeSignature(TypeSignature)
import Json
import Json.Serialize

data Effect = { name :: Ident,
                arguments :: [Ident],
                constraints :: [Constraint],
                members :: [M.Item]
              } deriving (Show, PartialEq, Eq, FromJson, ToJson)
