module Main {

effect MyEffect {
    type Foo

    fn op1()
    fn op2()
    fn op3()
}

fn foo() {
    op1();
    op2();
    op3();
}

struct Q {

}

instance Stuff MyEffect {
    type Foo = Q
    type Bar = Q
    fn op1() {
        println("op1");
    }
    fn op2() {
        println("op2");
    }
    fn op3() -> Int {
        println("op3");
        4
    }
}

fn main() {
    with MyEffect = Stuff {
            foo();
    }
}

}