module Main where

import Std.Util

data Person2 = { title :: String, age :: Int }
data Person = { name :: String, age :: Int }
data Empty = { }

createPerson name = Person { name = name, age = 5 }

ambiguousSet :: Person -> Person
ambiguousSet person = person { age = 6 }

nonAmbiguousSet person = person { name = "Beth", age = 6 }

main = do
    lily <- createPerson "Lily"
    john <- createPerson "John"
    lily <- nonAmbiguousSet lily
    john <- ambiguousSet john
    msg <- "{} and {} are {} years old together" % (lily.name, john.name, lily.age + john.age)
    assert (msg == "Beth and John are 12 years old together")
    
