module Siko.MIR.Backend.Ownership.V3.Lowering.LoweringInfo where

import Siko.MIR.Backend.Ownership.V3.TypeVariableInfo
import Siko.MIR.Backend.Ownership.V3.TypeVariableAllocator
import Siko.MIR.Backend.Ownership.V3.MemberInfo as M
import Siko.MIR.Backend.Ownership.V3.InferenceInfo
import Siko.MIR.Backend.Ownership.V3.Duplicator
import Siko.MIR.Backend.Ownership.V3.Lowering.LoweringInfo.Filter

import Map
import Set

data FunctionLoweringInfo = { members :: [M.MemberInfo],
                              args :: [TypeVariableInfo],
                              result :: TypeVariableInfo,
                              ownershipinfos :: [M.OwnershipInfo],
                              max :: Int,
                            } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data TypeLoweringInfo = { members :: [M.MemberInfo],
                          root :: TypeVariableInfo,
                          ownershipinfos :: [M.OwnershipInfo],
                          max :: Int,
                        } deriving (PartialEq, Eq, PartialOrd, Ord, Show)

data LoweringInfo = Function FunctionLoweringInfo
                  | Type TypeLoweringInfo
                  deriving (PartialEq, Eq, PartialOrd, Ord, Show)

createFunctionLoweringInfo :: [TypeVariableInfo] -> TypeVariableInfo -> LoweringInfo
createFunctionLoweringInfo args result = Function (FunctionLoweringInfo [] args result [] 0)

convertToFunctionLoweringInfo :: InferenceInfo -> [TypeVariableInfo] -> TypeVariableInfo -> LoweringInfo
convertToFunctionLoweringInfo inference_info args result = do
    //println "Creating function lowering info"
    lowering_info <- Function (FunctionLoweringInfo inference_info.members args result
            (toOwnershipInfo inference_info.ownership_values False) 0)
    //println "Unfiltered {}" % lowering_info
    sources <- List.push args result
    println "sources {}" % sources
    filterInfo lowering_info sources

createTypeLoweringInfoFromInferenceInfo :: InferenceInfo -> TypeVariableInfo -> LoweringInfo
createTypeLoweringInfoFromInferenceInfo inference_info root = do
    //println "Creating type lowering info"
    lowering_info <- Type (TypeLoweringInfo inference_info.members root
            (toOwnershipInfo inference_info.ownership_values False) 0)
    filterInfo lowering_info [root]

createTypeLoweringInfoFromLoweringInfo :: LoweringInfo -> TypeVariableInfo -> LoweringInfo
createTypeLoweringInfoFromLoweringInfo lowering_info root = do
    //println "Creating type lowering info"
    case lowering_info of
        Function info -> do
            output <- Type (TypeLoweringInfo info.members root info.ownershipinfos 0)
            filterInfo output [root]
        Type info -> do
            output <- Type (TypeLoweringInfo info.members root info.ownershipinfos 0)
            filterInfo output [root]

collectBorrows :: LoweringInfo -> Set TypeVariable
collectBorrows lowering_info =
    case lowering_info of
        Function function -> List.fold Set.empty function.ownershipinfos addBorrow
        Type type -> List.fold Set.empty type.ownershipinfos addBorrow
    where
        addBorrow :: Set TypeVariable -> M.OwnershipInfo -> Set TypeVariable
        addBorrow borrows ownershipinfo =
            case ownershipinfo of
                M.Owner _ -> borrows
                M.Borrower v _ -> Set.put borrows v

data Direction = Up | Down

normalizeRef :: LoweringInfo -> (LoweringInfo, Bool)
normalizeRef lowering_info =
    case lowering_info of
        Function _ -> panic "normalizeRef called on function lower info"
        Type type -> do
            ownershipinfos <- type.ownershipinfos
            (ownershipinfos, is_ref) <- List.fold ([], False) ownershipinfos (\(ownershipinfos, is_ref), ownershipinfo ->
                case ownershipinfo of
                    M.Borrower v _ -> if v == type.root.ownership_var
                        then (List.push ownershipinfos (M.Owner v), True)
                        else (List.push ownershipinfos ownershipinfo, is_ref)
                    _ -> (List.push ownershipinfos ownershipinfo, is_ref))
            lowering_info <- Type (type { ownershipinfos = ownershipinfos })
            lowering_info <- normalizeLoweringInfo lowering_info
            (lowering_info, is_ref)

normalizeLoweringInfo :: LoweringInfo -> LoweringInfo
normalizeLoweringInfo lowering_info =
    // FIXME: we need a better normalization algorithm
    // that is more robust
    case lowering_info of
        Function info -> do
            duplicator <- createNormalizer
            (duplicator, args) <- List.mapS duplicator info.args duplicate
            (duplicator, result) <- duplicate duplicator info.result
            (duplicator, members) <- List.mapS duplicator info.members duplicate
            (duplicator, ownershipinfos) <- List.mapS duplicator info.ownershipinfos duplicate
            members <- members |> sort
            ownershipinfos <- ownershipinfos |> sort
            Function (FunctionLoweringInfo members args result ownershipinfos (getMax duplicator))
        Type info -> do
            duplicator <- createNormalizer
            (duplicator, root) <- duplicate duplicator info.root
            (duplicator, members) <- List.mapS duplicator info.members duplicate
            (duplicator, ownershipinfos) <- List.mapS duplicator info.ownershipinfos duplicate
            members <- members |> sort
            ownershipinfos <- ownershipinfos |> sort
            Type (TypeLoweringInfo members root ownershipinfos (getMax duplicator))

getLoweringInfoForArg :: LoweringInfo -> Int -> LoweringInfo
getLoweringInfoForArg lowering_info index = do
    case lowering_info of
        Function info -> do
            arg <- atIndex info.args index
            createTypeLoweringInfoFromLoweringInfo lowering_info arg
        Type info -> panic "getLoweringInfoForArg called on type lowering info"

getLoweringInfoForResult :: LoweringInfo -> LoweringInfo
getLoweringInfoForResult lowering_info = do
    case lowering_info of
        Function info -> createTypeLoweringInfoFromLoweringInfo lowering_info info.result
        Type info -> panic "getLoweringInfoForResult called on type lowering info"

getLoweringInfoForMember :: LoweringInfo -> String -> LoweringInfo
getLoweringInfoForMember lowering_info name = do
    case lowering_info of
        Function info -> panic "getLoweringInfoForMember called on function lowering info"
        Type info -> do
            memberConstraint <- List.filter info.members (\constraint -> case constraint of
                    M.Member n root member_info -> n == name && info.root.arg_group_var == root
                    _ -> False)
            case head memberConstraint of
                Some (M.Member name root member_info) -> createTypeLoweringInfoFromLoweringInfo lowering_info member_info
                Some _ -> panic "memberConstraint is not a memberConstraint"
                None -> do
                    root <- createRoot
                    Type (TypeLoweringInfo [] root [M.Owner root.ownership_var] 0)

getLoweringInfoForVariant :: LoweringInfo -> Int -> LoweringInfo
getLoweringInfoForVariant lowering_info index = do
    case lowering_info of
        Function info -> panic "getLoweringInfoForVariant called on function lowering info"
        Type info -> do
            variantConstraint <- List.filter info.members (\constraint -> case constraint of
                    M.Variant i root member_info -> i == index && info.root.arg_group_var == root
                    _ -> False)
            case head variantConstraint of
                Some (M.Variant index root member_info) ->
                    createTypeLoweringInfoFromLoweringInfo lowering_info member_info
                Some _ -> panic "variantConstraint is not a variantConstraint"
                None -> do
                    root <- createRoot
                    Type (TypeLoweringInfo [] root [M.Owner root.ownership_var] 0)