module Siko.MIR.Backend.Ownership.V3.Lowering.Type where

import Siko.MIR.Backend.Ownership.V3.Lowering.Context
import Siko.MIR.Backend.Ownership.V3.Lowering.Naming
import Siko.MIR.Backend.Ownership.V3.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.V3.TypeVariableInfo
import Siko.MIR.Backend.Ownership.V3.MemberInfo as M
import Siko.LIR.Type as LT
import Siko.MIR.Type as MT
import Siko.LIR.Function as LF
import Siko.MIR.Function as MF

lowerType :: Context -> LoweringInfo -> MT.Type -> (Context, LT.Type)
lowerType context lowering_info mir_type = do
    case mir_type of
        MT.Record id _ -> do
            //println "Record input {}" % lowering_info
            lowering_info <- normalizeLoweringInfo lowering_info
            (lowering_info, is_ref) <- normalizeRef lowering_info
            lir_key <- RecordKey id lowering_info
            context <- addItem context lir_key
            (context, lir_id) <- getLIRId context lir_key
            //println "lowerType: {} {} {}" % (lir_id, lir_key, lowering_info)
            lifetimes <- collectLifetimes lowering_info
            if is_ref
            then (context, LT.Ref (LT.Lifetime 0) (LT.Record lir_id lifetimes)) // FIXME lifetime
            else (context, LT.Record lir_id lifetimes)
        MT.Adt id _ -> do
            lowering_info <- normalizeLoweringInfo lowering_info
            (lowering_info, is_ref) <- normalizeRef lowering_info
            lir_key <- AdtKey id lowering_info
            context <- addItem context lir_key
            (context, lir_id) <- getLIRId context lir_key
            //println "lowerType: {} {}" % (lir_id, lir_key)
            lifetimes <- collectLifetimes lowering_info
            if is_ref
            then (context, LT.Ref (LT.Lifetime 0) (LT.Adt lir_id lifetimes)) // FIXME lifetime
            else (context, LT.Adt lir_id lifetimes)
        _ -> (context, LT.Never)

lowerFunctionType :: Context -> LoweringInfo -> MF.FunctionType -> (Context, LF.FunctionType, [LT.Lifetime])
lowerFunctionType context lowering_info mir_function_type = do
    //println "lowerFunctionType {}" % lowering_info
    (context, args) <- List.mapSE context mir_function_type.args (\context, index, arg_type -> do
        lowering_info <- getLoweringInfoForArg context.config lowering_info index
        lowerType context lowering_info arg_type)
    (context, result) <- lowerType context (getLoweringInfoForResult context.config lowering_info) mir_function_type.result
    lifetimes <- collectLifetimes lowering_info
    (context, LF.FunctionType args result, lifetimes)

collectLifetimes :: LoweringInfo -> [LT.Lifetime]
collectLifetimes lowering_info = do
        lifetimes <- case lowering_info of
                Function function -> List.fold [] function.ownershipinfos addLifetime
                Type type -> List.fold [] type.ownershipinfos addLifetime
        lifetimes |> sort |> dedup
    where
        addLifetime :: [LT.Lifetime] -> M.OwnershipInfo -> [LT.Lifetime]
        addLifetime lifetimes ownershipinfo =
            case ownershipinfo of
                M.Owner _ -> lifetimes
                M.Borrower v i -> List.push lifetimes (LT.Lifetime i)
