module Siko.ClosureLowering.ProfileBuilder {

import Std.Map
import Siko.AST.QualifiedName
import Siko.ClosureLowering.InferProfiles
import Siko.ClosureLowering.Profile
import Siko.ClosureLowering.Statistics
import Siko.HIR.Program

pub struct ProfileBuildResult {
    pub profiles: Map[QualifiedName, FunctionProfile],
}

pub fn build_profiles(program: Program) -> ProfileBuildResult {
    stats.profile_build_start();
    defer stats.profile_build_end();
    let profiles = infer_profiles(program);
    ProfileBuildResult(profiles)
}

}
