module Libc.Fcntl {

import Libc.FileDescriptor
import Libc.String
import IO.Error
import Arch.Errno

fn open(path: *U8, flags: I32, ...) -> I32 = extern "C"

@safe
pub fn openFile(path: &String, flags: I32, mode: I32) -> Result[FileDescriptor, Error] {
    let cPath = CString.fromString(path.clone());
    let fd = open(cPath.asPtr(), flags, mode);
    if fd < 0.toI32() {
        let err = Arch.Errno.getErrnoCode();
        return Err(Error.new(err));
    }
    Ok(FileDescriptor(fd: fd))
}

}