module Std.Libc.Pthread {

import Std.Arch.Pthread

@extern("C")
pub fn pthread_attr_init(attr: *PthreadAttr) -> I32

@extern("C", "", "GC_pthread_create")
pub fn gc_pthread_create(thread: *PThread,
                         attr: *PthreadAttr,
                         start_routine: fn*(void*) -> void*, arg: void*) -> I32

@extern("C")
pub fn pthread_mutex_lock(mutex: *Mutex) -> I32

@extern("C")
pub fn pthread_mutex_unlock(mutex: *Mutex) -> I32

@extern("C")
pub fn pthread_mutex_init(mutex: *Mutex, attr: *MutexAttr) -> I32

@extern("C")
pub fn pthread_mutexattr_init(attr: *MutexAttr) -> I32

}