module Main where

import Std.Util

main = do
       b <- ['\n', '\t', '\r', '\\', '\'']
       a <- case 'g' of
            'a'..'g' -> assert False
            'a'..='g' -> assert True
            '\'' -> assert False
            '\\' -> assert False
            '\r' -> assert False
            '\n' -> assert False
            '\t' -> assert False
            '"' -> assert False
            _ -> assert False
