@prelude
module Std.Int.I8 {

import Std.Intrinsics

@builtin
pub struct I8 {
    @builtin
    @op(eq)
    pub fn eq(a: I8, b: I8) -> Bool

    @builtin
    @op(lt)
    pub fn lt(a: I8, b: I8) -> Bool

    @builtin
    @op(add)
    pub fn add(a: I8, b: I8) -> I8

    @builtin
    @op(sub)
    pub fn sub(a: I8, b: I8) -> I8

    @builtin
    @op(mul)
    pub fn mul(a: I8, b: I8) -> I8

    @builtin
    @op(div)
    pub fn div(a: I8, b: I8) -> I8

    @builtin
    @op(neg)
    pub fn neg(a: I8) -> I8

    @builtin
    @op(mod)
    pub fn mod(a: I8, b: I8) -> I8

    @builtin
    @op(band)
    pub fn band(a: I8, b: I8) -> I8

    @builtin
    @op(bor)
    pub fn bor(a: I8, b: I8) -> I8

    @builtin
    @op(xor)
    pub fn bxor(a: I8, b: I8) -> I8

    @builtin
    @op(not)
    pub fn not(a: I8) -> I8

    @builtin
    @op(shl)
    pub fn shl(a: I8, n: I8) -> I8

    @builtin
    @op(shr)
    pub fn shr(a: I8, n: I8) -> I8

    @safe
    pub fn as_int(a: I8) -> Int {
        transmute(a)
    }
}

instance PartialEq[I8] {
    fn eq(a: I8, b: I8) -> Bool {
        a.eq(b)
    }
}

instance Eq[I8] {}

instance PartialOrd[I8] {
    fn partial_cmp(a: I8, b: I8) -> Option[Ordering] {
        if a.eq(b) {
            Some(Ordering.Equal)
        } else {
            if a.lt(b) {
                Some(Ordering.Less)
            } else {
                Some(Ordering.Greater)
            }
        }
    }
}

instance Ord[I8] {
    fn cmp(a: I8, b: I8) -> Ordering {
        if a.eq(b) {
            Ordering.Equal
        } else {
            if a.lt(b) {
                Ordering.Less
            } else {
                Ordering.Greater
            }
        }
    }
}

instance Add[I8] {
    type Output = I8
    fn add(a: I8, b: I8) -> I8 {
        a.add(b)
    }
}

instance Sub[I8] {
    type Output = I8
    fn sub(a: I8, b: I8) -> I8 {
        a.sub(b)
    }
}

instance Mul[I8] {
    type Output = I8
    fn mul(a: I8, b: I8) -> I8 {
        a.mul(b)
    }
}

instance Div[I8] {
    type Output = I8
    fn div(a: I8, b: I8) -> I8 {
        a.div(b)
    }
}

instance Mod[I8] {
    type Output = I8
    fn mod(a: I8, b: I8) -> I8 {
        a.mod(b)
    }
}

instance Neg[I8] {
    type Output = I8
    fn neg(a: I8) -> I8 {
        a.neg()
    }
}

instance BitAnd[I8] {
    type Output = I8
    fn band(a: I8, b: I8) -> I8 {
        a.band(b)
    }
}

instance BitOr[I8] {
    type Output = I8
    fn bor(a: I8, b: I8) -> I8 {
        a.bor(b)
    }
}

instance BitXor[I8] {
    type Output = I8
    fn bxor(a: I8, b: I8) -> I8 {
        a.bxor(b)
    }
}

instance Shl[I8] {
    type Output = I8
    fn shl(a: I8, b: I8) -> I8 {
        a.shl(b)
    }
}

instance Shr[I8] {
    type Output = I8
    fn shr(a: I8, b: I8) -> I8 {
        a.shr(b)
    }
}

instance BNot[I8] {
    type Output = I8
    fn bnot(a: I8) -> I8 {
        a.not()
    }
}

instance ToString[I8] {
    fn to_string(a: I8) -> String {
        a.as_int().to_string()
    }
}

instance Clone[I8] {
    fn clone(a: I8) -> I8 {
        a
    }
}

}
