module Terminal {

pub fn yellow(mut s: &String) -> String {
    let mut yellow = String.new();
    yellow.pushChar(27.toU8());
    yellow.pushChar('[');
    yellow.pushChar('3');
    yellow.pushChar('3');
    yellow.pushChar('m');
    yellow = yellow + s;
    yellow.pushChar(27.toU8());
    yellow.pushChar('[');
    yellow.pushChar('0');
    yellow.pushChar('m');
    return yellow;
}

pub fn green(mut s: &String) -> String {
    let mut green = String.new();
    green.pushChar(27.toU8());
    green.pushChar('[');
    green.pushChar('3');
    green.pushChar('2');
    green.pushChar('m');
    green = green + s;
    green.pushChar(27.toU8());
    green.pushChar('[');
    green.pushChar('0');
    green.pushChar('m');
    return green;
}

pub fn red(mut s: &String) -> String {
    let mut red = String.new();
    red.pushChar(27.toU8());
    red.pushChar('[');
    red.pushChar('3');
    red.pushChar('1');
    red.pushChar('m');
    red = red + s;
    red.pushChar(27.toU8());
    red.pushChar('[');
    red.pushChar('0');
    red.pushChar('m');
    return red;
}

}
