module Siko.HIR.Type(Type(..),
                     TypeVar(..),
                     Constraint(..),
                     RowKind(..),
                     collectVars,
                     getArgs,
                     getArgsLimited,
                     getResultType,
                     isConcreteType,
                     isFunction,
                     removeFixed,
                     removeOwnership,
                     traverse,
                     getNameFromType) where

import Siko.HIR.FullyQualifiedName
import Siko.Util.SharedString as SS

data TypeVar = TypeVar Int deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data RowKind = NamedRow SS.SharedString
             | IndexedRow Int
             deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Constraint = ClassConstraint FullyQualifiedName [Type]
                | RowConstraint RowKind Type
                deriving (Show, PartialEq, Eq, PartialOrd, Ord)

data Type = Var TypeVar [Constraint]
          | FixedTypeArg SS.SharedString TypeVar [Constraint]
          | Named FullyQualifiedName [Type]
          | Function Type Type
          | Never TypeVar
          | Ref Int Type
          | Owner Type
          | Tuple [Type]
          deriving (Show, PartialEq, Eq, PartialOrd, Ord)

isFunction :: Type -> Bool
isFunction type = case type of
    Function _ _ -> True
    _ -> False

collectVarsFromConstraints :: [Constraint] -> [TypeVar]
collectVarsFromConstraints constraints = List.fold [] constraints (\all, c -> case c of
                ClassConstraint _ associated_types -> List.fold all associated_types (\all, ty -> all + collectVars ty)
                RowConstraint _ row_type -> all + collectVars row_type)

collectVars :: Type -> [TypeVar]
collectVars type = case type of
    Var var constraints -> [var] + collectVarsFromConstraints constraints
    FixedTypeArg _ var constraints -> [var] + collectVarsFromConstraints constraints
    Named _ args -> List.fold [] args (\vars, arg -> do
        vs <- collectVars arg
        vars + vs)
    Function from to -> collectVars from + collectVars to
    Never var -> [var]
    Ref _ t -> collectVars t
    Owner t -> collectVars t
    Tuple args -> List.fold [] args (\vars, arg -> do
        vs <- collectVars arg
        vars + vs)

getArgs :: Type -> [Type]
getArgs type =
    case type of
        Function from to -> [from] + getArgs to
        _ -> []

getArgsLimited :: Type -> Int -> [Type]
getArgsLimited type limit = if limit == 0 then []
    else case type of
        Function from to -> [from] + getArgsLimited to (limit - 1)
        _ -> []

getResultType :: Type -> Int -> Type
getResultType type arg_count =
    case type of
        Function from to -> if arg_count == 0 then type else getResultType to (arg_count - 1)
        _ -> type

isConcreteType :: Type -> Bool
isConcreteType type = case type of
    Var _ _ -> False
    FixedTypeArg _ _ _ -> False
    Named _ args -> args |> List.iter |> Iterator.fold (\concrete, arg -> do
        concrete && isConcreteType arg) True
    Function from to -> isConcreteType from && isConcreteType to
    Never var -> True
    Ref _ t -> isConcreteType t
    Owner t -> isConcreteType t
    Tuple args -> args |> List.iter |> Iterator.fold (\concrete, arg -> do
        concrete && isConcreteType arg) True

traverseConstraints :: (Type -> Type) -> Constraint -> Constraint
traverseConstraints f constraint = case constraint of
    ClassConstraint qn associated_types -> ClassConstraint qn (List.map associated_types (traverse f))
    RowConstraint kind type -> RowConstraint kind (traverse f type)

traverse :: (Type -> Type) -> Type -> Type
traverse f type = case type of
    Var _ _ -> f type
    FixedTypeArg name var constraints -> f (FixedTypeArg name var (List.map constraints (traverseConstraints f)))
    Named qn args -> do
        args <- List.map args (traverse f)
        f (Named qn args)
    Function from to -> do
        from <- traverse f from
        to <- traverse f to
        f (Function from to)
    Never var -> f type
    Ref lifetime t -> f (Ref lifetime (traverse f t))
    Owner t -> f (Owner (traverse f t))
    Tuple args -> do
        args <- List.map args (traverse f)
        f (Tuple args)

removeFixed :: Type -> Type
removeFixed type = traverse removeFixed_ type // FIXME: name!
    where removeFixed_ type = case type of
            FixedTypeArg _ var constraints -> Var var constraints
            _ -> type

removeOwnership :: Type -> Type
removeOwnership type = traverse removeOwnership_ type // FIXME: name!
    where removeOwnership_ type = case type of
        Ref _ t -> t
        Owner t -> t
        _ -> type

getNameFromType :: Type -> FullyQualifiedName
getNameFromType type = case type of
    Named qn _ -> qn
    _ -> panic "getNameFromType: type is not Named!"
