module ExportTest(foo) where

foo = 5

module Foo where

data A = A Int

data A2 = A2 Int | Boo

module Main where

import Foo
import Std.Util
import ExportTest

checker :: A -> String
checker a =
    case a of
        A x -> "{}" % x

checker2 :: A2 -> String
checker2 a =
    case a of
        A2 x -> "{}" % x
        Boo -> "boo"

main = do
    a <- A foo
    assert ("5" == checker a)
    a <- A2 foo
    assert ("5" == checker2 a)
