module Main {

effect Logger {
    fn log(msg: String)
}

effect Alarm {
    fn alert(msg: String)
}

fn console_log(msg: String) {
    println("console")
}

fn system_alert(msg: String) {
    println("system_alert")
}

fn another_alert(msg: String) {
    println("another_alert")
}

fn bar() {
    Logger.log("hello");
    Alarm.alert("world")
}

fn foo() {
    with alert = another_alert {
        bar()
    }
}

fn main() {
    with log = console_log, alert = system_alert {
        foo()
    }
}
}
