module Siko.MIR.Backend.Ownership.Lowering.LoweringInfo.Filter where

import Siko.Config
import Siko.Trace
import Siko.Util.DependencyProcessorLinear
import Siko.MIR.Backend.Ownership.GroupDependencyMap
import Siko.MIR.Backend.Ownership.OwnershipDependencyMap
import Siko.MIR.Backend.Ownership.TypeVariableInfo
import Siko.MIR.Backend.Ownership.MemberInfo as M
import Siko.MIR.Backend.Ownership.Lowering.LoweringInfo
import Siko.MIR.Backend.Ownership.Allocator
import Siko.MIR.Backend.Ownership.OrderedDependencyMap

import Map
import Map2
import Set
import List2 as List2
import List2 (List2)

data FilterInfo = { ordered_dep_map :: Map2 TypeVariable (List2 TypeVariableInfo),
                    ownership_dep_map :: Map2 TypeVariable (List2 TypeVariable)
                   }

getFilterInfoFromTypeLoweringInfo :: Config -> TypeLoweringInfo -> (TypeLoweringInfo, FilterInfo)
getFilterInfoFromTypeLoweringInfo config lowering_info = do
    (members, ordered_dep_map) <- getOrderedDependencyMap lowering_info.members
    (members, ownership_dep_map) <- calculateOwnershipDepMap config lowering_info.members
    (lowering_info { members = members }, FilterInfo ordered_dep_map ownership_dep_map)

getFilterInfoFromFunctionLoweringInfo :: Config -> FunctionLoweringInfo -> (FunctionLoweringInfo, FilterInfo)
getFilterInfoFromFunctionLoweringInfo config lowering_info = do
    (members, ordered_dep_map) <- getOrderedDependencyMap lowering_info.members
    (members, ownership_dep_map) <- calculateOwnershipDepMap config lowering_info.members
    (lowering_info { members = members }, FilterInfo ordered_dep_map ownership_dep_map)

filterMember :: List2 TypeVariableInfo -> List2 TypeVariable -> M.MemberInfo -> Bool
filterMember infos vars member =
    case member of
        M.Variant index ty root info -> List2.contains infos info && List2.contains vars root
        M.Field name ty root info -> List2.contains infos info && List2.contains vars root
        M.Extern index ty root info -> List2.contains infos info && List2.contains vars root

filterTypeLoweringInfo :: Config -> TypeLoweringInfo -> List2 TypeVariableInfo -> FilterInfo -> (TypeLoweringInfo, FilterInfo)
filterTypeLoweringInfo config lowering_info sources filter_info = do
    //trace config "------------ start filterInfo {} / {}-----------" % (lowering_info, sources)
    (members, ownershipinfos, allocator, filter_info) <- filterLoweringInfo config sources lowering_info.members lowering_info.ownershipinfos filter_info
    lowering_info <- lowering_info { members = members, ownershipinfos = ownershipinfos, allocator = allocator }
    //trace config "------------ end filterInfo {} / {}-----------" % (lowering_info, sources)
    (lowering_info, filter_info)

filterFunctionLoweringInfo :: Config -> FunctionLoweringInfo -> List2 TypeVariableInfo -> FilterInfo -> (FunctionLoweringInfo, FilterInfo)
filterFunctionLoweringInfo config lowering_info sources filter_info = do
    //trace config "------------ start filterInfo {} / {}-----------" % (lowering_info, sources)
    (members, ownershipinfos, allocator, filter_info) <- filterLoweringInfo config sources lowering_info.members lowering_info.ownershipinfos filter_info
    lowering_info <- lowering_info { members = members, ownershipinfos = ownershipinfos, allocator = allocator }
    //trace config "------------ end filterInfo {} / {}-----------" % (lowering_info, sources)
    (lowering_info, filter_info)

processTypeVariableInfo :: List2 TypeVariable
                           -> Map2 TypeVariable (List2 TypeVariableInfo)
                           -> Map2 TypeVariable M.OwnershipKind
                           -> List2 TypeVariableInfo
                           -> TypeVariableInfo ->
                           (Map2 TypeVariable (List2 TypeVariableInfo), Map2 TypeVariable M.OwnershipKind, List2 TypeVariableInfo)
processTypeVariableInfo visited deps_map kind_map relevants info = do
    if List2.contains visited info.arg_group_var
    then (deps_map, kind_map, relevants)
    else do
        visited <- List2.push visited info.arg_group_var
        before <- List2.getLength relevants
        (deps_map, kind_map, relevants) <- case Map2.get deps_map info.arg_group_var of
            Some deps -> do
                List2.fold (deps_map, kind_map, relevants) deps (\(deps_map, kind_map, relevants), info -> do
                    processTypeVariableInfo visited deps_map kind_map relevants info)
            None -> (deps_map, kind_map, relevants)
        after <- List2.getLength relevants
        borrower <- case Map2.get kind_map info.ownership_var of
            Some ownership ->
                case ownership of
                    M.Borrower _ -> True
                    _ -> False
            None -> False
        relevants <- if borrower || (after > before)
        then List2.push relevants info
        else relevants
        (deps_map, kind_map, relevants)

filterLoweringInfo :: Config -> List2 TypeVariableInfo ->
                      List2 M.MemberInfo -> List2 M.OwnershipInfo ->
                      FilterInfo ->
                      (List2 M.MemberInfo, List2 M.OwnershipInfo, Allocator, FilterInfo)
filterLoweringInfo config sources members ownershipinfos filter_info = do
    kind_map <- M.toOwnershipKind ownershipinfos
    (deps_map, kind_map, relevants) <- List2.fold (filter_info.ordered_dep_map, kind_map, List2.empty) sources (\(deps_map, kind_map, relevants), source -> do
         processTypeVariableInfo List2.empty deps_map kind_map relevants source)
    relevants <- relevants + sources
    //println "borrower_map {}" % borrower_map
    //println "relevants {}" % relevants
    group_vars <- List2.map relevants (\info -> info.arg_group_var)
    ownership_vars <- List2.map relevants (\info -> info.ownership_var)
    members <- List2.filter members (filterMember relevants group_vars)
    (members, ownership_vars) <- List2.foldLinear ownership_vars members (\ownership_vars, m -> case m of
        M.Variant _ _ root info -> List2.push ownership_vars info.ownership_var
        M.Field _ _ root info -> List2.push ownership_vars info.ownership_var
        M.Extern _ _ root info -> List2.push ownership_vars info.ownership_var)
    (_, ownershipinfos) <- List2.filterS ownership_vars ownershipinfos M.filterOwnershipInfo
    (members, allocator) <- List2.foldLinear createAllocator members (\allocator, m -> case m of
        M.Variant _ _ root info -> do
            allocator <- addTypeVariable allocator root
            allocator <- addTypeVariableInfo allocator info
            allocator
        M.Field _ _ root info -> do
            allocator <- addTypeVariable allocator root
            allocator <- addTypeVariableInfo allocator info
            allocator
        M.Extern _ _ root info -> do
            allocator <- addTypeVariable allocator root
            allocator <- addTypeVariableInfo allocator info
            allocator)
    (sources, allocator) <- List2.foldLinear allocator sources (\allocator, info -> addTypeVariableInfo allocator info)
    (ownershipinfos, allocator) <- List2.foldLinear allocator ownershipinfos (\allocator, o -> case o of
        M.OwnershipInfo _ (M.Borrower id) -> addBorrowId allocator id
        _ -> allocator)
    (members, ownershipinfos, allocator, filter_info)