module Siko.Backend.Ownership.ValueGraph.Creator where

import Siko.Backend.Ownership.ValueGraph
import Siko.Backend.Ownership.ValueGraph.Analyzer
import Siko.Backend.Ownership.ValueGraph.Visual
import Siko.MIR.Program as P
import Siko.MIR.Function as F
import Siko.MIR.Expr as E

import Map
import Set

processItems :: [E.Expr] -> ValueGraphs
processItems items = do
    last <- getLength items - 1
    loop (prev, index) <- (createValueGraphs, last) do
        if index < 0
            then break prev
            else do
                item <- atIndex items index
                item_value_graph_set <- processExpr item
                (after [item_value_graph_set, prev], index - 1)

processFieldAccess :: [String] -> E.Expr -> ValueGraphs
processFieldAccess fields expr = do
    E.Expr s_expr _ id <- expr
    case s_expr of
        E.FieldAccess name rhs -> processFieldAccess ([name] + fields) rhs
        E.VarRef v -> do
            graphs <- createValueGraphs
            graphs <- addNode graphs v (ValueFieldAccess id fields)
            graphs
        _ -> processExpr expr

processExpr :: E.Expr -> ValueGraphs
processExpr expr = do
    E.Expr s_expr _ id <- expr
    case s_expr of
        E.Do items -> processItems items
        E.Multi _ -> panic "Multi in value graph create"
        E.StaticFunctionCall id args -> processItems args
        E.IntegerLiteral _ -> createValueGraphs
        E.StringLiteral _ -> createValueGraphs
        E.FloatLiteral _ -> createValueGraphs
        E.CharLiteral _ -> createValueGraphs
        E.VarDecl v rhs -> do
            prev <- processExpr rhs
            graphs <- createValueGraphs
            graphs <- addNode graphs v (ValueDecl (show v))
            after [prev, graphs]
        E.VarRef v -> do
            graphs <- createValueGraphs
            graphs <- addNode graphs v (ValueRef id)
            graphs
        E.FieldAccess name receiver -> processFieldAccess [name] receiver
        E.If cond true_branch false_branch -> do
            cond_graphs <- processExpr cond
            true_graphs <- processExpr true_branch
            false_graphs <- processExpr false_branch
            branch_graphs <- choice [true_graphs, false_graphs]
            after [cond_graphs, branch_graphs]
        E.List items -> processItems items
        E.Return arg -> do
            graphs <- processExpr arg
            createEnds graphs
        E.Continue arg -> processExpr arg
        E.Break arg -> processExpr arg
        E.RecordUpdate _ _ -> panic "RecordUpdate in value graph create"
        E.Loop v initializer body _ _ -> do
            initializer_graph <- processExpr initializer
            loop_var_graph <- createValueGraphs
            loop_var_graph <- addNode loop_var_graph v (ValueDecl (show v))
            body_graph <- processExpr body
            loop_body <- mergeLoop [loop_var_graph, body_graph]
            after [initializer_graph, loop_body]
        E.CaseOf body cases -> do
            body_graph <- processExpr body
            branch_graphs <- cases |> List.iter |> map (\c -> processExpr c.body) |> toList
            branch_graphs <- choice branch_graphs
            after [body_graph, branch_graphs]
        E.Clone arg -> processExpr arg
        E.Deref arg -> processExpr arg
        E.Ref arg -> processExpr arg
        E.Move arg -> processExpr arg
        E.Box arg -> processExpr arg
        E.Converter arg _ -> processExpr arg

createEnds :: ValueGraphs -> ValueGraphs
createEnds  graphs = do
    keys <- getKeys graphs.nodes
    ends <- createValueGraphs
    ends <- keys |> List.iter |> fold (\ends, k -> addNode ends k End) ends
    after [graphs, ends]

visualize :: P.Identity -> ValueGraphs -> ()
visualize name graphs = do
    graphs.nodes |> Map.iter |> forEach (\(var, node) -> do
        graph_name <- "{}.{}" % (name, var)
        draw graph_name node)

collectNotMoves :: P.Identity -> E.Expr -> Int -> Set E.ExprId
collectNotMoves function_id body arg_count = do
    //println "Processing function {}" % function_id
    args <- repeat () arg_count // FIXME: make this nicer
    graphs <- createValueGraphs
    args <- args |> List.iter |> fold (\args, _ -> do
        index <- getLength args
        args + [E.Arg index]) []
    graphs <- args |> List.iter |> fold (\graphs, arg -> do
        addNode graphs arg (ValueDecl (show arg))) graphs
    body_graph <- processExpr body
    final_graph <- after [graphs, body_graph]
    final_graph <- unpackGraphs final_graph
    final_graph <- createEnds final_graph
    //visualize function_id final_graph
    not_moves <- Set.empty
    not_moves <- final_graph.nodes |> Map.iter |> fold (\not_moves, (var, node) -> analyze not_moves node) not_moves
    not_moves