module Siko.Query.HIRLowering where

import IO
import Map
import Siko.Config
import Siko.Constants
import Siko.HIR.Backend.ClosureConverter as CC
import Siko.HIR.Backend.EffectResolver as ER
import Siko.HIR.Backend.Lowering as L
import Siko.HIR.Backend.Monomorphization as MO
import Siko.HIR.Backend.StateProvider as BSP
import Siko.HIR.Backend.UpdateTransformer as UT
import Siko.HIR.Data as HD
import Siko.HIR.Effect as Eff
import Siko.HIR.FullyQualifiedName as FQ
import Siko.HIR.Function as F
import Siko.HIR.Type as T
import Siko.LIR.Backend as LB
import Siko.MIR.Backend as MB
import Siko.MIR.Data as MD
import Siko.MIR.Identity as MI
import Siko.MIR.Program as MP
import Siko.Query.Database as DB
import Siko.Query.Driver
import Siko.Query.Item as I
import Siko.Trace
import Siko.Transpiler as Transpiler

transformUpdates :: Driver -> I.Key -> Driver
transformUpdates driver key = do
    fn <- DB.get driver.db key
    fn <- I.asTypedFunction fn
    state <- BSP.createStateProvider driver
    (state, fn) <- UT.processFunction state fn
    base_main_qn <- FQ.FullPath getMainModuleName getMainFunctionName
    unreachable_qn <- FQ.FullPath getStdUtilBasicModuleName getUnreachableName
    fn_name <- fn.name
    is_entry_point <- case fn.kind of
        F.Normal info -> case info.source of
            Some (F.EffectMember _) -> True
            Some (F.InstanceMember _) -> True
            Some (F.ClassMember _) -> True
            _ -> fn.name == base_main_qn || fn.name == unreachable_qn
        F.Interface _ -> True
        _ -> False
    key <- I.UpdateTransformedFunctionKey fn.name
    item <- I.UpdateTransformedFunction fn
    driver <- addToDb driver key item
    if is_entry_point
    then do
        resolve_cmd <- I.ResolveEffects (I.ResolvedEffectsFunctionKey (FQ.Effectless fn_name None))
        addCommands driver [resolve_cmd]
    else driver

resolveEffects :: Driver -> I.Key -> Driver
resolveEffects driver key = do
    case DB.getOpt driver.db key of
        Some resolved_fn -> driver
        None -> do
            case I.getFullyQualifiedName key of
                FQ.Effectless base_qn resolution_set -> do
                    resolution_set <- case resolution_set of
                        Some resolution_set -> resolution_set
                        None -> Eff.EffectResolutionSet Map.empty Map.empty
                    fn <- DB.get driver.db (I.UpdateTransformedFunctionKey base_qn)
                    fn <- I.asUpdateTransformedFunction fn
                    base_main_qn <- FQ.FullPath getMainModuleName getMainFunctionName
                    unreachable_qn <- FQ.FullPath getStdUtilBasicModuleName getUnreachableName
                    fn_name <- fn.name
                    state <- BSP.createStateProvider driver
                    (state, resolved_fn, qns) <- ER.resolveEffects state base_qn resolution_set
                    item <- I.ResolvedEffectsFunction resolved_fn
                    cmds <- List.map qns (\qn -> I.ResolveEffects (I.ResolvedEffectsFunctionKey qn))
                    driver <- addToDb driver key item
                    driver <- if fn.name == base_main_qn
                    then do
                        cmd <- I.MonomorphizeFunction (I.MonomorphizedFunctionKey (FQ.Monomorphized (I.getFullyQualifiedName key) (T.Tuple [])))
                        addCommands driver [cmd]
                    else driver
                    driver <- if fn.name == unreachable_qn
                    then do
                        cmd <- I.MonomorphizeFunction (I.MonomorphizedFunctionKey (FQ.Monomorphized (I.getFullyQualifiedName key) T.Never))
                        addCommands driver [cmd]
                    else driver
                    addCommands driver cmds
                qn -> panic "resolveEffects called with unexpected qn {}" % qn

monomorphizeFunction :: Driver -> I.Key -> Driver
monomorphizeFunction driver key = do
    case DB.getOpt driver.db key of
        Some monomorphized_fn -> driver
        None -> do
            case I.getFullyQualifiedName key of
                FQ.Monomorphized base_qn type -> do
                    fn <- DB.get driver.db (I.ResolvedEffectsFunctionKey base_qn)
                    fn <- I.asResolvedEffectsFunction fn
                    state <- BSP.createStateProvider driver
                    state <- state { ignore_never = True }
                    (state, monomorphized_fn, functions, records, adts, external_class_impls) <- MO.monomorphizeFunction state base_qn type
                    driver <- List.fold driver external_class_impls (\driver, external_class_impl -> do
                        key <- I.ExternalClassImplKey external_class_impl
                        case DB.getOpt driver.db key of
                            Some _ -> driver
                            None -> do
                                state <- BSP.createStateProvider driver
                                state <- state { ignore_never = True }
                                (state, function) <- MO.monomorphizeClassImpl state external_class_impl
                                (driver, item) <- case function of
                                    Some qn -> do
                                        cmds <- [I.MonomorphizeFunction (I.MonomorphizedFunctionKey qn)]
                                        (addCommands driver cmds, I.ExternalClassImpl (Some qn))
                                    None -> (driver, I.ExternalClassImpl None)
                                addToDb driver key item)
                    item <- I.MonomorphizedFunction monomorphized_fn
                    driver <- addToDb driver key item
                    cmds <- List.map functions (\qn -> I.MonomorphizeFunction (I.MonomorphizedFunctionKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.map records (\qn -> I.MonomorphizeRecord (I.MonomorphizedRecordKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.map adts (\qn -> I.MonomorphizeAdt (I.MonomorphizedAdtKey qn))
                    addCommands driver cmds
                qn -> panic "monomorphizeFunction called with unexpected qn {}" % qn

monomorphizeRecord :: Driver -> I.Key -> Driver
monomorphizeRecord driver key = do
    case DB.getOpt driver.db key of
        Some monomorphized_record -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            case qn of
                FQ.Record name args -> do
                    state <- BSP.createStateProvider driver
                    (state, record, records, adts) <- MO.monomorphizeRecord state name args
                    item <- I.MonomorphizedRecord record
                    driver <- addToDb driver key item
                    cmds <- List.map records (\qn -> I.MonomorphizeRecord (I.MonomorphizedRecordKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.map adts (\qn -> I.MonomorphizeAdt (I.MonomorphizedAdtKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.push cmds (I.ClosureConvertRecord (I.ClosureConvertedRecordKey qn))
                    addCommands driver cmds
                qn -> panic "monomorphizeRecord called with unexpected qn {}" % qn

monomorphizeAdt :: Driver -> I.Key -> Driver
monomorphizeAdt driver key = do
    case DB.getOpt driver.db key of
        Some monomorphized_adt -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            case qn of
                FQ.Adt name args -> do
                    state <- BSP.createStateProvider driver
                    (state, adt, records, adts) <- MO.monomorphizeAdt state name args
                    item <- I.MonomorphizedAdt adt
                    driver <- addToDb driver key item
                    cmds <- List.map records (\qn -> I.MonomorphizeRecord (I.MonomorphizedRecordKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.map adts (\qn -> I.MonomorphizeAdt (I.MonomorphizedAdtKey qn))
                    driver <- addCommands driver cmds
                    cmds <- List.push cmds (I.ClosureConvertAdt (I.ClosureConvertedAdtKey qn))
                    addCommands driver cmds
                qn -> panic "monomorphizeAdt called with unexpected qn {}" % qn

closureConvertFunction :: Driver -> I.Key -> Driver
closureConvertFunction driver key = do
    fn <- DB.get driver.db key
    fn <- I.asMonomorphizedFunction fn
    state <- BSP.createStateProvider driver
    (state, fn, closure_names, closure_instances) <- CC.closureConvertFunction state fn
    cmds <- List.map closure_instances (\i -> I.CreateClosureInstance (I.ClosureInstanceKey i))
    driver <- addCommands driver cmds
    cmds <- List.map closure_names (\i -> I.CreateClosure (I.ClosureKey i))
    driver <- addCommands driver cmds
    key <- I.ClosureConvertedFunctionKey (I.getFullyQualifiedName key)
    item <- I.ClosureConvertedFunction fn
    qn <- I.getFullyQualifiedName key
    base_main_qn <- FQ.FullPath getMainModuleName getMainFunctionName
    is_entry_point <- fn.name == base_main_qn
    driver <- if is_entry_point
    then addCommands driver [I.LowerHIRFunction (I.MIRFunctionKey (MI.Identity qn)), I.RunLegacyBackend]
    else driver
    addToDb driver key item

closureConvertRecord :: Driver -> I.Key -> Driver
closureConvertRecord driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            record <- DB.get driver.db (I.MonomorphizedRecordKey qn)
            record <- I.asMonomorphizedRecord record
            state <- BSP.createStateProvider driver
            (state, record, closure_names, closure_instances) <- CC.closureConvertRecord state record
            cmds <- List.map closure_instances (\i -> I.CreateClosureInstance (I.ClosureInstanceKey i))
            driver <- addCommands driver cmds
            cmds <- List.map closure_names (\i -> I.CreateClosure (I.ClosureKey i))
            driver <- addCommands driver cmds
            item <- I.ClosureConvertedRecord record
            addToDb driver key item

closureConvertAdt :: Driver -> I.Key -> Driver
closureConvertAdt driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            adt <- DB.get driver.db (I.MonomorphizedAdtKey qn)
            adt <- I.asMonomorphizedAdt adt
            state <- BSP.createStateProvider driver
            (state, adt, closure_names, closure_instances) <- CC.closureConvertAdt state adt
            cmds <- List.map closure_instances (\i -> I.CreateClosureInstance (I.ClosureInstanceKey i))
            driver <- addCommands driver cmds
            cmds <- List.map closure_names (\i -> I.CreateClosure (I.ClosureKey i))
            driver <- addCommands driver cmds
            item <- I.ClosureConvertedAdt adt
            addToDb driver key item

createClosureInstance :: Driver -> I.Key -> Driver
createClosureInstance driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            addToDb driver key I.ClosureInstance

createClosure :: Driver -> I.Key -> Driver
createClosure driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            closure_instances <- DB.getWatchedKeys driver.db I.ClosureInstanceKind
            instances <- List.filterMap closure_instances (\i -> case i of
                I.ClosureInstanceKey i -> if i.closure_name == qn
                    then Some i
                    else None
                _ -> panic "Closure instance key is not closure instance key")
            state <- BSP.createStateProvider driver
            (state, items) <- List.foldE (state, []) instances (\(state, items), index, i -> do
                (state, fn) <- CC.createVariantCtor state i index
                items <- List.push items (I.ClosureConvertedFunctionKey fn.name, I.ClosureConvertedFunction fn)
                (state, items))
            (state, closure_call_fn) <- CC.createClosureCall state instances qn
            (state, adt) <- CC.createClosureAdt state instances qn
            driver <- addToDb driver key I.Closure
            driver <- List.fold driver items (\driver, (key, item) -> addToDb driver key item)
            driver <- addToDb driver (I.ClosureConvertedFunctionKey qn) (I.ClosureConvertedFunction closure_call_fn)
            key <- I.ClosureConvertedAdtKey qn
            item <- I.ClosureConvertedAdt adt
            addToDb driver key item

lowerFunction :: Driver -> I.Key -> Driver
lowerFunction driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            fn <- DB.get driver.db (I.ClosureConvertedFunctionKey qn)
            fn <- I.asClosureConvertedFunction fn
            state <- BSP.createStateProvider driver
            (state, mir_fn, functions, tuples, records, adts) <- L.lowerFunction state qn fn
            driver <- addToDb driver key (I.MIRFunction mir_fn)
            driver <- List.fold driver functions (\driver, mir_id -> addCommands driver [I.LowerHIRFunction (I.MIRFunctionKey mir_id)])
            driver <- List.fold driver tuples (\driver, mir_id -> addCommands driver [I.LowerTuple (I.MIRRecordKey mir_id)])
            driver <- List.fold driver records (\driver, mir_id -> addCommands driver [I.LowerHIRRecord (I.MIRRecordKey mir_id)])
            driver <- List.fold driver adts (\driver, mir_id -> addCommands driver [I.LowerHIRAdt (I.MIRAdtKey mir_id)])
            driver

getExternalClassImpl :: Driver -> FQ.FullyQualifiedName -> (Driver, [MD.ExternalClassImpl])
getExternalClassImpl driver qn = do
    type <- T.Named qn []
    impl_kinds <- [HD.PartialEqKind,
                   HD.EqKind,
                   HD.PartialOrdKind,
                   HD.OrdKind]
    List.fold (driver, []) impl_kinds (\(driver, external_class_impls), kind -> do
        case DB.getOpt driver.db (I.ExternalClassImplKey (kind, type)) of
            Some (I.ExternalClassImpl impl) -> do
                (driver, impl) <- case (kind, impl) of
                    (HD.PartialEqKind, Some impl) -> do
                        mir_id <- MI.Identity impl
                        driver <- addCommands driver [I.LowerHIRFunction (I.MIRFunctionKey mir_id)]
                        (driver, MD.PartialEq mir_id)
                    (HD.EqKind, None) -> (driver, MD.Eq)
                    (HD.PartialOrdKind, Some impl) -> do
                        mir_id <- MI.Identity impl
                        driver <- addCommands driver [I.LowerHIRFunction (I.MIRFunctionKey mir_id)]
                        (driver, MD.PartialOrd mir_id)
                    (HD.OrdKind, Some impl) -> do
                        mir_id <- MI.Identity impl
                        driver <- addCommands driver [I.LowerHIRFunction (I.MIRFunctionKey mir_id)]
                        (driver, MD.Ord mir_id)
                    _ -> panic "Unexpected external class impl {}/{}" % (kind, impl)
                external_class_impls <- List.push external_class_impls impl
                (driver, external_class_impls)
            _ -> (driver, external_class_impls))

lowerRecord :: Driver -> I.Key -> Driver
lowerRecord driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            record <- DB.get driver.db (I.ClosureConvertedRecordKey qn)
            record <- I.asClosureConvertedRecord record
            state <- BSP.createStateProvider driver
            (state, mir_record, tuples, adts, records) <- L.lowerRecord state qn record
            (driver, external_class_impls) <- getExternalClassImpl driver qn
            mir_record <- mir_record { external_class_impls = external_class_impls }
            driver <- List.fold driver tuples (\driver, mir_id -> addCommands driver [I.LowerTuple (I.MIRRecordKey mir_id)])
            driver <- List.fold driver records (\driver, mir_id -> addCommands driver [I.LowerHIRRecord (I.MIRRecordKey mir_id)])
            driver <- List.fold driver adts (\driver, mir_id -> addCommands driver [I.LowerHIRAdt (I.MIRAdtKey mir_id)])
            addToDb driver key (I.MIRRecord mir_record)

lowerAdt :: Driver -> I.Key -> Driver
lowerAdt driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            adt <- DB.get driver.db (I.ClosureConvertedAdtKey qn)
            adt <- I.asClosureConvertedAdt adt
            state <- BSP.createStateProvider driver
            (state, mir_adt, tuples) <- L.lowerAdt state qn adt
            (driver, external_class_impls) <- getExternalClassImpl driver qn
            mir_adt <- mir_adt { external_class_impls = external_class_impls }
            driver <- List.fold driver tuples (\driver, mir_id -> addCommands driver [I.LowerTuple (I.MIRRecordKey mir_id)])
            addToDb driver key (I.MIRAdt mir_adt)

lowerTuple :: Driver -> I.Key -> Driver
lowerTuple driver key = do
    case DB.getOpt driver.db key of
        Some _ -> driver
        None -> do
            qn <- I.getFullyQualifiedName key
            tuple_args <- case qn of
                FQ.Tuple args -> args
                _ -> panic "Tuple is not a tuple!"
            state <- BSP.createStateProvider driver
            (state, mir_record, ctor_fn, records, adts) <- L.createTuple state (MI.Identity qn) tuple_args
            driver <- List.fold driver records (\driver, mir_id -> addCommands driver [I.LowerHIRRecord (I.MIRRecordKey mir_id)])
            driver <- List.fold driver adts (\driver, mir_id -> addCommands driver [I.LowerHIRAdt (I.MIRAdtKey mir_id)])
            driver <- addToDb driver key (I.MIRRecord mir_record)
            addToDb driver (I.MIRFunctionKey ctor_fn.id) (I.MIRFunction ctor_fn)

runlegacyBackend :: Driver -> Driver
runlegacyBackend driver = do
    //println "Start legacy backend"
    mir_program <- MP.createProgram
    mir_functions <- DB.getWatchedKeys driver.db I.MIRFunctionKind
    mir_functions <- List.map mir_functions (\key -> case DB.get driver.db key of
        I.MIRFunction fn -> fn
        _ -> panic "MIR function is not a function in runlegacyBackend")
    mir_records <- DB.getWatchedKeys driver.db I.MIRRecordKind
    mir_records <- List.map mir_records (\key -> case DB.get driver.db key of
        I.MIRRecord record -> record
        _ -> panic "MIR record is not a record in runlegacyBackend")
    mir_adts <- DB.getWatchedKeys driver.db I.MIRAdtKind
    mir_adts <- List.map mir_adts (\key -> case DB.get driver.db key of
        I.MIRAdt adt -> adt
        _ -> panic "MIR adt is not an adt in runlegacyBackend")
    mir_program <- List.fold mir_program mir_functions (\mir_program, fn -> do
        //println "Adding fn {}" % fn.id
        MP.addFunction mir_program fn.id fn)
    mir_program <- List.fold mir_program mir_records (\mir_program, r -> do
        //println "Adding record {}" % r.id
        MP.addRecord mir_program r.id r)
    mir_program <- List.fold mir_program mir_adts (\mir_program, adt -> do
        //println "Adding adt {}" % adt.id
        MP.addAdt mir_program adt.id adt)
    trace "MIR processing.."
    lir_program <- MB.processProgram mir_program
    config <- getConfig ()
    lir_program <- if config.disable_lir_transforms
    then lir_program
    else do
        trace "LIR processing.."
        LB.processProgram lir_program
    trace "Transpiling.."
    rust_output <- Transpiler.transpile lir_program
    rust_source_file <- getOutputFileName Rust
    binary_file <- getOutputFileName Binary
    writeTextFile rust_source_file rust_output
    trace "Compiling.."
    compilation_result <- if config.optimized
    then runCommand ["rustc",
                     "-O",
                     "-o",
                     binary_file,
                     rust_source_file]
    else runCommand ["rustc",
                     "-o",
                     binary_file,
                     rust_source_file]
    if compilation_result
    then exit 0
    else exit 1
    driver
