module Siko.MIR.Backend.Lowering.Function where

import Map
import Siko.LIR.Function as LF
import Siko.LIR.Program as LP
import Siko.LIR.Type as LT
import Siko.MIR.Backend.Duplicator
import Siko.MIR.Backend.EqualitySolver as Solver
import Siko.MIR.Backend.Lowering.Context
import Siko.MIR.Backend.Lowering.Expr
import Siko.MIR.Backend.Lowering.FunctionLoweringInfo
import Siko.MIR.Backend.Lowering.LoweringDataProvider
import Siko.MIR.Backend.Lowering.LoweringInfo.FilterInfo
import Siko.MIR.Backend.Lowering.Type
import Siko.MIR.Backend.Lowering.TypeLoweringInfo
import Siko.MIR.Backend.Ownership.Borrow as B
import Siko.MIR.Backend.Ownership.ControlFlowGraph
import Siko.MIR.Backend.Ownership.ControlFlowGraph.BorrowChecker as CFGBorrow
import Siko.MIR.Backend.Ownership.ControlFlowGraph.Builder as CFGB
import Siko.MIR.Backend.Ownership.ControlFlowGraph.Visualizer as CFGVisualizer
import Siko.MIR.Backend.Ownership.DataFlowGraph as DFG
import Siko.MIR.Backend.Ownership.DataFlowGraph.Builder as DFGB
import Siko.MIR.Backend.Ownership.DataFlowGraph.Inference as DFGI
import Siko.MIR.Backend.Ownership.DataFlowGraph.Visualizer as DFGVisualizer
import Siko.MIR.Backend.Ownership.DataFlowProfileStore
import Siko.MIR.Backend.Query as Q
import Siko.MIR.Backend.TypeVariableInfo
import Siko.MIR.Expr as ME
import Siko.MIR.Function as MF
import Siko.MIR.Identity as I
import Siko.Trace

lowerLifetimeDependency :: B.LifetimeDependency -> LF.LifetimeDependency
lowerLifetimeDependency dep = LF.LifetimeDependency (toLifetime dep.from) (toLifetime dep.to)
    where
        toLifetime :: B.BorrowId -> LT.Lifetime
        toLifetime B.BorrowId i = LT.Lifetime i

lowerNormalFunction :: FunctionLoweringInfo ->
                       I.Identity ->
                       LP.Identity ->
                       MF.FunctionInfo ->
                       DataFlowProfileStore -> LoweringContext
lowerNormalFunction lowering_info mir_id lir_id info dataflow_profile_store = do
    name <- show lir_id
    control_flow_graph <- CFGB.build info.body name
    control_flow_graph <- CFGBorrow.checkBorrows control_flow_graph
    CFGVisualizer.visualize control_flow_graph name
    data_flow_graph <- DFGB.build info.body name dataflow_profile_store
    data_flow_graph <- injectLoweringInfo lowering_info data_flow_graph
    (data_flow_graph, ownership_dep_map_info, borrow_map) <- DFGI.process data_flow_graph control_flow_graph name
    DFGVisualizer.visualize data_flow_graph name
    borrows <- getBorrows control_flow_graph
    filter_info <- buildFilterInfo data_flow_graph
    lowering_context <- LoweringContext mir_id
                                        (GraphBased data_flow_graph)
                                        borrows
                                        filter_info
                                        Map.empty
                                        Map.empty
                                        ownership_dep_map_info
                                        borrow_map
    lowering_context

injectLoweringInfo :: FunctionLoweringInfo -> DFG.DataFlowGraph -> DFG.DataFlowGraph
injectLoweringInfo lowering_info data_flow_graph = do
    lowering_info <- unpackOwnership lowering_info
    duplicator <- createDuplicator data_flow_graph.allocator
    (duplicator, lowering_info) <- duplicate duplicator lowering_info
    data_flow_graph <- List.fold data_flow_graph lowering_info.ownershipinfos (\data_flow_graph, info -> do
        DFG.setOwnership data_flow_graph info.var info.kind)
    equals <- []
    equals <- List.foldE equals lowering_info.args (\equals, index, arg_info -> do
        arg_key <- ME.Arg index
        arg_key <- DFG.VarKey arg_key
        dfg_arg_info <- DFG.getTypeVariableInfo data_flow_graph arg_key
        Solver.addEqual equals dfg_arg_info arg_info)
    equals <- Solver.addEqual equals (DFG.getTypeVariableInfo data_flow_graph DFG.EndKey) lowering_info.result
    data_flow_graph <- Solver.processEquals equals data_flow_graph
    data_flow_graph

lowerFunction :: Context ->
                 FunctionLoweringInfo ->
                 I.Identity ->
                 LP.Identity -> Context
lowerFunction context lowering_info mir_id lir_id = do
    trace2 "Lowering function {}/{} {}" % (mir_id, lir_id, lowering_info)
    function <- Q.getFunction mir_id
    context <- case function.kind of
        MF.Normal info -> do
            //lowerNormalFunction lowering_info mir_id lir_id info context.dataflow_profile_store
            lowering_context <- lowerNormalFunction lowering_info mir_id lir_id info context.dataflow_profile_store
            (lowering_context, context, lir_body) <- lowerExpr lowering_context context info.body
            lir_kind <- LF.Normal lir_body
            (context, lir_function_type, lifetimes) <- lowerFunctionType context lowering_info function.type
            lifetime_dependencies <- List.map lowering_info.lifetime_dependencies lowerLifetimeDependency
            lir_function <- LF.Function lir_id lifetimes lifetime_dependencies lir_kind lir_function_type
            context <- addFunction context lir_function
            context
        MF.RecordCtor -> do
            lir_kind <- LF.RecordCtor
            (context, lir_function_type, lifetimes) <- lowerFunctionType context lowering_info function.type
            lifetime_dependencies <- []
            lir_function <- LF.Function lir_id lifetimes lifetime_dependencies lir_kind lir_function_type
            context <- addFunction context lir_function
            context
        MF.VariantCtor index -> do
            lir_kind <- LF.VariantCtor index
            (context, lir_function_type, lifetimes) <- lowerFunctionType context lowering_info function.type
            lifetime_dependencies <- []
            lir_function <- LF.Function lir_id lifetimes lifetime_dependencies lir_kind lir_function_type
            context <- addFunction context lir_function
            context
        MF.Extern type_mapping -> do
            lir_kind <- LF.Extern
            (context, lir_function_type, lifetimes) <- lowerFunctionType context lowering_info function.type
            lifetime_dependencies <- List.map lowering_info.lifetime_dependencies lowerLifetimeDependency
            lir_function <- LF.Function lir_id lifetimes lifetime_dependencies lir_kind lir_function_type
            context <- addFunction context lir_function
            context
    //trace "Lowering done"
    context
