module Siko.MIR.Backend.Lowering where

import Map
import Siko.LIR.Program as LP
import Siko.MIR.Backend.Allocator
import Siko.MIR.Backend.Lowering.Context
import Siko.MIR.Backend.Lowering.LoweringInfo
import Siko.MIR.Backend.Lowering.Naming
import Siko.MIR.Backend.MemberInfo as M
import Siko.MIR.Backend.Ownership.DataFlowProfileStore
import Siko.MIR.Backend.TypeVariableInfo
import Siko.MIR.Program as MP

lowerProgram :: DataFlowProfileStore -> LP.Program
lowerProgram dataflow_profile_store = do
    context <- createContext dataflow_profile_store
    allocator <- createAllocator
    (allocator, result) <- getNextTypeVariableInfo allocator
    main_key <- FunctionKey MP.getMainIdentity (FunctionLoweringInfo [] [] result [] allocator [])
    (context, main_lir_id) <- getLIRId context main_key
    context <- addItem context main_key
    context <- processQueue context
    lir_program <- LP.createProgram
    lir_program <- Map.fold lir_program context.lir_functions (\lir_program, (id, f) -> LP.addFunction lir_program id f)
    lir_program <- Map.fold lir_program context.lir_records (\lir_program, (id, r) -> LP.addRecord lir_program id r)
    lir_program <- Map.fold lir_program context.lir_adts (\lir_program, (id, a) -> LP.addAdt lir_program id a)
    lir_program
