module Siko.MIR.Backend.Lowering.Type where

import Map
import Siko.LIR.Function as LF
import Siko.LIR.Type as LT
import Siko.MIR.Backend.BorrowId
import Siko.MIR.Backend.Duplicator
import Siko.MIR.Backend.Lowering.Context
import Siko.MIR.Backend.Lowering.LoweringInfo
import Siko.MIR.Backend.Lowering.LoweringInfo.FilterInfo
import Siko.MIR.Backend.Lowering.LoweringInfo.Normalizer
import Siko.MIR.Backend.Lowering.Naming
import Siko.MIR.Backend.MemberInfo as M
import Siko.MIR.Backend.TypeVariableInfo
import Siko.MIR.Function as MF
import Siko.MIR.Type as MT

remapLifetime :: Duplicator -> LT.Lifetime -> LT.Lifetime
remapLifetime duplicator LT.Lifetime id = do
    BorrowId id <- remapBorrow duplicator (BorrowId id)
    LT.Lifetime id

lowerType :: Context -> TypeLoweringInfo -> MT.Type -> (Context, LT.Type)
lowerType context lowering_info mir_type = do
    case mir_type of
        MT.Record id -> do
            //println "Record input {}" % lowering_info
            (lowering_info, ref) <- normalizeRef lowering_info
            (lowering_info, duplicator) <- normalizeTypeLoweringInfo lowering_info
            lir_key <- RecordKey id lowering_info
            context <- addItem context lir_key
            (context, lir_id) <- getLIRId context lir_key
            //println "lowerType: {} {} {}" % (lir_id, lir_key, lowering_info)
            lifetimes <- collectLifetimes lowering_info.ownershipinfos
            lifetimes <- List.map lifetimes (remapLifetime duplicator)
            case ref of
                Some (BorrowId id) -> (context, LT.Ref (LT.Lifetime id) (LT.Record lir_id lifetimes))
                None -> (context, LT.Record lir_id lifetimes)
        MT.Adt id -> do
            //println "Adt input {}" % lowering_info
            (lowering_info, ref) <- normalizeRef lowering_info
            (lowering_info, duplicator) <- normalizeTypeLoweringInfo lowering_info
            lir_key <- AdtKey id lowering_info
            context <- addItem context lir_key
            (context, lir_id) <- getLIRId context lir_key
            //println "lowerType: {} {}" % (lir_id, lir_key)
            lifetimes <- collectLifetimes lowering_info.ownershipinfos
            lifetimes <- List.map lifetimes (remapLifetime duplicator)
            case ref of
                Some (BorrowId id) -> (context, LT.Ref (LT.Lifetime id) (LT.Adt lir_id lifetimes))
                None -> (context, LT.Adt lir_id lifetimes)
        MT.Never -> (context, LT.Never)
        t -> panic "Unexpected MIR type in LIR type lowering {}" % t

lowerFunctionType :: Context -> FunctionLoweringInfo -> MF.FunctionType -> (Context, LF.FunctionType, [LT.Lifetime])
lowerFunctionType context lowering_info mir_function_type = do
    filter_info <- buildFilterInfo lowering_info
    //println "lowerFunctionType {} {}" % (lowering_info, mir_function_type)
    (context, args) <- List.mapSE context mir_function_type.args (\context, index, arg_type -> do
        arg_lowering_info <- getLoweringInfoForArg lowering_info index filter_info
        //println "arg_lowering_info: {}" % arg_lowering_info
        (context, ty) <- lowerType context arg_lowering_info arg_type
        (context, ty))
    result_lowering_info <- getLoweringInfoForResult lowering_info filter_info
    //println "result_lowering_info: {}" % result_lowering_info
    (context, result) <- lowerType context result_lowering_info mir_function_type.result
    lifetimes <- collectLifetimes lowering_info.ownershipinfos
    (context, LF.FunctionType args result, lifetimes)

collectLifetimes :: [M.OwnershipInfo] -> [LT.Lifetime]
collectLifetimes ownershipinfos = do
    lifetimes <- List.fold [] ownershipinfos addLifetime
    lifetimes |> sort |> dedup
    where
        addLifetime :: [LT.Lifetime] -> M.OwnershipInfo -> [LT.Lifetime]
        addLifetime lifetimes info = case info.kind of
            M.Unknown -> lifetimes
            M.Owner -> lifetimes
            M.Borrower (BorrowId i) -> List.push lifetimes (LT.Lifetime i)
