module Siko.Driver {

import Siko.Parser.Module
import Siko.AST.Module
import Siko.Diagnostics
import Siko.Config
import Siko.CompilerHost
import Siko.Driver.Passes
import Siko.HIR.Program
import Siko.Package.Source as SP
import Siko.SanityCheck
import Std.Effects.Time
import Std.Map
import Std.Set

pub implicit current: Driver

pub struct CompilationError {}

pub struct Pass {
    pub name: String,
    pub label: String,
    pub run: fn(Driver) -> (),
    pub dump: Option[fn(Driver) -> ()],
    pub run_sanity_check: Bool = False,
}

pub struct Driver {
    pass: Option[String],
    pub program: Program,
    pub all_modules: Vec[Module],
    pub packages: Vec[SP.SourcePackage],
    pub pkg_reachability: Map[String, Set[String]],
    pub diagnostics: Vec[Diagnostic],

    pub fn new() -> Driver {
        Driver(
            pass: None,
            program: Program.new(),
            all_modules: Vec.new(),
            packages: Vec.new(),
            pkg_reachability: Map.new(),
            diagnostics: Vec.new(),
        )
    }

    pub fn has_error_diagnostic(d: Driver) -> Bool {
        for di in d.diagnostics {
            if di.severity.is_error() {
                return True;
            }
        }
        False
    }

    pub fn run_passes(d: Driver, passes: Vec[Pass]) -> Result[(), CompilationError] {
        let trace = get_config().trace;
        for pass in passes {
            let start = now();
            (pass.run)(d);
            if trace {
                CompilerEvents.pass_finished(
                    pass.label,
                    elapsed(start).to_millis(),
                );
            }
            if d.has_error_diagnostic() {
                return Err(CompilationError());
            }
            if pass.run_sanity_check {
                SanityCheck.check_program(d.program);
            }
            if d.pass == Some(pass.name) {
                match pass.dump {
                    Some(dump_fn) => (dump_fn)(d),
                    None => CompilerEvents.dump(d.program.format()),
                }
                return Ok(());
            }
        }
        Ok(())
    }

    pub fn compile(d: Driver, pass: Option[String], passes: Vec[Pass]) -> Result[(), CompilationError] {
        with current = d {
            d.pass = pass;
            d.run_passes(passes)
        }
    }

    pub fn compile_macro(d: Driver) -> Result[(), CompilationError] {
        with current = d {
            d.pass = None;
            d.run_passes(Passes.build_macro_passes(d))
        }
    }

    pub fn compile_interpreter_tests(d: Driver) -> Result[(), CompilationError] {
        with current = d {
            d.pass = None;
            d.run_passes(Passes.build_interpreter_test_program_passes(d))
        }
    }

    pub fn report_diagnostics(d: Driver) {
        for di in d.diagnostics {
            di.print();
        }
    }

    pub fn get_diagnostics(d: Driver) -> Vec[Diagnostic] {
        d.diagnostics
    }
}

pub fn add_diagnostic(d: Diagnostic) {
    current.diagnostics.push(d);
}
}
