module Siko.Resolver.Export(processExports) where

import Siko.Syntax.Module as M
import Siko.Resolver.Item
import Siko.Syntax.Import as SI
import Map

processExport :: SI.Export -> Item -> Bool
processExport export item = case export of
    SI.ExportAll -> True
    SI.ExportSpecific filters -> matchFilters filters item

processModule :: [Item] -> SI.Export -> [Item]
processModule locals export = List.filter locals (processExport export)

processExports :: Map String [Item] -> Map String M.Module -> Map String [Item]
processExports locals modules = do
    Map.map locals (\(name, locals) -> do
                                    mod <- Option.unwrap (get modules name)
                                    exported_items <- processModule locals mod.export
                                    (name, exported_items))