module Siko.Resolver.ResolvedItem where

import Siko.HIR.Program as HP
import Siko.Syntax.Ident
import Siko.Resolver.Item
import Siko.Resolver.Error
import Map

data ResolvedItem = ResolvedItem HP.FullyQualifiedName Item Explicitness deriving (Show)

instance PartialEq ResolvedItem where
    opEq (ResolvedItem qn1 _ _) (ResolvedItem qn2 _ _) = qn1 == qn2

getCandidates :: [ResolvedItem] -> [String]
getCandidates resolved_items = resolved_items |> List.iter |> Iterator.map (\(ResolvedItem name _ _) -> HP.getResolvableName name) |> toList

resolveItem :: Map String [ResolvedItem] -> (Ident -> ResolverError) -> Ident -> Result ResolvedItem ResolverError
resolveItem items err name = do
    n <- getString name
    case get items n of
        Some resolved_items -> if getLength resolved_items > 1
                        then do
                                resolved_items <- resolved_items |> List.iter |> Iterator.filter (\(ResolvedItem _ _ explicitness) -> explicitness == Explicit) |> toList
                                case getLength resolved_items of
                                    1 -> Ok (atIndex resolved_items 0)
                                    _ ->  Err (AmbiguousName name (getCandidates resolved_items))
                        else Ok (atIndex resolved_items 0)
        None -> Err (err name)