module String where

data String = extern

module Int where

data Int = extern

module Float where

data Float = extern

module Char where

data Char = extern

module Hack where

sink a :: ~a -> ~()
sink item = extern

module Main where

import Hack

data Outer = Outer Inner

data Inner = Inner
data Season = Spring | Summer | Fall | Winter

id a = a

data Foo = Foo Inner | Bar

main = do
    q <- "a"
    q <- 1
    q <- 1.2
    q <- 'c'
    b <- Inner
    c <- Inner
    a <- Outer b
    d <- Foo b
    sink (id a)
    sink (id a)
    sink (id a)
    sink (id d)
    sink (id d)
    sink (id d)
    b
    ()
