module Main where

data ImportedItem = ImportedItem
data Item = Item

importLocalItem :: String -> Item -> [ImportedItem]
importLocalItem module_name item = do
    [ImportedItem]

adder :: [ImportedItem] -> [ImportedItem] -> [ImportedItem]
adder a b = a + b

processLocals :: String -> [Item] -> [ImportedItem]
processLocals module_name locals = do
    imported_items <- locals |> List.iter |> Iterator.map (importLocalItem module_name) |> Iterator.fold (\total, items -> total + items)  []
    //imported_items <- locals |> List.iter |> Iterator.map (importLocalItem module_name) |> Iterator.fold adder  []
    imported_items

main = ()