module Main where

import Std.Util

main = do 
    assert (1 < 2)
    assert (1 <= 2)
    assert (2 <= 2)

    assert (2 > 1)
    assert (2 >= 1)
    assert (2 >= 2)

    assert !(1 > 2)
    assert !(1 >= 2)

    assert !(2 < 1)
    assert !(2 <= 1)

    assert ("a" < "b")
    assert ("a" <= "b")
    assert ("b" <= "b")

    assert ("b" > "a")
    assert ("b" >= "a")
    assert ("b" >= "b")

    assert !("a" > "b")
    assert !("a" >= "b")

    assert !("b" < "a")
    assert !("b" <= "a")

    assert (1.0 < 2.0)
    assert (1.0 <= 2.0)
    assert (2.0 <= 2.0)

    assert (2.0 > 1.0)
    assert (2.0 >= 1.0)
    assert (2.0 >= 2.0)

    assert !(1.0 > 2.0)
    assert !(1.0 >= 2.0)

    assert !(2.0 < 1.0)
    assert !(2.0 <= 1.0)

    assert (max 1 2 == 2)
    assert (min 1 2 == 1)

    assert ((cmp 1 2) == Less)
    assert ((cmp 2 2) == Equal)
    assert ((cmp 2 1) == Greater)