module Siko.Resolver.Error {

import Siko.AST.Identifier
import Siko.AST.QualifiedName
import Siko.Location
import Siko.Interner as I

pub enum ResolveError {
    ModuleNotFound(name: Identifier),
    AmbiguousName(name: Identifier, candidates: Vec[QualifiedName]),
    NameNotFound(name: Identifier),
    NotAType(name: Identifier),
    NotATrait(name: Identifier),
    HigherKindedTypeNotSupported(name: Identifier),
    InvalidTypeArgCount(name: Identifier, expected: Int, got: Int),
    InvalidTraitArgCount(name: Identifier, expected: Int, got: Int),
    UnknownAssociatedType(name: Identifier),
    NotAVariant(name: Identifier),
    WrongPatternArgCount(name: Identifier, expected: Int, got: Int),
    InvalidEffectHandler(name: Identifier),
    NamedArgOnDynamicCall(location: Location),
    DefaultArgNotAtEnd(name: Identifier),
    DefaultArgNotAllowed(name: Identifier),
    StructFieldDefaultNotAtEnd(name: Identifier),
    StructPatternPrivateFields(name: Identifier),
    StructCtorPrivateFields(name: Identifier),
    WrongNamedPatternArg(variant: Identifier, got: I.String, expected: I.String),
    PatternItemNotNamed(variant: Identifier, name: I.String),
    RedundantRestPattern(name: Identifier),
    DuplicateNamedPatternArg(variant: Identifier, name: I.String),
    PositionalArgWithRest(variant: Identifier),
}

}
