module Main where

import Std.Util

data Counter = Counter Int

instance Iterator Counter > Int where
     next (Counter i) = if i > 10
            then (Counter i, None)
            else (Counter (i + 1), Some i)

main = do
    sum <- Counter 0 |> Iterator.filter (\elem -> elem > 3) |> Iterator.map show |> Iterator.fold (\sum, i -> sum + "-" + i) ""
    assert (sum == "-4-5-6-7-8-9-10")

data ImportedItem = ImportedItem
data Item = Item

importLocalItem :: String -> Item -> [ImportedItem]
importLocalItem module_name item = do
    [ImportedItem]

processLocals :: String -> [Item] -> [ImportedItem]
processLocals module_name locals = do
    imported_items <- locals |> List.iter |> Iterator.map (importLocalItem module_name) |> Iterator.fold (\total, items -> total + items)  []
    imported_items
