module Siko.Syntax.Effect where

import Siko.Syntax.Class
import Siko.Syntax.Function
import Siko.Syntax.Ident
import Siko.Syntax.TypeSignature(TypeSignature)

data Effect = { name :: Ident,
                arguments :: [Ident],
                constraints :: [Constraint],
                member_functions :: [Function],
                member_function_type_signatures :: [FunctionSignature]
              } deriving (Show, PartialEq, Eq)
