module Main {

struct String2 {

}

struct Address {
    city: String2
    street: String2
}

struct Person {
    name: String2
    address: Address
}

fn main() {
    let address = Address(String2(), String2());
    let person = Person(String2(), address);
    person.address.city;
    person.address;
    other();
    other2();
}

fn other() {
    let address = Address(String2(), String2());
    let person = Person(String2(), address);
    if True {
        person.address.city;
    } else {
        person.address;
    }
}

fn other2() {
    let address = Address(String2(), String2());
    let person = Person(String2(), address);
    if True {
        person.address.city;
    } else {
        person.address;
    }
    person;
}

}
     
