module Main where

import Std.Util
import Map

create :: Map Int Int
create = empty

main = do
    m <- create
    assert (show m == "{}")
    assert (getSize m == 0)
    (m, _) <- insert m 1 2
    (m, _) <- insert m 3 4
    assert (show m == "{1: 2, 3: 4}")
    assert (getSize m == 2)
    assert (get m 1 == Some 2)
    assert (get m 3 == Some 4)
    assert (get m 5 == None)
    (m, _) <- remove m 3
    assert (get m 3 == None)
    ()