module Std.Basic.Util {

fn siko_runtime_abort() = extern
fn siko_runtime_num(v: Int) = extern
fn siko_runtime_str(v: String) = extern
fn siko_runtime_bool(v: Bool) = extern
fn siko_runtime_true() -> Bool = extern
fn siko_runtime_false() -> Bool = extern

fn assert(v: Bool) {
    if v {
    } else {
        siko_runtime_abort();
    }
}

fn printNum(v: Int) {
    siko_runtime_num(v);
}

fn printStr(v: String) {
    siko_runtime_str(v);
}

fn printBool(v: Bool) {
    siko_runtime_bool(v);
}

fn getTrue() -> Bool {
    siko_runtime_true()
}

fn getFalse() -> Bool {
    siko_runtime_false()
}

fn panic(msg: String) {
    printStr("PANIC");
    printStr(msg);
    siko_runtime_abort();
}

}
