module Cell where

data Cell a = extern

instance (Show a) => Show Cell a where
    show cell = show (get cell)

create a :: a -> ~Cell ~a
create item = extern

take a :: Cell a -> ~a
take cell = extern

put a :: Cell a -> a -> ~()
put cell item = extern

get a :: Cell a -> ~a
get cell = extern

update a :: Cell a -> (a -> a) -> ()
update cell f = do
    item <- take cell
    new <- f item
    put cell new
