module Map where

data Map k v = extern

instance (Show k, Show v) => Show Map k v where
    show a = extern

instance (PartialEq k, PartialEq v) => PartialEq Map k v where
    opEq a b = extern

instance (Eq k, Eq v) => Eq Map k v

empty k v :: (Ord k) => Map k v
empty = extern

insert k v :: (Ord k) => Map k v -> k -> v -> (Map k v, Option v)
insert m k v = extern

get k v :: (Ord k) => Map k v -> k -> Option v
get m k = extern

remove k v :: (Ord k) => Map k v -> k -> (Map k v, Option v)
remove m k = extern

alter k v :: (Ord k) => (Option v -> Option v) -> k -> Map k v -> (Map k v, Option v)
alter f k m = extern

iter k v :: Map k v -> Iterator (k, v)
iter m = extern

toMap k v :: Iterator (k, v) -> Map k v
toMap i = extern

getSize k v :: Map k v -> Int
getSize m = extern