module Option where

data Option a = Some a
              | None
              deriving (PartialEq, Eq, PartialOrd, Ord, Show)

@Inline
isSome a :: Option a -> Bool
isSome o = case o of
    Some _ -> True
    None -> False

@Inline
isNone a :: Option a -> Bool
isNone o = case o of
    Some _ -> False
    None -> True

@Inline
unwrap a :: Option a -> a
unwrap o = case o of
    Some a -> a
    None -> panic "Option unwrap called on None"

@Inline
expect a :: Option a -> String -> a
expect o msg = case o of
    Some a -> a
    None -> panic "Option expect failed: {}" % msg
