module Rc where

data Rc a = { value :: a }

create a :: a -> Rc a
create item = Rc item

get a :: Rc a -> a
get rc = rc.value

instance (Show a) => Show Rc a where
    show a = show (get a)

instance (PartialEq a) => PartialEq Rc a where
    opEq a b = opEq (get a) (get b)

instance (Eq a) => Eq Rc a

instance (PartialOrd a) => PartialOrd Rc a where
    partialCmp a b = partialCmp (get a) (get b)

instance (Ord a) => Ord Rc a where
    cmp a b = cmp (get a) (get b)
