module Siko.LIR.Data where

import Json
import Json.Serialize
import Siko.LIR.Program
import Siko.LIR.Type

data ExternalClassImpl = PartialEq Identity
                       | Eq
                       | PartialOrd Identity
                       | Ord Identity
                       deriving (Show, PartialEq, Eq, ToJson, FromJson)

data Variant = { name :: String,
                 type :: Type
               } deriving (Show, PartialEq, Eq, ToJson, FromJson)

data AlgebraicDataType = { id :: Identity,
                           lifetimes :: [Lifetime],
                           variants :: [Variant],
                           external_class_impls :: [ExternalClassImpl]
                         } deriving (PartialEq, Eq, ToJson, FromJson)

data RecordField = { index :: Int,
                     type :: Type
                   } deriving (PartialEq, Eq, ToJson, FromJson)

data ExternalRecordInfo = { type_args :: [Type] } deriving (PartialEq, Eq, ToJson, FromJson)

data Record = { id :: Identity,
                lifetimes :: [Lifetime],
                fields :: [RecordField],
                external_info :: Option ExternalRecordInfo,
                external_class_impls :: [ExternalClassImpl],
                implicit_member_lifetime :: Option Lifetime
              } deriving (PartialEq, Eq, ToJson, FromJson)

dumpAdt :: AlgebraicDataType -> String
dumpAdt adt = do
    variants <- adt.variants |> List.iter |> Iterator.map (\v -> "{} {}" % (v.name, v.type)) |> toList
    "adt {} = {}" % (adt.id, join variants " | ")

dumpRecord :: Record -> String
dumpRecord record = do
    fields <- record.fields |> List.iter |> Iterator.map (\field -> "field{} :: {}" % (field.index, field.type)) |> toList
    if List.isEmpty fields
    then if isSome record.external_info
        then "record {} = extern" % record.id
        else "record {}" % record.id
    else ("record {}" % record.id) + " = { " + (join fields ", ") + " }"
