module Main where

import Std.Util

main = do
    list <- ["apple", "banana", "banana"]
    apple <- atIndex list 0
    assert (apple == "apple")
    len <- getLength list
    assert (len == 3)
    d <- dedup list
    assert (d == ["apple", "banana"])
    empty :: [Int] <- []
    assert (isEmpty empty)
    sorted <- sort [3, 2]
    assert (sorted == [2, 3])
    add <- [1] + [2]
    assert (add == [1, 2])
    case head [1] of
        Some v -> assert (v == 1)
        None -> assert False
    double <- [1, 2] |> List.iter |> map (\x -> x * 2) |> toList
    assert (double == [2, 4])
    case tail [1, 2] of
        Some v -> assert (v == [2])
        None -> assert False
