module Siko.Backend.Ownership.Inference.Collection where

import Siko.MIR.Program as P
import Siko.MIR.Expr as E
import Siko.MIR.Data as D
import Siko.MIR.Type as T
import Siko.MIR.Function as F
import Siko.Util.DependencyProcessor
import Siko.Backend.Ownership.ValueGraph.Creator as C
import Siko.Backend.Ownership.Inference.Common as Common
import Siko.Backend.Ownership.Unification as U
import Siko.Util.Counter

import Map
import Set

collectVars :: Common.Context -> Common.MovedVars -> [T.OwnershipKind] -> (Common.Context, [T.OwnershipVar])
collectVars context moved_vars kinds = do
    List.mapS context kinds (\context, kind -> case kind of
        T.VarKind v -> do
            context <- Common.addOwnershipVar context v (T.VarKind v) moved_vars
            (context, v)
        T.OwnerKind -> do
            (context, v) <- Common.getNextOwnershipVar context
            context <- Common.addOwnershipVar context v kind moved_vars
            (context, v)
        T.BorrowKind i -> do
            (context, v) <- Common.getNextOwnershipVar context
            (context, borrower_set_id) <- Common.createrBorrowerSetId context
            context <- Common.addBorrowerSet context borrower_set_id Set.empty
            context <- Common.addOwnershipVar context v (T.BorrowKind borrower_set_id) moved_vars
            (context, v))

convertibleConstraints :: Common.Context -> Common.MovedVars -> T.Type -> T.Type -> Common.Context
convertibleConstraints context moved_vars src dest = do
    src_kinds <- T.collectOwnershipKinds src
    dest_kinds <- T.collectOwnershipKinds dest
    (context, src_vars) <- collectVars context moved_vars src_kinds
    (context, dest_vars) <- collectVars context moved_vars dest_kinds
    context <- List.zipSE context src_vars dest_vars (\context, index, src_var, dest_var -> do
        if index == 0
            then Common.addConverter context (Common.Converter Common.NormalConverter src_var dest_var)
            else Common.addEqual context src_var dest_var)
    context

borrowConstraints :: Common.Context -> Common.MovedVars -> T.Type -> T.Type -> Common.Context
borrowConstraints context moved_vars src dest = do
    src_kinds <- T.collectOwnershipKinds src
    dest_kinds <- T.collectOwnershipKinds dest
    (context, src_vars) <- collectVars context moved_vars src_kinds
    (context, dest_vars) <- collectVars context moved_vars dest_kinds
    context <- List.zipSE context src_vars dest_vars (\context, index, src_var, dest_var -> do
        context <- if index == 0
            then do
                converter <- Common.Converter Common.BorrowConverter src_var dest_var
                b <- Common.Borrower src_var
                context <- context { borrowers = context.borrowers + [b] }
                Common.addConverter context converter
            else do
                context <- Common.addEqual context src_var dest_var
                context
        context)
    context

equalConstraints :: Common.Context -> Common.MovedVars -> T.Type -> T.Type -> Common.Context
equalConstraints context moved_vars src dest = do
    src_kinds <- T.collectOwnershipKinds src
    dest_kinds <- T.collectOwnershipKinds dest
    (context, src_vars) <- collectVars context moved_vars src_kinds
    (context, dest_vars) <- collectVars context moved_vars dest_kinds
    context <- List.zipS context src_vars dest_vars (\context, src_var, dest_var -> do
        context <- Common.addEqual context src_var dest_var
        context)
    context

getRecordType :: Common.Context -> T.Type -> D.Record
getRecordType context type = do
    record_id <- T.getIdentity type
    record <- P.getRecord context.global_context.program record_id
    ownership_vars <- T.collectOwnershipArgs type
    sub <- U.batch record.ownership_vars ownership_vars
    record <- U.apply record sub
    record

getAdtType :: Common.Context -> T.Type -> D.AlgebraicDataType
getAdtType context type = do
    adt_id <- T.getIdentity type
    adt <- P.getAdt context.global_context.program adt_id
    ownership_vars <- T.collectOwnershipArgs type
    sub <- U.batch adt.ownership_vars ownership_vars
    adt <- U.apply adt sub
    adt

getRecordFieldType :: D.Record -> String -> T.Type
getRecordFieldType record name =
    case find record.fields (\f -> f.name == name) of
        Some f -> do
            f :: D.RecordField <- f // FIXME
            f.type
        None -> panic "No field named {}" % name

mergeMovedVars :: [Common.MovedVars] -> Common.MovedVars
mergeMovedVars moved_var_sets = do
    moved_var_sets |> List.iter |> fold (\merged, moved_vars -> do
            // FIXME: set merge does not work in rust interpreter, fix this!
            // merged_vars <- merged.vars + moved_vars.vars
            vs <- merged.vars.items + moved_vars.vars.items
            vs <- vs |> sort |> dedup
            vs <- Set vs
            merged { vars = vs }
        ) (Common.MovedVars Set.empty)

addMovedVar :: Common.MovedVars -> T.OwnershipVar -> Common.MovedVars
addMovedVar moved_vars var = do
    (vars, _) <- Set.insert moved_vars.vars var
    moved_vars { vars = vars }

processExpr :: Common.Context -> Common.MovedVars -> E.Expr -> (Common.Context, Common.MovedVars)
processExpr context moved_vars expr = do
    E.Expr s_expr type id <- expr
    case s_expr of
        E.Do items -> do
            (context, moved_vars) <- items |> List.iter |> fold (\(context, moved_vars), item -> processExpr context moved_vars item) (context, moved_vars)
            E.Expr _ last_type _ <- atIndex items (getLength items - 1)
            context <- convertibleConstraints context moved_vars last_type type
            (context, moved_vars)
        E.VarDecl v rhs -> do
            (context, moved_vars) <- processExpr context moved_vars rhs
            E.Expr _ rhs_type _ <- rhs
            context <- Common.addVarType context v rhs_type
            (context, moved_vars)
        E.StaticFunctionCall id args -> do
            info <- case get context.global_context.inference_infos id of
                Some info -> info
                None -> panic "No inference info found for function {}" % id
            (context, info) <- Common.cloneFunctionInfo context info
            context <- info.var_constraints |> Map.iter |> fold (\context, (src_var, constraints) -> do
                    constraints |> Set.iter |> fold (\context, dest_var ->
                        Common.addConverter context (Common.Converter Common.NormalConverter src_var dest_var)) context) context
            function_type <- info.function_type
            (context, moved_vars) <- args |> List.iter |> fold (\(context, moved_vars), arg -> processExpr context moved_vars arg) (context, moved_vars)
            context <- List.zipS context args function_type.args (\context, arg_expr, f_arg_type -> do
                E.Expr _ arg_expr_type _ <- arg_expr
                convertibleConstraints context moved_vars arg_expr_type f_arg_type)
            context <- equalConstraints context moved_vars function_type.result type
            (context, moved_vars)
        E.VarRef v -> do
            var_type <- Common.getVarType context v
            (context, moved_vars) <- if Set.contains context.not_moves id
                then do
                    context <- borrowConstraints context moved_vars var_type type
                    (context, moved_vars)
                else do
                    vars <- T.collectOwnershipVars var_type
                    moved_var <- atIndex vars 0
                    moved_var <- case moved_var of
                        T.VarKind v -> v
                        _ -> panic "Var is not varkind in move"
                    moved_vars <- addMovedVar moved_vars moved_var
                    context <- equalConstraints context moved_vars var_type type
                    (context, moved_vars)
            (context, moved_vars)
        E.CaseOf body cases -> do
            (context, moved_vars) <- processExpr context moved_vars body
            (context, moved_var_sets) <- cases |> List.iter |> fold (\(context, moved_var_sets), c -> do
                context <- case c.checker of
                    E.VariantChecker index v type -> do
                        context <- Common.addVarType context v type
                        E.Expr _ body_type _ <- body
                        adt <- getAdtType context body_type
                        variant <- atIndex adt.variants index
                        equalConstraints context moved_vars variant.type body_type
                    _ -> context
                (context, moved_vars) <- processExpr context moved_vars c.body
                E.Expr _ body_type _ <- c.body
                context <- convertibleConstraints context moved_vars body_type type
                moved_var_sets <- moved_var_sets + [moved_vars]
                (context, moved_var_sets)) (context, [])
            moved_vars <- mergeMovedVars moved_var_sets
            (context, moved_vars)
        E.FieldAccess name receiver -> do
            (context, moved_vars) <- processExpr context moved_vars receiver
            E.Expr _ receiver_type _ <- receiver
            record <- getRecordType context receiver_type
            field_type <- getRecordFieldType record name
            context <- equalConstraints context moved_vars field_type type
            (context, moved_vars)
        _ -> panic "NYI {}" % s_expr

collectConstraints :: Common.GlobalContext -> U.OwnershipVarGenerator -> F.FunctionType -> P.Identity -> E.Expr -> Common.Context
collectConstraints global_context var_gen function_type function_id body = do
    not_moves <- C.collectNotMoves function_id body (getLength function_type.args)
    context <- Common.createContext global_context not_moves var_gen
    context <- foldE (\context, index, arg_type -> Common.addVarType context (E.Arg index) arg_type) context function_type.args
    moved_vars <- Common.MovedVars Set.empty
    (context, moved_vars) <- processExpr context moved_vars body
    E.Expr _ body_type _ <- body
    context <- convertibleConstraints context moved_vars body_type function_type.result
    context
