module Siko.HIR.Backend.Unification.Data where

import Siko.HIR.Backend.Unification as U
import Siko.HIR.Backend.Unification.Substitution as S
import Siko.HIR.Backend.Unification.Util as UUtil
import Siko.HIR.Data as D
import Siko.HIR.Type as T

instance S.Apply D.Record where
    apply record sub = do
        (_, record) <- S.transform () record (\_, t -> ((), S.apply t sub))
        record

instance S.Transform D.RecordField where
    transform state (D.RecordField name type) f = do
        (state, type) <- S.transform state type f
        (state, D.RecordField name type)

instance S.Transform D.Variant where
    transform state variant f = do
        (state, items) <- S.transform state variant.items f
        (state, variant { items = items })

instance S.Transform D.Record where
    transform state record f = do
        (state, type_args) <- S.transform state record.type_args f
        (state, fields) <- S.transform state record.fields f
        (state, type) <- S.transform state record.type f
        name <- Std.Intrinsics.clone record.name
        (state, D.Record name 
                         record.location 
                         type_args 
                         fields 
                         record.external 
                         type 
                         record.implicit_member)

instance S.Apply D.AlgebraicDataType where
    apply adt sub = do
        (_, adt) <- S.transform () adt (\_, t -> ((), S.apply t sub))
        adt

instance S.Transform D.AlgebraicDataType where
    transform state adt f = do
        (state, type_args) <- S.transform state adt.type_args f
        (state, variants) <- S.transform state adt.variants f
        (state, type) <- S.transform state adt.type f
        name <- Std.Intrinsics.clone adt.name
        (state, D.AlgebraicDataType name adt.location type_args variants type)

instance S.Collectable D.Record where
    collect collector record = S.collect collector record.type

instance S.Collectable D.AlgebraicDataType where
    collect collector adt = S.collect collector adt.type

instantiateAdt a :: (U.Context a) => a -> D.AlgebraicDataType -> T.Type -> Result (a, D.AlgebraicDataType) a
instantiateAdt context adt adt_type = do
    sub <- S.createSubstitution
    (adt, context) <- UUtil.instantiateGeneric adt context
    (context, sub) <- case U.unify context sub adt.type adt_type of
        Ok (context, sub) -> (context, sub)
        Err (context, sub) -> return Err context
    adt <- S.apply adt sub
    Ok (context, adt)

instantiateRecord a :: (U.Context a) => a -> D.Record -> T.Type -> Result (a, D.Record) a
instantiateRecord context record record_type = do
    sub <- S.createSubstitution
    (record, context) <- UUtil.instantiateGeneric record context
    (context, sub) <- case U.unify context sub record.type record_type of
        Ok (context, sub) -> (context, sub)
        Err (context, sub) -> return Err context
    record <- S.apply record sub
    Ok (context, record)
