module Std.Net.TcpStream {

import Std.IO.Error
import Std.IO.Reader
import Std.IO.Writer
import Std.IO.Closer
import Std.Libc.FileDescriptor
import Std.Arch.Errno
import Std.Arch.Socket
import Std.Libc.Socket
import Std.Net.Utils
import Std.Slice

pub struct TcpStream {
    fd: FileDescriptor,

    pub fn new(fd: I32) -> TcpStream {
        TcpStream(FileDescriptor.new(fd))
    }

    pub fn get_fd(s: TcpStream) -> FileDescriptor {
        s.fd
    }

    @safe
    pub fn connect(host: String, port: U16) -> Result[TcpStream, Error] {
        let addr = parse_address(host)?;
        let sock = Std.Libc.Socket.socket(Domain.code(Domain.AF_INET), SockType.code(SockType.SOCK_STREAM), 0);
        if sock < 0 {
            return Err(Error.new(Std.Arch.Errno.get_errno()));
        }
        let fd = FileDescriptor.new(sock);
        let sockaddr = SockaddrIn.new(Domain.AF_INET, port, addr);
        let ret = Std.Libc.Socket.connect(sock, &sockaddr, sockaddr.len().as_int().as_i32());
        if ret < 0 {
            let errno = Std.Arch.Errno.get_errno();
            defer fd.close();
            return Err(Error.new(errno));
        }
        Ok(TcpStream.new(sock))
    }

    @safe
    pub fn connect_async(host: String, port: U16) -> Result[TcpStream, Error] {
        let addr = parse_address(host)?;
        let sock = Std.Libc.Socket.socket(Domain.code(Domain.AF_INET), SockType.code(SockType.SOCK_STREAM), 0);
        if sock < 0 {
            return Err(Error.new(Std.Arch.Errno.get_errno()));
        }
        let s = FileDescriptor.new(sock);
        s.set_nonblocking(True);
        let sockaddr = SockaddrIn.new(Domain.AF_INET, port, addr);
        let ret = Std.Libc.Socket.connect(sock, &sockaddr, sockaddr.len().as_int().as_i32());
        if ret < 0 {
            let errno = Std.Arch.Errno.get_errno();
            if errno != Std.Arch.Errno.Errno.EINPROGRESS {
                defer s.close();
                return Err(Error.new(errno));
            }
        }
        Ok(TcpStream.new(sock))
    }

    @safe
    pub fn check_connect_result(s: TcpStream) -> Result[(), Error] {
        let error = 0;
        let error_len = sizeof(I32).as_int().as_u32();
        let ret = Std.Libc.Socket.getsockopt(
            s.fd.get_fd(),
            Std.Arch.Socket.SOL_SOCKET,
            Std.Arch.Socket.SO_ERROR,
            &error,
            &error_len,
        );
        if ret < 0 {
            return Err(Error.new(Std.Arch.Errno.get_errno()));
        }
        if error != 0 {
            let errno: Option[Std.Arch.Errno.Errno] = from_int(error.as_int());
            return Err(Error.new(errno.expect("Failed to parse socket error code ${error}")));
        }
        Ok(())
    }

    pub fn close(s: TcpStream) -> Result[(), Error] {
        s.fd.close()
    }

    pub fn set_nonblocking(s: TcpStream, nonblocking: Bool) -> Result[(), Error] {
        s.fd.set_nonblocking(nonblocking)
    }
}

instance Reader[TcpStream] {
    fn read(s: TcpStream, buf: Slice[U8]) -> Result[Int, Error] {
        s.fd.read(buf)
    }
}

instance Writer[TcpStream] {
    fn write(s: TcpStream, buf: Slice[U8]) -> Result[Int, Error] {
        s.fd.write(buf)
    }
}

instance Closer[TcpStream] {
    fn close(s: TcpStream) -> Result[(), Error] {
        s.close()
    }
}

}
