module Main where

foo a :: a -> Int -> a
foo a index = foo2 a (index - 1)

foo2 a :: a -> Int -> a
foo2 a index = if index > 0
    then foo a index
    else a

untyped a index = if index > 0
    then untyped a (index - 1)
    else 0

typed a :: a -> Int -> Int
typed a index = if index > 0
    then untyped a (index - 1)
    else 0

mixfoo a index = mixfoo2 a (index - 1)

mixfoo2 a :: a -> Int -> a
mixfoo2 a index = if index > 0
    then mixfoo a index
    else a

main = ()
