module Main where

import Std.Util

main = do
    a <- 4 + 5
    assert (a == 9)
    b <- 4.0 + 5.9
    assert (b == 9.9)
    c <- "4" + "5"
    assert (c == "45")
    a <- 4 - 5
    assert (a == -1)
    b <- 4.0 - 5.0
    assert (b == -1.0)
    a <- 4 * 5
    assert (a == 20)
    b <- 4.0 * 5.2
    a <- 20 / 5
    assert (a == 4)
    b <- 20.0 / 3.0
    a <- 4.02 + 4.03
    assert (a == 8.05)
    