module Main {

import Std.IO.EventLoop
import Std.Net.TcpListener
import Std.Net.TcpStream
import Std.Time
import Std.VecDeque
import Std.Coroutine

struct State {
    eventloop: EventLoop,
    current_task: Option[Task],
    stop: Bool,
    ready_queue: VecDeque[Task],

    fn new() -> State {
        State(eventloop: EventLoop.new(),
              current_task: None,
              stop: False,
              ready_queue: VecDeque.new())
    }

    fn run_ready_queue(s: State) {
        while True {
            match s.ready_queue.pop_front() {
                Some(task) => {
                        s.current_task = Some(task);
                        resume(task.coroutine.unwrap());
                        s.current_task = None;
                    }
                None => break,
            }
        }
    }

    fn add_ready(s: State, task: Task) {
        s.ready_queue.push_back(task);
    }

    fn spawn_task(s: State, f: fn() -> ()) {
        let task = Task(None);
        let task_co = co run(f);
        task.coroutine = Some(task_co);
        s.add_ready(task);
    }

    fn run_tasks(s: State) {
        while !s.stop {
            s.run_ready_queue();
            s.eventloop.run_once(milliseconds(10));
        }
    }
}

fn run(f: fn() -> ()) {
    f();
}

implicit current: State

struct Task {
    coroutine: Option[co(()) -> ()]
}

fn spawn(f: fn() -> ()) {
    current.spawn_task(f);
}

fn get_current_task() -> Task {
    current.current_task.unwrap()
}

fn listen(port: U16) -> Result[TcpListener, Error] {
    let listener = match TcpListener.bind(port) {
        Ok(l) => l,
        Err(e) => return Err(e),
    };
    listener.set_nonblocking(True)?;
    return Ok(listener);
}

fn accept(listener: TcpListener) co(()) -> () {
    let fd = listener.get_fd().get_fd();
    let task = get_current_task();
    current.eventloop.register_read(fd, || {
        current.add_ready(task);
    });
    yield ();
    match listener.accept() {
        Ok(_) => println("accepted connection"),
        Err(e) => panic("accept failed: ${e}"),
    }
    current.stop = True;
}

fn server(port: U16) -> Result[(), Error] {
    let listener = match listen(port) {
        Ok(l) => l,
        Err(e) => panic("listen failed: ${e}"),
    };
    accept(listener);
    Ok(())
}

fn client(port: U16) {
    let _ = TcpStream.connect_async("127.0.0.1", port).unwrap();
}

fn main() {
    let port = 19870.as_u16();
    let s = State.new();
    with current = s {
        spawn(|| server(port).unwrap());
        spawn(|| client(port));
        s.run_tasks();
    }
}

}
