module Siko.Syntax.Location where

data FileId = FileId Int deriving (Show)
data LocationId = LocationId Int deriving (Show)

data Position = {
              line :: Int,
              offset :: Int
            } deriving (Show)

data Span = {
                start :: Position,
                end :: Position
            } deriving (Show)

data Location = {
                  file_id :: FileId,
                  span :: Span,
                } deriving (Show)

