module Siko.Syntax.Operator where

data BuiltinOperator = Add
                    | Sub
                    | Mul
                    | Div
                    | PipeForward
                    | And
                    | Or
                    | Equals
                    | NotEquals
                    | LessThan
                    | GreaterThan
                    | LessOrEqualThan
                    | GreaterOrEqualThan
                    | Not
                    | Minus
                    | Bind
                    | Arrow deriving (Show)
