module Siko.Syntax.TypeSignature where

import Siko.Syntax.Ident

data TypeSignature = TypeArg Ident
                  | Named Ident [TypeSignature]
                  | Variant Ident [TypeSignature]
                  | List TypeSignature
                  | Tuple [TypeSignature]
                  | Function TypeSignature TypeSignature
                  | Never
                  | Ref TypeSignature
                  | Wildcard deriving (Show)
