name: Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - name: Install ts
      run: sudo apt install -y moreutils
    - name: Stage0
      run: make stage0
      working-directory: ./
    - name: Stage1
      run: make stage1
      working-directory: ./
    - name: Run tests
      run: make test
      working-directory: ./
