name: Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./build.sh
      working-directory: ./rust/
    - name: Run tests
      run: ./tests.sh
      working-directory: ./sikoc/
