name: Master

on: [push]

jobs:
  linux-tests:

    runs-on: ubuntu-latest
    env:
      SIKO_TARGET_OS: linux

    steps:
    - uses: actions/checkout@v5
      with:
          submodules: recursive
    - name: Install Boehm GC and LLVM
      run: sudo apt-get install -y libgc-dev llvm-dev # valgrind
    - name: Bootstrap
      run: make base.bin
    - name: Compile compiler
      run: make siko.bin
    - name: Compile testrunner
      run: make runner.bin
      working-directory: ./
    - name: Run tests
      #run: make test-valgrind
      run: make test
      working-directory: ./

  macos-tests:

    runs-on: macos-latest
    env:
      SIKO_TARGET_OS: macos
      HOMEBREW_REQUIRE_TAP_TRUST: 1

    steps:
    - uses: actions/checkout@v5
      with:
          submodules: recursive
    - name: Install Boehm GC and LLVM
      run: brew install bdw-gc llvm
    - name: Bootstrap
      run: make base.bin
    - name: Compile compiler
      run: make siko.bin
    - name: Compile testrunner
      run: make runner.bin
      working-directory: ./
    - name: Run tests
      run: make test
      working-directory: ./
